In [1]:
import json
import time

import joblib
import numpy as np
import pandas as pd
import torch

from benchmark.config import DATA_PROCESSED, DATASETS, MODELS_DIR, RESULTS_BENCHMARK
from benchmark.metrics import evaluate_regression
from benchmark.models.xrfm_model import make_processor
from benchmark.models.xrfm_model import fit_best_xrfm, fit_xrfm_cross_validation

data_name = "abalone"
cfg = DATASETS[data_name]
processed = DATA_PROCESSED / data_name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train_df = pd.read_csv(processed / "train.csv")
train_df.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,F,0.445,0.325,0.125,0.4550,0.1785,0.1125,0.140,9
1,I,0.515,0.400,0.135,0.6965,0.3200,0.1255,0.175,9
2,I,0.565,0.440,0.175,0.8735,0.4140,0.2100,0.210,11
3,M,0.415,0.325,0.140,0.4170,0.1535,0.1015,0.144,10
4,I,0.620,0.490,0.160,1.0660,0.4460,0.2460,0.305,11

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3341 entries, 0 to 3340
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sex             3341 non-null   object
 1   length          3341 non-null   float64
 2   diameter        3341 non-null   float64
 3   height          3341 non-null   float64
 4   whole_weight    3341 non-null   float64
 5   shucked_weight  3341 non-null   float64
 6   viscera_weight  3341 non-null   float64
 7   shell_weight    3341 non-null   float64
 8   rings           3341 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 235.0+ KB

In [4]:
test_df = pd.read_csv(processed / "test.csv")
test_df.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,I,0.550,0.425,0.15,0.7665,0.3390,0.1760,0.2100,8
1,M,0.545,0.450,0.16,0.8615,0.2925,0.1545,0.3650,16
2,M,0.330,0.250,0.09,0.1970,0.0850,0.0410,0.0605,10
3,I,0.485,0.380,0.14,0.6730,0.2175,0.1300,0.1950,18
4,I,0.525,0.400,0.13,0.6445,0.3450,0.1285,0.2000,8

In [5]:
with open(processed / "metadata.json") as f:
    metadata = json.load(f)

print(metadata)

{'num_cols': ['length', 'diameter', 'height', 'whole_weight', 'shucked_weight', 'viscera_weight', 'shell_weight'], 'cat_cols': ['sex'], 'target_col': 'rings'}

In [6]:
X = train_df.drop(columns=metadata["target_col"])
y = train_df[metadata["target_col"]].to_numpy().astype(np.float32)

processor = make_processor(metadata)
n_num_cols = len(metadata["num_cols"])

In [7]:
best_trial = fit_xrfm_cross_validation(
    X, y, processor, n_num_cols, task=cfg["task"], device=device
)

print(f"Best params: {best_trial.params}")
print(f"Best MSE: {best_trial.value}")

[I 2026-04-22 15:41:33,921] A new study created in memory with name: no-name-899811ad-6c62-4561-80cc-40dfca4b6995

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2666

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 0: 0.6263368129730225 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.01267695426940918 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.010926246643066406 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.011103153228759766 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.011678934097290039 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.015205144882202148 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.012942075729370117 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.013994216918945312 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.01326751708984375 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.012358665466308594 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.013750076293945312 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.01265859603881836 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.011794805526733398 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.010921239852905273 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.010788679122924805 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.012599468231201172 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.01122903823852539 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.011533737182617188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.011641979217529297 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.011399507522583008 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.01295614242553711 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.011792659759521484 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.011136054992675781 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.011149406433105469 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:35,151] Trial 0 finished with value: 4.925948715209961 and parameters: {'exponent': 1.0271644858581115, 'kernel_type': 'k2q', 'bandwidth': 1.970613996905623, 'diag': True, 'reg': 0.0026485784758470345}. Best is trial 0 with value: 4.925948715209961.

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.011145830154418945 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:869: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Time taken for round 0: 1.0890138149261475 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.0827944278717041 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08398008346557617 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08551549911499023 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 4: 0.08427190780639648 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08429646492004395 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08405494689941406 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08497905731201172 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08555126190185547 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08362603187561035 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08218812942504883 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08400845527648926 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08563375473022461 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08376097679138184 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08441734313964844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08396053314208984 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08466649055480957 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08465743064880371 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08440184593200684 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08482789993286133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0843501091003418 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08614158630371094 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0852360725402832 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08443927764892578 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:38,538] Trial 1 finished with value: 4.932258605957031 and parameters: {'exponent': 0.7598959983417237, 'kernel_type': 'kpq', 'bandwidth': 31.128146769150394, 'diag': True, 'norm_p': 1.204380550596923, 'reg': 1.5178988352304667e-06}. Best is trial 0 with value: 4.925948715209961.

Time taken for round 4: 0.08480620384216309 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013095617294311523 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012328147888183594 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.01204681396484375 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.011367321014404297 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.010766983032226562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.012977838516235352 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.013777017593383789 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012643098831176758 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01212763786315918 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011428356170654297 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013244152069091797 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.011917352676391602 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.011237144470214844 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 3: 0.01128387451171875 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011557817459106445 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013423442840576172 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012070178985595703 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.010895490646362305 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.011211872100830078 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011781930923461914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013056755065917969 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012022018432617188 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.01113128662109375 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:38,927] Trial 2 finished with value: 4.591622066497803 and parameters: {'exponent': 0.7416781387847737, 'kernel_type': 'k2q', 'bandwidth': 175.8288583045548, 'diag': True, 'reg': 0.5118691608584706}. Best is trial 2 with value: 4.591622066497803.

Time taken for round 3: 0.011881351470947266 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.012593269348144531 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08381319046020508 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08445096015930176 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08513689041137695 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08499360084533691 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 4: 0.08388590812683105 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08408308029174805 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08486080169677734 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08506107330322266 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08448910713195801 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08468389511108398 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0841064453125 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08484768867492676 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08603477478027344 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08380722999572754 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08471894264221191 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0840919017791748 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08726096153259277 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08519911766052246 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08501338958740234 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08513379096984863 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08507227897644043 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08485841751098633 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08454251289367676 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08556675910949707 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08449339866638184 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:41,323] Trial 3 finished with value: 4.336088752746582 and parameters: {'exponent': 0.7550981778629094, 'kernel_type': 'kpq', 'bandwidth': 6.5017130686590825, 'diag': True, 'norm_p': 1.6741056103679175, 'reg': 0.15816844334894103}. Best is trial 3 with value: 4.336088752746582.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 0: 0.013179779052734375 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.011631011962890625 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012083768844604492 seconds
Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013834953308105469 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012411117553710938 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.011919498443603516 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013168096542358398 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.014940738677978516 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 2657
Time taken for round 2: 0.013254404067993164 seconds
Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013862848281860352 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.011752605438232422 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012622356414794922 seconds
Early stopping at iteration 3
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013303995132446289 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.011616945266723633 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.010661602020263672 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:41,616] Trial 4 finished with value: 5.183063602447509 and parameters: {'exponent': 1.2386834737442696, 'kernel_type': 'k2q', 'bandwidth': 90.48888237464404, 'diag': True, 'reg': 0.8236923920601619}. Best is trial 3 with value: 4.336088752746582.

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012424707412719727 seconds
Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.09728145599365234 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08385920524597168 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0838472843170166 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08310484886169434 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08263874053955078 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08483147621154785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08286166191101074 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08354830741882324 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08280706405639648 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08284354209899902 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08476114273071289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08263278007507324 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08315420150756836 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0826883316040039 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08271241188049316 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08518218994140625 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08449506759643555 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08227348327636719 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08292508125305176 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08350324630737305 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08473324775695801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08563399314880371 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0840296745300293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08321571350097656 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08247494697570801 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:43,987] Trial 5 finished with value: 4.271482181549072 and parameters: {'exponent': 1.3169801908670333, 'kernel_type': 'kpq', 'bandwidth': 19.84662081152421, 'diag': False, 'norm_p': 1.7995055455137243, 'reg': 0.05330158533580604}. Best is trial 5 with value: 4.271482181549072.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08536553382873535 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08264899253845215 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0833432674407959 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08319973945617676 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08335041999816895 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08434224128723145 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0832829475402832 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08300209045410156 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0829610824584961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08280706405639648 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08502459526062012 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08359050750732422 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08316993713378906 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08270859718322754 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.0824899673461914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08488011360168457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0839087963104248 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08257889747619629 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08330798149108887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08285927772521973 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08467888832092285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08315086364746094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08388590812683105 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08369922637939453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08269667625427246 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:46,343] Trial 6 finished with value: 5.049731159210205 and parameters: {'exponent': 1.0948486965751747, 'kernel_type': 'kpq', 'bandwidth': 63.44132593183689, 'diag': False, 'norm_p': 1.4194589751409419, 'reg': 0.00011913672272764324}. Best is trial 5 with value: 4.271482181549072.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.016711950302124023 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012403488159179688 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012320756912231445 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.011983156204223633 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0113525390625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.012847185134887695 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.015388727188110352 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.013651847839355469 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01422572135925293 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.012552022933959961 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013987064361572266 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.01256704330444336 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.013306379318237305 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 3: 0.012827396392822266 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.013075113296508789 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.012652397155761719 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012848615646362305 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.011701583862304688 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012417316436767578 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011871337890625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.014165401458740234 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.011976480484008789 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012121200561523438 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01161646842956543 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:46,755] Trial 7 finished with value: 4.439147663116455 and parameters: {'exponent': 0.9163728423001612, 'kernel_type': 'k2q', 'bandwidth': 11.925101256066307, 'diag': True, 'reg': 0.021609288204221935}. Best is trial 5 with value: 4.271482181549072.

Time taken for round 4: 0.012609481811523438 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.014462471008300781 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012971878051757812 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012214422225952148 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01176595687866211 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.01212310791015625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013769149780273438 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012679576873779297 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.013527154922485352 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012063980102539062 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 2657
Time taken for round 4: 0.011775732040405273 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013150453567504883 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012113332748413086 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.013298511505126953 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.011897802352905273 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.012044906616210938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.017153263092041016 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.015252828598022461 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.01285243034362793 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01268315315246582 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.012427806854248047 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013124704360961914 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012001752853393555 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012385845184326172 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012265682220458984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.012753725051879883 seconds
Tree has no split, stopping training

[I 2026-04-22 15:41:47,166] Trial 8 finished with value: 5.094033813476562 and parameters: {'exponent': 1.2060200075435343, 'kernel_type': 'k2q', 'bandwidth': 2.792736238727968, 'diag': True, 'reg': 0.0007660547961224706}. Best is trial 5 with value: 4.271482181549072.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013434171676635742 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012801647186279297 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.011722326278686523 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.011853456497192383 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 2657
Time taken for round 4: 0.011662006378173828 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013844013214111328 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012531280517578125 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012176990509033203 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012477874755859375 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.01252436637878418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.01686859130859375 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012873649597167969 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012384653091430664 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012377500534057617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011740446090698242 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.014483213424682617 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012532711029052734 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.012759208679199219 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.01240992546081543 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 4: 0.011651992797851562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 0: 0.013617753982543945 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 1: 0.012549161911010742 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 2: 0.01260066032409668 seconds
Using cheap batch size
Optimal M batch size: 2657
Time taken for round 3: 0.012890338897705078 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.012529611587524414 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:41:47,572] Trial 9 finished with value: 4.699792003631591 and parameters: {'exponent': 0.7450034897059166, 'kernel_type': 'k2q', 'bandwidth': 1.880953078065556, 'diag': True, 'reg': 2.8141896704489657e-06}. Best is trial 5 with value: 4.271482181549072.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08481478691101074 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08377194404602051 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08289027214050293 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08345460891723633 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08342456817626953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08498620986938477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08346080780029297 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08324193954467773 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08302831649780273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.0823361873626709 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0848550796508789 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08331966400146484 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08278417587280273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08350396156311035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08281111717224121 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08490109443664551 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0835123062133789 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08361053466796875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08350467681884766 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08326268196105957 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08436989784240723 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08307933807373047 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08335661888122559 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.083038330078125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08293318748474121 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:49,940] Trial 10 finished with value: 4.273269891738892 and parameters: {'exponent': 1.393989129231174, 'kernel_type': 'kpq', 'bandwidth': 25.301974338838594, 'diag': False, 'norm_p': 1.8620961232850153, 'reg': 0.02493991040271981}. Best is trial 5 with value: 4.271482181549072.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08458828926086426 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08324718475341797 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08293271064758301 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08362007141113281 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.0831148624420166 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08681225776672363 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08370041847229004 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08311605453491211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08275055885314941 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08272576332092285 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08527016639709473 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08327412605285645 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08264565467834473 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08304882049560547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08261799812316895 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08588027954101562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08397841453552246 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08300042152404785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0826730728149414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08263373374938965 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0854489803314209 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08321905136108398 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08243966102600098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08259367942810059 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08289241790771484 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:52,303] Trial 11 finished with value: 4.27286696434021 and parameters: {'exponent': 1.3976307055228718, 'kernel_type': 'kpq', 'bandwidth': 26.126532970938573, 'diag': False, 'norm_p': 1.8626186481339537, 'reg': 0.022750308999261715}. Best is trial 5 with value: 4.271482181549072.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.083984375 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08327436447143555 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08350229263305664 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0827493667602539 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08231949806213379 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08542990684509277 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0843350887298584 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08364558219909668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08256888389587402 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.0830984115600586 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08520293235778809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08352971076965332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08233141899108887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0836939811706543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08277630805969238 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08495450019836426 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08403778076171875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08387422561645508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08278584480285645 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08330893516540527 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0855722427368164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08301949501037598 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08291029930114746 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08303308486938477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08420920372009277 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:54,666] Trial 12 finished with value: 4.262643051147461 and parameters: {'exponent': 1.370062308536912, 'kernel_type': 'kpq', 'bandwidth': 8.935768281229366, 'diag': False, 'norm_p': 1.8734548216357445, 'reg': 0.0258399640306377}. Best is trial 12 with value: 4.262643051147461.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08562946319580078 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08390355110168457 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08417034149169922 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08463263511657715 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08413267135620117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08519935607910156 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08352398872375488 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08229398727416992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08260011672973633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08260011672973633 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08415102958679199 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08238911628723145 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08299899101257324 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08339285850524902 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08242130279541016 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08386588096618652 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08292531967163086 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08328866958618164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08351802825927734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08479714393615723 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08383345603942871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08254551887512207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08366227149963379 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08465361595153809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08404111862182617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:57,033] Trial 13 finished with value: 4.65138349533081 and parameters: {'exponent': 1.26252993156702, 'kernel_type': 'kpq', 'bandwidth': 6.472413709162851, 'diag': False, 'norm_p': 1.6985302484573586, 'reg': 0.0027538801631505536}. Best is trial 12 with value: 4.262643051147461.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0847024917602539 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08397936820983887 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08381032943725586 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08440208435058594 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08370518684387207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08506917953491211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08332324028015137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08325004577636719 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08378124237060547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08286690711975098 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08651494979858398 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08292269706726074 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08328843116760254 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0830996036529541 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08306002616882324 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08513092994689941 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0835258960723877 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08338546752929688 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0837714672088623 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08366823196411133 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08491730690002441 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08310842514038086 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0836784839630127 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08514642715454102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08340835571289062 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:41:59,402] Trial 14 finished with value: 4.252799654006958 and parameters: {'exponent': 1.3194467368803158, 'kernel_type': 'kpq', 'bandwidth': 8.362204538483113, 'diag': False, 'norm_p': 1.7614942838713292, 'reg': 0.08721908158440389}. Best is trial 14 with value: 4.252799654006958.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08493828773498535 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08398938179016113 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08310675621032715 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08411741256713867 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08333420753479004 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08444643020629883 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08351588249206543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0839693546295166 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08340811729431152 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08358120918273926 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08490920066833496 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08301687240600586 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08352136611938477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08421874046325684 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08420968055725098 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08475542068481445 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 2.9343087673187256 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08390665054321289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08986139297485352 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.09113502502441406 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09257626533508301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.09126949310302734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.09176993370056152 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.09081602096557617 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:04,683] Trial 15 finished with value: 5.141119194030762 and parameters: {'exponent': 1.134105128502525, 'kernel_type': 'kpq', 'bandwidth': 5.0746138090111055, 'diag': False, 'norm_p': 1.5575330561334326, 'reg': 0.00019549257469451958}. Best is trial 14 with value: 4.252799654006958.

Using SVD
Time taken for round 4: 0.09084653854370117 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.09260058403015137 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0918569564819336 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.09099912643432617 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.09152650833129883 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.09174680709838867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09272527694702148 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.09180378913879395 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.09144949913024902 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.09107732772827148 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0912778377532959 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09275507926940918 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.19793391227722168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.09186196327209473 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.09114289283752441 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.09137630462646484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09331369400024414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.09132814407348633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.09083819389343262 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.09080171585083008 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.09110140800476074 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09263086318969727 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0911405086517334 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.09126758575439453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.09180045127868652 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.09165501594543457 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:07,377] Trial 16 finished with value: 4.269890689849854 and parameters: {'exponent': 1.3232963243847462, 'kernel_type': 'kpq', 'bandwidth': 11.23175961831484, 'diag': False, 'norm_p': 1.747385844385677, 'reg': 0.1349203580996224}. Best is trial 14 with value: 4.252799654006958.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.09087252616882324 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.09160614013671875 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0913691520690918 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0919198989868164 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.09161496162414551 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08807802200317383 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08320355415344238 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08386445045471191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08317446708679199 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08338403701782227 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08383893966674805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08327317237854004 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08330440521240234 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08285880088806152 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08296728134155273 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08370304107666016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08355593681335449 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08400392532348633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08404946327209473 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08414077758789062 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08124399185180664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08165478706359863 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08136749267578125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08086514472961426 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08233022689819336 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:09,777] Trial 17 finished with value: 6.002690124511719 and parameters: {'exponent': 0.9860742695659339, 'kernel_type': 'kpq', 'bandwidth': 1.0006446223000698, 'diag': False, 'norm_p': 0.990047932057783, 'reg': 0.0026195582374218093}. Best is trial 14 with value: 4.252799654006958.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08119726181030273 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07970261573791504 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08098173141479492 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08002114295959473 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08031439781188965 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08125948905944824 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0802769660949707 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08067512512207031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08011579513549805 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08080029487609863 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08167123794555664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07977294921875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08004450798034668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07991790771484375 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08114981651306152 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08239626884460449 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08103656768798828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08121395111083984 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0811614990234375 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08059191703796387 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08247137069702148 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08128833770751953 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08086466789245605 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08033919334411621 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08169865608215332 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:12,064] Trial 18 finished with value: 4.679943180084228 and parameters: {'exponent': 1.1594367870944864, 'kernel_type': 'kpq', 'bandwidth': 3.9738020329377393, 'diag': False, 'norm_p': 1.594230184756479, 'reg': 0.00803363403277877}. Best is trial 14 with value: 4.252799654006958.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08217883110046387 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08114743232727051 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08107662200927734 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0813748836517334 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08200693130493164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08206987380981445 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08052754402160645 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08120608329772949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08152985572814941 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08089566230773926 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08299088478088379 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08044934272766113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08135700225830078 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08127737045288086 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0816802978515625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08260703086853027 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08130407333374023 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08153319358825684 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0809476375579834 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0808401107788086 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08276128768920898 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08054351806640625 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0820457935333252 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08112907409667969 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08178305625915527 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:14,365] Trial 19 finished with value: 5.156392383575439 and parameters: {'exponent': 1.3146963818652475, 'kernel_type': 'kpq', 'bandwidth': 9.123528505203154, 'diag': False, 'norm_p': 1.7890419319226802, 'reg': 4.987385888273129e-05}. Best is trial 14 with value: 4.252799654006958.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08275890350341797 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0818171501159668 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08160185813903809 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08102965354919434 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08091616630554199 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08211994171142578 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0823674201965332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08062982559204102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08057856559753418 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08101320266723633 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0820615291595459 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08143949508666992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08141660690307617 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08094573020935059 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08776712417602539 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.082000732421875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08024859428405762 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08086323738098145 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0809013843536377 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08037114143371582 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08253788948059082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08074140548706055 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08060145378112793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08215904235839844 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:16,671] Trial 20 finished with value: 4.2879396915435795 and parameters: {'exponent': 0.9244443299202366, 'kernel_type': 'kpq', 'bandwidth': 54.5706769277564, 'diag': False, 'norm_p': 1.4360616402181736, 'reg': 0.1159254447902596}. Best is trial 14 with value: 4.252799654006958.

Using SVD
Time taken for round 4: 0.08135128021240234 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08213591575622559 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0812845230102539 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08205628395080566 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08078408241271973 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08165669441223145 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08237266540527344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08122014999389648 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0818336009979248 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08103513717651367 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08070492744445801 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08233404159545898 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08061766624450684 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08122777938842773 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08171367645263672 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08179688453674316 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08262443542480469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08131051063537598 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08066868782043457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08122968673706055 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08107900619506836 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08241486549377441 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08171772956848145 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0811612606048584 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08190035820007324 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08045387268066406 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:18,974] Trial 21 finished with value: 4.3199258804321286 and parameters: {'exponent': 1.3120095302443255, 'kernel_type': 'kpq', 'bandwidth': 12.84477173858008, 'diag': False, 'norm_p': 1.7516843819727825, 'reg': 0.2501072708350596}. Best is trial 14 with value: 4.252799654006958.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08187103271484375 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08122801780700684 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08092546463012695 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08115673065185547 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0811760425567627 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08237695693969727 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08168959617614746 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08073210716247559 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08117890357971191 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08161711692810059 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08209800720214844 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08034825325012207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0808420181274414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08083963394165039 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08139586448669434 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08250594139099121 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08153653144836426 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08152318000793457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08097982406616211 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08050417900085449 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08319926261901855 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08130860328674316 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08081603050231934 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08087515830993652 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08165407180786133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:21,272] Trial 22 finished with value: 4.2501549243927 and parameters: {'exponent': 1.3503199554896987, 'kernel_type': 'kpq', 'bandwidth': 8.606532566399528, 'diag': False, 'norm_p': 1.7260538920313004, 'reg': 0.07732093691954271}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08241534233093262 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08114385604858398 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08183455467224121 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08088517189025879 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08139681816101074 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08238863945007324 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08087015151977539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08055305480957031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08097100257873535 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0813751220703125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08329153060913086 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08077883720397949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08160567283630371 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08153939247131348 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08136129379272461 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08298540115356445 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08126640319824219 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08105039596557617 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08150386810302734 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08247208595275879 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08223462104797363 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08219432830810547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08097004890441895 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08078622817993164 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08219289779663086 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:23,576] Trial 23 finished with value: 4.3201030731201175 and parameters: {'exponent': 1.397520678848101, 'kernel_type': 'kpq', 'bandwidth': 7.247055799931126, 'diag': False, 'norm_p': 1.8141552423381442, 'reg': 0.0068884033777504485}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0827186107635498 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0811455249786377 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08074688911437988 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0819547176361084 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08112549781799316 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08370852470397949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08044290542602539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08127379417419434 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08129334449768066 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0803670883178711 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08279895782470703 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08105897903442383 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08042669296264648 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08039498329162598 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08122920989990234 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08266639709472656 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08108782768249512 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0814676284790039 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08076286315917969 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08076119422912598 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08298826217651367 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08162569999694824 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08138036727905273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08064579963684082 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08087539672851562 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:25,877] Trial 24 finished with value: 4.25326132774353 and parameters: {'exponent': 1.2618193165654021, 'kernel_type': 'kpq', 'bandwidth': 17.295147100407544, 'diag': False, 'norm_p': 1.6526103323019121, 'reg': 0.03873504315900886}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08253955841064453 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08190131187438965 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08091616630554199 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0808570384979248 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08101868629455566 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08189868927001953 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08148550987243652 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08139181137084961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08127737045288086 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08171963691711426 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0819389820098877 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08270955085754395 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08113670349121094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08061099052429199 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08116650581359863 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08334231376647949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08234572410583496 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0806879997253418 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08079147338867188 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08069944381713867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08258438110351562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0802769660949707 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0820474624633789 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08119368553161621 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08148717880249023 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:28,185] Trial 25 finished with value: 4.471241092681884 and parameters: {'exponent': 1.1903056941362917, 'kernel_type': 'kpq', 'bandwidth': 16.79364281331169, 'diag': False, 'norm_p': 1.6467232734753487, 'reg': 0.991518314112067}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08205342292785645 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08125615119934082 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08133697509765625 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08096933364868164 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0811617374420166 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08244752883911133 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08075881004333496 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08215045928955078 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0810556411743164 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08113789558410645 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08229756355285645 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08100366592407227 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08138847351074219 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0811614990234375 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08144688606262207 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0823366641998291 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08110499382019043 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08102941513061523 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08050847053527832 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08090758323669434 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08231854438781738 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08047890663146973 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0813601016998291 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08118510246276855 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08174300193786621 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:30,481] Trial 26 finished with value: 4.3163158893585205 and parameters: {'exponent': 1.2670677707530447, 'kernel_type': 'kpq', 'bandwidth': 36.819988916060765, 'diag': False, 'norm_p': 1.601428038539942, 'reg': 0.0764793811886122}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08191919326782227 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0815119743347168 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0805661678314209 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08096790313720703 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08172035217285156 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08389806747436523 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08178305625915527 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08067679405212402 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08138799667358398 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08182716369628906 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08303213119506836 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08187127113342285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08098626136779785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0818641185760498 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08085918426513672 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0831143856048584 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08120274543762207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08100104331970215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08153772354125977 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08051443099975586 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0829319953918457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08073282241821289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08106040954589844 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08153200149536133 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08132052421569824 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:32,786] Trial 27 finished with value: 4.589105892181396 and parameters: {'exponent': 1.103510558009577, 'kernel_type': 'kpq', 'bandwidth': 4.343350909186109, 'diag': False, 'norm_p': 1.7013470093326513, 'reg': 0.008873078821805604}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08278918266296387 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08087038993835449 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08104348182678223 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08095455169677734 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08120870590209961 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08255338668823242 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08177828788757324 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08094978332519531 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08075594902038574 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08107542991638184 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08225870132446289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08007407188415527 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0805819034576416 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08013367652893066 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08111977577209473 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08254599571228027 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08044576644897461 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08122420310974121 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08166790008544922 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08076834678649902 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08370327949523926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0811455249786377 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08048152923583984 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08044767379760742 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08167886734008789 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:35,083] Trial 28 finished with value: 4.361273765563965 and parameters: {'exponent': 1.2339646875961798, 'kernel_type': 'kpq', 'bandwidth': 18.9918985805602, 'diag': False, 'norm_p': 1.5062425615842037, 'reg': 0.35497019923889184}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013070821762084961 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012083292007446289 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011369705200195312 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011224746704101562 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012066841125488281 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012716531753540039 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012699604034423828 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011459112167358398 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010979413986206055 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01111912727355957 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01351785659790039 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011040925979614258 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.01136469841003418 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010996341705322266 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011493682861328125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013176918029785156 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011117696762084961 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011052370071411133 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011460065841674805 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011899471282958984 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012677907943725586 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011896848678588867 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011047601699829102 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010856866836547852 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:35,464] Trial 29 finished with value: 4.622915649414063 and parameters: {'exponent': 0.9989882056101818, 'kernel_type': 'k2q', 'bandwidth': 43.93082078399452, 'diag': False, 'reg': 0.0008147904532131114}. Best is trial 22 with value: 4.2501549243927.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011167526245117188 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08184623718261719 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08021140098571777 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08093500137329102 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07956552505493164 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07975625991821289 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0814979076385498 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08005928993225098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08087921142578125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08149933815002441 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Using SVD
Time taken for round 4: 0.07985758781433105 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0815894603729248 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08014416694641113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08055520057678223 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08020853996276855 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08069467544555664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08170771598815918 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08127284049987793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08005571365356445 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07999753952026367 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08048176765441895 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08162450790405273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07956242561340332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08019495010375977 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08008217811584473 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08059859275817871 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:40,316] Trial 30 finished with value: 4.888096332550049 and parameters: {'exponent': 1.3455578696541117, 'kernel_type': 'kpq', 'bandwidth': 2.8671150237543754, 'diag': False, 'norm_p': 1.7399923720632353, 'reg': 0.0029483936320241527}. Best is trial 22 with value: 4.2501549243927.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0817723274230957 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07977843284606934 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08102083206176758 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07977890968322754 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08011293411254883 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0895848274230957 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08753395080566406 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08689761161804199 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08737778663635254 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08708953857421875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08914852142333984 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08822107315063477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08661746978759766 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08735370635986328 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.09199929237365723 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08940720558166504 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08797764778137207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08689212799072266 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08800196647644043 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08763551712036133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08973145484924316 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08750200271606445 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0870361328125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08265471458435059 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07982254028320312 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:42,746] Trial 31 finished with value: 4.243610095977783 and parameters: {'exponent': 1.3553773104465028, 'kernel_type': 'kpq', 'bandwidth': 8.388151949088686, 'diag': False, 'norm_p': 1.648766798115747, 'reg': 0.05036872213158218}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08295488357543945 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08056783676147461 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.07991194725036621 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08028459548950195 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08048057556152344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08161520957946777 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08073210716247559 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07992815971374512 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08005976676940918 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08004021644592285 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08197808265686035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07971572875976562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08008360862731934 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08019852638244629 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08056473731994629 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0816197395324707 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0795297622680664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08072614669799805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08046698570251465 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07982373237609863 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08261990547180176 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0802915096282959 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08042097091674805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08010363578796387 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08007073402404785 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:45,022] Trial 32 finished with value: 4.25290732383728 and parameters: {'exponent': 1.2852537197023068, 'kernel_type': 'kpq', 'bandwidth': 15.01208300567543, 'diag': False, 'norm_p': 1.6472519418096403, 'reg': 0.05830229139605992}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08170771598815918 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08019781112670898 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08107709884643555 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0814814567565918 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08061957359313965 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08131122589111328 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08017230033874512 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08002638816833496 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08042478561401367 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08020210266113281 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08187437057495117 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08133578300476074 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08077025413513184 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08020830154418945 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0801694393157959 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08289146423339844 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08118963241577148 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08049726486206055 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08185386657714844 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08092308044433594 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0824744701385498 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08120918273925781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08098626136779785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0814812183380127 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08080816268920898 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:47,313] Trial 33 finished with value: 4.278468418121338 and parameters: {'exponent': 1.286715264620163, 'kernel_type': 'kpq', 'bandwidth': 8.87052784982483, 'diag': False, 'norm_p': 1.623390367456711, 'reg': 0.28753700935346144}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08232450485229492 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08415484428405762 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08064556121826172 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08159828186035156 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08144140243530273 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08296418190002441 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08096671104431152 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08062052726745605 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08103775978088379 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08172059059143066 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08240056037902832 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08121299743652344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08100628852844238 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08185815811157227 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08053970336914062 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08229184150695801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08107423782348633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08200287818908691 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08095908164978027 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0807347297668457 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08227109909057617 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08068132400512695 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08079409599304199 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08080101013183594 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08049845695495605 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:49,613] Trial 34 finished with value: 4.291583251953125 and parameters: {'exponent': 1.3543169363696093, 'kernel_type': 'kpq', 'bandwidth': 3.313510027030818, 'diag': False, 'norm_p': 1.708143770559863, 'reg': 0.05455913310816079}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.0815892219543457 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08228206634521484 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08254861831665039 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.0827937126159668 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08256101608276367 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08327794075012207 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.0823523998260498 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08223128318786621 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08278584480285645 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08266544342041016 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08176875114440918 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08283472061157227 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0820319652557373 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.0830078125 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08220052719116211 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08267879486083984 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08211517333984375 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08234834671020508 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08247947692871094 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08311200141906738 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08195900917053223 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.0830388069152832 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0823662281036377 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08254122734069824 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08335304260253906 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:51,942] Trial 35 finished with value: 4.642027854919434 and parameters: {'exponent': 1.1817005089000827, 'kernel_type': 'kpq', 'bandwidth': 5.4235091249900655, 'diag': True, 'norm_p': 1.5337773340013559, 'reg': 0.012316247617541102}. Best is trial 31 with value: 4.243610095977783.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012446880340576172 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011982440948486328 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011453866958618164 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011304140090942383 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011002779006958008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.018642425537109375 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.013318538665771484 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.012263774871826172 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012035608291625977 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011827707290649414 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013407468795776367 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012474775314331055 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011802434921264648 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012103796005249023 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011048316955566406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012687206268310547 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011208534240722656 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011616706848144531 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011210441589355469 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011499643325805664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012997627258300781 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011001348495483398 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011061906814575195 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010988235473632812 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:52,330] Trial 36 finished with value: 4.786412239074707 and parameters: {'exponent': 1.2918508521756118, 'kernel_type': 'k2q', 'bandwidth': 191.39702530865594, 'diag': False, 'reg': 0.11897541088241985}. Best is trial 31 with value: 4.243610095977783.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01203608512878418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08252716064453125 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08058500289916992 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08046483993530273 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08018660545349121 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08035492897033691 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08204460144042969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08008527755737305 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08052945137023926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08037209510803223 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0796656608581543 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08164238929748535 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07982325553894043 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08003664016723633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08083081245422363 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08021783828735352 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08206534385681152 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0797581672668457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08125066757202148 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07974100112915039 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0804142951965332 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08184289932250977 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07961440086364746 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07997322082519531 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08104634284973145 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08121824264526367 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:42:54,608] Trial 37 finished with value: 4.393827247619629 and parameters: {'exponent': 0.8081573756523133, 'kernel_type': 'kpq', 'bandwidth': 1.9185508179283675, 'diag': False, 'norm_p': 1.2769249720503644, 'reg': 0.553796917501038}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08109807968139648 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08301258087158203 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08187985420227051 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08249497413635254 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08233952522277832 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08146166801452637 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08133769035339355 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08187103271484375 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08179116249084473 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08303356170654297 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08134913444519043 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08221626281738281 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08284258842468262 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08224201202392578 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08221626281738281 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08109307289123535 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.0818939208984375 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08203554153442383 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08379268646240234 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08278179168701172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0815117359161377 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08237481117248535 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08182334899902344 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08193349838256836 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0820775032043457 seconds
Tree has no split, stopping training

[I 2026-04-22 15:42:56,930] Trial 38 finished with value: 4.336410808563232 and parameters: {'exponent': 1.2221211800258072, 'kernel_type': 'kpq', 'bandwidth': 14.883420667434319, 'diag': True, 'norm_p': 1.5796650867302195, 'reg': 0.2087123289773869}. Best is trial 31 with value: 4.243610095977783.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01250004768371582 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012446403503417969 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011371374130249023 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011786222457885742 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011038541793823242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012761354446411133 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012519598007202148 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.01102447509765625 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011674642562866211 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011082172393798828 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012598991394042969 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011383056640625 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011381387710571289 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.01143956184387207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011627912521362305 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.020231962203979492 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012041091918945312 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.012441158294677734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011598348617553711 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011789560317993164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013129234313964844 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011993169784545898 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.010877847671508789 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:42:57,318] Trial 39 finished with value: 4.305563926696777 and parameters: {'exponent': 1.3484820280844283, 'kernel_type': 'k2q', 'bandwidth': 22.412388509649862, 'diag': False, 'reg': 0.06217220358570884}. Best is trial 31 with value: 4.243610095977783.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011616945266723633 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011642932891845703 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08185815811157227 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08210873603820801 seconds
Early stopping at iteration 2

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08260297775268555 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.0820014476776123 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.08264827728271484 seconds
Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08130288124084473 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08250164985656738 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.08236479759216309 seconds
Early stopping at iteration 3
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08150196075439453 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08322858810424805 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08266735076904297 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08379483222961426 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08248114585876465 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.08230113983154297 seconds
Early stopping at iteration 3
Tree has no split, stopping training

[I 2026-04-22 15:42:58,738] Trial 40 finished with value: 5.303791618347168 and parameters: {'exponent': 1.338168317614181, 'kernel_type': 'kpq', 'bandwidth': 122.75918614232128, 'diag': True, 'norm_p': 1.6650529636804123, 'reg': 0.5536472345733385}. Best is trial 31 with value: 4.243610095977783.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08314800262451172 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08112096786499023 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08166956901550293 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08220767974853516 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0812385082244873 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08278942108154297 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08280396461486816 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08144402503967285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0816946029663086 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08089351654052734 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08295369148254395 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08176994323730469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08182358741760254 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08102202415466309 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08111953735351562 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08293318748474121 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08109593391418457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08076071739196777 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08148813247680664 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08201456069946289 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0827176570892334 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08125185966491699 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08067989349365234 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08078885078430176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08089113235473633 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:01,042] Trial 41 finished with value: 4.2557398796081545 and parameters: {'exponent': 1.25775956264278, 'kernel_type': 'kpq', 'bandwidth': 9.7618741796167, 'diag': False, 'norm_p': 1.6288740209969466, 'reg': 0.04161428261184856}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0825812816619873 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0812065601348877 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08135581016540527 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0827031135559082 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08142542839050293 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08316779136657715 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08203506469726562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08101058006286621 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08109760284423828 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08084797859191895 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08313679695129395 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08053278923034668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08053064346313477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08165264129638672 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08081316947937012 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08294296264648438 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08088302612304688 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08132362365722656 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08089160919189453 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08099603652954102 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08317899703979492 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08141255378723145 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08078694343566895 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08150744438171387 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:03,348] Trial 42 finished with value: 4.252522659301758 and parameters: {'exponent': 1.2894275486417635, 'kernel_type': 'kpq', 'bandwidth': 15.109363390876098, 'diag': False, 'norm_p': 1.670738641099821, 'reg': 0.03855978246084388}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08075213432312012 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08221960067749023 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08114242553710938 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08108305931091309 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08180379867553711 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08119559288024902 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08320283889770508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08256721496582031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0818331241607666 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08132624626159668 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08082270622253418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08265852928161621 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08184075355529785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08121895790100098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08131122589111328 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08115673065185547 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08282613754272461 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08103203773498535 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0812993049621582 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08113503456115723 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08113598823547363 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08386731147766113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08040452003479004 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08170294761657715 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08209753036499023 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0806276798248291 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:05,655] Trial 43 finished with value: 4.30511589050293 and parameters: {'exponent': 1.2948603672797168, 'kernel_type': 'kpq', 'bandwidth': 7.284152186532218, 'diag': False, 'norm_p': 1.7201917297211091, 'reg': 0.01505463987990537}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08255147933959961 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08175444602966309 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08147072792053223 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08137822151184082 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08181190490722656 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08394217491149902 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08114099502563477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08093452453613281 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08162093162536621 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08168601989746094 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08235049247741699 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08132243156433105 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08040952682495117 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0805814266204834 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0804290771484375 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08260393142700195 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08148980140686035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08055543899536133 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08229923248291016 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08113265037536621 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08233880996704102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08177900314331055 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08039498329162598 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08145427703857422 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08072900772094727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:07,959] Trial 44 finished with value: 4.347140693664551 and parameters: {'exponent': 1.3715436447306912, 'kernel_type': 'kpq', 'bandwidth': 31.191924649661427, 'diag': False, 'norm_p': 1.6824861139810743, 'reg': 0.09626194266175343}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012952566146850586 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.017128705978393555 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.012304306030273438 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012065887451171875 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.011654853820800781 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012659072875976562 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012917041778564453 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011578798294067383 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011255741119384766 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01195216178894043 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012651920318603516 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.0123443603515625 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011244058609008789 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011764764785766602 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012350082397460938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012574911117553711 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012270450592041016 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011936426162719727 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011464595794677734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012162446975708008 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01461935043334961 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.016844987869262695 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011971712112426758 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:08,358] Trial 45 finished with value: 4.483321189880371 and parameters: {'exponent': 1.0726555805166749, 'kernel_type': 'k2q', 'bandwidth': 13.056033672125958, 'diag': False, 'reg': 0.0043676417479034755}. Best is trial 31 with value: 4.243610095977783.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.01170492172241211 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012275457382202148 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08248686790466309 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08081507682800293 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08279585838317871 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08199906349182129 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08169698715209961 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08160066604614258 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08076167106628418 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08021855354309082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08116650581359863 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0799703598022461 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08170795440673828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08010292053222656 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08032417297363281 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08025693893432617 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08078694343566895 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08187198638916016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07998919486999512 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08036589622497559 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07990741729736328 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08105635643005371 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08313369750976562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08116769790649414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08032965660095215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08018207550048828 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:10,643] Trial 46 finished with value: 4.299969482421875 and parameters: {'exponent': 1.2210858953462165, 'kernel_type': 'kpq', 'bandwidth': 5.724182435879819, 'diag': False, 'norm_p': 1.769144907285847, 'reg': 0.032368323370442625}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08092641830444336 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08097696304321289 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08185672760009766 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.0829920768737793 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08282232284545898 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 4: 0.08230352401733398 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08125424385070801 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08246278762817383 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08191561698913574 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 2.875506639480591 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Time taken for round 4: 0.08210539817810059 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0813133716583252 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.0824882984161377 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08228802680969238 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08515429496765137 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0912928581237793 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0894622802734375 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08901405334472656 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08910751342773438 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08938956260681152 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08970522880554199 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08899903297424316 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08910536766052246 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08975911140441895 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.09005331993103027 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08973002433776855 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:15,856] Trial 47 finished with value: 5.363765048980713 and parameters: {'exponent': 1.3693063664215708, 'kernel_type': 'kpq', 'bandwidth': 11.066544756849089, 'diag': True, 'norm_p': 1.8141060684781714, 'reg': 6.9471796755151665e-06}. Best is trial 31 with value: 4.243610095977783.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08980059623718262 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08848714828491211 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0875554084777832 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08804011344909668 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0874471664428711 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08986830711364746 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08789277076721191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08723783493041992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.087860107421875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08714771270751953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09025144577026367 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08774518966674805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08748602867126465 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08799862861633301 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08968138694763184 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08400273323059082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08007454872131348 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0805046558380127 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08000016212463379 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08022189140319824 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08194470405578613 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0802454948425293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08003807067871094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08010697364807129 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07996177673339844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:18,273] Trial 48 finished with value: 4.320019817352295 and parameters: {'exponent': 1.1468924704684926, 'kernel_type': 'kpq', 'bandwidth': 7.764736853639575, 'diag': False, 'norm_p': 1.6746734950068454, 'reg': 0.02180484698893983}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08158659934997559 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08035445213317871 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08036184310913086 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08036112785339355 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0803062915802002 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08168196678161621 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08042001724243164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08102011680603027 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08042216300964355 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0807497501373291 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08199429512023926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0800468921661377 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08242917060852051 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08186006546020508 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08048152923583984 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08168458938598633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08104658126831055 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0813746452331543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08010363578796387 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08116626739501953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08220100402832031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08027815818786621 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08120465278625488 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08018374443054199 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08085870742797852 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:20,563] Trial 49 finished with value: 4.791861438751221 and parameters: {'exponent': 0.8070443180482189, 'kernel_type': 'kpq', 'bandwidth': 23.11182641840342, 'diag': False, 'norm_p': 1.4826911148964361, 'reg': 0.0004239562747084251}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.011792898178100586 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012631654739379883 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011160135269165039 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010908842086791992 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01102447509765625 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012903928756713867 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011456727981567383 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011213064193725586 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011039018630981445 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012007713317871094 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012813329696655273 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011490345001220703 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011038780212402344 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.010789632797241211 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01191258430480957 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012876272201538086 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011493921279907227 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011261463165283203 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011162996292114258 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01139068603515625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013497591018676758 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.01167440414428711 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.010960578918457031 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011104822158813477 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:20,941] Trial 50 finished with value: 4.271852111816406 and parameters: {'exponent': 1.2912553582601543, 'kernel_type': 'k2q', 'bandwidth': 4.357714041655042, 'diag': False, 'reg': 0.1598226611850813}. Best is trial 31 with value: 4.243610095977783.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01173090934753418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08166766166687012 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08031249046325684 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0804128646850586 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08012700080871582 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08017897605895996 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08216094970703125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07961273193359375 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08070826530456543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0795598030090332 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0799567699432373 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08208489418029785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08020591735839844 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08185362815856934 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08079075813293457 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08125829696655273 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08202219009399414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08070516586303711 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07985806465148926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0796053409576416 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08114957809448242 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08179354667663574 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08011937141418457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08168172836303711 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08022594451904297 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08072924613952637 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:23,221] Trial 51 finished with value: 4.258624029159546 and parameters: {'exponent': 1.2610462609078412, 'kernel_type': 'kpq', 'bandwidth': 16.337626056940938, 'diag': False, 'norm_p': 1.646361529946539, 'reg': 0.07413697319803922}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08230233192443848 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07978487014770508 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.07978224754333496 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08019900321960449 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0797426700592041 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08201956748962402 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08034038543701172 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08096694946289062 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08032059669494629 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08087968826293945 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08321928977966309 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08006668090820312 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08035993576049805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07995295524597168 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08016324043273926 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08200669288635254 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07994437217712402 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07989501953125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07990837097167969 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08015704154968262 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08193302154541016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07982850074768066 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07988262176513672 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08030056953430176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0795755386352539 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:25,502] Trial 52 finished with value: 4.2554460048675535 and parameters: {'exponent': 1.3217515916469251, 'kernel_type': 'kpq', 'bandwidth': 17.915464639570576, 'diag': False, 'norm_p': 1.6495146256006106, 'reg': 0.04356865941714741}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08210134506225586 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07992792129516602 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08145570755004883 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08055734634399414 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0799567699432373 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08167552947998047 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08092808723449707 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08043026924133301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08067822456359863 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08068323135375977 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08191251754760742 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07973790168762207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07972860336303711 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08070182800292969 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07996177673339844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08276677131652832 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08063530921936035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08044028282165527 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08075475692749023 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08063316345214844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08178210258483887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08031439781188965 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08099055290222168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07998371124267578 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:27,784] Trial 53 finished with value: 4.261575222015381 and parameters: {'exponent': 1.2474980500778254, 'kernel_type': 'kpq', 'bandwidth': 29.53774867882804, 'diag': False, 'norm_p': 1.7219179424078563, 'reg': 0.018304258580932237}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.07984232902526855 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08234047889709473 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08071064949035645 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08078384399414062 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08100366592407227 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08097600936889648 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08244562149047852 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07960104942321777 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07966113090515137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08037304878234863 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08072185516357422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0816347599029541 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07999634742736816 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07991695404052734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08024954795837402 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07968831062316895 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08189988136291504 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08065986633300781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08026242256164551 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08042073249816895 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07975077629089355 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08175802230834961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07990884780883789 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08040356636047363 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07945847511291504 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08050417900085449 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:30,060] Trial 54 finished with value: 4.246875762939453 and parameters: {'exponent': 1.3727178877579664, 'kernel_type': 'kpq', 'bandwidth': 13.778611693866814, 'diag': False, 'norm_p': 1.624960746970242, 'reg': 0.03588257228439947}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0817251205444336 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08062338829040527 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08022809028625488 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08154988288879395 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08047628402709961 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08143734931945801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08223533630371094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07989001274108887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08044862747192383 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07950043678283691 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08167314529418945 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07972836494445801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07983183860778809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07938957214355469 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08011937141418457 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08214998245239258 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0798337459564209 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0813455581665039 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07944369316101074 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.080230712890625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08155274391174316 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0796811580657959 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07985186576843262 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08058404922485352 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08012795448303223 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:32,337] Trial 55 finished with value: 4.553594779968262 and parameters: {'exponent': 1.375233808024557, 'kernel_type': 'kpq', 'bandwidth': 10.42821982771366, 'diag': False, 'norm_p': 1.6202362441566065, 'reg': 0.001778538834624613}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08114218711853027 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08079886436462402 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0808558464050293 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0801842212677002 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0802910327911377 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0815894603729248 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07961225509643555 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08140230178833008 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07944321632385254 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0797419548034668 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08171224594116211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08010268211364746 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08141160011291504 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07912087440490723 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.07996535301208496 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08225059509277344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08094668388366699 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08049201965332031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07977938652038574 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07988953590393066 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08236193656921387 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08053231239318848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08147382736206055 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08058428764343262 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:34,616] Trial 56 finished with value: 4.27961311340332 and parameters: {'exponent': 1.3975384949709972, 'kernel_type': 'kpq', 'bandwidth': 13.951316807708876, 'diag': False, 'norm_p': 1.6910149064026583, 'reg': 0.005777624120503052}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08052945137023926 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08228421211242676 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08229756355285645 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08266615867614746 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08263969421386719 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08270740509033203 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08175015449523926 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08287620544433594 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08289217948913574 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08269715309143066 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08273673057556152 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.0831139087677002 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08282661437988281 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08233118057250977 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.0821068286895752 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0829620361328125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08192276954650879 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08362746238708496 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0825655460357666 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08294129371643066 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08238005638122559 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08316993713378906 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08206510543823242 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0833272933959961 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08237862586975098 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08298277854919434 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:36,950] Trial 57 finished with value: 4.3864601135253904 and parameters: {'exponent': 1.32764388469424, 'kernel_type': 'kpq', 'bandwidth': 8.27155659127281, 'diag': True, 'norm_p': 1.7798355392357736, 'reg': 0.011275389144060255}. Best is trial 31 with value: 4.243610095977783.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08380389213562012 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08054208755493164 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08085322380065918 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08144092559814453 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08064055442810059 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08255743980407715 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0805821418762207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08053255081176758 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08031964302062988 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08117485046386719 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08278775215148926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08131694793701172 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08083820343017578 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08027315139770508 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08191752433776855 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08222556114196777 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0810689926147461 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08132600784301758 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0801699161529541 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08029985427856445 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0824885368347168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08160638809204102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0807487964630127 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08026003837585449 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:39,243] Trial 58 finished with value: 4.341333389282227 and parameters: {'exponent': 1.302144205806771, 'kernel_type': 'kpq', 'bandwidth': 12.461192632148121, 'diag': False, 'norm_p': 1.8335408239755764, 'reg': 0.34369487963361833}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08089351654052734 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08115005493164062 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08047294616699219 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08097720146179199 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08046317100524902 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08054041862487793 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08144521713256836 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08092761039733887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08142447471618652 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0800635814666748 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08215975761413574 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0817408561706543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08080577850341797 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08164811134338379 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08046150207519531 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08064150810241699 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08123445510864258 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08063340187072754 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.081329345703125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08038568496704102 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08045005798339844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0813438892364502 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08103370666503906 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0811910629272461 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08078432083129883 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:41,530] Trial 59 finished with value: 4.636257362365723 and parameters: {'exponent': 0.7012281674249343, 'kernel_type': 'kpq', 'bandwidth': 6.457708657598951, 'diag': False, 'norm_p': 0.7822968656772149, 'reg': 0.14771887986169857}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08098125457763672 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08243870735168457 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08075976371765137 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08244729042053223 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08116006851196289 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08072471618652344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08246397972106934 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08045458793640137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08107328414916992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0800924301147461 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08061361312866211 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08230471611022949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08153319358825684 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0809779167175293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08091020584106445 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08069181442260742 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08214950561523438 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08072876930236816 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08127284049987793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08080744743347168 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08075571060180664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08413887023925781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08079266548156738 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0812685489654541 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08111357688903809 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:43,826] Trial 60 finished with value: 4.24596643447876 and parameters: {'exponent': 1.368070264842936, 'kernel_type': 'kpq', 'bandwidth': 10.379950163591774, 'diag': False, 'norm_p': 1.5603306953829723, 'reg': 0.029180155603451323}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.0812234878540039 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08254170417785645 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0806725025177002 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08137822151184082 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08105087280273438 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08179402351379395 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08273792266845703 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0805978775024414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08098387718200684 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08195781707763672 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08145618438720703 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0826261043548584 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0811007022857666 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08131003379821777 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08123016357421875 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0811154842376709 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08217740058898926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08218717575073242 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08061361312866211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08097195625305176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08046126365661621 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08236145973205566 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0809030532836914 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08071517944335938 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08142948150634766 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08061838150024414 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:46,125] Trial 61 finished with value: 4.260080814361572 and parameters: {'exponent': 1.3663364531102018, 'kernel_type': 'kpq', 'bandwidth': 6.290872113688401, 'diag': False, 'norm_p': 1.5672319388785176, 'reg': 0.02912233104322083}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08284235000610352 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0812382698059082 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0822150707244873 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08124470710754395 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08108687400817871 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08282184600830078 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 2.786129951477051 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0810086727142334 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0829019546508789 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08854341506958008 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09057903289794922 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08811664581298828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08787178993225098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08771896362304688 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08870649337768555 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0903627872467041 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08886122703552246 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08782052993774414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08858895301818848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08868241310119629 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0916128158569336 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08865571022033691 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08819437026977539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08819365501403809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08905506134033203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:43:51,270] Trial 62 finished with value: 4.283764982223511 and parameters: {'exponent': 1.3379121647289427, 'kernel_type': 'kpq', 'bandwidth': 20.90225078373074, 'diag': False, 'norm_p': 1.6126037236534045, 'reg': 0.08113105364193136}. Best is trial 31 with value: 4.243610095977783.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.09093809127807617 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08876705169677734 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08829736709594727 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0884084701538086 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08790373802185059 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09064269065856934 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08866548538208008 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08938217163085938 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08624434471130371 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08110690116882324 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08245706558227539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08087754249572754 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08080482482910156 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08040833473205566 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08170557022094727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08333349227905273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08112597465515137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08081555366516113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08076667785644531 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0807645320892334 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08254480361938477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0805044174194336 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08058571815490723 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08077096939086914 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0800478458404541 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:53,637] Trial 63 finished with value: 4.276987552642822 and parameters: {'exponent': 1.3804477368822425, 'kernel_type': 'kpq', 'bandwidth': 10.182852330430414, 'diag': False, 'norm_p': 1.5444960805522403, 'reg': 0.216603549548332}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0821523666381836 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0812685489654541 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08092832565307617 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08061981201171875 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08075857162475586 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08264541625976562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08133983612060547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08145570755004883 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08433127403259277 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08029961585998535 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08265352249145508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08072018623352051 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08142495155334473 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08063054084777832 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0806422233581543 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08254003524780273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0809934139251709 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0814046859741211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08028936386108398 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08074760437011719 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08266496658325195 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08080387115478516 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08066248893737793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08111405372619629 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08072066307067871 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:55,936] Trial 64 finished with value: 4.2557720184326175 and parameters: {'exponent': 1.3258679439120769, 'kernel_type': 'kpq', 'bandwidth': 13.804367488600004, 'diag': False, 'norm_p': 1.7427657051222005, 'reg': 0.05130431742222257}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08326196670532227 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08070611953735352 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08103108406066895 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08040928840637207 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0810997486114502 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08286619186401367 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08171916007995605 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08115053176879883 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08177733421325684 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08060002326965332 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08283495903015137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08133506774902344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08094453811645508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08051061630249023 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08082365989685059 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08243584632873535 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08155250549316406 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.084014892578125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08078885078430176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08168911933898926 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08294534683227539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08093118667602539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08093118667602539 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08070254325866699 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08085465431213379 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:43:58,237] Trial 65 finished with value: 4.266349506378174 and parameters: {'exponent': 1.3528541339936333, 'kernel_type': 'kpq', 'bandwidth': 8.842764262227064, 'diag': False, 'norm_p': 1.5793250113341564, 'reg': 0.016682891246179336}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08177852630615234 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08135986328125 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08089447021484375 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0818479061126709 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08133697509765625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08356618881225586 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08113503456115723 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08212590217590332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08172130584716797 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.081085205078125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08307933807373047 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08156371116638184 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08374309539794922 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08116483688354492 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08111071586608887 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08321022987365723 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08065938949584961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08195304870605469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08143854141235352 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0815281867980957 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08332037925720215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0821528434753418 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08074402809143066 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08117270469665527 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08158612251281738 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:00,549] Trial 66 finished with value: 4.25307331085205 and parameters: {'exponent': 1.2739254745231734, 'kernel_type': 'kpq', 'bandwidth': 11.46932005694803, 'diag': False, 'norm_p': 1.5926365749646823, 'reg': 0.030905969472704208}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08273458480834961 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08089542388916016 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08144497871398926 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0825800895690918 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08131909370422363 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08276605606079102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0812067985534668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08120107650756836 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08098316192626953 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08193469047546387 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08283638954162598 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.080810546875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08117938041687012 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08050179481506348 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08187317848205566 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08314228057861328 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08114814758300781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08146023750305176 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08039569854736328 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08118391036987305 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08279585838317871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08122706413269043 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08119940757751465 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08077192306518555 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08098173141479492 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:02,853] Trial 67 finished with value: 4.2849109172821045 and parameters: {'exponent': 1.3061100631405014, 'kernel_type': 'kpq', 'bandwidth': 15.787631646168457, 'diag': False, 'norm_p': 1.6690844910481768, 'reg': 0.127601288444451}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01285862922668457 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 1: 0.012096643447875977 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011626958847045898 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012336254119873047 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012048006057739258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012921810150146484 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.013734102249145508 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011905193328857422 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.018504858016967773 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.014601469039916992 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.013123750686645508 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012193918228149414 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011829853057861328 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011635065078735352 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.012235641479492188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01343083381652832 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012475013732910156 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 2: 0.011506795883178711 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011249542236328125 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011993885040283203 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01354074478149414 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.015353918075561523 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.013273239135742188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:03,260] Trial 68 finished with value: 4.425006771087647 and parameters: {'exponent': 1.3995183850976176, 'kernel_type': 'k2q', 'bandwidth': 4.837039809274448, 'diag': False, 'reg': 0.0045756205340150785}. Best is trial 31 with value: 4.243610095977783.

Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012372970581054688 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011710166931152344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0819854736328125 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08014416694641113 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08069038391113281 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07980680465698242 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08001470565795898 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08184194564819336 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08052539825439453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08129620552062988 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08046698570251465 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08045506477355957 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08294129371643066 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08215618133544922 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08181071281433105 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08061099052429199 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08147573471069336 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08278489112854004 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08142352104187012 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08099102973937988 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08109402656555176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0810084342956543 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08313655853271484 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08264660835266113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08110284805297852 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08087992668151855 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08142399787902832 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:05,552] Trial 69 finished with value: 4.302863693237304 and parameters: {'exponent': 1.196222854501534, 'kernel_type': 'kpq', 'bandwidth': 3.3664498075588125, 'diag': False, 'norm_p': 1.5081432635663303, 'reg': 0.08052257199393827}. Best is trial 31 with value: 4.243610095977783.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08212041854858398 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.0839235782623291 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.08308911323547363 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08327460289001465 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 4: 0.08289408683776855 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08206796646118164 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08283638954162598 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08303403854370117 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08294987678527832 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08321022987365723 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08229660987854004 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08321714401245117 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08239102363586426 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08371448516845703 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08262014389038086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08296084403991699 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08221983909606934 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08297228813171387 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08251380920410156 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08310651779174805 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08281922340393066 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08303189277648926 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08242392539978027 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08274674415588379 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08249545097351074 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:07,892] Trial 70 finished with value: 4.460294437408447 and parameters: {'exponent': 1.2831520047261806, 'kernel_type': 'kpq', 'bandwidth': 7.8870075880857256, 'diag': True, 'norm_p': 1.63513930048511, 'reg': 0.010526155533989003}. Best is trial 31 with value: 4.243610095977783.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08248472213745117 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08186650276184082 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08116912841796875 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08063697814941406 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08035874366760254 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08171391487121582 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08072543144226074 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08027315139770508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0807194709777832 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08066916465759277 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08232975006103516 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08046603202819824 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08101892471313477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0807032585144043 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08125591278076172 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08374810218811035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07998299598693848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08055949211120605 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08167767524719238 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08142518997192383 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0822601318359375 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08144855499267578 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08067440986633301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08022356033325195 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:10,184] Trial 71 finished with value: 4.2615374565124515 and parameters: {'exponent': 1.271023652539581, 'kernel_type': 'kpq', 'bandwidth': 11.631444464730967, 'diag': False, 'norm_p': 1.5999745659800724, 'reg': 0.02401316188032651}. Best is trial 31 with value: 4.243610095977783.

Using SVD
Time taken for round 4: 0.08005475997924805 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08194303512573242 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08021807670593262 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0807797908782959 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07978057861328125 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0803685188293457 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0819387435913086 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08060717582702637 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08174443244934082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0800323486328125 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08053278923034668 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08231806755065918 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0800938606262207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07996940612792969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08076667785644531 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08040666580200195 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08389163017272949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08197641372680664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08129024505615234 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07987689971923828 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08051228523254395 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08207511901855469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0808863639831543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08005809783935547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07957816123962402 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08073115348815918 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:12,469] Trial 72 finished with value: 4.238507509231567 and parameters: {'exponent': 1.352764391836791, 'kernel_type': 'kpq', 'bandwidth': 11.766809264858821, 'diag': False, 'norm_p': 1.5800871803543342, 'reg': 0.044938800765250496}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08262872695922852 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08005952835083008 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08015990257263184 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08052897453308105 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08114981651306152 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08214306831359863 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08076357841491699 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08040714263916016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08002042770385742 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08077406883239746 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08217573165893555 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0808260440826416 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08014822006225586 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08028936386108398 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08097171783447266 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0820772647857666 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08105254173278809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0802609920501709 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08092784881591797 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08020949363708496 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09155035018920898 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08047318458557129 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08131957054138184 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08049368858337402 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08026623725891113 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:14,767] Trial 73 finished with value: 4.293523931503296 and parameters: {'exponent': 1.359763738480231, 'kernel_type': 'kpq', 'bandwidth': 26.3813290974044, 'diag': False, 'norm_p': 1.72588705214047, 'reg': 0.05355946191703267}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08220672607421875 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08021116256713867 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08114981651306152 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07979393005371094 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07995867729187012 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08363580703735352 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08009123802185059 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08117032051086426 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08139753341674805 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08051633834838867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08259320259094238 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08016610145568848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08018255233764648 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08009529113769531 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08015561103820801 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08262777328491211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0802450180053711 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08089542388916016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08175396919250488 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08080196380615234 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08190536499023438 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08018732070922852 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08046340942382812 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07977771759033203 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08037996292114258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:17,054] Trial 74 finished with value: 4.3386434555053714 and parameters: {'exponent': 1.3105710487726334, 'kernel_type': 'kpq', 'bandwidth': 19.16597547454989, 'diag': False, 'norm_p': 1.5601663427354948, 'reg': 0.21878133078013626}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08223676681518555 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08017754554748535 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0801231861114502 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08050203323364258 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08145594596862793 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08205962181091309 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08022332191467285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08140707015991211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08078837394714355 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08071279525756836 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08166885375976562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08017468452453613 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08047842979431152 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08027362823486328 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0798642635345459 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08205437660217285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08044862747192383 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08043742179870605 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07980227470397949 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08020687103271484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0826883316040039 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08058691024780273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08054590225219727 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08133912086486816 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:19,339] Trial 75 finished with value: 4.338736724853516 and parameters: {'exponent': 1.3369144160179727, 'kernel_type': 'kpq', 'bandwidth': 9.734074289094327, 'diag': False, 'norm_p': 1.7625169531424532, 'reg': 0.45679613882100123}. Best is trial 72 with value: 4.238507509231567.

Using SVD
Time taken for round 4: 0.08076691627502441 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08207106590270996 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07988452911376953 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.07963418960571289 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.0810556411743164 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08095359802246094 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08184647560119629 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08001279830932617 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08221626281738281 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08117055892944336 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08110189437866211 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08369278907775879 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08124041557312012 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08087539672851562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08178186416625977 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08129167556762695 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08294034004211426 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08143329620361328 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08053374290466309 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08115386962890625 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08147072792053223 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08213233947753906 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08117341995239258 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08104896545410156 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08097386360168457 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0811309814453125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:21,637] Trial 76 finished with value: 5.4473748207092285 and parameters: {'exponent': 1.37858474853958, 'kernel_type': 'kpq', 'bandwidth': 7.1316576912542935, 'diag': False, 'norm_p': 1.6598067857373524, 'reg': 2.1941288722503112e-05}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08262491226196289 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08041167259216309 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08085012435913086 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 2.8073720932006836 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Using SVD
Time taken for round 4: 0.0813746452331543 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08740973472595215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08818554878234863 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08821487426757812 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0877828598022461 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08807206153869629 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09048628807067871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08881974220275879 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08838677406311035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08783221244812012 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08773994445800781 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09118866920471191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08916020393371582 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0880589485168457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08815431594848633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08794546127319336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09054374694824219 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08808231353759766 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08866715431213379 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08773446083068848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08786725997924805 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:26,822] Trial 77 finished with value: 4.279088973999023 and parameters: {'exponent': 1.3528936736079669, 'kernel_type': 'kpq', 'bandwidth': 14.701030296746067, 'diag': False, 'norm_p': 1.692971551457966, 'reg': 0.10834721118120509}. Best is trial 72 with value: 4.238507509231567.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08516168594360352 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08124852180480957 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08174538612365723 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08136391639709473 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08159255981445312 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08302831649780273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.081512451171875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08109569549560547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08098721504211426 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08034753799438477 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08261275291442871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08279252052307129 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08089542388916016 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08072066307067871 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08084392547607422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08249521255493164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08154582977294922 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08180570602416992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08047795295715332 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08116340637207031 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08280539512634277 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08141827583312988 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08149385452270508 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08111023902893066 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:29,128] Trial 78 finished with value: 4.7244462966918945 and parameters: {'exponent': 1.2356895742175364, 'kernel_type': 'kpq', 'bandwidth': 1.2750980589767307, 'diag': False, 'norm_p': 1.6121812666280801, 'reg': 0.03488497885849864}. Best is trial 72 with value: 4.238507509231567.

Using SVD
Time taken for round 4: 0.08093690872192383 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08232593536376953 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08146524429321289 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08109641075134277 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08090639114379883 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0819542407989502 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08439302444458008 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0821998119354248 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0812385082244873 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08115363121032715 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08074259757995605 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08246588706970215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08084845542907715 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08121776580810547 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08104872703552246 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08103704452514648 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08264470100402832 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08112311363220215 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08069682121276855 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08149003982543945 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08060145378112793 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08270835876464844 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08115506172180176 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08089041709899902 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08091092109680176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08038997650146484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:31,428] Trial 79 finished with value: 4.250514125823974 and parameters: {'exponent': 1.319530399270103, 'kernel_type': 'kpq', 'bandwidth': 12.284608103578716, 'diag': False, 'norm_p': 1.634102397483554, 'reg': 0.07238651409724285}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012626171112060547 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012123823165893555 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011560201644897461 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.012581825256347656 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011567354202270508 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.012939929962158203 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.012237787246704102 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011224031448364258 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.011064291000366211 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011611223220825195 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01216578483581543 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.015237808227539062 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.013969898223876953 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 2657
Using SVD
Time taken for round 3: 0.01142430305480957 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011624574661254883 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.011816263198852539 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.01188349723815918 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011543989181518555 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 3: 0.011023759841918945 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.01256871223449707 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 0: 0.01275944709777832 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 1: 0.011839866638183594 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 2: 0.011862993240356445 seconds
Using cheap batch size
Optimal M batch size: 2657

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:31,814] Trial 80 finished with value: 4.26380090713501 and parameters: {'exponent': 1.3849481367072916, 'kernel_type': 'k2q', 'bandwidth': 5.687886730052687, 'diag': False, 'reg': 0.160335323635881}. Best is trial 72 with value: 4.238507509231567.

Using SVD
Time taken for round 3: 0.011021137237548828 seconds
Using cheap batch size
Optimal M batch size: 2657
Using SVD
Time taken for round 4: 0.011261940002441406 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08232808113098145 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08118438720703125 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08084297180175781 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08038544654846191 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0801093578338623 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08217430114746094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07991409301757812 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08053469657897949 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0803840160369873 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08017635345458984 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08188843727111816 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08029508590698242 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.07963800430297852 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07966756820678711 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08008503913879395 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08246088027954102 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08047318458557129 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08046269416809082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07968354225158691 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0799245834350586 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08155083656311035 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07925057411193848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0807793140411377 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07986855506896973 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08013129234313965 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:34,088] Trial 81 finished with value: 4.238781976699829 and parameters: {'exponent': 1.3140620125061029, 'kernel_type': 'kpq', 'bandwidth': 9.05870346591558, 'diag': False, 'norm_p': 1.5329786949250808, 'reg': 0.05344268922930827}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08134913444519043 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07996177673339844 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08047723770141602 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07980680465698242 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08007216453552246 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0821375846862793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08068346977233887 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0807030200958252 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07942461967468262 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08002543449401855 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08204984664916992 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0803077220916748 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08044815063476562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08070850372314453 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07993578910827637 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08177304267883301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07985806465148926 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08092975616455078 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08106303215026855 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08056521415710449 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08195614814758301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07990908622741699 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08028888702392578 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07991600036621094 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.080535888671875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:36,367] Trial 82 finished with value: 4.269890594482422 and parameters: {'exponent': 1.3177620303114432, 'kernel_type': 'kpq', 'bandwidth': 8.831150405651712, 'diag': False, 'norm_p': 1.4933541412472522, 'reg': 0.01421504473599}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08163642883300781 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08083963394165039 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0801246166229248 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08059096336364746 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08023691177368164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08172297477722168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08275127410888672 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08073735237121582 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0803372859954834 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08031892776489258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08177304267883301 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07969832420349121 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08045482635498047 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07993173599243164 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07956266403198242 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08235836029052734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07983112335205078 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08117437362670898 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08034157752990723 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07961225509643555 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08185029029846191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07969522476196289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08069944381713867 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08019900321960449 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0803992748260498 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:38,646] Trial 83 finished with value: 4.311722755432129 and parameters: {'exponent': 0.9277996275055882, 'kernel_type': 'kpq', 'bandwidth': 12.420945278036912, 'diag': False, 'norm_p': 1.7025390508757687, 'reg': 0.040812831007346964}. Best is trial 72 with value: 4.238507509231567.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08208703994750977 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.07956385612487793 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0811011791229248 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07988286018371582 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08054447174072266 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08180618286132812 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07963371276855469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08133101463317871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0797727108001709 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08022332191467285 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0818631649017334 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07974934577941895 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08126449584960938 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07956933975219727 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08028388023376465 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08175921440124512 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07964515686035156 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08042502403259277 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0796518325805664 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07996225357055664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08198356628417969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08206415176391602 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0803976058959961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08010315895080566 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:40,923] Trial 84 finished with value: 4.248604965209961 and parameters: {'exponent': 1.3385835761771139, 'kernel_type': 'kpq', 'bandwidth': 6.738197583356655, 'diag': False, 'norm_p': 1.5260941696247405, 'reg': 0.061100757485075374}. Best is trial 72 with value: 4.238507509231567.

Using SVD
Time taken for round 4: 0.07956528663635254 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08161401748657227 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08042120933532715 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08196830749511719 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08043217658996582 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0809028148651123 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08187413215637207 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08055567741394043 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08103656768798828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07999968528747559 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07974720001220703 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0818490982055664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0795447826385498 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08007979393005371 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07959890365600586 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07989692687988281 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08224630355834961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08032846450805664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08002090454101562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07948923110961914 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08090734481811523 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08218550682067871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08136487007141113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0812368392944336 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08093714714050293 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:43,207] Trial 85 finished with value: 4.266234016418457 and parameters: {'exponent': 1.3417782028375138, 'kernel_type': 'kpq', 'bandwidth': 6.675654155539784, 'diag': False, 'norm_p': 1.5324566562420014, 'reg': 0.022362501114567595}. Best is trial 72 with value: 4.238507509231567.

Using SVD
Time taken for round 4: 0.0820009708404541 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08267760276794434 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0806272029876709 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08109235763549805 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08091068267822266 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08178377151489258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08195781707763672 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08145666122436523 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08146882057189941 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08167123794555664 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08050155639648438 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0824594497680664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08123779296875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08106684684753418 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08115100860595703 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08121514320373535 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08243274688720703 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08170938491821289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0805966854095459 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08146023750305176 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08093643188476562 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08227753639221191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08151888847351074 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0801692008972168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08103394508361816 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08116579055786133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:45,503] Trial 86 finished with value: 4.233418607711792 and parameters: {'exponent': 1.3024852816384869, 'kernel_type': 'kpq', 'bandwidth': 10.482410034390034, 'diag': False, 'norm_p': 1.454298682825814, 'reg': 0.0665834603359922}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08230853080749512 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08158612251281738 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08130621910095215 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08083796501159668 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0804145336151123 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08265876770019531 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0815885066986084 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08096790313720703 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08055353164672852 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08131074905395508 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08247590065002441 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08044767379760742 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08085274696350098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08050060272216797 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07987713813781738 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08209681510925293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08033561706542969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08033967018127441 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08006954193115234 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07969117164611816 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.081512451171875 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07987165451049805 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0799257755279541 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08006572723388672 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07994723320007324 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:47,786] Trial 87 finished with value: 4.235003232955933 and parameters: {'exponent': 1.3649813519864435, 'kernel_type': 'kpq', 'bandwidth': 10.622366801053529, 'diag': False, 'norm_p': 1.45037570284822, 'reg': 0.060195299981309514}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 0: 0.08138751983642578 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 1: 0.08145284652709961 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 2: 0.0823969841003418 seconds
Using expensive batch size
Optimal M batch size: 2672
Time taken for round 3: 0.08239316940307617 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0820932388305664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08175325393676758 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08154082298278809 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08215522766113281 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08226704597473145 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0821237564086914 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08153605461120605 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08310961723327637 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08296990394592285 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.08181238174438477 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.08333706855773926 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08195352554321289 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08214759826660156 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.0825202465057373 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.082550048828125 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.08234000205993652 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 0: 0.08197593688964844 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 1: 0.08214259147644043 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 2: 0.08282041549682617 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 3: 0.0828697681427002 seconds
Using expensive batch size
Optimal M batch size: 2673
Time taken for round 4: 0.0825047492980957 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:50,111] Trial 88 finished with value: 4.476323795318604 and parameters: {'exponent': 1.3584373533084364, 'kernel_type': 'kpq', 'bandwidth': 10.40788183057985, 'diag': True, 'norm_p': 1.4286663639672872, 'reg': 0.007792039623430186}. Best is trial 86 with value: 4.233418607711792.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08273911476135254 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08273673057556152 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08060288429260254 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08066439628601074 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08134841918945312 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08252811431884766 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08073282241821289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08089780807495117 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08091306686401367 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08113718032836914 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08241701126098633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08087778091430664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08113384246826172 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08024334907531738 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07920408248901367 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08179187774658203 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07974004745483398 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08010578155517578 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08250141143798828 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08008980751037598 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08174586296081543 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07980966567993164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08115220069885254 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.07989788055419922 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:52,398] Trial 89 finished with value: 4.260132789611816 and parameters: {'exponent': 1.3842358255660765, 'kernel_type': 'kpq', 'bandwidth': 5.096542604066574, 'diag': False, 'norm_p': 1.4636946985199277, 'reg': 0.09559432573918918}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.08011627197265625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08181476593017578 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08060240745544434 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08021306991577148 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.07961201667785645 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08077621459960938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08123254776000977 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07991337776184082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08010005950927734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0801079273223877 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07969975471496582 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08261656761169434 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08009457588195801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08047676086425781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08034849166870117 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08040285110473633 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0823371410369873 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0810847282409668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08084440231323242 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08124399185180664 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08166027069091797 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08245587348937988 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08025598526000977 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08029794692993164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08011245727539062 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0803835391998291 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:44:54,680] Trial 90 finished with value: 4.260967063903808 and parameters: {'exponent': 1.3360707294884437, 'kernel_type': 'kpq', 'bandwidth': 7.760129895072254, 'diag': False, 'norm_p': 1.4523329471931408, 'reg': 0.05074069674706363}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0818023681640625 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08046436309814453 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08065295219421387 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08121609687805176 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08077788352966309 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08176898956298828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07972168922424316 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08022546768188477 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0807180404663086 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07970952987670898 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08165431022644043 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.079925537109375 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08070182800292969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08024311065673828 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.07999563217163086 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08177375793457031 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.07997250556945801 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08161568641662598 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08052778244018555 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08092021942138672 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08264541625976562 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08090734481811523 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0809335708618164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0809786319732666 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:44:56,961] Trial 91 finished with value: 4.2374170303344725 and parameters: {'exponent': 1.3061790586516007, 'kernel_type': 'kpq', 'bandwidth': 9.301569732424465, 'diag': False, 'norm_p': 1.5213286562383006, 'reg': 0.06421775923488246}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.08066725730895996 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08341813087463379 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 2.8652424812316895 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08820915222167969 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08892416954040527 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Using SVD
Time taken for round 4: 0.08897733688354492 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09123969078063965 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08916187286376953 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08885335922241211 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08858394622802734 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08960127830505371 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09260797500610352 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08925437927246094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08875036239624023 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08879971504211426 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08930611610412598 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.09138226509094238 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08960461616516113 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08877944946289062 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08946704864501953 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 4: 0.08905291557312012 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08202862739562988 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08073282241821289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08070874214172363 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08068728446960449 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0821082592010498 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:45:02,205] Trial 92 finished with value: 4.246637201309204 and parameters: {'exponent': 1.3652889991163133, 'kernel_type': 'kpq', 'bandwidth': 9.388816498488646, 'diag': False, 'norm_p': 1.4044457692536425, 'reg': 0.062505897359736}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08350348472595215 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0808107852935791 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08144545555114746 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08158659934997559 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08069515228271484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08280324935913086 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08056402206420898 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08072066307067871 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08163881301879883 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08045196533203125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0829169750213623 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08076953887939453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08095622062683105 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08077406883239746 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08116626739501953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08252072334289551 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08124303817749023 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0807039737701416 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0807342529296875 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0804443359375 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08306336402893066 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08063507080078125 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08046436309814453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08123135566711426 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:45:04,501] Trial 93 finished with value: 4.248761129379273 and parameters: {'exponent': 1.366494083992153, 'kernel_type': 'kpq', 'bandwidth': 9.472397548767608, 'diag': False, 'norm_p': 1.397108800645364, 'reg': 0.17794416892232337}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.0804145336151123 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08278608322143555 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08086466789245605 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08104443550109863 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08085012435913086 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0823359489440918 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08241701126098633 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08159542083740234 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08108162879943848 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08074760437011719 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08124089241027832 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08256077766418457 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08017539978027344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08103609085083008 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08231616020202637 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08093714714050293 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08249473571777344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08112502098083496 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08173918724060059 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08054494857788086 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08170795440673828 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08246660232543945 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08111453056335449 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08087778091430664 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08168458938598633 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:45:06,802] Trial 94 finished with value: 4.2705078125 and parameters: {'exponent': 1.0342625163240102, 'kernel_type': 'kpq', 'bandwidth': 10.951818832609385, 'diag': False, 'norm_p': 1.3567761012968609, 'reg': 0.06399524567546416}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.0811300277709961 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08239173889160156 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08098292350769043 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08099818229675293 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08195805549621582 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08148956298828125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0827951431274414 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08075165748596191 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08032679557800293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08079290390014648 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08088135719299316 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0828866958618164 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0805354118347168 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08083367347717285 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08079361915588379 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08088064193725586 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08262372016906738 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08102107048034668 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0812830924987793 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08141469955444336 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08161401748657227 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.082427978515625 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08133792877197266 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08021044731140137 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08070015907287598 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08154726028442383 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:45:09,099] Trial 95 finished with value: 4.238664770126343 and parameters: {'exponent': 1.3072176217947196, 'kernel_type': 'kpq', 'bandwidth': 6.901249853534693, 'diag': False, 'norm_p': 1.4013101500639147, 'reg': 0.11568245281775344}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08351850509643555 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08081746101379395 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08118796348571777 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08141684532165527 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08076000213623047 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08324861526489258 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08101916313171387 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08124065399169922 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08053016662597656 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08069849014282227 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08313584327697754 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08127140998840332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08129763603210449 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08121967315673828 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08081388473510742 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08262443542480469 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08141350746154785 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08226752281188965 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08063411712646484 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08104753494262695 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08286094665527344 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08155369758605957 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08101463317871094 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08045530319213867 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:45:11,403] Trial 96 finished with value: 4.3662186622619625 and parameters: {'exponent': 1.309003195511274, 'kernel_type': 'kpq', 'bandwidth': 6.105846650803915, 'diag': False, 'norm_p': 1.3926315726900502, 'reg': 0.01943352501298559}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.08185052871704102 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08239006996154785 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.0809626579284668 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08123779296875 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08413910865783691 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 4: 0.08139634132385254 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08242368698120117 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08116650581359863 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08106327056884766 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08099961280822754 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08110237121582031 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08332633972167969 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0808720588684082 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08096432685852051 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.0804743766784668 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08045172691345215 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08236074447631836 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08137035369873047 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08110642433166504 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08060908317565918 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0817861557006836 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08323502540588379 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08140206336975098 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08075666427612305 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08081674575805664 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08040046691894531 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:45:13,704] Trial 97 finished with value: 4.2354692935943605 and parameters: {'exponent': 1.25023446837493, 'kernel_type': 'kpq', 'bandwidth': 8.17119642723567, 'diag': False, 'norm_p': 1.3989165333659117, 'reg': 0.11550799308229676}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08299684524536133 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.080780029296875 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.0811014175415039 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08143806457519531 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08142828941345215 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08415484428405762 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08084797859191895 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0806584358215332 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08155488967895508 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0814056396484375 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08268237113952637 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08095264434814453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08090710639953613 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08124256134033203 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08147382736206055 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08288359642028809 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08073139190673828 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08102607727050781 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08161616325378418 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08140826225280762 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.0825965404510498 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.0807027816772461 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.0809774398803711 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08020663261413574 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08168959617614746 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 15:45:16,003] Trial 98 finished with value: 4.263692951202392 and parameters: {'exponent': 1.2956522083052155, 'kernel_type': 'kpq', 'bandwidth': 4.649258914957217, 'diag': False, 'norm_p': 1.3981997977750877, 'reg': 0.27981886241613957}. Best is trial 86 with value: 4.233418607711792.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.0832221508026123 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08975863456726074 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08086180686950684 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08079290390014648 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08103537559509277 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08258509635925293 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08092212677001953 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08157634735107422 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08131790161132812 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08125782012939453 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08296704292297363 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08157491683959961 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08144092559814453 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08093690872192383 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08205246925354004 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08385562896728516 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08136582374572754 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08046483993530273 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08118414878845215 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08071732521057129 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2673, d: 10, and nval: 668
======================================================================
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 0: 0.08390140533447266 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 1: 0.08079385757446289 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 2: 0.08097004890441895 seconds
Using expensive batch size
Optimal M batch size: 2673
Using SVD
Time taken for round 3: 0.08126378059387207 seconds
Using expensive batch size
Optimal M batch size: 2673

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 15:45:18,314] Trial 99 finished with value: 4.312680196762085 and parameters: {'exponent': 1.2499295655605867, 'kernel_type': 'kpq', 'bandwidth': 7.599681238472753, 'diag': False, 'norm_p': 1.3550153005300731, 'reg': 0.7566696295660661}. Best is trial 86 with value: 4.233418607711792.

Using SVD
Time taken for round 4: 0.08146905899047852 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
Best params: {'exponent': 1.3024852816384869, 'kernel_type': 'kpq', 'bandwidth': 10.482410034390034, 'diag': False, 'norm_p': 1.454298682825814, 'reg': 0.0665834603359922}
Best MSE: 4.233418607711792

In [8]:
model, pipeline, fit_time, train_metrics, val_metrics = fit_best_xrfm(
    X,
    y,
    best_trial,
    processor,
    n_num_cols,
    task=cfg["task"],
    device=device,
)

print(f"Training time: {fit_time:.2f}s")
print(f"Train RMSE: {train_metrics['rmse']:.4f}")
print(f"Val RMSE:   {val_metrics['rmse']:.4f}")
joblib.dump(model, MODELS_DIR / data_name / "xrfm.joblib")
joblib.dump(pipeline, MODELS_DIR / data_name / "xrfm_pipeline.joblib")

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 2672, d: 10, and nval: 669
======================================================================
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 0: 0.08524918556213379 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 1: 0.08352136611938477 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 2: 0.08366775512695312 seconds
Using expensive batch size
Optimal M batch size: 2672
Using SVD
Time taken for round 3: 0.08358454704284668 seconds
Using expensive batch size
Optimal M batch size: 2672

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.08348751068115234 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
Using hard routing for tree prediction
Training time: 0.46s
Train RMSE: 1.9135
Val RMSE:   2.0783

['/home/shado/college_project/comp9417/9417GroupProject/models/abalone/xrfm_pipeline.joblib']

In [9]:
model = joblib.load(MODELS_DIR / data_name / "xrfm.joblib")
pipeline = joblib.load(MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [10]:
X_test = test_df.drop(columns=metadata["target_col"])
y_test = test_df[metadata["target_col"]].to_numpy().astype(np.float32)

X_test = pipeline.transform(X_test)
t0 = time.perf_counter()
y_pred = model.predict(X_test)
infer_time = (time.perf_counter() - t0) / len(X_test)

Using hard routing for tree prediction

In [11]:
results = evaluate_regression(y_test, y_pred)
print(f"RMSE: {results['rmse']:.4f}")
print(f"Inference time per sample: {infer_time * 1e6:.2f}µs")

RMSE: 2.1013
Inference time per sample: 10.11µs

In [12]:
output = {
    **results,
    "train_metrics": train_metrics,
    "val_metrics": val_metrics,
    "fit_time_s": fit_time,
    "infer_time_per_sample_s": infer_time,
    "best_params": {
        "tuning_metric": model.tuning_metric,
        "split_method": model.split_method,
        "max_leaf_size": model.max_leaf_size,
        **model.rfm_params,
    },
}

results_dir = RESULTS_BENCHMARK / "abalone"
with open(results_dir / "xrfm.json", "w") as f:
    json.dump(output, f, indent=4)

print(f"Results saved to {results_dir / 'xrfm.json'}")

Results saved to /home/shado/college_project/comp9417/9417GroupProject/results/abalone/xrfm.json