In [1]:
import json
import time

import joblib
import numpy as np
import pandas as pd
import torch

from benchmark.config import DATA_PROCESSED, DATASETS, MODELS_DIR, RESULTS_BENCHMARK
from benchmark.metrics import evaluate_regression
from benchmark.models.xrfm_model import make_processor
from benchmark.models.xrfm_model import fit_best_xrfm, fit_xrfm_cross_validation

data_name = "diamonds"
cfg = DATASETS[data_name]
processed = DATA_PROCESSED / data_name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
train_df = pd.read_csv(processed / "train.csv")
train_df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,volumn
0,1.26,Ideal,J,SI1,62.0,56.0,5301,6.90,6.93,4.29,205.13
1,1.04,Ideal,G,VS2,61.6,55.0,6617,6.51,6.55,4.02,171.41
2,0.72,Ideal,H,IF,62.1,58.0,3283,5.72,5.75,3.56,117.09
3,0.26,Very Good,E,VVS2,61.4,57.0,506,4.10,4.13,2.52,42.67
4,0.23,Very Good,E,VVS2,63.0,58.0,505,3.95,3.99,2.50,39.40

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43152 entries, 0 to 43151
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    43152 non-null  float64
 1   cut      43152 non-null  object
 2   color    43152 non-null  object
 3   clarity  43152 non-null  object
 4   depth    43152 non-null  float64
 5   table    43152 non-null  float64
 6   price    43152 non-null  int64
 7   x        43152 non-null  float64
 8   y        43152 non-null  float64
 9   z        43152 non-null  float64
 10  volumn   43152 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 3.6+ MB

In [4]:
test_df = pd.read_csv(processed / "test.csv")
test_df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,volumn
0,1.20,Very Good,I,VVS2,59.9,55.0,6558,6.88,6.94,4.14,197.67
1,0.30,Very Good,I,VS1,62.9,58.0,473,4.26,4.29,2.69,49.16
2,0.41,Premium,G,VVS2,61.6,56.0,1076,4.78,4.76,2.94,66.89
3,0.43,Ideal,E,VS2,62.2,57.0,981,4.80,4.84,3.00,69.70
4,0.53,Very Good,E,VVS2,62.3,55.0,2280,5.18,5.22,3.23,87.34

In [5]:
with open(processed / "metadata.json") as f:
    metadata = json.load(f)

print(metadata)

{'num_cols': ['carat', 'depth', 'table', 'x', 'y', 'z', 'volumn'], 'cat_cols': ['cut', 'color', 'clarity'], 'target_col': 'price'}

In [6]:
X = train_df.drop(columns=metadata["target_col"])
y = train_df[metadata["target_col"]].to_numpy().astype(np.float32)

processor = make_processor(metadata)
n_num_cols = len(metadata["num_cols"])

In [7]:
best_trial = fit_xrfm_cross_validation(
    X, y, processor, n_num_cols, task=cfg["task"], device=device
)

print(f"Best params: {best_trial.params}")
print(f"Best MSE: {best_trial.value}")

[I 2026-04-23 00:36:36,402] A new study created in memory with name: no-name-d7435424-b049-4c8d-a13b-c887621a9080

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method

Getting AGOP on subset
X_train torch.Size([24617, 27]) y_train torch.Size([24617, 1]) X_val torch.Size([1296, 27]) y_val torch.Size([1296, 1])
======================================================================
Fitting RFM with ntrain: 24617, d: 27, and nval: 1296
======================================================================

Using cheap batch size
Optimal M batch size: 2666

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.6333506107330322 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.6883180141448975 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.6731793880462646 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.6516377925872803 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.6684756278991699 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.647620439529419 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.6568038463592529 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.49s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.49s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:00<00:01, 19.19it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:00<00:00, 32.26it/s]

Tuning split temperature:  31%|███       | 11/36 [00:00<00:00, 33.25it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 29.75it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 28.16it/s]

Tuning split temperature:  58%|█████▊    | 21/36 [00:00<00:00, 27.55it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 28.12it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 28.50it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:01<00:00, 28.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.13it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.33it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.99it/s]

Selected split_temperature=0.182074901698571 based on validation mse=289434.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24525, 27]) y_train torch.Size([24525, 1]) X_val torch.Size([1291, 27]) y_val torch.Size([1291, 1])
======================================================================
Fitting RFM with ntrain: 24525, d: 27, and nval: 1291
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6677191257476807 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.7040088176727295 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.7093110084533691 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.7122528553009033 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.693505048751831 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6947672367095947 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.31s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.31s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 39.37it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 37.43it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 34.28it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.55it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 29.85it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 29.69it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.68it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.66it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.67it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.67it/s]

Selected split_temperature=0.182074901698571 based on validation mse=294869.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24525, 27]) y_train torch.Size([24525, 1]) X_val torch.Size([1291, 27]) y_val torch.Size([1291, 1])
======================================================================
Fitting RFM with ntrain: 24525, d: 27, and nval: 1291
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6804864406585693 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.7168595790863037 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.7337851524353027 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.7192931175231934 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.7071185111999512 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6617660522460938 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.7016093730926514 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.695338249206543 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.7057809829711914 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.683236837387085 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.27s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.27s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.65it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.24it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.13it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.91it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 28.99it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.51it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.49it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.58it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=308193.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24525, 27]) y_train torch.Size([24525, 1]) X_val torch.Size([1291, 27]) y_val torch.Size([1291, 1])
======================================================================
Fitting RFM with ntrain: 24525, d: 27, and nval: 1291
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6636502742767334 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.6975753307342529 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.7503204345703125 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.7458682060241699 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.7034962177276611 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6785993576049805 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.6935534477233887 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.7095544338226318 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.7103157043457031 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.6999642848968506 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.25s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.25s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.49it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.68it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.06it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.59it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.26it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.24it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.10it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.82it/s]

Selected split_temperature=0.182074901698571 based on validation mse=288560.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24525, 27]) y_train torch.Size([24525, 1]) X_val torch.Size([1291, 27]) y_val torch.Size([1291, 1])
======================================================================
Fitting RFM with ntrain: 24525, d: 27, and nval: 1291
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6712744235992432 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.7230098247528076 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.7055344581604004 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.676314115524292 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.6805830001831055 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 0: 0.6917245388031006 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 1: 0.6943140029907227 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 2: 0.6762173175811768 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 3: 0.689751386642456 seconds

Using cheap batch size
Optimal M batch size: 2665
Time taken for round 4: 0.6782131195068359 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.07s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.07s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.99it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.24it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.13it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.08it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.09it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:03<00:02,  3.89it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:03<00:01,  5.03it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:03<00:00,  6.49it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:03<00:00,  8.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:03<00:00,  9.36it/s]

[I 2026-04-23 00:37:30,185] Trial 0 finished with value: 301839.91875 and parameters: {'exponent': 1.0271644858581115, 'kernel_type': 'k2q', 'bandwidth': 1.970613996905623, 'diag': True, 'reg': 0.0026485784758470345}. Best is trial 0 with value: 301839.91875.

Selected split_temperature=0.21212000487151167 based on validation mse=328142.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24525, 27]) y_train torch.Size([24525, 1]) X_val torch.Size([1291, 27]) y_val torch.Size([1291, 1])
======================================================================
Fitting RFM with ntrain: 24525, d: 27, and nval: 1291
======================================================================

Using cheap batch size
Optimal M batch size: 2666
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2558

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:869: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Time taken for round 0: 5.572937726974487 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.781158924102783 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.695836544036865 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.696974039077759 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.741938591003418 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.412521123886108 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.74265718460083 seconds

Building trees: 100%|██████████| 1/1 [00:42<00:00, 42.10s/it]

Building trees: 100%|██████████| 1/1 [00:42<00:00, 42.10s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.63it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:22,  1.52it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:22,  1.48it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.45it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.43it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:25<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.01s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:14,  1.77s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.60s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.49s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.41s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:05,  1.35s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.29s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.26s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=342523.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.764183759689331 seconds

Early stopping at iteration 1
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.734327793121338 seconds

Building trees: 100%|██████████| 1/1 [00:14<00:00, 14.83s/it]

Building trees: 100%|██████████| 1/1 [00:14<00:00, 14.83s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:46,  1.62s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:37,  1.35s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:32,  1.19s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:28,  1.09s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:25,  1.03s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:24,  1.01s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:23,  1.01s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:22,  1.03s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:22,  1.05s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.09s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.11s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.13s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  2.03s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.19s/it]

Selected split_temperature=0.4552388837310289 based on validation mse=428946.437500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4266
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.8496668338775635 seconds

Early stopping at iteration 1
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4364
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.748220443725586 seconds

Building trees: 100%|██████████| 1/1 [00:14<00:00, 14.99s/it]

Building trees: 100%|██████████| 1/1 [00:14<00:00, 14.99s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:32,  1.93s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:27,  1.71s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:23,  1.55s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:20,  1.45s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:17,  1.38s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.32s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.29s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:11,  1.24s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.22s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=385090.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.765714168548584 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.658520221710205 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.686938285827637 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.748873949050903 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.687384605407715 seconds

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.89s/it]

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.89s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:36,  1.92s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.68s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.52s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.41s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:20,  1.34s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.29s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.26s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.23s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=443438.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4380
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.774799346923828 seconds

Early stopping at iteration 1
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4250
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 7.706188917160034 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.686654806137085 seconds

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.52s/it]

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.52s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.68it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.49it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:24,  2.06s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:19,  1.80s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:16,  1.62s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:13,  1.49s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:11,  1.40s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:09,  1.34s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.29s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.26s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.24s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.23s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.22s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=406129.281250
Using soft routing for tree prediction

[I 2026-04-23 00:43:04,280] Trial 1 finished with value: 401225.71875 and parameters: {'exponent': 0.7598959983417237, 'kernel_type': 'kpq', 'bandwidth': 31.128146769150394, 'diag': True, 'norm_p': 1.204380550596923, 'reg': 1.5178988352304667e-06}. Best is trial 0 with value: 301839.91875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6385762691497803 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6887145042419434 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6795001029968262 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6689231395721436 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6540701389312744 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.647341251373291 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6631667613983154 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.72it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.72it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.84it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.84it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.14it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.70it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.18it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.12it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=403364.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6584577560424805 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7171196937561035 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6845152378082275 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6767127513885498 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6528267860412598 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6526751518249512 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6651983261108398 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.97it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.38it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.22it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.30it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.14it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.04it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.03it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=435221.625000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6595897674560547 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7155055999755859 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.710029125213623 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6902761459350586 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.671316385269165 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6802623271942139 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6846330165863037 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.93s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.93s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.72it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.61it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.31it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.42it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.21it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.86it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.03it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=438326.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6595220565795898 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6889722347259521 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6667039394378662 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6790482997894287 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6748378276824951 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.679081916809082 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6608448028564453 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:00<00:00, 49.88it/s]

Tuning split temperature:  31%|███       | 11/36 [00:00<00:00, 44.77it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 39.34it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 35.72it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 31.07it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 28.57it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.34it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=466558.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4381
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6898186206817627 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7157588005065918 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.7094521522521973 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.670644998550415 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6804945468902588 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4249
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6494591236114502 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6606099605560303 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.88s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.88s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.80it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.08it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.37it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.58it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.49it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.19it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

[I 2026-04-23 00:43:47,658] Trial 2 finished with value: 432541.9125 and parameters: {'exponent': 0.7416781387847737, 'kernel_type': 'k2q', 'bandwidth': 175.8288583045548, 'diag': True, 'reg': 0.5118691608584706}. Best is trial 0 with value: 301839.91875.

Selected split_temperature=0.21212000487151167 based on validation mse=419238.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.770997762680054 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.6410441398620605 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.698270320892334 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.715942621231079 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.69044303894043 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.755720376968384 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.726697206497192 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.37s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.37s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.67it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:56,  1.77s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:42,  1.39s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:34,  1.16s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:29,  1.03s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:26,  1.06it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:24,  1.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:23,  1.12it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:22,  1.12it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:21,  1.10it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:21,  1.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.04it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.00it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.03s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.07s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.09s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:01,  1.95s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.72s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.17s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=264349.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.765291452407837 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.685466289520264 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.708811283111572 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.682965040206909 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.691299915313721 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 7.749952554702759 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.669251203536987 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.672595262527466 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.66808819770813 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.685249328613281 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.31s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.70it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:40,  1.77s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:33,  1.54s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:29,  1.40s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:26,  1.30s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:23,  1.24s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.21s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.19s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.18s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.0 based on validation mse=273742.937500
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4276
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 7.717664957046509 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.6841044425964355 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.695105314254761 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.676123380661011 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.687847852706909 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4354
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.749817609786987 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.6876020431518555 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.652717113494873 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.6843156814575195 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.7393574714660645 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.36s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.36s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.26it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  2.00s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.75s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:22,  1.58s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:18,  1.46s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.37s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.32s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.28s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.25s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=290304.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4289
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.76190710067749 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.685885190963745 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.638214349746704 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.685125350952148 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.695357322692871 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4341
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.757281064987183 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.685571193695068 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.68420672416687 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 7.637172698974609 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.689778804779053 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.27s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.27s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.70it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.06s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.80s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.61s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.48s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.39s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.33s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.28s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.25s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.07282170089875539 based on validation mse=279751.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.769474983215332 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.696159362792969 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.690787315368652 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.68889594078064 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.6516828536987305 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.743052244186401 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.676921367645264 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.6839141845703125 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.678055286407471 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.679161548614502 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.30s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.30s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:03<02:03,  3.54s/it]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:02,  1.85s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:43,  1.31s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:34,  1.06s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:28,  1.07it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:25,  1.16it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:23,  1.21it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:22,  1.24it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.23it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:20,  1.20it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:38<00:06,  2.07s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:40<00:03,  1.80s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:41<00:01,  1.61s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.48s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.18s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=289896.187500
Using soft routing for tree prediction

[I 2026-04-23 00:51:43,791] Trial 3 finished with value: 279608.8 and parameters: {'exponent': 0.7550981778629094, 'kernel_type': 'kpq', 'bandwidth': 6.5017130686590825, 'diag': True, 'norm_p': 1.6741056103679175, 'reg': 0.15816844334894103}. Best is trial 3 with value: 279608.8.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6866638660430908 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7164657115936279 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6694774627685547 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.650463342666626 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.82s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.82s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.38it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.78it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.74it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.61it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.81it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.11it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.74it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.75it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.32it/s]

Selected split_temperature=0.28790202327301256 based on validation mse=702111.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6589326858520508 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6903438568115234 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6441075801849365 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.09s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.09s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.74it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.81it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.95it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.27it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.83it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.39it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.28790202327301256 based on validation mse=756162.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6626255512237549 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6821246147155762 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6366803646087646 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6781339645385742 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.77s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.77s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.49it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.18it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.33it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.45it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.46it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.53it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.83it/s]

Selected split_temperature=0.28790202327301256 based on validation mse=728437.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6794145107269287 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.691709041595459 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6699860095977783 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.57it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.66it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.04it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.18it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.95it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.08it/s]

Selected split_temperature=0.28790202327301256 based on validation mse=800870.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6623170375823975 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6873993873596191 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6682155132293701 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.13s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.13s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.81it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.94it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.96it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.82it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.70it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:03<00:01,  3.71it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:04<00:00,  4.73it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  6.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.72it/s]

[I 2026-04-23 00:52:14,977] Trial 4 finished with value: 738371.775 and parameters: {'exponent': 1.2386834737442696, 'kernel_type': 'k2q', 'bandwidth': 90.48888237464404, 'diag': True, 'reg': 0.8236923920601619}. Best is trial 3 with value: 279608.8.

Selected split_temperature=0.3354101966249685 based on validation mse=704277.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775136709213257 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.849369764328003 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.8784308433532715 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566683292388916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.570163011550903 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.74420166015625 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 6.866884469985962 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.55s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.55s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:25<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:18,  2.08s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:14,  1.82s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.63s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:09,  1.51s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:07,  1.41s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:05,  1.36s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.33s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.31s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:39<00:01,  1.30s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.29s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.12s/it]

Selected split_temperature=0.182074901698571 based on validation mse=292743.406250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.827033996582031 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.6448469161987305 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.983303070068359 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 6.603222608566284 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.643409729003906 seconds

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.15s/it]

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.15s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:21,  2.00s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.75s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:14,  1.58s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:11,  1.46s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:09,  1.38s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.32s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.28s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.25s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.23s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=299594.000000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.770392179489136 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.561297178268433 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.568082571029663 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.5218212604522705 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.555567979812622 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.755312442779541 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.02s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.02s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:32,  2.02s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:26,  1.77s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:22,  1.60s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:19,  1.48s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.40s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.34s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:11,  1.27s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.25s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.24s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.22s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.03953071244130627 based on validation mse=313460.093750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7626588344573975 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562621831893921 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.751331329345703 seconds

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.25s/it]

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.25s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:25<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:18,  2.10s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:14,  1.83s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.64s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:09,  1.51s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:07,  1.42s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:05,  1.35s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.28s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.26s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.12s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=320208.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.770498275756836 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5693888664245605 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.569413185119629 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576680898666382 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.530399560928345 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.747601270675659 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559725284576416 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.62s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.62s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:35,  1.95s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:29,  1.71s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.54s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.43s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.36s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.30s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.27s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.24s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.22s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.07282170089875539 based on validation mse=314744.343750
Using soft routing for tree prediction

[I 2026-04-23 00:58:30,114] Trial 5 finished with value: 308150.08125 and parameters: {'exponent': 1.3169801908670333, 'kernel_type': 'kpq', 'bandwidth': 19.84662081152421, 'diag': False, 'norm_p': 1.7995055455137243, 'reg': 0.05330158533580604}. Best is trial 3 with value: 279608.8.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.767924070358276 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.52449631690979 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560941934585571 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564514875411987 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.569154500961304 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.729951858520508 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 36.00s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 36.00s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:40,  1.77s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:33,  1.54s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:29,  1.39s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:25,  1.30s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:23,  1.24s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.21s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.19s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.18s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=292286.687500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4314
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.71814751625061 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570067644119263 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5777268409729 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.572237491607666 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5615150928497314 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4317
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.72953987121582 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.553013563156128 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.51253604888916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.544670820236206 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.547581195831299 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.16s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.16s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:29,  2.00s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.74s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:20,  1.57s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:17,  1.45s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.36s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=279588.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761603832244873 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563925743103027 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.515375852584839 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.570183515548706 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.557828664779663 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752451658248901 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5664002895355225 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.59s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.59s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.72s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.48s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.34s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.25s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:23,  1.19s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:21,  1.16s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.14s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=315582.312500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.719287395477295 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5667619705200195 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561982154846191 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.559307336807251 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.565084457397461 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750955581665039 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.565848350524902 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.541570663452148 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.712756633758545 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.651610612869263 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.50s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.50s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:19<00:30,  1.88s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:25,  1.67s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.52s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.42s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.35s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.27s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.24s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=324107.406250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.770819664001465 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567267894744873 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.1739661693573 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5839903354644775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5661211013793945 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7457005977630615 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.555315017700195 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561813831329346 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.557962417602539 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5071120262146 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.89s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.04s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.78s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.59s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.46s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.37s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.26s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=315079.281250
Using soft routing for tree prediction

[I 2026-04-23 01:05:58,341] Trial 6 finished with value: 305328.75 and parameters: {'exponent': 1.0948486965751747, 'kernel_type': 'kpq', 'bandwidth': 63.44132593183689, 'diag': False, 'norm_p': 1.4194589751409419, 'reg': 0.00011913672272764324}. Best is trial 3 with value: 279608.8.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6895322799682617 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.8227272033691406 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6968514919281006 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6713871955871582 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6826052665710449 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6597850322723389 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6527636051177979 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.97s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.97s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.44it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.64it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.60it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.43it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.38it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267434.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6595325469970703 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6867904663085938 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6869266033172607 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.669811487197876 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.681267499923706 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6567637920379639 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6548061370849609 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6645965576171875 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6686208248138428 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6592633724212646 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.67it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.01it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.09it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.29it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.14it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.39it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.86it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.85it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=273775.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4259
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6613695621490479 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.691699743270874 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6710362434387207 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 3.6359386444091797 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6779730319976807 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4371
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6746032238006592 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6703133583068848 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6824886798858643 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6858103275299072 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.67128586769104 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.48it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.88it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.29it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.74it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.40it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.47it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.99it/s]

Selected split_temperature=0.182074901698571 based on validation mse=287222.406250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6618359088897705 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6910061836242676 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6833148002624512 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6732296943664551 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7038073539733887 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6879963874816895 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6819968223571777 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.668602466583252 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.7124319076538086 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7023301124572754 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.59it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.48it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.63it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.03it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=278261.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4379
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6596601009368896 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6927917003631592 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6833798885345459 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6706962585449219 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6810283660888672 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4251
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6709048748016357 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6722452640533447 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6802096366882324 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6805520057678223 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7099854946136475 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.04it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.53it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.96it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.64it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.44it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.21it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.87it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 28.41it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.81it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 29.05it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.42it/s]

[I 2026-04-23 01:06:50,069] Trial 7 finished with value: 279145.21875 and parameters: {'exponent': 0.9163728423001612, 'kernel_type': 'k2q', 'bandwidth': 11.925101256066307, 'diag': True, 'reg': 0.021609288204221935}. Best is trial 7 with value: 279145.21875.

Selected split_temperature=0.13414886285344563 based on validation mse=289031.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.664067268371582 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6702761650085449 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6935696601867676 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6670718193054199 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6822221279144287 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 3.6023190021514893 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.651015043258667 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.74s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.74s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.60it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.00it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.97it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.95it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.13it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=298078.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6609201431274414 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6953420639038086 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6827754974365234 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6695337295532227 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.685490608215332 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6482434272766113 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.13s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.13s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.39it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.75it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.72it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.86it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.86it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.67it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.29it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=302512.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.660973072052002 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.697803258895874 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6832120418548584 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6755766868591309 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6829144954681396 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6718978881835938 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6729762554168701 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6758053302764893 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6864252090454102 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.22s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.22s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.65it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.26it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.21it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.27it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.21it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.62it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.74it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=313365.093750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6678478717803955 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6919608116149902 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6678166389465332 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6804156303405762 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6748814582824707 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6755316257476807 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.669475793838501 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6812434196472168 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6858663558959961 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.672710657119751 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.02it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.63it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.11it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 26.96it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.19it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.83it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.36it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.74it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.01it/s]

Selected split_temperature=0.182074901698571 based on validation mse=292443.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4390
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6917967796325684 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6920425891876221 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 3.6426167488098145 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.675302267074585 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6760001182556152 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4240
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6712379455566406 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6700136661529541 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6795704364776611 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6915349960327148 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.697368860244751 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.15it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.47it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.57it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.74it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.32it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.86it/s]

[I 2026-04-23 01:07:41,139] Trial 8 finished with value: 307209.10625 and parameters: {'exponent': 1.2060200075435343, 'kernel_type': 'k2q', 'bandwidth': 2.792736238727968, 'diag': True, 'reg': 0.0007660547961224706}. Best is trial 7 with value: 279145.21875.

Selected split_temperature=0.21212000487151167 based on validation mse=329646.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6624536514282227 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6905567646026611 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.685713529586792 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6958162784576416 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.83s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.83s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.17it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.81it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.47it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.51it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.56it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.88it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.56it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.71it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.58it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.97it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=291288.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6642963886260986 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6869790554046631 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6847972869873047 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6753802299499512 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6669507026672363 seconds

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.47s/it]

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.47s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.95it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.44it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.00it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.89it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.60it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=303481.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4269
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6602952480316162 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6907179355621338 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6964402198791504 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.670720100402832 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6836426258087158 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4361
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6722095012664795 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.674837589263916 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6783020496368408 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6869518756866455 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.23s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.23s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.57it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.95it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.04it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.21it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.99it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.10it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.59it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.66it/s]

Selected split_temperature=0.3354101966249685 based on validation mse=306587.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4286
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6631407737731934 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6958513259887695 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 3.620572328567505 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6791572570800781 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6771829128265381 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4344
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6839535236358643 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.14s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.14s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.04it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.26it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.70it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.33it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.99it/s]

Selected split_temperature=0.0 based on validation mse=297531.375000
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6606874465942383 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6937472820281982 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6828534603118896 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6740577220916748 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6879129409790039 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6639361381530762 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6802055835723877 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.85s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.85s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.86it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.02it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.44it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.54it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.56it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.27it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.79it/s]

[I 2026-04-23 01:08:21,861] Trial 9 finished with value: 307480.48125 and parameters: {'exponent': 0.7450034897059166, 'kernel_type': 'k2q', 'bandwidth': 1.880953078065556, 'diag': True, 'reg': 2.8141896704489657e-06}. Best is trial 7 with value: 279145.21875.

Selected split_temperature=0.13414886285344563 based on validation mse=338513.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6631505489349365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.696678876876831 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6836221218109131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7061524391174316 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.711251974105835 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6696617603302002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6520833969116211 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6646404266357422 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6692490577697754 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6549351215362549 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.03it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.56it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.65it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.14it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.28it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.79it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.15it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=270398.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7058253288269043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7243943214416504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7164883613586426 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7096543312072754 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6892149448394775 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6325099468231201 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6561779975891113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6637382507324219 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6604483127593994 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6616828441619873 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.98it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.40it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.37it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:03<00:01,  3.73it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:03<00:00,  4.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  6.19it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.82it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268949.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669726371765137 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7147512435913086 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7136185169219971 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.70914626121521 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6999528408050537 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6625277996063232 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6782100200653076 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6715795993804932 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7120974063873291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7060713768005371 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.04s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.04s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.61it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.49it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.38it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.53it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=290207.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6640968322753906 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.720304012298584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6845815181732178 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6806061267852783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6814470291137695 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6634232997894287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6772744655609131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6739461421966553 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6829719543457031 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6841380596160889 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.04it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.50it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.80it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.89it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=281324.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619582176208496 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6932501792907715 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6879537105560303 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6720249652862549 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6844482421875 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6544005870819092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6671133041381836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6781954765319824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6773953437805176 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6836261749267578 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.85it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.90it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.19it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.68it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.78it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.84it/s]

[I 2026-04-23 01:09:15,607] Trial 10 finished with value: 278646.13125 and parameters: {'exponent': 0.9364012267236584, 'kernel_type': 'k2q', 'bandwidth': 7.547668737995126, 'diag': False, 'reg': 0.0295551492784938}. Best is trial 10 with value: 278646.13125.

Selected split_temperature=0.09883799050275041 based on validation mse=282350.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6353750228881836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7152090072631836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7058911323547363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.673713207244873 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6828672885894775 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6478171348571777 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6558914184570312 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.81s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.21it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.74it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.96it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.12it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.11it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=270207.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6605381965637207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6918449401855469 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6827654838562012 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6728413105010986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6881558895111084 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6575465202331543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6558034420013428 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6611747741699219 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6668641567230225 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6593568325042725 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.98it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.46it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.04it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.22it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.08it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.10it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.04it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=266050.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.704460620880127 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7210900783538818 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7148292064666748 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7074964046478271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6999940872192383 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6546347141265869 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6565370559692383 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6816308498382568 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6797018051147461 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6746633052825928 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.05s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.05s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.68it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.08it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.02it/s]

Selected split_temperature=0.06250708904468986 based on validation mse=289529.218750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7029874324798584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6952614784240723 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6885054111480713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.677793025970459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6755051612854004 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.628568410873413 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6721467971801758 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7079641819000244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7170648574829102 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6720452308654785 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.99s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 12.00s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.64it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.67it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.96it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.89it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.84it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.75it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.40it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.01it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=280727.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6610705852508545 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6790411472320557 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6991012096405029 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.667548418045044 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6865942478179932 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6525101661682129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6714684963226318 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6762607097625732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6823601722717285 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6767077445983887 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.83it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.31it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.46it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.20it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.97it/s]

[I 2026-04-23 01:10:10,386] Trial 11 finished with value: 277777.875 and parameters: {'exponent': 0.9287322809174521, 'kernel_type': 'k2q', 'bandwidth': 7.747562096309485, 'diag': False, 'reg': 0.015302498684740692}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=282374.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6929209232330322 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6924381256103516 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6723945140838623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6808841228485107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6785879135131836 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6566946506500244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6567468643188477 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.41it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.44it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.67it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.60it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 31.14it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.65it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.182074901698571 based on validation mse=274090.593750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616246700286865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.718177318572998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7110912799835205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7104897499084473 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7171807289123535 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6617343425750732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6519689559936523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6656174659729004 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6670687198638916 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6557657718658447 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.28it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.67it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.77it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:03<00:02,  3.64it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:03<00:01,  4.72it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:03<00:00,  6.10it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:04<00:00,  7.71it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.75it/s]

Selected split_temperature=0.182074901698571 based on validation mse=279133.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4278
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6755456924438477 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6923303604125977 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858885288238525 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6672959327697754 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6886401176452637 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4352
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6696019172668457 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6762146949768066 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6789610385894775 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6850717067718506 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6785058975219727 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.43it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.96it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.23it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.02it/s]

Selected split_temperature=0.0 based on validation mse=295384.812500
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6632435321807861 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6938564777374268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6819934844970703 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6753726005554199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.708275318145752 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6860547065734863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6752316951751709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6699304580688477 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6943387985229492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.676548957824707 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.42it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.75it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.28it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.09it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.26it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.22it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.78it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.69it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.72it/s]

Selected split_temperature=0.182074901698571 based on validation mse=280410.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6642899513244629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.690274715423584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.683638334274292 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6763491630554199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6824333667755127 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6659979820251465 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6685924530029297 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.67510986328125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7080984115600586 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7004826068878174 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.60it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.03it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.53it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.90it/s]

[I 2026-04-23 01:11:02,166] Trial 12 finished with value: 285054.56875 and parameters: {'exponent': 0.9191982040118036, 'kernel_type': 'k2q', 'bandwidth': 7.323898374305409, 'diag': False, 'reg': 0.0036880414911128648}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.1562854472336314 based on validation mse=296253.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.647794246673584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7189192771911621 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7139148712158203 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7127735614776611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.709944486618042 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6653523445129395 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6517789363861084 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.94s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.94s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.76it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.67it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.62it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.17it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.47it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.24it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=271596.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6658823490142822 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6747851371765137 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6763558387756348 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6774547100067139 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6790895462036133 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6604342460632324 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6558682918548584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6665947437286377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6687567234039307 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6577095985412598 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.79s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.00it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.65it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.51it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.37it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.21it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.02it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268697.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6639301776885986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692685604095459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.683598518371582 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6704659461975098 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6840405464172363 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6704573631286621 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6736936569213867 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6806983947753906 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6907002925872803 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6769876480102539 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.86it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.47it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.48it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.49it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.75it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.01it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.43it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.06it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.01it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.01it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.42it/s]

Selected split_temperature=0.0 based on validation mse=288780.031250
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4290
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6665201187133789 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6876001358032227 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6843292713165283 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6716446876525879 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6781442165374756 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4340
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6203508377075195 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6714587211608887 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6804704666137695 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6880323886871338 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6737875938415527 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.39it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.36it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.51it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.01it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.58it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.25it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.54it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.88it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=276709.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6645934581756592 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6921954154968262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6855690479278564 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6701114177703857 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6819944381713867 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6634025573730469 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6760332584381104 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6773207187652588 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6841425895690918 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6785392761230469 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.35it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.74it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.73it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.61it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.98it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.94it/s]

[I 2026-04-23 01:11:56,902] Trial 13 finished with value: 278599.93125 and parameters: {'exponent': 0.952275897380878, 'kernel_type': 'k2q', 'bandwidth': 4.8324893510285, 'diag': False, 'reg': 0.01236543339251769}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=287217.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6652023792266846 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6914129257202148 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6866776943206787 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6725869178771973 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6848347187042236 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6413130760192871 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6412405967712402 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.78s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.78s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.85it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.32it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.53it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.32it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 34.00it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.23it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.15it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.182074901698571 based on validation mse=282247.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6676974296569824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6927609443664551 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6867406368255615 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6726090908050537 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6811840534210205 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6418254375457764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.661766529083252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6584255695343018 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6709229946136475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6610164642333984 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.94it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.73it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:03<00:03,  3.35it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:03<00:01,  4.44it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:03<00:00,  5.85it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00,  7.62it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.73it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=287965.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6649942398071289 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7176051139831543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7108185291290283 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6777191162109375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.683910608291626 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6609280109405518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6623959541320801 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6787137985229492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6833820343017578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6747255325317383 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.05it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.00it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.10it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.85it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.76it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.74it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.09it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=308589.718750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6895458698272705 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7196741104125977 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7138457298278809 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.69478440284729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6794517040252686 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6960055828094482 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7069828510284424 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6875574588775635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.695030927658081 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6828203201293945 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.08s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.08s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.48it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.55it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.59it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=283323.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.665229320526123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.714160680770874 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.712698221206665 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6878082752227783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6846163272857666 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6577677726745605 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6772933006286621 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6705517768859863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7139086723327637 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6833810806274414 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.98s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.98s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.84it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.94it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.22it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.35it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.96it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

[I 2026-04-23 01:12:48,702] Trial 14 finished with value: 296002.6625 and parameters: {'exponent': 1.0415744384590764, 'kernel_type': 'k2q', 'bandwidth': 3.6453089857830587, 'diag': False, 'reg': 0.00013572231247761845}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.182074901698571 based on validation mse=317886.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6254522800445557 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6948716640472412 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6877810955047607 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.670341968536377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6904385089874268 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6570999622344971 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6517360210418701 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6500594615936279 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6705613136291504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6543924808502197 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.75s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.75it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.70it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.04it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.94it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.93it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.08it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=280121.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6636052131652832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6979403495788574 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6838085651397705 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6732392311096191 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6857514381408691 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6595563888549805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6587023735046387 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6636745929718018 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6759076118469238 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6627001762390137 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.50it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=294666.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6644725799560547 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6970105171203613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6833639144897461 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6739082336425781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6862049102783203 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6604213714599609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.676192045211792 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6727323532104492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.677762508392334 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6920101642608643 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.30it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.72it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.98it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.25it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.08it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.98it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.98it/s]

Selected split_temperature=0.07282170089875539 based on validation mse=309881.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4291
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6667795181274414 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.693187952041626 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6855535507202148 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.6259605884552 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6811981201171875 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4339
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6778526306152344 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.676947832107544 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6831848621368408 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6830334663391113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6917898654937744 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 39.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 36.57it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 34.63it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 31.52it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 30.71it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 30.37it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 30.09it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.40it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=284941.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4379
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6648967266082764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692664384841919 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6902866363525391 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6738252639770508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6856944561004639 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4251
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6545343399047852 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6643538475036621 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6719653606414795 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6817710399627686 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.679818868637085 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.00it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.04it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.33it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.23it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.70it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.90it/s]

[I 2026-04-23 01:13:45,254] Trial 15 finished with value: 295983.96875 and parameters: {'exponent': 0.8614601464311625, 'kernel_type': 'k2q', 'bandwidth': 1.199342328992225, 'diag': False, 'reg': 0.006724213134140834}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=310309.218750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6638333797454834 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7208211421966553 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6993653774261475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6732230186462402 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6864259243011475 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6649081707000732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6652495861053467 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.88s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.88s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.75it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.32it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.73it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.20it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.00it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.78it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.70it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.76it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.75it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=283188.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7015769481658936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.705127477645874 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6942524909973145 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6864748001098633 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6884102821350098 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624348163604736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6601018905639648 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6787433624267578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.3765766620635986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6641354560852051 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.66s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.66s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.60it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.30it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 26.89it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.38it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.70it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.16it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 24.83it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 25.44it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.52it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.00it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=288381.625000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7013499736785889 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7653939723968506 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7288246154785156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.726820707321167 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7242035865783691 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6914427280426025 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6916849613189697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6903872489929199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.702984094619751 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6929821968078613 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.28s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.28s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 40.89it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 33.64it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.36it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.21it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.12it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.03it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.15it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.29it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=309326.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6643819808959961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6771533489227295 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.695770263671875 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.672842264175415 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6829559803009033 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6695494651794434 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6727292537689209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6796643733978271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7021908760070801 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7094259262084961 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.23it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.69it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.53it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.28it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.27it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.41it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.70it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.50it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.65it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.47it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.84it/s]

Selected split_temperature=0.182074901698571 based on validation mse=282563.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4384
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6673297882080078 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901826858520508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6857430934906006 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6693930625915527 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6900801658630371 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4246
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6781456470489502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6723308563232422 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6797640323638916 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6879301071166992 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6765143871307373 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.49s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.49s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.02it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.32it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.43it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.60it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.13it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.92it/s]

[I 2026-04-23 01:14:40,110] Trial 16 finished with value: 296350.06875 and parameters: {'exponent': 1.122087137875329, 'kernel_type': 'k2q', 'bandwidth': 4.54662556601831, 'diag': False, 'reg': 0.0003074779846369913}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.182074901698571 based on validation mse=318290.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.662574052810669 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7191166877746582 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7025086879730225 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6763501167297363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6897687911987305 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6688916683197021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6533877849578857 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.67it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.46it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.26it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.22it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=276317.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6893832683563232 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6922240257263184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6881837844848633 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6912548542022705 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6770222187042236 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6408774852752686 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6592249870300293 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6629209518432617 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.52s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.52s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.93it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.04it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.22it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.05it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=282061.093750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4263
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6630795001983643 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6881043910980225 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.690453052520752 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6692707538604736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6835041046142578 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4367
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6578683853149414 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6842072010040283 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6727094650268555 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6831827163696289 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6872715950012207 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.90it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.28it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.98it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.85it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=300653.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6935312747955322 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926720142364502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6736648082733154 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6853170394897461 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.6279492378234863 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6759858131408691 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6734981536865234 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6803395748138428 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6820926666259766 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6766941547393799 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.88s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.35it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.76it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.81it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.09it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.61it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.57it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=289017.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6958746910095215 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7192623615264893 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7135705947875977 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.713573694229126 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7120006084442139 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6882226467132568 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6721353530883789 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.70845627784729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7166829109191895 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7082901000976562 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.19s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.19s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.96it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.41it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.28it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.08it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.55it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.89it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.33it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 24.99it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 25.61it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.65it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.18it/s]

[I 2026-04-23 01:15:30,785] Trial 17 finished with value: 290431.00625 and parameters: {'exponent': 0.83693914677561, 'kernel_type': 'k2q', 'bandwidth': 15.024082886631351, 'diag': False, 'reg': 4.1947890504844455e-05}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=304105.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.717293977737427 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575672388076782 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.574042797088623 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.5349836349487305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5726540088653564 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.677192449569702 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.553825855255127 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.552383899688721 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.06s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.06s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:22,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.50it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:45,  1.68s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:37,  1.42s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:31,  1.26s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:27,  1.16s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:25,  1.10s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:23,  1.08s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:22,  1.08s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.09s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.10s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.12s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.13s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.15s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.182074901698571 based on validation mse=303643.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4303
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.702962636947632 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567218065261841 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.563035011291504 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.567286491394043 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.567641019821167 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.6713409423828125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.505062103271484 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.551700830459595 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.545403003692627 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.548152208328247 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.02s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.02s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:35,  1.95s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:29,  1.71s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.54s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.43s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:19,  1.36s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.30s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.27s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.24s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.22s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=309418.750000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.702674388885498 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5227954387664795 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561889410018921 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565172433853149 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.562560081481934 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.693124771118164 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.90s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.90s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:41,  1.75s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:34,  1.52s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:30,  1.37s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:26,  1.28s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:24,  1.23s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:22,  1.20s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.18s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.18s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.18s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.20s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=328926.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.6489644050598145 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562250137329102 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561043977737427 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566304922103882 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.556886672973633 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.691979169845581 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.56644344329834 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.532007932662964 seconds

Building trees: 100%|██████████| 1/1 [00:47<00:00, 47.98s/it]

Building trees: 100%|██████████| 1/1 [00:47<00:00, 47.98s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:25<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:18,  2.08s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:14,  1.82s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.64s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:09,  1.51s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:07,  1.42s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:05,  1.35s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.28s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.25s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.182074901698571 based on validation mse=331799.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.710955381393433 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.568151473999023 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.567293405532837 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.568889617919922 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.532021522521973 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.680725336074829 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.555703163146973 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.55570650100708 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.03s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.03s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.81s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:33,  1.59s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:28,  1.44s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:25,  1.34s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:22,  1.27s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.24s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.21s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.20s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=312246.937500
Using soft routing for tree prediction

[I 2026-04-23 01:22:46,617] Trial 18 finished with value: 317206.91875 and parameters: {'exponent': 0.9924585397166127, 'kernel_type': 'kpq', 'bandwidth': 43.84113746366272, 'diag': False, 'norm_p': 0.9925046300784962, 'reg': 0.10661287492158883}. Best is trial 11 with value: 277777.875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6613011360168457 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6928653717041016 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.681556224822998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6756043434143066 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6820261478424072 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6135358810424805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6564474105834961 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.74s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.74s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.06it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.24it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.14it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.37it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.83it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.99it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=268934.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.663754940032959 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7151913642883301 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6838433742523193 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6809628009796143 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6646013259887695 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6549978256225586 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6554677486419678 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6647806167602539 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6658029556274414 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.655951976776123 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.11it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.69it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.83it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.45it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.18it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.52it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 28.14it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.64it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.94it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.32it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=267952.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.664625883102417 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6934685707092285 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6873915195465088 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.668635368347168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6829779148101807 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.67270827293396 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6712357997894287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6812822818756104 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6841566562652588 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6657307147979736 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.52it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.54it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.55it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.28it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.51it/s]

Selected split_temperature=0.182074901698571 based on validation mse=290190.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6629621982574463 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6923277378082275 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.682948112487793 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6710457801818848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.682722806930542 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6978394985198975 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7083349227905273 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7110061645507812 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7031252384185791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.67848801612854 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.00s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.00s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.76it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.31it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.30it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:03<00:03,  3.51it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:03<00:02,  4.59it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:03<00:01,  6.00it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:03<00:00,  7.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00,  9.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.78it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=283087.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6614193916320801 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6971526145935059 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6832849979400635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6695723533630371 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6848313808441162 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6701951026916504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6729259490966797 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.681725025177002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6833486557006836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6717381477355957 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.67it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.00it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.28it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.46it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.26it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.57it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.84it/s]

[I 2026-04-23 01:23:41,191] Trial 19 finished with value: 278727.95 and parameters: {'exponent': 0.8624387193928215, 'kernel_type': 'k2q', 'bandwidth': 9.757810676379755, 'diag': False, 'reg': 0.011575165702524369}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=283474.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6637182235717773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926343441009521 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6821846961975098 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6684315204620361 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.682039737701416 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6587123870849609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.650423526763916 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.19it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.49it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.98it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.39it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.26it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.62it/s]

Selected split_temperature=0.04605387583570519 based on validation mse=270824.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4303
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6630878448486328 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6918540000915527 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6822049617767334 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6703119277954102 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6619610786437988 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6418805122375488 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6595091819763184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6639208793640137 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6675999164581299 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6558148860931396 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.76s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.88it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.47it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.42it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.44it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.18it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.36it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.16it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.17it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=263649.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619157791137695 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.688474178314209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6815166473388672 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6690521240234375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.6669394969940186 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6856653690338135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6763966083526611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6731045246124268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7087359428405762 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7019870281219482 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.97s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.97s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 40.53it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 33.94it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.89it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.72it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.28it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.56it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=288620.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4299
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6675863265991211 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6997365951538086 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6900331974029541 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6761038303375244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6949772834777832 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6799509525299072 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6762795448303223 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6889076232910156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6810140609741211 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6722371578216553 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.14it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.43it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.12it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.45it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.87it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.43it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.32it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=299500.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6646077632904053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7186813354492188 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7151727676391602 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7105138301849365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7113697528839111 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6953256130218506 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6794331073760986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7161548137664795 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7187056541442871 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7127382755279541 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.19s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.19s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.71it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.77it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.07it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.68it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.35it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.83it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.71it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.37it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.60it/s]

[I 2026-04-23 01:24:33,084] Trial 20 finished with value: 280945.85 and parameters: {'exponent': 1.1567938986375246, 'kernel_type': 'k2q', 'bandwidth': 22.313964699968146, 'diag': False, 'reg': 0.0013964856196374417}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.21212000487151167 based on validation mse=282134.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6731829643249512 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7043416500091553 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6772494316101074 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.687368631362915 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6855964660644531 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.339250326156616 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6622285842895508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7005860805511475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6803708076477051 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.671177864074707 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.61s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.61s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.38it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 40.83it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 37.89it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.22it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.20it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 31.85it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 30.86it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 30.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.78it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=269475.718750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6852121353149414 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7017977237701416 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7144172191619873 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6890249252319336 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7057647705078125 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6558711528778076 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6580321788787842 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.689995288848877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6813182830810547 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6628587245941162 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.00s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.00s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.27it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 42.37it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.92it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.99it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.79it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.89it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.53it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.31it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.99it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268228.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4259
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.692547082901001 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.720268964767456 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7083401679992676 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6769123077392578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6810417175292969 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4371
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6613516807556152 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6697852611541748 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6757707595825195 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7093985080718994 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7063052654266357 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.97it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 36.87it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 34.82it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 31.58it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.94it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 28.75it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 28.99it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 29.17it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 29.34it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 29.39it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.27it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=289356.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6611974239349365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.717841386795044 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7140965461730957 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6741044521331787 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6865160465240479 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6674621105194092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6771812438964844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6717712879180908 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.2907538414001465 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6748278141021729 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.55s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.55s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.04it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.45it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.38it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.96it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.50it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.27it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.81it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=279499.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6622419357299805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6954188346862793 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6845955848693848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6693143844604492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6823787689208984 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6706016063690186 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6716172695159912 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.682363748550415 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6814515590667725 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6763014793395996 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.04it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.62it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.41it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.35it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.25it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 26.98it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.25it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.92it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.35it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.69it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.07it/s]

[I 2026-04-23 01:25:29,474] Trial 21 finished with value: 277870.25 and parameters: {'exponent': 0.9532282633904808, 'kernel_type': 'k2q', 'bandwidth': 5.656911333619153, 'diag': False, 'reg': 0.03346278462776802}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.11514774870862055 based on validation mse=282789.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6643636226654053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6933462619781494 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6827266216278076 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6731200218200684 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6660079956054688 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6300196647644043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6649196147918701 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6634039878845215 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6609146595001221 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.10s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.10s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.03it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.67it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.59it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.07it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.45it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.25it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.11it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.06it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.21it/s]

Selected split_temperature=0.08483837917962198 based on validation mse=280631.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6644570827484131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6996197700500488 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6747643947601318 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.682300329208374 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6780178546905518 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6606051921844482 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6546280384063721 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6702930927276611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.668269157409668 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6561157703399658 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 44.77it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.90it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.37it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.29it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.28it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 29.81it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.79it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00,  3.51it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.72it/s]

Selected split_temperature=0.07282170089875539 based on validation mse=288733.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6648330688476562 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6822762489318848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6923007965087891 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6685547828674316 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6843702793121338 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6707861423492432 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6746726036071777 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6814818382263184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6884620189666748 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6805269718170166 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.51it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.26it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.92it/s]

Selected split_temperature=0.029125376821935778 based on validation mse=302811.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4293
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6643273830413818 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692528486251831 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6733295917510986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6743078231811523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6775586605072021 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4337
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6744089126586914 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6751599311828613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6743452548980713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6909148693084717 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.664461612701416 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.89it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.36it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.54it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.60it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.63it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

Selected split_temperature=0.07282170089875539 based on validation mse=299223.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6617228984832764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7191863059997559 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7159667015075684 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7066006660461426 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7127199172973633 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7062654495239258 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6894621849060059 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6804783344268799 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6861023902893066 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.674689531326294 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.09s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.09s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.75it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.82it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.90it/s]

[I 2026-04-23 01:26:22,437] Trial 22 finished with value: 293679.0 and parameters: {'exponent': 0.9715911388276843, 'kernel_type': 'k2q', 'bandwidth': 4.37721308576403, 'diag': False, 'reg': 0.21218539240460138}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.06250708904468986 based on validation mse=296996.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6613783836364746 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 3.6340930461883545 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6949679851531982 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6690263748168945 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6813294887542725 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6365742683410645 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.640639066696167 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6688470840454102 seconds

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.39s/it]

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.39s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.74it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.37it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.00it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.53it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.62it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.45it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=271622.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618866920471191 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6907641887664795 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6891887187957764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6739628314971924 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6806259155273438 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6541469097137451 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6605613231658936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6647133827209473 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6695156097412109 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.660651683807373 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.48it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.27it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.14it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=272151.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4260
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624360084533691 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6964030265808105 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6839158535003662 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6738500595092773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6821484565734863 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4370
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6784055233001709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6743214130401611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6780965328216553 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6892883777618408 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6739006042480469 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.60it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.55it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.88it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.09it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.21it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.31it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.39it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.71it/s]

Selected split_temperature=0.182074901698571 based on validation mse=292937.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6654326915740967 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6917819976806641 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6814956665039062 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6705129146575928 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6844685077667236 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6146204471588135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6808998584747314 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6792411804199219 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6859779357910156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6759943962097168 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.75it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.38it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.50it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.19it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.12it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.16it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.68it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.97it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=279012.406250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4381
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6623461246490479 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.684809684753418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6955227851867676 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6709728240966797 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6813912391662598 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4249
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6473827362060547 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6588478088378906 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6821048259735107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6757340431213379 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6807324886322021 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.42it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.96it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.95it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.68it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.02it/s]

[I 2026-04-23 01:27:17,486] Trial 23 finished with value: 280973.1625 and parameters: {'exponent': 0.808155280216631, 'kernel_type': 'k2q', 'bandwidth': 5.397673648407642, 'diag': False, 'reg': 0.015075246533550132}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=289142.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4319
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6615517139434814 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6928186416625977 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6874434947967529 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6693248748779297 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6872901916503906 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4312
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6439511775970459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6574716567993164 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.30it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.84it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.50it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.35it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.45it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.19it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.74it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=266010.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6665284633636475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6889328956604004 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.685591459274292 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6746411323547363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6808335781097412 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6647605895996094 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6604883670806885 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6640803813934326 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6693301200866699 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6609046459197998 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.56it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:03<00:03,  3.50it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:03<00:02,  4.59it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:03<00:01,  6.00it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:03<00:00,  7.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00,  9.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.80it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268753.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4273
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6668586730957031 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6940383911132812 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6825239658355713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6748261451721191 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6793060302734375 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4357
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6697018146514893 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6742739677429199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6750888824462891 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6855247020721436 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6788878440856934 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.04it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.94it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.66it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.37it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.99it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=291197.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6694400310516357 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6855299472808838 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6926469802856445 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6685070991516113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6850607395172119 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6505684852600098 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6824524402618408 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6723537445068359 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6839873790740967 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.662959098815918 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.82it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.69it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.45it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.41it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.06it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.28it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.78it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.89it/s]

Selected split_temperature=0.05365345951302222 based on validation mse=281248.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.664452314376831 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692903995513916 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.68918776512146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6708517074584961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6781702041625977 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6444156169891357 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6863675117492676 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6708741188049316 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6833248138427734 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6821115016937256 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.98it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.05it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.36it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.66it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.76it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

[I 2026-04-23 01:28:08,833] Trial 24 finished with value: 277998.9125 and parameters: {'exponent': 1.0726397611800362, 'kernel_type': 'k2q', 'bandwidth': 2.27450157135097, 'diag': False, 'reg': 0.060044003311480985}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=282783.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.614468812942505 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6983034610748291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6852724552154541 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6717674732208252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6863353252410889 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6435592174530029 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.66084885597229 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.660780668258667 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6691770553588867 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6656351089477539 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.51it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.38it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.65it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.08it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.69it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.45it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.95it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=274272.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6633446216583252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6963951587677002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6840362548828125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6722617149353027 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6833972930908203 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.683579683303833 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6889629364013672 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6969459056854248 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6731393337249756 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6625974178314209 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.38it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.30it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.07it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.03it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.33it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.46it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.07it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=274713.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6643435955047607 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7066614627838135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6830170154571533 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6553962230682373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6986532211303711 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6762945652008057 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6802663803100586 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6741149425506592 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6815204620361328 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6839118003845215 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.33it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.47it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.25it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.03it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=301368.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6931889057159424 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6946244239807129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858057975769043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6805942058563232 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.636409044265747 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6784200668334961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.673274040222168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6819815635681152 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6898086071014404 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6765415668487549 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.26it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.40it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.80it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.87it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.11it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.66it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.33it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.90it/s]

Selected split_temperature=0.182074901698571 based on validation mse=285307.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4379
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.668325662612915 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.696967601776123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858203411102295 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6559069156646729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6914386749267578 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4251
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6658623218536377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6815569400787354 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6857225894927979 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6845743656158447 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6831099987030029 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.99it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.65it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.46it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.24it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.40it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.45it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.89it/s]

[I 2026-04-23 01:29:05,397] Trial 25 finished with value: 285420.275 and parameters: {'exponent': 1.0850529617960842, 'kernel_type': 'k2q', 'bandwidth': 1.0768682636800708, 'diag': False, 'reg': 0.058407949709093104}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.13414886285344563 based on validation mse=291438.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778408050537109 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57646107673645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.576805591583252 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.540001153945923 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580007791519165 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.744560480117798 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.553771257400513 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5507566928863525 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.552619218826294 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.501056909561157 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.26s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.26s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:10,  2.05s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:07,  1.78s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.60s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.47s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.38s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=273469.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780418634414673 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570800304412842 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.577801704406738 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.571164608001709 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575114011764526 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.74763298034668 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5618603229522705 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.553181171417236 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.559692859649658 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.556578874588013 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.30s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.30s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:43,  1.67s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:35,  1.42s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:30,  1.27s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:26,  1.17s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:24,  1.12s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:23,  1.10s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:21,  1.09s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:20,  1.09s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.09s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=278575.156250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.717679500579834 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.56213116645813 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.566880226135254 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.559380769729614 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563446283340454 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.758319616317749 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.525120735168457 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.568756818771362 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.569159507751465 seconds

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.70s/it]

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.70s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.08s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.10s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.76s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:17,  1.58s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.45s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.32s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.28s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.25s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.23s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=300332.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76626181602478 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581550598144531 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.606305360794067 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.310431718826294 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.680493116378784 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.833723068237305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.566587448120117 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564709663391113 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.27s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.27s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:08<00:41,  1.54s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:34,  1.32s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:29,  1.18s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:26,  1.09s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:24,  1.05s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:22,  1.03s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.04s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:20,  1.06s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:18<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:19<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:33<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:34<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.07s/it]

Selected split_temperature=0.025000000000000005 based on validation mse=297350.562500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4380
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.725621223449707 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575404405593872 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56788969039917 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.568438768386841 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5712950229644775 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4250
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.747303009033203 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.514378786087036 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56584620475769 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566567420959473 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.566601753234863 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.27s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.27s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:33,  1.96s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:27,  1.71s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:23,  1.54s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:19,  1.43s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:17,  1.35s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.29s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.22s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=294083.406250
Using soft routing for tree prediction

[I 2026-04-23 01:36:50,319] Trial 26 finished with value: 288762.075 and parameters: {'exponent': 1.0415046249304305, 'kernel_type': 'kpq', 'bandwidth': 2.6754827238954753, 'diag': False, 'norm_p': 1.5004864282542085, 'reg': 0.20400840461443198}. Best is trial 11 with value: 277777.875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6632726192474365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6934380531311035 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6830341815948486 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6721444129943848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6847586631774902 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6563248634338379 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6564619541168213 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.99it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 38.26it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.64it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.58it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.24it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.44it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 33.08it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=285108.093750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4315
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6629526615142822 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6907594203948975 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6847617626190186 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.5807061195373535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7113966941833496 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4316
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6728289127349854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6591229438781738 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.666344165802002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6653180122375488 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6605989933013916 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.77s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.77s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.46it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.50it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.25it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.44it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.57it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.69it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.182074901698571 based on validation mse=291952.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4262
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6643373966217041 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.689589262008667 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6868946552276611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6700558662414551 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6830875873565674 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4368
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6761810779571533 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6750450134277344 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6753208637237549 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.709355354309082 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7027654647827148 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.50it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.87it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.49it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.24it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

Selected split_temperature=0.0 based on validation mse=308405.250000
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4291
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.665797233581543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.694770097732544 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6687486171722412 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6809029579162598 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6781668663024902 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4339
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6774308681488037 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6731534004211426 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.681246280670166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6867406368255615 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.672313928604126 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 43.57it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.67it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.24it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.16it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.80it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.00it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.80it/s]

Selected split_temperature=0.182074901698571 based on validation mse=282821.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6621453762054443 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6968832015991211 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.684927225112915 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6709194183349609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6918566226959229 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6737160682678223 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6745812892913818 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6822221279144287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.686159610748291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6772177219390869 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.08it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.45it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.86it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.44it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.09it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.96it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

[I 2026-04-23 01:37:44,854] Trial 27 finished with value: 295884.99375 and parameters: {'exponent': 1.1761772528009447, 'kernel_type': 'k2q', 'bandwidth': 1.5809821898918912, 'diag': False, 'reg': 0.0034737529393032234}. Best is trial 11 with value: 277777.875.

Selected split_temperature=0.1562854472336314 based on validation mse=311137.593750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6671397686004639 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6757652759552002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.690183162689209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6718976497650146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7084226608276367 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6914031505584717 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6913514137268066 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.92s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.92s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.01it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.82it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.66it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.55it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.54it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.82it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.65it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.77it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.61it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.00it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267597.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669785976409912 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6853146553039551 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6665384769439697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6864621639251709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.674201250076294 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.668372631072998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6528940200805664 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6655874252319336 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6654937267303467 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6572227478027344 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.21it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.71it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.55it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.98it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.04it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268091.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6671957969665527 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692598819732666 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6830322742462158 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.67311692237854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6797730922698975 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6891746520996094 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6815333366394043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6851518154144287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6854250431060791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6709389686584473 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.27it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.93it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.55it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:03<00:06,  3.08it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:03<00:04,  4.17it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:03<00:02,  5.54it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:03<00:01,  7.24it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:03<00:00,  9.36it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:04<00:00, 11.77it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00, 14.37it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.59it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=289701.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6606795787811279 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6962978839874268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6833651065826416 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6719868183135986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6830289363861084 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6572680473327637 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.658087968826294 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6766595840454102 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6809139251708984 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6780705451965332 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.39it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.89it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.32it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.00it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.05365345951302222 based on validation mse=278328.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6638350486755371 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6948826313018799 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6854660511016846 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6722545623779297 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6804571151733398 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6741602420806885 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7013716697692871 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7042295932769775 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6861379146575928 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.680445671081543 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.07it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.63it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.75it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.18it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.80it/s]

[I 2026-04-23 01:38:36,657] Trial 28 finished with value: 277413.0875 and parameters: {'exponent': 0.9941620000240445, 'kernel_type': 'k2q', 'bandwidth': 2.9107212011839474, 'diag': False, 'reg': 0.05060156574452101}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.11514774870862055 based on validation mse=283346.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6664631366729736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7218244075775146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6903045177459717 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7115252017974854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6898283958435059 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6578118801116943 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.651893138885498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6559622287750244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6855902671813965 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6527316570281982 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.71it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.72it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.02it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.98it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.07282170089875539 based on validation mse=285532.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.6168839931488037 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6879880428314209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6920912265777588 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6663305759429932 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6869831085205078 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6413884162902832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6398558616638184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6649940013885498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6641011238098145 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6653149127960205 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.73s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.73s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.00it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.15it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.30it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.43it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.53it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.54it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

Selected split_temperature=0.0 based on validation mse=297332.718750
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6611673831939697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6913037300109863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.686790943145752 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6744287014007568 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6840031147003174 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6720402240753174 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6766018867492676 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6807398796081543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6847743988037109 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6769571304321289 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.90it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.28it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.29it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.72it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.78it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

Selected split_temperature=0.03393150300079013 based on validation mse=309299.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4292
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7037899494171143 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7199254035949707 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7002732753753662 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6548807621002197 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6926009654998779 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4338
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.675539493560791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6764488220214844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7027931213378906 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7146313190460205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7111737728118896 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.07s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.08s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.11it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.74it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.49it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.06it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.52it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.84it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.28it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 24.97it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 25.50it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.62it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.16it/s]

Selected split_temperature=0.06250708904468986 based on validation mse=313842.406250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6684756278991699 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6870887279510498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.68878173828125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.63210391998291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.683861494064331 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6913919448852539 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6832489967346191 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6843383312225342 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6870303153991699 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.673558235168457 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.09it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.61it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.32it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.33it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.23it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.03it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.17it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.80it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.33it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.72it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.07it/s]

[I 2026-04-23 01:39:33,609] Trial 29 finished with value: 302783.0125 and parameters: {'exponent': 1.0058058563398056, 'kernel_type': 'k2q', 'bandwidth': 3.1536630769703455, 'diag': False, 'reg': 0.39642899279241767}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.06250708904468986 based on validation mse=307908.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4319
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6625635623931885 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6952755451202393 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6836695671081543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6713411808013916 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6884880065917969 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4312
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6372678279876709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6580960750579834 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.79s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.39it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.74it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.69it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.09it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.96it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=275841.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6376533508300781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6971092224121094 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6852908134460449 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6744751930236816 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6844069957733154 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6427390575408936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6353716850280762 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6677067279815674 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6676416397094727 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.656496524810791 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.75s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.75s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.65it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.67it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.69it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.17it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.28it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.53it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.182074901698571 based on validation mse=281471.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.66575026512146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7164795398712158 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7143282890319824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6714801788330078 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6850006580352783 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618659496307373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6619937419891357 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6767849922180176 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.6396069526672363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6731157302856445 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.88s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.86it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.23it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.06it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.0 based on validation mse=300446.687500
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6654307842254639 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926488876342773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6845462322235107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6695761680603027 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6891744136810303 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6697030067443848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6770353317260742 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.677232027053833 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.686403751373291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6764984130859375 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.18it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.25it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.56it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.52it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.97it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.53it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.31it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.88it/s]

Selected split_temperature=0.182074901698571 based on validation mse=283534.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4393
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6898221969604492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901392936706543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6874659061431885 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6734232902526855 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.674288272857666 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4237
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6530067920684814 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.685389518737793 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6728713512420654 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6820068359375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6807029247283936 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.83it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.91it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.89it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.06it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.89it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.67it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 28.05it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.79it/s]

[I 2026-04-23 01:40:25,095] Trial 30 finished with value: 288966.9 and parameters: {'exponent': 0.8902098325522361, 'kernel_type': 'k2q', 'bandwidth': 8.488259562370697, 'diag': False, 'reg': 0.0012471383315373478}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.1562854472336314 based on validation mse=303540.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6628444194793701 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7201755046844482 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7046420574188232 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.678459882736206 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6818299293518066 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6580908298492432 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6556024551391602 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6644725799560547 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.54s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.54s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.74it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.24it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.38it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.12it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.96it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.09it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267938.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669158935546875 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.683781623840332 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6876659393310547 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6750953197479248 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6839125156402588 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6348776817321777 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6594967842102051 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6579029560089111 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.666104793548584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6572954654693604 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.74s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.74s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.49it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.22it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.62it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.59it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.42it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.27it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268280.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6911451816558838 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7144238948822021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6836156845092773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7009124755859375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.696028470993042 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6807286739349365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6724326610565186 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6829395294189453 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6866500377655029 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6732814311981201 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  9.00s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.93it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.28it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.94it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.56it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.82it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.99it/s]

Selected split_temperature=0.025000000000000005 based on validation mse=290625.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6917965412139893 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7174718379974365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6825239658355713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6813538074493408 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6777682304382324 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6785979270935059 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6729769706726074 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6803951263427734 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6950037479400635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.674567699432373 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.14it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.47it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.47it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.02it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.95it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.02it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=280804.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6647539138793945 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7211651802062988 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.6508023738861084 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.683175802230835 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6808483600616455 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6771495342254639 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6694803237915039 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.683814287185669 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6813259124755859 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6735961437225342 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.90s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.90it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.84it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.87it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.10it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.87it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.10it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.98it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.90it/s]

[I 2026-04-23 01:41:20,458] Trial 31 finished with value: 278364.38125 and parameters: {'exponent': 1.0068424983247883, 'kernel_type': 'k2q', 'bandwidth': 1.8405765042044795, 'diag': False, 'reg': 0.05303687060705579}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.11514774870862055 based on validation mse=284173.593750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6638414859771729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6953837871551514 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6866843700408936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6722981929779053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7103893756866455 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6721820831298828 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6605815887451172 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.50it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.73it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.77it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.88it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.21it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.48it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.07it/s]

Selected split_temperature=0.09883799050275041 based on validation mse=267650.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6613917350769043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6954796314239502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6815080642700195 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6723611354827881 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6768534183502197 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6511547565460205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6576664447784424 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6641499996185303 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6677639484405518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6840603351593018 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.86it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.62it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.43it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.94it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.16it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.36it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.72it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.30it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.45it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.37it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.73it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=272357.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6434431076049805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6917293071746826 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6901028156280518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6715333461761475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7084066867828369 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.712651252746582 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6911211013793945 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.633277654647827 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6885473728179932 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6762185096740723 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.66it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.92it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.83it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.04it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=292897.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6674988269805908 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6905617713928223 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6852490901947021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6746647357940674 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6810705661773682 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6599664688110352 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6744439601898193 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.84s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.84s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.88it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.42it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.36it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.81it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.24it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.78it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.05it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=282471.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6628308296203613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6922101974487305 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6847841739654541 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6748385429382324 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6840565204620361 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6703705787658691 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.671680212020874 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6779193878173828 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6833007335662842 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6746468544006348 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.23it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.38it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.11it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.40it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.86it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

[I 2026-04-23 01:42:10,130] Trial 32 finished with value: 280208.20625 and parameters: {'exponent': 1.0924283759041364, 'kernel_type': 'k2q', 'bandwidth': 2.3681556089558193, 'diag': False, 'reg': 0.08521545694489362}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.13414886285344563 based on validation mse=285663.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618561744689941 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7186546325683594 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6904053688049316 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6756575107574463 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6789031028747559 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6805648803710938 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6894404888153076 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6848187446594238 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6504225730895996 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.668889045715332 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.66it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.49it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.51it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.69it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.04it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.32it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.09it/s]

Selected split_temperature=0.09883799050275041 based on validation mse=271055.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4303
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.665966272354126 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.68338942527771 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6900219917297363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6715357303619385 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6857116222381592 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6354191303253174 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.644355058670044 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6643359661102295 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6702337265014648 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6571576595306396 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.73s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.73s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.91it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.83it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.64it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.85it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.73it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.40it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.01it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=270359.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6651103496551514 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.718468189239502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7119133472442627 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6865091323852539 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7149314880371094 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6874558925628662 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6780402660369873 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.679424524307251 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6697118282318115 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.692004919052124 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.99it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.42it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.84it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.69it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.08it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.00it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.89it/s]

Selected split_temperature=0.04605387583570519 based on validation mse=290932.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4288
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619231700897217 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6941311359405518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.686159610748291 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6718440055847168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.709191083908081 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4342
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6858880519866943 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6747238636016846 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6777627468109131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6842896938323975 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6780526638031006 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.30it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.80it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.41it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.99it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=279361.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4384
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6904387474060059 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6917760372161865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.6457622051239014 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.675818920135498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6764194965362549 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4246
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6685047149658203 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6666109561920166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6880526542663574 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.680647611618042 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6891779899597168 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.90s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.49it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.62it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.92it/s]

[I 2026-04-23 01:43:06,901] Trial 33 finished with value: 279780.03125 and parameters: {'exponent': 0.8078102560695968, 'kernel_type': 'k2q', 'bandwidth': 3.6850488994480997, 'diag': False, 'reg': 0.030157094403034164}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.13414886285344563 based on validation mse=287192.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.71081280708313 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.576672077178955 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.6791911125183105 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.553309679031372 seconds

Building trees: 100%|██████████| 1/1 [00:23<00:00, 23.83s/it]

Building trees: 100%|██████████| 1/1 [00:23<00:00, 23.83s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:20,  2.36s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:52,  1.59s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:39,  1.23s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:32,  1.03s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:27,  1.08it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:24,  1.16it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:23,  1.21it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:21,  1.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.23it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:20,  1.21it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:39<00:04,  2.05s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:01,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.60s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.182074901698571 based on validation mse=439639.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.73640251159668 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5604774951934814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560906410217285 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564713001251221 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57053542137146 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.614077091217041 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.672350168228149 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.626286745071411 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.575965881347656 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.555501461029053 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.33s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.33s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:37,  1.71s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:31,  1.51s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:27,  1.38s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:24,  1.29s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:22,  1.24s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:18<00:20,  1.20s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:19<00:18,  1.18s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.17s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:33<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.07s/it]

Selected split_temperature=0.182074901698571 based on validation mse=410640.312500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.652279376983643 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.560532093048096 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583096504211426 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564547300338745 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559091567993164 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.6872968673706055 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.568093538284302 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.52111291885376 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.568147659301758 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.573368072509766 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.13s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.13s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.07it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.08s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.10s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.01s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.75s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.57s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:15,  1.45s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.36s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.30s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=532764.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7042059898376465 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563200235366821 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.567461013793945 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.692601680755615 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.565074682235718 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.571341037750244 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565850019454956 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.568593263626099 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.05s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.05s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:46,  1.65s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:37,  1.38s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:31,  1.20s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:27,  1.10s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:24,  1.04s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:23,  1.01s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:22,  1.01s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:21,  1.02s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.03s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=532179.562500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.708284854888916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57022500038147 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5714709758758545 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.567556858062744 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57242488861084 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.682343482971191 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.523091554641724 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.559834241867065 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5621373653411865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.565035343170166 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.14s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.14s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:34,  1.93s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:28,  1.69s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.52s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.41s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.33s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.28s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.24s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=538306.687500
Using soft routing for tree prediction

[I 2026-04-23 01:50:26,583] Trial 34 finished with value: 490706.08125 and parameters: {'exponent': 0.9630335265434886, 'kernel_type': 'kpq', 'bandwidth': 1.479815470801011, 'diag': False, 'norm_p': 0.9638803577454941, 'reg': 0.004842948849622082}. Best is trial 28 with value: 277413.0875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6613688468933105 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6944794654846191 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6778485774993896 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.671837329864502 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6799321174621582 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6583700180053711 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6508216857910156 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6565449237823486 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6829969882965088 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.12s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.12s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.76it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.80it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.15it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.53it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.33it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.10it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.28it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=300380.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6660940647125244 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.713416337966919 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6933412551879883 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6762144565582275 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6817901134490967 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6646711826324463 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6803245544433594 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6903457641601562 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6948306560516357 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6765050888061523 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.65it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.61it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.10it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.29it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.47it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.65it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.92it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=316028.093750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6628239154815674 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.716942548751831 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.7118449211120605 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6690258979797363 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6888363361358643 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6749875545501709 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6717731952667236 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.679473876953125 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6819043159484863 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6711463928222656 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.88it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.30it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.32it/s]

Selected split_temperature=0.182074901698571 based on validation mse=333492.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6923458576202393 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6895840167999268 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6721677780151367 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6836495399475098 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6713078022003174 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6753697395324707 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6691362857818604 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6800541877746582 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.56s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.56s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 48.80it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 45.48it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.99it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 36.04it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 33.79it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 32.40it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:00<00:00, 31.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.93it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=331937.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6601738929748535 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6916024684906006 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6825747489929199 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.668168306350708 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 3.6375105381011963 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6422603130340576 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6648762226104736 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6756205558776855 seconds

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.45s/it]

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.45s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.16it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 41.82it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 38.42it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.72it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.52it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 32.19it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 31.33it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 30.79it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 33.02it/s]

[I 2026-04-23 01:51:19,645] Trial 35 finished with value: 320423.8125 and parameters: {'exponent': 1.0702769837540553, 'kernel_type': 'k2q', 'bandwidth': 10.336479049392569, 'diag': True, 'reg': 0.3156726316777943}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.1562854472336314 based on validation mse=320280.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4315
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6615743637084961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.694974422454834 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6775131225585938 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6734089851379395 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6790437698364258 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4316
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6491947174072266 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6434640884399414 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.77s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.77s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.88it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.73it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.73it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.41it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.43it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 31.40it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.96it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=272486.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6634280681610107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7140333652496338 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7142856121063232 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6709375381469727 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6822178363800049 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6467735767364502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6597335338592529 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6600372791290283 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6686875820159912 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6627383232116699 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.89it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.56it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.68it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.80it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.41it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.57it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.02it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=279657.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6900830268859863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7094197273254395 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6819901466369629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6792745590209961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6795110702514648 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6706633567810059 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6811904907226562 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7080864906311035 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7171206474304199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7124958038330078 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.05s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.05s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.93it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.48it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.13it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.17it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.99it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.89it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:04<00:00,  3.75it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.76it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=296278.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6657302379608154 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7198994159698486 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.71370530128479 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7021622657775879 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6799886226654053 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6717636585235596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6747806072235107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6789841651916504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6831228733062744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6772544384002686 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.60it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.96it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.18it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.34it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.42it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.50it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.78it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=282614.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4378
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6656734943389893 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7185952663421631 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.707831859588623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6500396728515625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6977355480194092 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4252
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.661041259765625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.670363187789917 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6721723079681396 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6851823329925537 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6809737682342529 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.06it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.70it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.57it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.32it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.37it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.41it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.89it/s]

[I 2026-04-23 01:52:11,372] Trial 36 finished with value: 285174.98125 and parameters: {'exponent': 0.7009510996362425, 'kernel_type': 'k2q', 'bandwidth': 5.629273350248307, 'diag': False, 'reg': 0.008519878785603749}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.13414886285344563 based on validation mse=294837.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77475118637085 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570876836776733 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.527005672454834 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5724778175354 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.569684743881226 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.744853973388672 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.06s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.06s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:39,  1.87s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:32,  1.64s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:28,  1.48s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.38s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:22,  1.32s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:20,  1.28s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:18,  1.25s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:17,  1.24s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.23s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.22s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.21s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=366485.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.722345590591431 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.573789596557617 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.557713747024536 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.559815883636475 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.562365770339966 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.758520841598511 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57688307762146 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.488346338272095 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.669990301132202 seconds

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.79s/it]

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.79s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:22,  1.50it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:21,  1.96s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.72s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:14,  1.56s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:11,  1.45s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.37s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.31s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.24s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.23s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=394981.718750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760487794876099 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.561777353286743 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560885667800903 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.518774509429932 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559718132019043 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760693788528442 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.02s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.02s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.99s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.75s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:22,  1.58s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:18,  1.46s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.37s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.32s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.28s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.25s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.025000000000000005 based on validation mse=398424.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760955333709717 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5699403285980225 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.521628141403198 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750185251235962 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563578128814697 seconds

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.46s/it]

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.46s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.66it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:32,  2.01s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:26,  1.77s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:22,  1.60s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:19,  1.48s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.40s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.34s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:11,  1.27s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.25s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.24s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.22s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.11s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=419712.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77206563949585 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578653335571289 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.533069849014282 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562521934509277 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563586235046387 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7514262199401855 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.556450366973877 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.63s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.63s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.67it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:45,  1.67s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:36,  1.41s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:31,  1.25s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:27,  1.15s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:25,  1.09s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:23,  1.07s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:22,  1.07s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.08s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.10s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.07282170089875539 based on validation mse=407492.468750
Using soft routing for tree prediction

[I 2026-04-23 01:58:51,826] Trial 37 finished with value: 397419.30625 and parameters: {'exponent': 1.1357285477080539, 'kernel_type': 'kpq', 'bandwidth': 15.99825902605717, 'diag': False, 'norm_p': 1.4912953334636938, 'reg': 0.9994242580023474}. Best is trial 28 with value: 277413.0875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6641008853912354 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.69576096534729 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6789379119873047 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6715412139892578 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7079124450683594 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4303
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6708245277404785 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6565546989440918 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.80s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.80it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.38it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.38it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.14it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.94it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.43it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.27it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.15it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.97it/s]

Selected split_temperature=0.08483837917962198 based on validation mse=264375.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6591005325317383 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.688929557800293 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6804327964782715 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6675879955291748 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7090394496917725 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6722218990325928 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.653329610824585 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6635761260986328 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6648135185241699 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6563119888305664 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.82s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.14it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.71it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 31.82it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.24it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.07it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.13it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.87it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.46it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.09it/s]

Selected split_temperature=0.025000000000000005 based on validation mse=268112.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4275
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.661531925201416 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6829981803894043 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6902101039886475 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6673827171325684 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6831657886505127 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4355
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6509809494018555 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6750097274780273 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6515531539916992 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6935176849365234 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6745872497558594 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.84s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.19it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.42it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.93it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.88it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.85it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.72it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.13it/s]

Selected split_temperature=0.04605387583570519 based on validation mse=288229.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6650881767272949 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6869020462036133 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6818943023681641 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6695470809936523 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.7082428932189941 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 3.636777400970459 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6715731620788574 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6739387512207031 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6858453750610352 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6732463836669922 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.28it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.66it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.51it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.24it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.82it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.0 based on validation mse=279007.125000
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6635661125183105 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6907551288604736 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6863803863525391 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6743223667144775 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6838057041168213 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6749587059020996 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6680011749267578 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.687830924987793 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6812856197357178 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6763007640838623 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.82it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.97it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.96it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.84it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.81it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.67it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 28.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.93it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.79it/s]

[I 2026-04-23 01:59:46,381] Trial 38 finished with value: 278764.3875 and parameters: {'exponent': 1.3401811194465532, 'kernel_type': 'k2q', 'bandwidth': 2.3325425859414413, 'diag': True, 'reg': 0.1410226161753384}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.08483837917962198 based on validation mse=294096.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4316
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624095439910889 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6828920841217041 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6945304870605469 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6736905574798584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6815755367279053 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4315
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6413381099700928 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.13s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.13s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:00<00:00, 49.79it/s]

Tuning split temperature:  31%|███       | 11/36 [00:00<00:00, 44.62it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 39.41it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 36.12it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 32.21it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.28it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.84it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.09883799050275041 based on validation mse=384524.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.661909818649292 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6896400451660156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6881425380706787 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6677961349487305 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6876277923583984 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6566662788391113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.654221773147583 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6625726222991943 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6691572666168213 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.13s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.13s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.86it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.48it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.05it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.38it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=433898.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6647951602935791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6925497055053711 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6763379573822021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6742069721221924 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6801488399505615 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6781322956085205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6717450618743896 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.81s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:00<00:00, 49.82it/s]

Tuning split temperature:  31%|███       | 11/36 [00:00<00:00, 44.53it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 39.25it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 36.01it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 31.42it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 28.71it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.43it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.53it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.98it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=422929.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619489192962646 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6906025409698486 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.683915376663208 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6735785007476807 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6796696186065674 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6715314388275146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6698412895202637 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6764113903045654 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.53s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.53s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.84it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.37it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.45it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.87it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.30it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=472423.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6649742126464844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6981046199798584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6754813194274902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6783192157745361 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6792647838592529 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6684789657592773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6707966327667236 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6734201908111572 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6832230091094971 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.20s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.20s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.90it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.23it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.66it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.83it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.73it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.00it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.87it/s]

[I 2026-04-23 02:00:32,401] Trial 39 finished with value: 424733.4625 and parameters: {'exponent': 1.2962518347168492, 'kernel_type': 'k2q', 'bandwidth': 167.1980274781167, 'diag': False, 'reg': 0.033404273276354396}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.11514774870862055 based on validation mse=409891.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.769933223724365 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.642782211303711 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.691645383834839 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.687679767608643 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.689120054244995 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.734790086746216 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.57s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.57s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.68it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.49it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:45,  1.68s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:36,  1.42s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:31,  1.25s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:27,  1.15s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:25,  1.10s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:23,  1.07s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:22,  1.07s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.09s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.11s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.182074901698571 based on validation mse=279490.843750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.767332077026367 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.692863702774048 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.682324409484863 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.684370756149292 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.680220603942871 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.732703924179077 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.626233100891113 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.669380187988281 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.665166616439819 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.67179536819458 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.14s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.15s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:37,  1.89s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:31,  1.65s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:26,  1.49s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:23,  1.39s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:21,  1.32s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.28s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.25s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.23s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.21s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=286442.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.7658820152282715 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.6339428424835205 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.693407297134399 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.726213216781616 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.6932289600372314 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.782399415969849 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.74851131439209 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.471841335296631 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.784096717834473 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.832626581192017 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.56s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.56s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.64it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:25,  1.93s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:20,  1.71s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.55s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.44s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.36s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.31s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.24s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.22s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=299651.437500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.768192529678345 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.68402624130249 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.639115571975708 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.681617021560669 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.69363260269165 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.746394395828247 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.68742036819458 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.6932384967803955 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.684882164001465 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.6474690437316895 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.28s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.28s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.70it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:27<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:14,  2.06s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:10,  1.80s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.61s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.48s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.39s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.33s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.28s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.25s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.182074901698571 based on validation mse=285203.687500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.769418954849243 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.684858083724976 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.694904565811157 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.692753314971924 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.650634527206421 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.744666337966919 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.6836323738098145 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.676483869552612 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.679098606109619 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.694180011749268 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.33s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.33s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:58,  1.83s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:44,  1.42s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:35,  1.19s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:30,  1.04s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:26,  1.05it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:24,  1.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:22,  1.13it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:22,  1.14it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:21,  1.12it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:21,  1.09it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.06it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:41<00:02,  2.07s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.80s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.18s/it]

Selected split_temperature=0.182074901698571 based on validation mse=311468.437500
Using soft routing for tree prediction

[I 2026-04-23 02:08:24,883] Trial 40 finished with value: 292451.3625 and parameters: {'exponent': 0.9006657809447237, 'kernel_type': 'kpq', 'bandwidth': 26.18980724666157, 'diag': True, 'norm_p': 1.2228654774857641, 'reg': 0.0021958182495040346}. Best is trial 28 with value: 277413.0875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6657419204711914 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901803016662598 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.682924747467041 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6745083332061768 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.705402135848999 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6797049045562744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6518869400024414 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6649737358093262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6714999675750732 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.18s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.18s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.28it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.71it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.74it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.09it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.27it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.08it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267608.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616165637969971 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6948540210723877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6838293075561523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6682591438293457 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6864383220672607 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6514668464660645 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6591789722442627 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6610727310180664 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6711485385894775 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.653038501739502 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.79s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.79s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.15it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.69it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.82it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.16it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.63it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.35it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.94it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268216.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616642475128174 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.70086669921875 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6817331314086914 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6700272560119629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6821227073669434 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6685233116149902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6899278163909912 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6799125671386719 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7097256183624268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7046108245849609 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.04it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.49it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.25it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.88it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.39it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.18it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.73it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.92it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=291132.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4286
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6633543968200684 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692988395690918 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6885561943054199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6746957302093506 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6881206035614014 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4344
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6789250373840332 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.672429084777832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7004852294921875 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7141025066375732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7072088718414307 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.94s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.95s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.40it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.50it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.18it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.46it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.54it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.80it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.38it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.98it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=281067.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6644928455352783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6950628757476807 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6836600303649902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6751863956451416 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6891353130340576 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6748428344726562 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6983702182769775 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7094416618347168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7088916301727295 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6791422367095947 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.99s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.77it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.98it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.25it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.74it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.00it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.90it/s]

[I 2026-04-23 02:09:18,002] Trial 41 finished with value: 278376.66875 and parameters: {'exponent': 1.0025322314903438, 'kernel_type': 'k2q', 'bandwidth': 1.9185508179283675, 'diag': False, 'reg': 0.053990338435750435}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.13414886285344563 based on validation mse=283858.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6641643047332764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.69834303855896 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6823837757110596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6727516651153564 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.681720495223999 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.655059814453125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6584246158599854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6695451736450195 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.669339656829834 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6607215404510498 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.70it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.82it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.21it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.56it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.24it/s]

Selected split_temperature=0.09883799050275041 based on validation mse=269982.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619350910186768 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 3.6384992599487305 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6953125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6668233871459961 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6867480278015137 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6501610279083252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6563491821289062 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.668595552444458 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.664229154586792 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6610798835754395 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.14it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.40it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.01it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.33it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.83it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.16it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.13it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=270357.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4274
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.701880693435669 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7221736907958984 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.716916561126709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6929938793182373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6829652786254883 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4356
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6704187393188477 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6731753349304199 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6790473461151123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6860642433166504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.675377607345581 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.02s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.02s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.92it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.08it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.65it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.38it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.47it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.11it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.51it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.03953071244130627 based on validation mse=294759.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.663825273513794 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6924517154693604 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6870801448822021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6699371337890625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6847438812255859 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6659212112426758 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6742508411407471 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6763005256652832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6759071350097656 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6863219738006592 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.50it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.33it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.81it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.06it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.99it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=284036.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6631412506103516 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.692338228225708 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6931560039520264 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6724512577056885 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.6352524757385254 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6759819984436035 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6714529991149902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7055392265319824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.713515043258667 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7081685066223145 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.95s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.92it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.01it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.33it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.74it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.04it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.94it/s]

[I 2026-04-23 02:10:14,691] Trial 42 finished with value: 281181.5125 and parameters: {'exponent': 1.0196587679512887, 'kernel_type': 'k2q', 'bandwidth': 1.452831393155981, 'diag': False, 'reg': 0.0776867617536194}. Best is trial 28 with value: 277413.0875.

Selected split_temperature=0.11514774870862055 based on validation mse=286771.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6915428638458252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.718111515045166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7117617130279541 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7109003067016602 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7135331630706787 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.67423415184021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6519606113433838 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6711723804473877 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.66s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.66s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 44.61it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.94it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.71it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 35.84it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 33.02it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.78it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:00<00:00, 27.84it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 26.80it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.89it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267821.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6658122539520264 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6928186416625977 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6844997406005859 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6733050346374512 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6814603805541992 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6378448009490967 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6424686908721924 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6587905883789062 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6596755981445312 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6888718605041504 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.83it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.63it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.09it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.19it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.36it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.70it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.29it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.49it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.77it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=265898.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4273
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6699652671813965 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.712007999420166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6922645568847656 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6754622459411621 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7099525928497314 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4357
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6889135837554932 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6757283210754395 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6766669750213623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.6360995769500732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6801297664642334 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.60it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.04it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.05365345951302222 based on validation mse=288857.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6615731716156006 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6949248313903809 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.684013843536377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6729083061218262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6866552829742432 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6744933128356934 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6768395900726318 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6803150177001953 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6863927841186523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6752498149871826 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.88it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.24it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.42it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.86it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.41it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.74it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

Selected split_temperature=0.182074901698571 based on validation mse=278532.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6635901927947998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.691486120223999 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.669095516204834 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6816625595092773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6766588687896729 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6795287132263184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6728579998016357 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.680260419845581 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6689908504486084 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6756768226623535 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.74it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.27it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.68it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.84it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.03it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.16it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.28it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.38it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.62it/s]

[I 2026-04-23 02:11:07,231] Trial 43 finished with value: 276644.5 and parameters: {'exponent': 0.9833273417607269, 'kernel_type': 'k2q', 'bandwidth': 6.580514761187084, 'diag': False, 'reg': 0.019176249388265662}. Best is trial 43 with value: 276644.5.

Selected split_temperature=0.09883799050275041 based on validation mse=282113.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6640970706939697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7228784561157227 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7079105377197266 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6745200157165527 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6862802505493164 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6442224979400635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6395552158355713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6607818603515625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.660459041595459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.663604736328125 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.83s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 37.51it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 35.38it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 32.03it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 29.25it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:03<00:04,  3.24it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:03<00:02,  4.34it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:03<00:01,  5.76it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:03<00:00,  7.54it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:04<00:00,  9.66it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.71it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269608.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6653616428375244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6860110759735107 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6924781799316406 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6679677963256836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6849312782287598 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6560976505279541 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6591784954071045 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6618649959564209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6701855659484863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6611330509185791 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.39it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.58it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.31it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.79it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=268657.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6665632724761963 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7157807350158691 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7125866413116455 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6768128871917725 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.685814380645752 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6769416332244873 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6753101348876953 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6781198978424072 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6857035160064697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6775126457214355 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.97s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.66it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.02it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.82it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.80it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.21it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=289864.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6903324127197266 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6940550804138184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6738271713256836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6820006370544434 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6770641803741455 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.67635178565979 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6694130897521973 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6822919845581055 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6838374137878418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6745331287384033 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.40it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.76it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.63it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.94it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.11it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.29it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.37it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.40it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.76it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=281503.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.622173547744751 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901078224182129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6914393901824951 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6723818778991699 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6790428161621094 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6574287414550781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6779975891113281 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6765193939208984 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6885859966278076 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6800520420074463 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.67it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.82it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.23it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.01it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.70it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.64it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

[I 2026-04-23 02:12:03,816] Trial 44 finished with value: 278466.66875 and parameters: {'exponent': 0.9373158443958803, 'kernel_type': 'k2q', 'bandwidth': 6.213606220553803, 'diag': False, 'reg': 0.03349414571362176}. Best is trial 43 with value: 276644.5.

Selected split_temperature=0.11514774870862055 based on validation mse=282700.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6631393432617188 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6982030868530273 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7061460018157959 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6988790035247803 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6817588806152344 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.650550127029419 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6504263877868652 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.86s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.86s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.69it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.76it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.18it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.13it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267588.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6630454063415527 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6942489147186279 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6741909980773926 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6756665706634521 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6783969402313232 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6599674224853516 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6802644729614258 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6960301399230957 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7000749111175537 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6768648624420166 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.13it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.61it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.27it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.50it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.40it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=265263.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4276
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6647491455078125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7088873386383057 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6840221881866455 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.674445390701294 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7080898284912109 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4354
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 3.64119815826416 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6758646965026855 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6598806381225586 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.680464506149292 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6786999702453613 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.69it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.39it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.36it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.87it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.61it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.95it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.94it/s]

Selected split_temperature=0.025000000000000005 based on validation mse=285790.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4289
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669213771820068 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6946380138397217 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.684542179107666 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6729364395141602 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6836855411529541 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4341
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6699450016021729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6739380359649658 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6774284839630127 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6914308071136475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6819977760314941 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.30it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.58it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.88it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.13it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.24it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.38it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.45it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.41it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.78it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=275834.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6636221408843994 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6979269981384277 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858906745910645 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6714944839477539 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.68414306640625 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624393463134766 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6759271621704102 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7087891101837158 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7123908996582031 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7096514701843262 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.01s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.01s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.92it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.56it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.46it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.03it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 25.41it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.08it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 24.82it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 24.64it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 24.54it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 25.63it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.52it/s]

[I 2026-04-23 02:12:55,842] Trial 45 finished with value: 275425.80625 and parameters: {'exponent': 1.060868979576922, 'kernel_type': 'k2q', 'bandwidth': 3.58342638469842, 'diag': False, 'reg': 0.022543351145917725}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.13414886285344563 based on validation mse=282652.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.662447452545166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7158863544464111 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7126796245574951 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7055742740631104 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6916534900665283 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6540350914001465 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6559860706329346 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6623902320861816 seconds

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.51s/it]

Building trees: 100%|██████████| 1/1 [00:10<00:00, 10.52s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 43.99it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.95it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.63it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 35.84it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 32.99it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.79it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:00<00:00, 27.89it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 26.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269626.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6633813381195068 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7160463333129883 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6854715347290039 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6611757278442383 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.689375638961792 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.651630163192749 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.663081169128418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6580748558044434 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6670880317687988 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6623504161834717 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.98it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.37it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.94it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.08it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.28it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.43it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 29.56it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.61it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.85it/s]

Selected split_temperature=0.13414886285344563 based on validation mse=268309.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.688230037689209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7095332145690918 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6852095127105713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6758158206939697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.678922176361084 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6680259704589844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6803877353668213 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6726899147033691 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7128255367279053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7010746002197266 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.98s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.98s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.53it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.63it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.64it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.14it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.66it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.32it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.55it/s]

Selected split_temperature=0.03953071244130627 based on validation mse=288357.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6605863571166992 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901159286499023 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6855912208557129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.670769214630127 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6841211318969727 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6676738262176514 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6730971336364746 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6784079074859619 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6876096725463867 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6757700443267822 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.95it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.58it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.14it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.28it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.25it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.10it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.78it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.33it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.66it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.02it/s]

Selected split_temperature=0.182074901698571 based on validation mse=288491.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4381
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6648447513580322 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6925976276397705 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6868398189544678 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.670525074005127 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6837220191955566 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4249
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6617908477783203 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6766786575317383 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6728622913360596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6781191825866699 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6808910369873047 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.83s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.83s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.05it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.10it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.42it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.80it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.89it/s]

[I 2026-04-23 02:13:51,180] Trial 46 finished with value: 279113.75 and parameters: {'exponent': 0.9710943159736984, 'kernel_type': 'k2q', 'bandwidth': 11.613819420436414, 'diag': False, 'reg': 0.01766020739521834}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.11514774870862055 based on validation mse=280782.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6649904251098633 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6904230117797852 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6823627948760986 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6700940132141113 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6843962669372559 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6551399230957031 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6503281593322754 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.47it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.50it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.18it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.40it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.21it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.182074901698571 based on validation mse=280130.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6650712490081787 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.690683126449585 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6834604740142822 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6710531711578369 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6826674938201904 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6494045257568359 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6552062034606934 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6423418521881104 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6795098781585693 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6563634872436523 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.52it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.94it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.97it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.182074901698571 based on validation mse=286590.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6616659164428711 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.704120397567749 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.7003650665283203 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6823124885559082 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6994423866271973 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6708328723907471 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6888470649719238 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6824984550476074 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6998231410980225 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6901297569274902 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.92s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.64it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.70it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 33.29it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 29.24it/s]

Tuning split temperature:  58%|█████▊    | 21/36 [00:00<00:00, 28.77it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 28.31it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 28.33it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 28.54it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 28.67it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.58it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.53it/s]

Selected split_temperature=0.05365345951302222 based on validation mse=299802.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6799945831298828 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.70853590965271 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.702932596206665 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6844933032989502 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6958482265472412 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6832072734832764 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6869597434997559 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6924567222595215 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6963489055633545 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6734626293182373 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.06s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.06s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.10it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.67it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.17it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.03it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.06it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.70it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.26it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.64it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.99it/s]

Selected split_temperature=0.06250708904468986 based on validation mse=282760.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6627118587493896 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6895434856414795 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6863703727722168 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6704812049865723 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.683795690536499 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6540172100067139 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.677283763885498 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6731259822845459 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6791400909423828 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6873452663421631 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.95it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.21it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.83it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.74it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.41it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.45it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.83it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.50it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

[I 2026-04-23 02:14:42,993] Trial 47 finished with value: 291840.00625 and parameters: {'exponent': 0.8819162222988294, 'kernel_type': 'k2q', 'bandwidth': 3.65066621990893, 'diag': True, 'reg': 0.006837217855357432}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.182074901698571 based on validation mse=309916.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6865711212158203 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6887598037719727 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6879227161407471 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6715145111083984 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6596605777740479 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6544520854949951 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.15s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.15s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.09it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.72it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:02<00:07,  3.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:03<00:04,  4.23it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:03<00:03,  5.68it/s]

Tuning split temperature:  58%|█████▊    | 21/36 [00:03<00:02,  7.46it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:03<00:01,  9.50it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:03<00:00, 11.68it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:03<00:00, 13.88it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:03<00:00, 16.22it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:03<00:00, 18.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:03<00:00,  9.05it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=392953.406250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6660974025726318 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7161014080047607 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6713666915893555 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.657921552658081 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6694045066833496 seconds

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.49s/it]

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.49s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.99it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.45it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.95it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.87it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.28it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.11it/s]

Selected split_temperature=0.6178775819758303 based on validation mse=483804.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6612625122070312 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6919455528259277 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6849753856658936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6707415580749512 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6885261535644531 seconds

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.51s/it]

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.51s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.60it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.18it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.84it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.51it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.30it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.02it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=393606.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6659440994262695 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6905467510223389 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7073564529418945 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7218601703643799 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.91s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.91s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.20it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.74it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.90it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.75it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.67it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.92it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 26.13it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 27.10it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.20it/s]

Selected split_temperature=0.4552388837310289 based on validation mse=459346.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6668801307678223 seconds

Early stopping at iteration 1
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6787960529327393 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6690523624420166 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.11s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.11s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.25it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.70it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.79it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.08it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.66it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.97it/s]

[I 2026-04-23 02:15:18,371] Trial 48 finished with value: 448568.95 and parameters: {'exponent': 0.932952637723254, 'kernel_type': 'k2q', 'bandwidth': 8.342964835513559, 'diag': False, 'reg': 1.029929157887692e-06}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.3354101966249685 based on validation mse=513134.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6641438007354736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6938445568084717 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6820487976074219 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6731557846069336 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.686180830001831 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6626861095428467 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 3.607231616973877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6698181629180908 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6673104763031006 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.10s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.10s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.94it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.65it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.57it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.44it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.10it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=268691.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4316
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6941542625427246 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7190160751342773 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.713432788848877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6903645992279053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6836915016174316 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4315
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6615273952484131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6615293025970459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6653943061828613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6658329963684082 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6876993179321289 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.25it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.78it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.58it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.54it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.55it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.53it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.83it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.71it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.80it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.66it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.02it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=267927.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4274
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6696481704711914 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6873626708984375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.670971155166626 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6828687191009521 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6743834018707275 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4356
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7007415294647217 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6874275207519531 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6846437454223633 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6873316764831543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6727111339569092 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.05it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.36it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.83it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.47it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.44it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.30it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.75it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=288751.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624326705932617 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6942503452301025 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6890792846679688 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6698017120361328 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6941361427307129 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6705701351165771 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6770951747894287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6780049800872803 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6719551086425781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6848204135894775 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.49it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.48it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.41it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.93it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.17it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.65it/s]

Selected split_temperature=0.182074901698571 based on validation mse=282041.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6613833904266357 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6932003498077393 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.70831298828125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7057526111602783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7175703048706055 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6864054203033447 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6735019683837891 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6820058822631836 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.686347484588623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6759521961212158 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.03s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.11it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.02it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.88it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.10it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.27it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.38it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.43it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.68it/s]

[I 2026-04-23 02:16:14,653] Trial 49 finished with value: 277910.2875 and parameters: {'exponent': 1.046994084481927, 'kernel_type': 'k2q', 'bandwidth': 7.212958864196743, 'diag': False, 'reg': 0.021949642749335616}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.08483837917962198 based on validation mse=282138.593750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779839992523193 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5730507373809814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.573832273483276 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577749013900757 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5329811573028564 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.739286661148071 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.554041862487793 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.547532320022583 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.17s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.17s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.83s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.60s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:24,  1.35s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.24s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.20s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=291228.781250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7713401317596436 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.507981300354004 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.569070100784302 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565738201141357 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559851169586182 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7368834018707275 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.541855335235596 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.5298614501953125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.551788330078125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.547428131103516 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.16s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.16s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.01s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.76s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.58s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.45s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.36s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.30s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=290093.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4273
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763463497161865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559314489364624 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.55795955657959 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.507802963256836 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559128999710083 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4357
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.753734111785889 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562976360321045 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.567371368408203 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562784910202026 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.530563831329346 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:06<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.10s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.15s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:10,  2.04s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:07,  1.78s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.59s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.46s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.37s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.03393150300079013 based on validation mse=317395.562500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.764729261398315 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.587153434753418 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56103253364563 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.56526517868042 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.568329572677612 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.751158237457275 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563783884048462 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.563533544540405 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.569077730178833 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.561771631240845 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.31s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:43,  1.67s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:35,  1.42s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:30,  1.26s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:26,  1.17s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:24,  1.12s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:22,  1.09s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:20,  1.09s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.09s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=286755.187500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.7139856815338135 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570112705230713 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.590978384017944 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566908121109009 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.564382314682007 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.748687982559204 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.520882606506348 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.566826343536377 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.559443473815918 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.569896936416626 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.26s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.26s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:33,  1.96s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:27,  1.71s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:23,  1.54s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:19,  1.43s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:17,  1.35s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.29s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.23s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=317726.562500
Using soft routing for tree prediction

[I 2026-04-23 02:24:04,901] Trial 50 finished with value: 300640.0125 and parameters: {'exponent': 1.2570595228423944, 'kernel_type': 'kpq', 'bandwidth': 3.1490586272165495, 'diag': False, 'norm_p': 1.805894843861751, 'reg': 0.0004450778169783424}. Best is trial 45 with value: 275425.80625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7140069007873535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7263448238372803 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7244691848754883 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7077903747558594 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6870639324188232 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6654491424560547 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6640617847442627 seconds

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.01s/it]

Building trees: 100%|██████████| 1/1 [00:07<00:00,  7.01s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.66it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.20it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.45it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.74it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.75it/s]

Selected split_temperature=0.09883799050275041 based on validation mse=269455.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6733405590057373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7000250816345215 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.693535327911377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 3.3736395835876465 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6918303966522217 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6633374691009521 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6639466285705566 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6764116287231445 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.675403356552124 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6934776306152344 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.64s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.64s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.48it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 33.55it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.09it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.30it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.23it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.17it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.12it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.19it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=269314.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6836600303649902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7116987705230713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6945765018463135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6982283592224121 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.70060133934021 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7084040641784668 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6805739402770996 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6773145198822021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7128417491912842 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7072217464447021 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.15s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.15s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.17it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.68it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 28.68it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 27.63it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.63it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.87it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.76it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.82it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.59it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 28.02it/s]

Selected split_temperature=0.03393150300079013 based on validation mse=290751.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6709504127502441 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6824862957000732 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6825194358825684 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6642134189605713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6867005825042725 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6749846935272217 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6941931247711182 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6845977306365967 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6823828220367432 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6763942241668701 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 44.67it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.92it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.17it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.08it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.37it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 29.81it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.84it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.70it/s]

Selected split_temperature=0.182074901698571 based on validation mse=283452.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.661686897277832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6911046504974365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6849701404571533 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.672677755355835 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6856198310852051 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6558678150177002 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6780376434326172 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6702096462249756 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7128787040710449 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7118260860443115 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.53s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.53s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.05it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.54it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.44it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.61it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.98it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.43it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.06it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 26.11it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.47it/s]

[I 2026-04-23 02:24:59,716] Trial 51 finished with value: 279241.00625 and parameters: {'exponent': 1.0555167141373594, 'kernel_type': 'k2q', 'bandwidth': 6.775012467063278, 'diag': False, 'reg': 0.02757942159245964}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.08483837917962198 based on validation mse=283231.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6655187606811523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6710107326507568 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6866166591644287 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6710715293884277 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6816501617431641 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.640833854675293 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6393833160400391 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.88it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.39it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.14it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.27it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.38it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.05it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=270519.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669924259185791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6943111419677734 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6915860176086426 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6680238246917725 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6864049434661865 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6375713348388672 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6388566493988037 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6680915355682373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6617867946624756 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6621737480163574 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.35it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.56it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.33it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.94it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.03it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=267189.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624860763549805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6920361518859863 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6846332550048828 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6770126819610596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7072651386260986 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.683659553527832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6742260456085205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6782116889953613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7112479209899902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7108829021453857 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.97s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.98s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.91it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.65it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.64it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.96it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.18it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.56it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.12it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 25.93it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.42it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=288505.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6686460971832275 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7157623767852783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7136185169219971 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.706890344619751 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7138011455535889 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7073936462402344 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6818428039550781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6827540397644043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6834940910339355 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6701719760894775 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.08s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.08s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.84it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.93it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.14it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.26it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.37it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.35it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.69it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=276547.718750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.660153865814209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926572322845459 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7059204578399658 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7091071605682373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7143113613128662 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6872596740722656 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6723423004150391 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7009272575378418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7148416042327881 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6854071617126465 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.06s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.06s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.97it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.68it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.48it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.25it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.28it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.03it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.48it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.83it/s]

[I 2026-04-23 02:25:51,751] Trial 52 finished with value: 277922.325 and parameters: {'exponent': 1.0377192985986152, 'kernel_type': 'k2q', 'bandwidth': 4.2765228457674365, 'diag': False, 'reg': 0.010554780326831766}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.13414886285344563 based on validation mse=286849.218750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6615958213806152 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6944727897644043 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.679481029510498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6728458404541016 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6818058490753174 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6540162563323975 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.65537428855896 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.93it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.91it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.57it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.53it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.21it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.46it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.94it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.182074901698571 based on validation mse=276233.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.658515453338623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 3.675410270690918 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6841254234313965 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6815268993377686 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6795806884765625 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.662736177444458 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6539511680603027 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6690998077392578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6595616340637207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6650664806365967 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.78s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.40it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.77it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.63it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.14it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.04it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.31it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.77it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.89it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.07it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=281669.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6623890399932861 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6965343952178955 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6831066608428955 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6749110221862793 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.684213399887085 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6794817447662354 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6727383136749268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.675609827041626 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6843948364257812 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.675396203994751 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.90it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.53it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.36it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.36it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.50it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.23it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.97it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=299538.093750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6671066284179688 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.689979076385498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6842124462127686 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6688907146453857 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6842381954193115 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6750380992889404 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6759095191955566 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6811633110046387 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6822059154510498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6796483993530273 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.40it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.38it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.75it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.73it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.54it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=279800.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6614735126495361 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7217791080474854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6792099475860596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6850020885467529 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.6379127502441406 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6679229736328125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6743340492248535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6698908805847168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6922523975372314 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6747562885284424 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.00it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.00it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.19it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.82it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.44it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.03it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.38it/s]

[I 2026-04-23 02:26:46,298] Trial 53 finished with value: 287758.5625 and parameters: {'exponent': 0.9937219372123037, 'kernel_type': 'k2q', 'bandwidth': 5.7980835776492246, 'diag': False, 'reg': 0.002490395437394937}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.182074901698571 based on validation mse=301550.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6602871417999268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926541328430176 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6828317642211914 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6733651161193848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6802644729614258 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6593194007873535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6556379795074463 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.79s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.79s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.02it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.58it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.48it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.26it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.08it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.13it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=270941.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6608524322509766 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6991465091705322 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6805586814880371 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6719965934753418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6827235221862793 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6553606986999512 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.656184196472168 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6687040328979492 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6650385856628418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6573445796966553 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.80s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 46.85it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 44.70it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.81it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 35.97it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 32.53it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.54it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:00<00:00, 27.76it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 26.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=270168.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4265
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6680283546447754 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6949851512908936 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858677864074707 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6731421947479248 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6819264888763428 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4365
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.657139778137207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.673774003982544 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6747279167175293 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6844577789306641 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.681821346282959 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.72it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.73it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.02it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.72it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.40it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.99it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.03953071244130627 based on validation mse=291176.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6662867069244385 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6930999755859375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.685014009475708 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6714920997619629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.683119535446167 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.671544075012207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6736774444580078 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6796419620513916 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6851010322570801 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6771173477172852 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.05it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.21it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.88it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.92it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.07it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.22it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.37it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.48it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.70it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=291778.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616015434265137 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6930580139160156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.682776927947998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.702906608581543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.703406572341919 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6598844528198242 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6765296459197998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6718921661376953 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6830694675445557 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6778478622436523 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.00it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.20it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.48it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.21it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.97it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

[I 2026-04-23 02:27:37,794] Trial 54 finished with value: 281012.25 and parameters: {'exponent': 0.9751624741413789, 'kernel_type': 'k2q', 'bandwidth': 12.765937670651539, 'diag': False, 'reg': 0.01892284719087142}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.09883799050275041 based on validation mse=280996.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6617605686187744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6927075386047363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6850321292877197 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6762619018554688 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6848032474517822 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6614837646484375 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6561353206634521 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.73it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.06it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.97it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269226.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6605863571166992 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6946024894714355 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.6429364681243896 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6748321056365967 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.685474157333374 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6565685272216797 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6529092788696289 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6679694652557373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6650166511535645 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6578166484832764 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.29it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.67it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.92it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.69it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.17it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=263906.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4278
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6617670059204102 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6820118427276611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6957435607910156 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.670478343963623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6807429790496826 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4352
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6519629955291748 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6746950149536133 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.671184778213501 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6793985366821289 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.685096263885498 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.91it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.46it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.60it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.94it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.21it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.05it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.81it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.76it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.01it/s]

Selected split_temperature=0.025000000000000005 based on validation mse=284716.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4293
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6620099544525146 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6967501640319824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6858928203582764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.668698787689209 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6874558925628662 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4337
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6604578495025635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6743111610412598 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6705811023712158 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6899588108062744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6757118701934814 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.54it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.13it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.79it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.45it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.19it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.99it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.182074901698571 based on validation mse=279676.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6623120307922363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6804461479187012 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6925997734069824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6728641986846924 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6778078079223633 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6562871932983398 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6754987239837646 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.674508810043335 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6845841407775879 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6804957389831543 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.82s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.83s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.03it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.04it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.34it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.89it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.27it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.75it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.37it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.51it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

[I 2026-04-23 02:28:32,202] Trial 55 finished with value: 276082.0125 and parameters: {'exponent': 1.1119676226867898, 'kernel_type': 'k2q', 'bandwidth': 8.458502683121411, 'diag': False, 'reg': 0.005954635511636996}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.11514774870862055 based on validation mse=282883.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6638195514678955 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.699028491973877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6859121322631836 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6680235862731934 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.80s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.80s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.39it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.72it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.75it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.05it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.41it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.51it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.65it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.182074901698571 based on validation mse=307709.625000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4312
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6869709491729736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7101469039916992 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4319
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.656327486038208 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.60it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.84it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.88it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.21it/s]

Selected split_temperature=0.4552388837310289 based on validation mse=309928.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4269
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6624305248260498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6877954006195068 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.683722972869873 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4361
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6808469295501709 seconds

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.81s/it]

Building trees: 100%|██████████| 1/1 [00:04<00:00,  4.82s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.15it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.64it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.97it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.93it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=324683.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6677885055541992 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6911838054656982 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6835973262786865 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6807115077972412 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.674048662185669 seconds

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.50s/it]

Building trees: 100%|██████████| 1/1 [00:05<00:00,  5.50s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.29it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.39it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.11it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.53it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.98it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.83it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.88it/s]

Selected split_temperature=0.182074901698571 based on validation mse=315521.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618266105651855 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7222752571105957 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.631366729736328 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6729321479797363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6733944416046143 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.48s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.48s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.72it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.35it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.78it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.83it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.11it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.63it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

[I 2026-04-23 02:29:06,207] Trial 56 finished with value: 318801.25 and parameters: {'exponent': 1.1161010994840233, 'kernel_type': 'k2q', 'bandwidth': 18.449085852813596, 'diag': False, 'reg': 3.887259864723194e-06}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.4552388837310289 based on validation mse=336162.875000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6599023342132568 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6779510974884033 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6944444179534912 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6711122989654541 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6854379177093506 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.634312629699707 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6428303718566895 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 43.80it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.66it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.76it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 35.84it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 33.71it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:00<00:00, 28.14it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 27.13it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.16it/s]

Selected split_temperature=0.182074901698571 based on validation mse=278021.468750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6616964340209961 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6928558349609375 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.679729700088501 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6727986335754395 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.684380054473877 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6561193466186523 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6573929786682129 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6613860130310059 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6651842594146729 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6780862808227539 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.99it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 36.86it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 34.80it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 31.69it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 29.07it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 28.80it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.06it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 29.26it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 29.42it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 29.54it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.36it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=284343.593750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6615333557128906 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6892952919006348 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6847617626190186 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6759026050567627 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6804673671722412 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6602110862731934 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6764554977416992 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6659824848175049 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6932415962219238 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6748507022857666 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.15it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.58it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.64it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.93it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.21it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.93it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.01it/s]

Selected split_temperature=0.03953071244130627 based on validation mse=297265.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.7005910873413086 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7216370105743408 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6936876773834229 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6754751205444336 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6814188957214355 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6741039752960205 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6641936302185059 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.683861494064331 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6856026649475098 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6669557094573975 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.53it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.48it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.34it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.80it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.35it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.15it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.67it/s]

Selected split_temperature=0.182074901698571 based on validation mse=280356.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6625363826751709 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.6924829483032227 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.6801087856292725 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.674030065536499 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6889121532440186 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 0: 0.6766006946563721 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 1: 0.7028250694274902 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 2: 0.701791524887085 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 3: 0.6787064075469971 seconds

Using cheap batch size
Optimal M batch size: 2613
Time taken for round 4: 0.6817233562469482 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.01it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.03it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.84it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.27it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.12it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.95it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.85it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.20it/s]

[I 2026-04-23 02:29:57,760] Trial 57 finished with value: 288311.50625 and parameters: {'exponent': 0.9187522591919417, 'kernel_type': 'k2q', 'bandwidth': 9.288483844241064, 'diag': True, 'reg': 0.004393048198719494}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.1562854472336314 based on validation mse=301570.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6664817333221436 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6913111209869385 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6840643882751465 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6696124076843262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6910970211029053 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6568069458007812 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6578159332275391 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.82s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.82s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.57it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.77it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.30it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.04it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.00it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.17it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269564.781250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.662794828414917 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6911647319793701 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6857771873474121 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6777448654174805 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.680819034576416 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6430385112762451 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.656120777130127 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6632838249206543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.66754150390625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6641542911529541 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.74s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.74s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.21it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.56it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.38it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.56it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.75it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.13it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.71it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=264679.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6628618240356445 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7214524745941162 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7033507823944092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6743969917297363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6861610412597656 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6761593818664551 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6739912033081055 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6837158203125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6870839595794678 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6786670684814453 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.62it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.69it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.67it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.61it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.98it/s]

Selected split_temperature=0.025000000000000005 based on validation mse=285131.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6600992679595947 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6929962635040283 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6815578937530518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6772794723510742 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6825766563415527 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6746783256530762 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.674626350402832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6816582679748535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6857008934020996 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6745524406433105 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.19it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.64it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.44it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.49it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.60it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.87it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.47it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.93it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.87it/s]

Selected split_temperature=0.182074901698571 based on validation mse=275514.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4390
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618354320526123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7186994552612305 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7059614658355713 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6740009784698486 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6853187084197998 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4240
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6727111339569092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6754891872406006 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.641188621520996 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6850626468658447 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6748583316802979 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.62it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.95it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.22it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.47it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.60it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.37it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.72it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

[I 2026-04-23 02:30:52,337] Trial 58 finished with value: 275993.4875 and parameters: {'exponent': 1.1709031786597064, 'kernel_type': 'k2q', 'bandwidth': 4.621407455558512, 'diag': False, 'reg': 0.00681212364025387}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.13414886285344563 based on validation mse=285077.031250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6663699150085449 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6952097415924072 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6836955547332764 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6713712215423584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7122788429260254 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6703653335571289 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6783623695373535 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.89s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.89s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 38.78it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 35.59it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 32.12it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 29.75it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:00<00:00, 29.82it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.84it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 29.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.81it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.98it/s]

Selected split_temperature=0.182074901698571 based on validation mse=284649.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6627569198608398 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6776609420776367 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6931123733520508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6696004867553711 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6871743202209473 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4331
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6357312202453613 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6403071880340576 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6564805507659912 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.644033670425415 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6634113788604736 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.73s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.73s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.08it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.38it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.01it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.61it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.32it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.00it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.28790202327301256 based on validation mse=287994.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4274
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619422435760498 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6938281059265137 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6855287551879883 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6695601940155029 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6822776794433594 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4356
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6697471141815186 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6718347072601318 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7021138668060303 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7164716720581055 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.710113525390625 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  9.00s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  9.00s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.24it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.67it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.45it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 26.82it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 26.07it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 25.45it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 25.09it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 25.71it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 27.36it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=308535.000000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6922440528869629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6652548313140869 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6933810710906982 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6716663837432861 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6803359985351562 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6660826206207275 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6755335330963135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6792337894439697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6830487251281738 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.679818868637085 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.99it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.48it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.84it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.16it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.70it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.62it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=280861.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6623179912567139 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6910319328308105 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6749067306518555 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.743159294128418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7410945892333984 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.7185459136962891 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.670649528503418 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6716756820678711 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6922705173492432 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6695706844329834 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.11s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.11s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.33it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.45it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.77it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.81it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.03it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.57it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.04it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

[I 2026-04-23 02:31:44,353] Trial 59 finished with value: 295485.125 and parameters: {'exponent': 1.1965439255734482, 'kernel_type': 'k2q', 'bandwidth': 4.825211086790693, 'diag': False, 'reg': 0.0005676366677929843}. Best is trial 45 with value: 275425.80625.

Selected split_temperature=0.182074901698571 based on validation mse=315384.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6636242866516113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6835603713989258 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6944754123687744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6718249320983887 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6817977428436279 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6476359367370605 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6551182270050049 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.81it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.44it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.56it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.89it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.00it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.30it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.84it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.50it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.07it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267868.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6649775505065918 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6909761428833008 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6908900737762451 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.669593334197998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.3929443359375 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6306009292602539 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6614744663238525 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.660313606262207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6458439826965332 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6714694499969482 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.48s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.48s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.14it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 35.42it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.12it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.72it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.71it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.89it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.49it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.12it/s]

Selected split_temperature=0.0 based on validation mse=263947.656250
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6926364898681641 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6916623115539551 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6889357566833496 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6745121479034424 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6830120086669922 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6628293991088867 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6771013736724854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6733968257904053 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6903026103973389 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6761260032653809 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.54it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.06it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.18it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.91it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.01it/s]

Selected split_temperature=0.03953071244130627 based on validation mse=284557.218750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4291
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6654853820800781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6883406639099121 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.685880184173584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6694817543029785 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.683802604675293 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4339
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6567850112915039 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6581213474273682 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6710648536682129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6807160377502441 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6786074638366699 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.21it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.59it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.91it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.83it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.69it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.96it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=274989.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4390
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669163703918457 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6909465789794922 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6877803802490234 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6710758209228516 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6849572658538818 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4240
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6729662418365479 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6717407703399658 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.643601417541504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6820611953735352 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6740567684173584 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.91it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.39it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.30it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.81it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.39it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.63it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.86it/s]

[I 2026-04-23 02:32:38,522] Trial 60 finished with value: 275027.525 and parameters: {'exponent': 1.2483428086673989, 'kernel_type': 'k2q', 'bandwidth': 4.032778385316483, 'diag': False, 'reg': 0.006790324398333243}. Best is trial 60 with value: 275027.525.

Selected split_temperature=0.11514774870862055 based on validation mse=283774.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.661015510559082 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.69632887840271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6861469745635986 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6701819896697998 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7118072509765625 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6712253093719482 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.656334400177002 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.87s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.22it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.57it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.63it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.76it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.88it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.23it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.77it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.51it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 32.05it/s]

Selected split_temperature=0.182074901698571 based on validation mse=264381.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6642799377441406 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6989092826843262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6869263648986816 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6704790592193604 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6877572536468506 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6564357280731201 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6598784923553467 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.681398868560791 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6645948886871338 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6613967418670654 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.84s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.51it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 36.67it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 34.90it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.02it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.92it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.05it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=262330.437500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4276
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6667490005493164 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6927886009216309 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6839568614959717 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6719305515289307 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6882617473602295 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4354
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.674370288848877 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6738564968109131 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.680689811706543 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6851842403411865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6588766574859619 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.10it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.38it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.86it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.44it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.25it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.94it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.24it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 27.73it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.69it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.79it/s]

Selected split_temperature=0.0 based on validation mse=283886.562500
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4299
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6672492027282715 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7174999713897705 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6963744163513184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6587791442871094 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6955771446228027 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6793272495269775 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6736083030700684 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6801109313964844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6858229637145996 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6711099147796631 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.46it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.66it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.62it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.54it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.182074901698571 based on validation mse=275202.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6635079383850098 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6944010257720947 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6872367858886719 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6718418598175049 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7093391418457031 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6834771633148193 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.67462158203125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6719343662261963 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.67818284034729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6866745948791504 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.27it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.47it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.83it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.44it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.98it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.86it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.97it/s]

[I 2026-04-23 02:33:30,194] Trial 61 finished with value: 273737.25625 and parameters: {'exponent': 1.3993613623005245, 'kernel_type': 'k2q', 'bandwidth': 3.8304382130860923, 'diag': False, 'reg': 0.006581484384013103}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.1562854472336314 based on validation mse=282885.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.669403076171875 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6895287036895752 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6873836517333984 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6729912757873535 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6810622215270996 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6543798446655273 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6530923843383789 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.93it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.73it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.74it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.07it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.72it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.45it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.09it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.15it/s]

Selected split_temperature=0.182074901698571 based on validation mse=269496.062500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6677217483520508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6907234191894531 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6881427764892578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6915543079376221 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6800589561462402 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6562387943267822 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6790633201599121 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6961450576782227 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6618504524230957 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6676969528198242 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.16it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.52it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.78it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.23it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.77it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.76it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.10it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=266731.718750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6877169609069824 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7118055820465088 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6818764209747314 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6918723583221436 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6844949722290039 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6648850440979004 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6665487289428711 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6730382442474365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6830756664276123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6791043281555176 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.44it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.96it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.80it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.70it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.15it/s]

Selected split_temperature=0.182074901698571 based on validation mse=289679.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4292
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616055965423584 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6921961307525635 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6891312599182129 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.668262243270874 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.687042236328125 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4338
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6819052696228027 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6724631786346436 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6835825443267822 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6866788864135742 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.664639949798584 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.74it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.09it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.24it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.60it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.55it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.22it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.50it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.87it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=276360.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6636576652526855 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6932141780853271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6824893951416016 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6723806858062744 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6806972026824951 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6750152111053467 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6727402210235596 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.6346397399902344 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6874024868011475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6717514991760254 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.14it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.20it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.45it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.87it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.90it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.17it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.67it/s]

[I 2026-04-23 02:34:24,793] Trial 62 finished with value: 277838.325 and parameters: {'exponent': 1.2488464915854416, 'kernel_type': 'k2q', 'bandwidth': 3.1944214043321693, 'diag': False, 'reg': 0.006251876027679087}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.13414886285344563 based on validation mse=286923.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6966302394866943 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7252097129821777 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7098839282989502 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6750810146331787 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6903955936431885 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6388792991638184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6491873264312744 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.97s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.98s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 43.98it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.46it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.32it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.02it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.68it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 29.86it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 27.88it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.88it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.73it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=274394.562500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4309
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6632332801818848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7145984172821045 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7032458782196045 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6748542785644531 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.666471004486084 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4322
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6513278484344482 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6576666831970215 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6628189086914062 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6682054996490479 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6554429531097412 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.18it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.62it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.73it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.59it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.44it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.59it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 28.20it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.64it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.99it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.34it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=271586.281250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4260
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.688096284866333 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6847934722900391 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6849260330200195 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.674917459487915 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6778857707977295 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4370
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6723766326904297 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6697847843170166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6865122318267822 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6839547157287598 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6729657649993896 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.95it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 43.20it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 39.14it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 36.05it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.76it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 30.27it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.06it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 26.96it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.78it/s]

Selected split_temperature=0.05365345951302222 based on validation mse=294704.343750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6879096031188965 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7088265419006348 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6605195999145508 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6854064464569092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6767737865447998 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6863644123077393 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6698720455169678 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7062397003173828 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7142899036407471 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6973066329956055 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.19it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.39it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.41it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.85it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.94it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.08it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.20it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.25it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.30it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.66it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=277585.968750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6641664505004883 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7165119647979736 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7096474170684814 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6503486633300781 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.698965311050415 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6581902503967285 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6780469417572021 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6742997169494629 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.675602912902832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6895110607147217 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.93s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.87it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.97it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.68it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.62it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.34it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.35it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.71it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.39it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.85it/s]

[I 2026-04-23 02:35:16,571] Trial 63 finished with value: 282644.09375 and parameters: {'exponent': 1.3911544938359275, 'kernel_type': 'k2q', 'bandwidth': 4.056551918654813, 'diag': False, 'reg': 0.0015726328394730128}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.13414886285344563 based on validation mse=294949.375000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616501808166504 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6976447105407715 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6818757057189941 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6698827743530273 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6820504665374756 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6558606624603271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6569631099700928 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.78it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.80it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.13it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.68it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.38it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.21it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 30.07it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.22it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269656.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6676256656646729 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6918714046478271 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6821248531341553 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6735928058624268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.644641399383545 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4331
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618952751159668 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6564114093780518 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6680316925048828 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6672239303588867 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6560142040252686 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.77s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.78s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.43it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.53it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.97it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.14it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.07it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.96it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.95it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.08it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=267951.500000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4276
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6602237224578857 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.696160078048706 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6844277381896973 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6698033809661865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6919164657592773 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4354
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6612815856933594 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6772146224975586 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6742866039276123 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6866412162780762 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6769227981567383 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.89s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.76it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.60it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.88it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.46it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.20it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.03it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=290018.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6710822582244873 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6915266513824463 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6709699630737305 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6806318759918213 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6815066337585449 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6861817836761475 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6726834774017334 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7043819427490234 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.710637092590332 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6752274036407471 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.28it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.62it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.15it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.87it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:01<00:00, 29.84it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.21it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.00it/s]

Selected split_temperature=0.182074901698571 based on validation mse=276921.687500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4378
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.664177656173706 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6990408897399902 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6840114593505859 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.674036979675293 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6849963665008545 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4252
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6719820499420166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6893634796142578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 3.622241735458374 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6863138675689697 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.674884557723999 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.00it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.29it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.51it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.72it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.88it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.08it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.24it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.20it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.29it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.63it/s]

[I 2026-04-23 02:36:11,143] Trial 64 finished with value: 278228.81875 and parameters: {'exponent': 1.1549607099782007, 'kernel_type': 'k2q', 'bandwidth': 2.769015916017895, 'diag': False, 'reg': 0.010453243731660622}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.13414886285344563 based on validation mse=286595.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4311
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6669979095458984 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.690021276473999 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.687838077545166 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6709628105163574 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6833102703094482 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4320
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6605169773101807 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6546227931976318 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.82s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.82s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.84it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.74it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.34it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.55it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.99it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.65it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.42it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.15it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=274914.656250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619188785552979 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7199742794036865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7156546115875244 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7133162021636963 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6830160617828369 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.659543514251709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6562004089355469 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6512467861175537 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.676006555557251 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6617019176483154 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.90s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.26it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.63it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.61it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.98it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.28it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.16it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.01it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.86it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.09it/s]

Selected split_temperature=0.182074901698571 based on validation mse=272948.531250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4266
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6606879234313965 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7004246711730957 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.684481143951416 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6729905605316162 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6861555576324463 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4364
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6767914295196533 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6787688732147217 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6739723682403564 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.693946361541748 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6757404804229736 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.92s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.13it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.48it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.46it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.95it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 28.94it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 29.12it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:00<00:00, 29.19it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 29.35it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.35it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.70it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=293035.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4290
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6638550758361816 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6930840015411377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6847717761993408 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6744215488433838 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6772041320800781 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4340
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6674785614013672 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.675933837890625 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6779468059539795 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6896514892578125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6750128269195557 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.41it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.55it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.42it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.78it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 29.82it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 29.80it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 29.77it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 29.73it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 29.65it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.87it/s]

Selected split_temperature=0.182074901698571 based on validation mse=277949.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6619186401367188 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6926462650299072 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6863358020782471 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6723432540893555 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6824183464050293 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6541306972503662 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6550502777099609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6816153526306152 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6843743324279785 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6738824844360352 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.86s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.77it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.71it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.13it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.71it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.48it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.18it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.99it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.82it/s]

[I 2026-04-23 02:37:02,797] Trial 65 finished with value: 282749.63125 and parameters: {'exponent': 1.2100621537546137, 'kernel_type': 'k2q', 'bandwidth': 4.665787200100453, 'diag': False, 'reg': 0.002616550225788603}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.21212000487151167 based on validation mse=294899.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4315
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6616899967193604 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7160956859588623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6876029968261719 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6736376285552979 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7124407291412354 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4316
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6714732646942139 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6571316719055176 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.89s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.89s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.02it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.72it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.85it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.71it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.47it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.24it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.53it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 28.17it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.66it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.92it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.33it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=269021.937500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6633517742156982 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6897220611572266 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.687131404876709 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6702067852020264 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 3.6431734561920166 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.659949541091919 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6566622257232666 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6650967597961426 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6682591438293457 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6574795246124268 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.76s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.58it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.61it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 33.03it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 32.06it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.32it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.12it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.14it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=265200.906250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4269
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6609890460968018 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7017738819122314 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6866466999053955 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6708219051361084 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.685124397277832 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4361
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6561925411224365 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.672569990158081 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6731166839599609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6794066429138184 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6848404407501221 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 41.79it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.41it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.40it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.39it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.95it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.87it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.93it/s]

Selected split_temperature=0.182074901698571 based on validation mse=286865.312500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6899216175079346 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.693101167678833 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6884171962738037 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6767063140869141 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6783781051635742 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.670799732208252 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.673088550567627 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7071306705474854 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7218420505523682 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7098033428192139 seconds

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.04s/it]

Building trees: 100%|██████████| 1/1 [00:09<00:00,  9.04s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.40it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.33it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.16it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.76it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.34it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.13it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.90it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

Selected split_temperature=0.1562854472336314 based on validation mse=277673.156250
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6618733406066895 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6901149749755859 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6869251728057861 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6710455417633057 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6816480159759521 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6701574325561523 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 3.616635799407959 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6841716766357422 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6826739311218262 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6729254722595215 seconds

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Building trees: 100%|██████████| 1/1 [00:11<00:00, 11.84s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.14it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.64it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.36it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.29it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.19it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 26.97it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.10it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:01<00:00, 27.82it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.37it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.75it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.06it/s]

[I 2026-04-23 02:37:57,620] Trial 66 finished with value: 276926.9125 and parameters: {'exponent': 1.2733575262735726, 'kernel_type': 'k2q', 'bandwidth': 3.7195045157191995, 'diag': False, 'reg': 0.005404381500627757}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.13414886285344563 based on validation mse=285873.218750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6631114482879639 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6949498653411865 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6757500171661377 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6732749938964844 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6813418865203857 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4303
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6592717170715332 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6500630378723145 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.38it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.64it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.06it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.06it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.02it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.93it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.15it/s]

Selected split_temperature=0.182074901698571 based on validation mse=282772.843750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6630449295043945 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6945810317993164 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6852123737335205 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6690769195556641 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.690201997756958 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6657388210296631 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6549410820007324 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6650896072387695 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6664159297943115 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6551311016082764 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.81s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 39.28it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.88it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.58it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.52it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 32.25it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.58it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.76it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.06it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=283504.125000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4273
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6604022979736328 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7174501419067383 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7023115158081055 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6773731708526611 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6842718124389648 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4357
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.673689603805542 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6732940673828125 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6816351413726807 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6831696033477783 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6732587814331055 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.23it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.68it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 30.52it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 27.12it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 25.43it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 25.17it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 24.89it/s]

Tuning split temperature:  78%|███████▊  | 28/36 [00:01<00:00, 24.66it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:01<00:00, 24.51it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 25.55it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 26.53it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=302059.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6491870880126953 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6949372291564941 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6853327751159668 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6766321659088135 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6868832111358643 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6658024787902832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6619079113006592 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6792340278625488 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6851894855499268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6751737594604492 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.85s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.17it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.49it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 37.15it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 35.07it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 33.24it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 31.99it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 29.83it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.80it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.95it/s]

Selected split_temperature=0.24712300293414508 based on validation mse=279171.187500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6611747741699219 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7259609699249268 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7119235992431641 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7063195705413818 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7129201889038086 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 5.015691757202148 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6884198188781738 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6767520904541016 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6859455108642578 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6743323802947998 seconds

Building trees: 100%|██████████| 1/1 [00:13<00:00, 13.37s/it]

Building trees: 100%|██████████| 1/1 [00:13<00:00, 13.37s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.08it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 37.95it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.33it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 32.56it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 31.71it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.90it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.51it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 28.77it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.79it/s]

[I 2026-04-23 02:38:50,882] Trial 67 finished with value: 290834.7625 and parameters: {'exponent': 1.2806624976560657, 'kernel_type': 'k2q', 'bandwidth': 4.944303253279444, 'diag': False, 'reg': 0.0008433254607332487}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.182074901698571 based on validation mse=306665.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4318
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6663737297058105 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.7150921821594238 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6995434761047363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6546010971069336 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6985023021697998 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4313
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6637768745422363 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6580572128295898 seconds

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.85s/it]

Building trees: 100%|██████████| 1/1 [00:06<00:00,  6.85s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 40.60it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:00<00:00, 37.96it/s]

Tuning split temperature:  53%|█████▎    | 19/36 [00:00<00:00, 35.44it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 33.46it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:00<00:00, 31.58it/s]

Tuning split temperature:  86%|████████▌ | 31/36 [00:00<00:00, 28.89it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 27.59it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.05it/s]

Selected split_temperature=0.11514774870862055 based on validation mse=267826.718750
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6671831607818604 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6956086158752441 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.7104372978210449 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.7047452926635742 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.7042949199676514 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6330020427703857 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6622607707977295 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6602311134338379 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6684248447418213 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6586122512817383 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:00<00:00, 49.62it/s]

Tuning split temperature:  31%|███       | 11/36 [00:00<00:00, 44.61it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 39.56it/s]

Tuning split temperature:  58%|█████▊    | 21/36 [00:00<00:00, 35.13it/s]

Tuning split temperature:  69%|██████▉   | 25/36 [00:00<00:00, 30.91it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 28.61it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 27.39it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 27.19it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 31.18it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=263621.750000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4266
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6652102470397949 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6941955089569092 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.685126781463623 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6770272254943848 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6862998008728027 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4364
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6760153770446777 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6725010871887207 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6824052333831787 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6878669261932373 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6719448566436768 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.91s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 35.90it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.68it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:03<00:08,  2.71it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:03<00:05,  3.86it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:03<00:03,  5.30it/s]

Tuning split temperature:  58%|█████▊    | 21/36 [00:03<00:02,  7.03it/s]

Tuning split temperature:  67%|██████▋   | 24/36 [00:03<00:01,  9.02it/s]

Tuning split temperature:  75%|███████▌  | 27/36 [00:03<00:00, 11.46it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:03<00:00, 14.08it/s]

Tuning split temperature:  92%|█████████▏| 33/36 [00:04<00:00, 16.75it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00, 19.21it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:04<00:00,  8.58it/s]

Selected split_temperature=0.182074901698571 based on validation mse=286643.812500
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.663682222366333 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6952128410339355 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6817257404327393 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6706671714782715 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.685356855392456 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6890773773193359 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6865367889404297 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6861770153045654 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6840808391571045 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6738886833190918 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.94s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  11%|█         | 4/36 [00:00<00:00, 36.24it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:00<00:00, 33.70it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:00<00:00, 32.43it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:00<00:00, 30.36it/s]

Tuning split temperature:  56%|█████▌    | 20/36 [00:00<00:00, 28.31it/s]

Tuning split temperature:  64%|██████▍   | 23/36 [00:00<00:00, 27.05it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 27.36it/s]

Tuning split temperature:  81%|████████  | 29/36 [00:00<00:00, 27.95it/s]

Tuning split temperature:  89%|████████▉ | 32/36 [00:01<00:00, 28.44it/s]

Tuning split temperature:  97%|█████████▋| 35/36 [00:01<00:00, 28.74it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 29.14it/s]

Selected split_temperature=0.21212000487151167 based on validation mse=275949.250000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6625423431396484 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6907505989074707 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6802258491516113 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6793522834777832 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6780891418457031 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 0: 0.6554441452026367 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 1: 0.6773891448974609 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 2: 0.6732800006866455 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 3: 0.6831884384155273 seconds

Using cheap batch size
Optimal M batch size: 2613
Using SVD
Time taken for round 4: 0.6800546646118164 seconds

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.87s/it]

Building trees: 100%|██████████| 1/1 [00:08<00:00,  8.88s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:00<00:00, 42.03it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:00<00:00, 38.24it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:00<00:00, 34.51it/s]

Tuning split temperature:  50%|█████     | 18/36 [00:00<00:00, 31.24it/s]

Tuning split temperature:  61%|██████    | 22/36 [00:00<00:00, 30.80it/s]

Tuning split temperature:  72%|███████▏  | 26/36 [00:00<00:00, 30.43it/s]

Tuning split temperature:  83%|████████▎ | 30/36 [00:00<00:00, 30.17it/s]

Tuning split temperature:  94%|█████████▍| 34/36 [00:01<00:00, 29.79it/s]

Tuning split temperature: 100%|██████████| 36/36 [00:01<00:00, 30.91it/s]

[I 2026-04-23 02:39:42,685] Trial 68 finished with value: 276034.21875 and parameters: {'exponent': 1.3964584991333098, 'kernel_type': 'k2q', 'bandwidth': 3.7604604632111753, 'diag': False, 'reg': 0.0036049486757344486}. Best is trial 61 with value: 273737.25625.

Selected split_temperature=0.13414886285344563 based on validation mse=286129.625000
Using soft routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779129505157471 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578413248062134 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.53412127494812 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.57486367225647 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.571639537811279 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7370445728302 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.07s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.08s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.81s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:33,  1.58s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:28,  1.43s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:25,  1.33s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:22,  1.27s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.23s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.21s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.20s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=269160.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.714225769042969 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562059640884399 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5609962940216064 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563198804855347 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5627806186676025 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.736058712005615 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.554638385772705 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.499366760253906 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.548992156982422 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.541608572006226 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.11s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.11s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.01s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.75s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.57s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.45s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.36s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.30s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=259992.171875
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4273
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76898717880249 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.55815577507019 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.518356800079346 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563537120819092 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559310436248779 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4357
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.754103422164917 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57453727722168 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.563962459564209 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564748287200928 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.514212131500244 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.24s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.24s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:06<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.28it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.04s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.59s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.46s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.37s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.26s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.029125376821935778 based on validation mse=291428.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76751446723938 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.558490037918091 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5575971603393555 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.573534965515137 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.56015944480896 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.758333683013916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579058647155762 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.566455364227295 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576173305511475 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.564178705215454 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.31s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:44,  1.66s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:36,  1.40s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:30,  1.23s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:27,  1.13s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:24,  1.08s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:23,  1.05s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:21,  1.05s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:21,  1.05s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:20,  1.06s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.08s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=280449.968750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.810662508010864 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.68533992767334 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.657775402069092 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5686469078063965 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.56830358505249 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752725839614868 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.192793607711792 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.556410074234009 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5552661418914795 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.55822229385376 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.19s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.19s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:34,  1.93s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:28,  1.69s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.52s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.41s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.33s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.28s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.24s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=281113.343750
Using soft routing for tree prediction

[I 2026-04-23 02:47:24,180] Trial 69 finished with value: 276428.825 and parameters: {'exponent': 1.3949313568403086, 'kernel_type': 'kpq', 'bandwidth': 7.414057357053286, 'diag': False, 'norm_p': 1.6974189103756352, 'reg': 0.0016724346565000433}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.765764236450195 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.510620832443237 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564716100692749 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560499906539917 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.566913843154907 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.730780601501465 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.96s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.96s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:40,  1.77s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:33,  1.54s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:29,  1.39s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:26,  1.30s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:23,  1.24s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.21s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.19s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.18s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=267463.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4310
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.716039180755615 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5576112270355225 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5670998096466064 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.556493759155273 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.561257600784302 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4321
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.73258113861084 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.543359994888306 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.509767293930054 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.545849084854126 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.550298452377319 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.11s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.11s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:29,  1.99s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.74s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:20,  1.57s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:17,  1.44s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.36s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=258612.093750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.762250185012817 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.565185308456421 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.524965047836304 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.558816432952881 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5541603565216064 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752249479293823 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570135831832886 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.569670915603638 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.56532883644104 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.528113126754761 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.24s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.24s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:06<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:14,  2.04s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:10,  1.78s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:07,  1.60s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.47s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.37s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.31s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.26s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=288242.468750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763659477233887 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.560468673706055 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564720392227173 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564770936965942 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.525301456451416 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752448558807373 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.565513372421265 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.572216272354126 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565480947494507 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.571670055389404 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.29s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.29s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:48,  1.66s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:38,  1.37s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:31,  1.18s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:27,  1.07s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:25,  1.00s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:23,  1.03it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:22,  1.04it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.03it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.01it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=281041.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.773419141769409 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575697422027588 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.562371015548706 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562351226806641 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563088655471802 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.743602514266968 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5099122524261475 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.563132047653198 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.551986217498779 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.55333685874939 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:36,  1.90s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:29,  1.66s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.50s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.39s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.32s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.27s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.21s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=277944.875000
Using soft routing for tree prediction

[I 2026-04-23 02:55:05,925] Trial 70 finished with value: 274660.821875 and parameters: {'exponent': 1.3757599503785796, 'kernel_type': 'kpq', 'bandwidth': 11.248580275985754, 'diag': False, 'norm_p': 1.713813737625108, 'reg': 0.00185024193318001}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.768760919570923 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.529654264450073 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.559060096740723 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563381910324097 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.561394691467285 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7356181144714355 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.99s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.99s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.73s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.50s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.35s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.26s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:24,  1.21s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:22,  1.18s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.16s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.16s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.16s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=297314.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.721797466278076 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.725308418273926 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.6431403160095215 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.573879241943359 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.565154075622559 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.742558717727661 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.544102430343628 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.231152057647705 seconds

Building trees: 100%|██████████| 1/1 [00:48<00:00, 48.02s/it]

Building trees: 100%|██████████| 1/1 [00:48<00:00, 48.02s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.04s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.78s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.59s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:07,  1.46s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.37s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.26s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=281554.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4268
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7605719566345215 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562668085098267 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.562610387802124 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.56827449798584 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.515450954437256 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4362
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750531435012817 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.572523593902588 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561655759811401 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563117504119873 seconds

Building trees: 100%|██████████| 1/1 [00:49<00:00, 49.72s/it]

Building trees: 100%|██████████| 1/1 [00:49<00:00, 49.72s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:42,  1.69s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:34,  1.45s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:29,  1.30s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:26,  1.20s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:24,  1.15s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:22,  1.13s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:20,  1.11s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.03393150300079013 based on validation mse=317202.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.722409248352051 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.557580471038818 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561179161071777 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562220573425293 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.569987773895264 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752912521362305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563147068023682 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.517091512680054 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5738844871521 seconds

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.68s/it]

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.68s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:24,  2.03s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:19,  1.77s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:15,  1.58s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:13,  1.46s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.37s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.30s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.26s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.23s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.28790202327301256 based on validation mse=289536.593750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4392
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77276873588562 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.568078517913818 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.562893390655518 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.525848388671875 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.565576553344727 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4238
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.740568161010742 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.569403886795044 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.554796934127808 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.557698488235474 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.562315225601196 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.23s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.23s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:08,  2.04s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:05,  1.78s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.59s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.46s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.37s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.28790202327301256 based on validation mse=306972.562500
Using soft routing for tree prediction

[I 2026-04-23 03:02:29,469] Trial 71 finished with value: 298516.16875 and parameters: {'exponent': 1.396103137852339, 'kernel_type': 'kpq', 'bandwidth': 9.92709312504113, 'diag': False, 'norm_p': 1.6949339262026308, 'reg': 0.00021761553456874067}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7650651931762695 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559671878814697 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561661958694458 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565905809402466 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.561887502670288 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.691711187362671 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.98s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.99s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.06s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:12,  1.80s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:09,  1.61s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.48s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.39s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.33s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.28s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.25s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=270670.906250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.768122911453247 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57574462890625 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5717689990997314 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.556713581085205 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.513379335403442 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.73630428314209 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.549482107162476 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.569790363311768 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.553725719451904 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.548753261566162 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.22s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:58,  1.82s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:43,  1.41s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:35,  1.17s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:29,  1.03s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:26,  1.06it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:24,  1.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:22,  1.15it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.14it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:02,  2.01s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.76s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=262320.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4266
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.897648811340332 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.702036142349243 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.57680869102478 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.561666011810303 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.55946159362793 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4364
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.344257354736328 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563068628311157 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564060926437378 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.572282314300537 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57324743270874 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.22s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.83s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.60s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:24,  1.34s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.23s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=291416.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76139235496521 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.50407338142395 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560038805007935 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566002130508423 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.557451009750366 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.754362344741821 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.561469793319702 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.524325847625732 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566554546356201 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.570002317428589 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.76s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.58s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.45s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.36s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.30s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=279907.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7663750648498535 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586231231689453 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561634063720703 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.529726028442383 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563794136047363 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7479023933410645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5637266635894775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.596843242645264 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563127040863037 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.515912294387817 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.29s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.29s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:10,  2.04s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:07,  1.78s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.59s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.46s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.37s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=281918.531250
Using soft routing for tree prediction

[I 2026-04-23 03:10:11,077] Trial 72 finished with value: 277246.69375 and parameters: {'exponent': 1.353705763610383, 'kernel_type': 'kpq', 'bandwidth': 8.034605506876696, 'diag': False, 'norm_p': 1.7330783952992677, 'reg': 0.0017165495157003452}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.767101287841797 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570430755615234 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.570289611816406 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563284873962402 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.560990571975708 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.738105535507202 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 36.00s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.00s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.06s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.80s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.61s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.48s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.39s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.33s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.28s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.25s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=266862.750000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76481556892395 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5630621910095215 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565136432647705 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566490411758423 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.522836446762085 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.73636269569397 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.54931378364563 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.552921533584595 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.54426908493042 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5477213859558105 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.19s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.19s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:20,  2.36s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:52,  1.58s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:39,  1.23s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:32,  1.03s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:27,  1.08it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:24,  1.17it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:23,  1.21it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:21,  1.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:21,  1.23it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:20,  1.21it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:39<00:04,  2.04s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:01,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.59s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.04605387583570519 based on validation mse=259009.359375
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4271
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760408401489258 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567861795425415 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.570370674133301 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.553385972976685 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.554637908935547 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4359
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.716748476028442 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5681281089782715 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.571441888809204 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.573318719863892 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.572110176086426 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.29s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.29s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.79s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:32,  1.56s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:28,  1.41s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:24,  1.31s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:22,  1.25s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.21s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.03953071244130627 based on validation mse=288045.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.764047861099243 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.517675876617432 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.566377639770508 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.757364511489868 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5600268840789795 seconds

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.46s/it]

Building trees: 100%|██████████| 1/1 [00:31<00:00, 31.46s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.79s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:32,  1.56s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:28,  1.42s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:25,  1.32s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:22,  1.25s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.22s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=280358.812500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.819852590560913 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.553231477737427 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.703611373901367 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.67670750617981 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.574932336807251 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.747785568237305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.556837320327759 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.17165470123291 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.558356523513794 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.557663202285767 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.01s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.75s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.58s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.45s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.36s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.30s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=277110.218750
Using soft routing for tree prediction

[I 2026-04-23 03:17:26,325] Trial 73 finished with value: 274277.284375 and parameters: {'exponent': 1.3637822236294475, 'kernel_type': 'kpq', 'bandwidth': 14.120332865410134, 'diag': False, 'norm_p': 1.62206399442535, 'reg': 0.0033223049869264124}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761852502822876 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.56777811050415 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565841436386108 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.532214164733887 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5605316162109375 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.735649108886719 seconds

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.99s/it]

Building trees: 100%|██████████| 1/1 [00:35<00:00, 35.99s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.42it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:19,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:35,  1.95s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:28,  1.71s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.54s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.43s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.35s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.30s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.27s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.24s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.22s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=268401.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76665186882019 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.51753044128418 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.562192916870117 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.570369005203247 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.56941294670105 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.736870288848877 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.547101974487305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.551705598831177 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.497833728790283 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.546599388122559 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.18s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.18s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:20,  2.04s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:15,  1.77s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:12,  1.59s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:10,  1.46s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.37s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.31s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.26s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.23s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.04605387583570519 based on validation mse=260033.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.756299257278442 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.55453896522522 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564562082290649 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.516064643859863 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5589375495910645 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752121686935425 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575548887252808 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5639708042144775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.575551986694336 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5702972412109375 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.28s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.28s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:03<02:03,  3.53s/it]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:02,  1.83s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:42,  1.30s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:33,  1.05s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:28,  1.09it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:25,  1.18it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:23,  1.24it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:22,  1.27it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:21,  1.27it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:20,  1.26it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:39<00:04,  2.05s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:01,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.59s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.025000000000000005 based on validation mse=290784.093750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.764858722686768 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578075170516968 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.556641340255737 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.757821798324585 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.563546419143677 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.513997793197632 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.02s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.03s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.04s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.59s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.46s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.37s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.26s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=284452.843750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763977766036987 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564128160476685 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564426898956299 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566510200500488 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.524328947067261 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750815391540527 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.558365821838379 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.55638313293457 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.557003974914551 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.558314323425293 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:46,  1.66s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:37,  1.38s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:31,  1.21s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:27,  1.10s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:24,  1.04s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:23,  1.01s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:22,  1.01s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:21,  1.02s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.03s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=277968.781250
Using soft routing for tree prediction

[I 2026-04-23 03:24:46,091] Trial 74 finished with value: 276328.028125 and parameters: {'exponent': 1.3630281000975513, 'kernel_type': 'kpq', 'bandwidth': 16.125139644724133, 'diag': False, 'norm_p': 1.600340561439178, 'reg': 0.0036642119133303264}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7617411613464355 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567738771438599 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56426739692688 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560716390609741 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563852787017822 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.737556457519531 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.535576820373535 seconds

Building trees: 100%|██████████| 1/1 [00:43<00:00, 43.55s/it]

Building trees: 100%|██████████| 1/1 [00:43<00:00, 43.55s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.56it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:22,  1.49it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.47it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.45it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.43it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:21,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.34it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.26it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:26<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:27<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:13,  1.95s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:10,  1.72s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.56s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.44s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.37s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.31s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=272057.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4312
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761657953262329 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559225797653198 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.568379163742065 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560883045196533 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5160813331604 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4319
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.731127023696899 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.553044557571411 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.552539348602295 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5479912757873535 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.542569160461426 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.16s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.16s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:48,  1.66s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:38,  1.37s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:32,  1.19s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:27,  1.07s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:25,  1.01s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:23,  1.03it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:22,  1.03it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.00it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=265798.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4262
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.756859302520752 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564575672149658 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.557074785232544 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.571673154830933 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.551341772079468 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4368
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.755385398864746 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5215723514556885 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565114498138428 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.56702446937561 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.568857192993164 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.26s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:06<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:36,  1.91s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.67s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.53s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.42s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:20,  1.34s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.29s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.25s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.22s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.029125376821935778 based on validation mse=290942.312500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4288
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763253450393677 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.52400016784668 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56250786781311 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4342
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.758094787597656 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.56170654296875 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.563055992126465 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5678746700286865 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.58s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.58s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:47,  1.65s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:38,  1.37s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:31,  1.18s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:27,  1.07s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:25,  1.00s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:23,  1.03it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:22,  1.04it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.01it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.15s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=317874.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4393
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775658845901489 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.572271108627319 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5823891162872314 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.569397687911987 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.562422037124634 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4237
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.742470741271973 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.519360065460205 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565114259719849 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560253381729126 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.567190647125244 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.30s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.30s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:36,  1.90s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:29,  1.66s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.50s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.39s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.32s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.27s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.21s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=281985.531250
Using soft routing for tree prediction

[I 2026-04-23 03:32:18,122] Trial 75 finished with value: 285731.575 and parameters: {'exponent': 1.3194242243811383, 'kernel_type': 'kpq', 'bandwidth': 36.28156013123405, 'diag': False, 'norm_p': 1.599767674616606, 'reg': 0.0032047624005581703}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763996362686157 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5202248096466064 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.588193893432617 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.564049482345581 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.559073448181152 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.732676029205322 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.01s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.01s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.73s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.50s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.35s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.26s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:24,  1.21s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:22,  1.18s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.16s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.16s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.16s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.22s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.24s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.23s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=269639.843750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.30765438079834 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5654895305633545 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56855034828186 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.555927991867065 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.558491468429565 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.731998443603516 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.552980184555054 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.506877660751343 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.545091152191162 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.545511960983276 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.71s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.71s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:19,  1.13s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.79s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:23,  1.66s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:20,  1.57s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:18,  1.51s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:27<00:15,  1.42s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:13,  1.34s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:11,  1.29s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.25s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.04605387583570519 based on validation mse=265752.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4262
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7594850063323975 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570149183273315 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 6.437427282333374 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.555034637451172 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.554389953613281 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4368
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.754557847976685 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567837953567505 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.564538955688477 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.532188415527344 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.579887390136719 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.16s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.16s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.17it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.06s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.08s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.10s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.14s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.15s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.04s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.77s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.59s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:07,  1.46s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.37s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.26s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.23s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=287812.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4296
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760511636734009 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559558391571045 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4334
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7529072761535645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.523831605911255 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5643534660339355 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560475826263428 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.569196701049805 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.57s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.57s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:20,  1.62it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:20,  1.58it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.55it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.41it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.37it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:14<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:33,  1.95s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:27,  1.71s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:23,  1.54s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:19,  1.42s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:17,  1.34s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.29s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.22s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=294134.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77288556098938 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580224990844727 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.533741235733032 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.563196182250977 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.564589262008667 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.740187168121338 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559102296829224 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560678720474243 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.521089792251587 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.556927442550659 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.23s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.23s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.73it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.13s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.04s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.78s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:11,  1.59s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.46s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.37s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.31s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.26s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.23s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=280121.375000
Using soft routing for tree prediction

[I 2026-04-23 03:39:45,288] Trial 76 finished with value: 279491.975 and parameters: {'exponent': 1.3656573106466086, 'kernel_type': 'kpq', 'bandwidth': 14.06508308714063, 'diag': False, 'norm_p': 1.7493063738623524, 'reg': 0.008937698031676482}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.762718200683594 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.683159112930298 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.681294202804565 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.6769444942474365 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.63743782043457 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.729171991348267 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.50s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.50s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.68it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.52it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.49it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:28,  2.04s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:23,  1.79s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:19,  1.61s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:16,  1.48s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.40s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:12,  1.33s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:10,  1.29s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.24s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.23s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.22s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=269441.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.761748313903809 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.68333888053894 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.631914854049683 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.6838953495025635 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.678536891937256 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4331
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.7342529296875 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.667231321334839 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.674161434173584 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.669286489486694 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.67154860496521 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.20s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.20s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.49it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.46it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:19<00:17,  1.17s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:17,  1.22s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:16,  1.28s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:15,  1.31s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:24<00:14,  1.34s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:25<00:13,  1.36s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:28<00:11,  1.38s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.39s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:35<00:15,  2.65s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:37<00:11,  2.28s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:38<00:08,  2.01s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:39<00:05,  1.82s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:41<00:03,  1.66s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:42<00:01,  1.55s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.46s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.22s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=269851.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 5.127212285995483 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 5.04300594329834 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.729043245315552 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.6992456912994385 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 5.464157581329346 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.765491485595703 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.697097063064575 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.696754455566406 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.7015440464019775 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.709011793136597 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.08s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.08s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:04<01:06,  2.00s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:47,  1.48s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:37,  1.20s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:31,  1.04s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:27,  1.06it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:24,  1.12it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:23,  1.13it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:22,  1.13it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:22,  1.12it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:22,  1.09it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:21,  1.05it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.10s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.11s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:20<00:19,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:21<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:27<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:40<00:03,  1.89s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:41<00:01,  1.68s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.53s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.18s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=288034.187500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.7742018699646 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.699219465255737 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.698022365570068 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.694133758544922 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.703790664672852 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 7.717633485794067 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.749910593032837 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.42s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.42s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.68it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:24,  2.03s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:19,  1.78s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:15,  1.60s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:13,  1.47s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:11,  1.39s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:09,  1.33s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.29s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.26s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.23s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.22s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.182074901698571 based on validation mse=283341.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4391
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.782536268234253 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.697916507720947 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.700699090957642 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 7.659632682800293 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.702330827713013 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4239
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.755364656448364 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.691901445388794 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.691974639892578 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.698349952697754 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.660793781280518 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:26<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:27<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:28<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:12,  2.07s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:09,  1.80s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.62s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:04,  1.49s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.40s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.33s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.29s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=289054.406250
Using soft routing for tree prediction

[I 2026-04-23 03:47:21,495] Trial 77 finished with value: 279944.5625 and parameters: {'exponent': 1.3240750848281135, 'kernel_type': 'kpq', 'bandwidth': 22.134110629224814, 'diag': True, 'norm_p': 1.8620161696436495, 'reg': 0.0008893630753014231}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780591011047363 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579041957855225 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581093072891235 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58097243309021 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.587148904800415 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7489097118377686 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.584419250488281 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5629332065582275 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.26s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.26s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:34,  1.93s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:28,  1.69s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.53s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.42s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.34s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.29s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=293883.093750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.78719425201416 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5380003452301025 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5804784297943115 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581028938293457 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583966255187988 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4329
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7538533210754395 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562822341918945 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561999559402466 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.524058818817139 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.56294059753418 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:20,  2.04s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:16,  1.78s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:12,  1.59s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:10,  1.46s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.37s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.31s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.24s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=294554.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.862689018249512 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.574442625045776 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5790417194366455 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.165111303329468 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.586035251617432 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.769394874572754 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.589881896972656 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585729122161865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.586782693862915 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5847907066345215 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.25s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.25s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.06it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.00s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:21,  1.05s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:20,  1.09s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.10s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.11s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:15,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:27<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:28<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:29<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:31<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:05,  1.90s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.68s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.53s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.42s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.05365345951302222 based on validation mse=314313.000000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4294
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.784532070159912 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580327749252319 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.575347423553467 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.575752019882202 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.579585313796997 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4336
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.724491119384766 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581141233444214 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582253932952881 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.587881803512573 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.592391729354858 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.49s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.49s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.72s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.49s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.34s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.25s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:23,  1.20s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:22,  1.18s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.16s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.15s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.15s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=295989.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.616757869720459 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585901737213135 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58728551864624 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58706259727478 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.591755390167236 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.75905704498291 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58368182182312 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.545823574066162 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580546855926514 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578566789627075 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:25,  1.73s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.56s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.36s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.23s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=317779.125000
Using soft routing for tree prediction

[I 2026-04-23 03:55:13,337] Trial 78 finished with value: 303303.85 and parameters: {'exponent': 1.2243798557780332, 'kernel_type': 'kpq', 'bandwidth': 2.379236810162462, 'diag': False, 'norm_p': 1.617638330747709, 'reg': 0.0011504831451005601}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.786920070648193 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578636407852173 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.5339415073394775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5804221630096436 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57824444770813 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.74991774559021 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.25it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.85s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:32,  1.62s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:27,  1.47s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.37s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:22,  1.30s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:20,  1.26s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.24s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.22s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.21s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.20s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=267629.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780604600906372 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.531094789505005 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585658311843872 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.586542367935181 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583148717880249 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761699914932251 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.560699939727783 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.519507884979248 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562671899795532 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5591113567352295 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.34s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.77s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.59s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.46s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.31s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=261973.781250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4270
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778193235397339 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58069372177124 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582171440124512 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.53892707824707 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583189964294434 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4360
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.78180456161499 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583235502243042 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578060150146484 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581784963607788 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5339531898498535 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:10,  2.05s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:07,  1.78s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.60s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.47s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.38s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=288946.250000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.781505107879639 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5823073387146 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583854913711548 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576925277709961 seconds

Early stopping at iteration 4
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.726527690887451 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578628778457642 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.575865745544434 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.71s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.72s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.02s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.76s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.58s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:16,  1.46s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.37s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.31s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=281728.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4392
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.787552356719971 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583781480789185 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.54388427734375 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.582069158554077 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5859458446502686 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4238
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.766660451889038 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580069065093994 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578918218612671 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578998565673828 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.532262325286865 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.46s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.46s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=277746.531250
Using soft routing for tree prediction

[I 2026-04-23 04:02:42,669] Trial 79 finished with value: 275604.9 and parameters: {'exponent': 1.372846029276817, 'kernel_type': 'kpq', 'bandwidth': 11.348981166352193, 'diag': False, 'norm_p': 1.5507285568214997, 'reg': 0.007433076039729249}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778894901275635 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579636812210083 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581933975219727 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580334424972534 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.533150672912598 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.748890161514282 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.12s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.12s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:22,  2.06s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.80s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:14,  1.62s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:11,  1.49s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:09,  1.40s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.34s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.30s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.25s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.23s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.182074901698571 based on validation mse=310827.593750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777756452560425 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579418182373047 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580318927764893 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.610407829284668 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559114217758179 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.558704614639282 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562724590301514 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.52s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.52s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:37,  1.87s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:31,  1.64s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:26,  1.48s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:23,  1.37s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:20,  1.31s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.26s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.21s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.20s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.19s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=302326.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4260
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778510570526123 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.52992582321167 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5749287605285645 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4370
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.771708965301514 seconds

Building trees: 100%|██████████| 1/1 [00:26<00:00, 26.98s/it]

Building trees: 100%|██████████| 1/1 [00:26<00:00, 26.98s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  2.00s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.75s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:22,  1.58s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:19,  1.46s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.38s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.32s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.28s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.25s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.03393150300079013 based on validation mse=336096.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.776626348495483 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585179567337036 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.53401517868042 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578886985778809 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5779759883880615 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.767484664916992 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578678846359253 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.57845139503479 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.535448312759399 seconds

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.82s/it]

Building trees: 100%|██████████| 1/1 [00:52<00:00, 52.82s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:10,  2.05s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:07,  1.78s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.60s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.47s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.38s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.28790202327301256 based on validation mse=303302.281250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4392
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.789559364318848 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586820125579834 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583507299423218 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.584878444671631 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.582059621810913 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4238
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.759213209152222 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.15s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.15s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:20,  2.06s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:16,  1.80s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:12,  1.62s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:10,  1.49s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.40s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.33s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.29s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.26s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.24s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.182074901698571 based on validation mse=339323.593750
Using soft routing for tree prediction

[I 2026-04-23 04:09:17,387] Trial 80 finished with value: 318375.18125 and parameters: {'exponent': 1.3722664182886095, 'kernel_type': 'kpq', 'bandwidth': 11.015443313682223, 'diag': False, 'norm_p': 1.535635043660548, 'reg': 4.954180872875623e-05}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780622720718384 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586367607116699 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581644058227539 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.550551176071167 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5847601890563965 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.75664210319519 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.557175397872925 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.70s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.70s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:36,  1.92s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.68s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.52s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.42s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:20,  1.35s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.30s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.26s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.24s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.21s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=276921.250000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779506206512451 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5471556186676025 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580422639846802 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580185890197754 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5768067836761475 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7488439083099365 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5618908405303955 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561928033828735 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.516604661941528 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.567426919937134 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:22,  1.49it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.43it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.39it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.33it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.33it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:21,  1.94s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.71s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:13,  1.54s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:11,  1.43s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.35s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.29s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.26s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.23s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.04605387583570519 based on validation mse=273301.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.78305459022522 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5755298137664795 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582824230194092 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.523860931396484 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575805425643921 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.773920059204102 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.14s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.15s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.26it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.21it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.15it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.10it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.05it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.00it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.04s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:20,  1.07s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.10s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:19,  1.13s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:29,  1.86s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:24,  1.67s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.53s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:16,  1.37s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.32s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.28s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.25s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.0 based on validation mse=291466.843750
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775757074356079 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578256845474243 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.769261121749878 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583899736404419 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.584649085998535 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.589028358459473 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.582474946975708 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.54s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.54s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:45,  1.69s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:37,  1.43s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:31,  1.27s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:28,  1.17s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:25,  1.11s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:24,  1.09s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:22,  1.09s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.09s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.12s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.14s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.15s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.17s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:27<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:39<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.12s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=297791.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780497789382935 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580350637435913 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583436489105225 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579445838928223 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580516338348389 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760446786880493 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.534979343414307 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.573676586151123 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.573937177658081 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581955671310425 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.39s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.39s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.40it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.28it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:36,  1.93s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.69s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.53s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.42s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:20,  1.35s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:18,  1.30s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.26s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.24s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=286760.031250
Using soft routing for tree prediction

[I 2026-04-23 04:16:32,131] Trial 81 finished with value: 285248.325 and parameters: {'exponent': 1.3316630558884066, 'kernel_type': 'kpq', 'bandwidth': 19.461673054173787, 'diag': False, 'norm_p': 1.5405852337197883, 'reg': 0.013025459948460476}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.781070232391357 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.538240671157837 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.57869291305542 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576977968215942 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.588837623596191 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.747934341430664 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:42,  1.71s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:35,  1.47s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:30,  1.32s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:26,  1.22s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:24,  1.17s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:22,  1.15s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:21,  1.14s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.14s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.15s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=268597.906250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.714469909667969 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583508253097534 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58294939994812 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.584434747695923 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5829808712005615 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752094030380249 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.531177520751953 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.569465637207031 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.56300950050354 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.561583042144775 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:25,  1.73s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.56s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.36s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.23s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=261712.796875
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4264
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.771418571472168 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567396640777588 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.5334312915802 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.566900253295898 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5718994140625 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4366
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.768792629241943 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.590793609619141 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585161209106445 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.542274713516235 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581225872039795 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.39s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.39s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.04s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.78s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.59s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.47s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.38s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.03953071244130627 based on validation mse=286994.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4293
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.781640529632568 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5827717781066895 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.575844764709473 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4337
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.722315788269043 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58028507232666 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5799829959869385 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578683376312256 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.586034536361694 seconds

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.30s/it]

Building trees: 100%|██████████| 1/1 [00:45<00:00, 45.30s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.84s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.61s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.35s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.24s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.22s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.20s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.22s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.182074901698571 based on validation mse=285864.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7923500537872314 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.320703744888306 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582970380783081 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580904960632324 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580159902572632 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.76184344291687 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5808751583099365 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.539341926574707 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580503463745117 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578556537628174 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.22s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.76s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.58s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.46s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.31s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=278239.156250
Using soft routing for tree prediction

[I 2026-04-23 04:24:05,794] Trial 82 finished with value: 276281.846875 and parameters: {'exponent': 1.301393868513215, 'kernel_type': 'kpq', 'bandwidth': 13.434155863004232, 'diag': False, 'norm_p': 1.6434199918596892, 'reg': 0.006828743852499217}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.786323547363281 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579545259475708 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.576958179473877 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.537670373916626 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.585460424423218 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.754177093505859 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.12s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.12s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:35,  1.95s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:29,  1.71s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.55s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.44s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:19,  1.36s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:17,  1.31s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.27s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.23s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.22s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=266576.656250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777379989624023 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.543248653411865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580755949020386 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576048374176025 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575422048568726 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752663850784302 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.560152292251587 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.570183277130127 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.511054277420044 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.566851854324341 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:20,  2.04s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:16,  1.78s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:12,  1.59s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:10,  1.46s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.37s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.31s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.24s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=262136.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779190301895142 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5773327350616455 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.576972246170044 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.5294189453125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.573338985443115 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.772621393203735 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582807302474976 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585124969482422 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.584300756454468 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.585342884063721 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.42s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.42s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:31<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:32<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:04,  2.05s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.60s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.029125376821935778 based on validation mse=293342.718750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4299
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.78166651725769 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578252553939819 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.577571630477905 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576375961303711 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581455707550049 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4331
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.710136651992798 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5840089321136475 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585980176925659 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.587454795837402 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5829198360443115 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.47s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.47s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:40,  1.76s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:33,  1.53s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:29,  1.39s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:25,  1.29s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:23,  1.23s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.20s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.18s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.17s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=285856.312500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4388
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.746153831481934 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5821754932403564 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582383394241333 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.593198776245117 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.582537412643433 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4242
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7669596672058105 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.572601079940796 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.52602481842041 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.569572448730469 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583224058151245 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.41s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.41s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:29,  2.00s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.75s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:20,  1.57s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:17,  1.45s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.36s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=279388.906250
Using soft routing for tree prediction

[I 2026-04-23 04:31:48,773] Trial 83 finished with value: 277460.225 and parameters: {'exponent': 1.376500915107843, 'kernel_type': 'kpq', 'bandwidth': 8.9582311524592, 'diag': False, 'norm_p': 1.5623726135833698, 'reg': 0.002284790436918}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4316
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7894487380981445 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.577085494995117 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.533096075057983 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577528238296509 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.58181095123291 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4315
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750193357467651 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:37,  1.89s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:31,  1.66s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:26,  1.50s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:23,  1.40s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:21,  1.33s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.28s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.25s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:16,  1.23s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.22s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.21s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.19s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=268902.718750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780214786529541 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.527932167053223 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5737059116363525 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580716371536255 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.573244094848633 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.748754262924194 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564105987548828 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565993785858154 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.515010118484497 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5627453327178955 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.29s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.29s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:24,  2.03s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:19,  1.77s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:15,  1.59s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:13,  1.46s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.37s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.31s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.24s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=261697.734375
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7838521003723145 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578559637069702 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.587226152420044 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.538339853286743 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.574562311172485 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777832984924316 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585387945175171 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582300186157227 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579488515853882 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5866193771362305 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.44s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.44s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:08,  2.05s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:05,  1.79s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.60s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.47s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.38s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=287400.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4297
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778203010559082 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581411600112915 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582139015197754 seconds

Early stopping at iteration 3
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.768236398696899 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.525306940078735 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.590027809143066 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.15s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.15s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.05s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.78s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:11,  1.60s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.47s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.38s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.31s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.24s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=286614.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4393
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7880635261535645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586812257766724 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58286452293396 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.586650133132935 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.537222385406494 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4237
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.767503023147583 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.572562217712402 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5787670612335205 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.575392007827759 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.573205471038818 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.45s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.45s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:04<01:05,  1.99s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:47,  1.47s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:36,  1.19s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:30,  1.03s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:26,  1.08it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:24,  1.14it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:22,  1.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.19it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:21,  1.18it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.16it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:02,  2.05s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=278741.468750
Using soft routing for tree prediction

[I 2026-04-23 04:39:13,542] Trial 84 finished with value: 276671.378125 and parameters: {'exponent': 1.3409782455566046, 'kernel_type': 'kpq', 'bandwidth': 17.494617156556387, 'diag': False, 'norm_p': 1.6449255400844975, 'reg': 0.004192933745840646}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.783518552780151 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579943418502808 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.591066598892212 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580578327178955 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5837225914001465 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.707427501678467 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.559421539306641 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5660412311553955 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.556797981262207 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.56170916557312 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.38s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.38s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.83s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.61s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.35s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.24s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.22s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.20s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.24712300293414508 based on validation mse=274645.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779766321182251 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.535873651504517 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579092264175415 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580129384994507 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580039024353027 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761389493942261 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567440032958984 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.529981851577759 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560594320297241 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.563689947128296 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.35s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.35s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.77s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.58s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.46s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.31s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.26s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=273245.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4272
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.779369354248047 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579853773117065 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.57693338394165 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.532304286956787 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5788469314575195 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4358
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.771188020706177 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.589957237243652 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.584670066833496 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5899200439453125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5440733432769775 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.45s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.46s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.79s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=304098.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782871246337891 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5789079666137695 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58069634437561 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58368992805481 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5857274532318115 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775785207748413 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.584246397018433 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58321738243103 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.583021402359009 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.586639404296875 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.49s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.50s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:46,  1.65s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:37,  1.38s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:31,  1.21s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:27,  1.10s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:24,  1.04s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:23,  1.01s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:22,  1.01s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:21,  1.02s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.04s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:20,  1.05s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=278545.406250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4384
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.784538745880127 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.590118169784546 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5849974155426025 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581740379333496 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583028793334961 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4246
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763044595718384 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.53653359413147 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5842344760894775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.576308250427246 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580352544784546 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.44s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.44s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.71it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:34,  1.94s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:28,  1.69s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:24,  1.53s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:21,  1.42s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:18,  1.34s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.29s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.22s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.19s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=290666.187500
Using soft routing for tree prediction

[I 2026-04-23 04:47:14,871] Trial 85 finished with value: 284240.275 and parameters: {'exponent': 1.11532289466309, 'kernel_type': 'kpq', 'bandwidth': 5.3678187583625805, 'diag': False, 'norm_p': 1.3538993139519517, 'reg': 0.00818307862822375}. Best is trial 61 with value: 273737.25625.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7853779792785645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.538087606430054 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582808494567871 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581931114196777 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5822858810424805 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4303
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.74994421005249 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.560404539108276 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.67s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.67s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:48,  1.66s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:38,  1.37s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:32,  1.19s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:27,  1.07s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:25,  1.01s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:23,  1.03it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:22,  1.04it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.03it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.01it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=263370.750000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778468370437622 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581364393234253 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5832977294921875 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.616833209991455 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.589191675186157 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.753727674484253 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.531561613082886 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581392288208008 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.556939363479614 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.584894418716431 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.46s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.46s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:36,  1.91s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.67s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.51s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.40s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.33s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.28s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.22s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=260956.015625
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.776090145111084 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.5270469188690186 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579084634780884 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580505609512329 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.572596549987793 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.769995927810669 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582582712173462 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5825488567352295 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.536444902420044 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.587078094482422 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.41s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.41s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:22,  2.04s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.78s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:14,  1.59s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:11,  1.46s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.37s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.31s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.24s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=284122.593750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.780623912811279 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580099105834961 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582217216491699 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.532918453216553 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.585942506790161 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.771968841552734 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579796314239502 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.584750652313232 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581781625747681 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580183744430542 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.44s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:08,  2.05s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:05,  1.78s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.60s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.47s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.38s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=272996.156250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.790037393569946 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585379123687744 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5825841426849365 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.683600902557373 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.689694166183472 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.534618854522705 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5769829750061035 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5743408203125 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577327013015747 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.574995279312134 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.52s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.52s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:41,  1.68s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:34,  1.44s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:29,  1.30s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:26,  1.21s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:24,  1.16s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:22,  1.13s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:21,  1.12s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.12s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.13s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.14s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=279613.437500
Using soft routing for tree prediction

[I 2026-04-23 04:55:02,068] Trial 86 finished with value: 272211.79375 and parameters: {'exponent': 1.3488314714785494, 'kernel_type': 'kpq', 'bandwidth': 3.392738013710273, 'diag': False, 'norm_p': 1.744017313867038, 'reg': 0.0137131961354413}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.737732648849487 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580719470977783 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579141855239868 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577588796615601 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.58854341506958 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4303
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.752795457839966 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.11s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:22,  1.54it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.50it/s]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:59,  1.85s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:44,  1.44s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:07<00:36,  1.20s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:30,  1.06s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:27,  1.03it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:24,  1.09it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:23,  1.11it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:22,  1.12it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:21,  1.10it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:21,  1.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:21,  1.04it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:20,  1.00it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.03s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.06s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.09s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:40<00:04,  2.09s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:42<00:01,  1.83s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.64s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.20s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=316229.250000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.772437572479248 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580512046813965 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.748046875 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58621621131897 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.557955503463745 seconds

Building trees: 100%|██████████| 1/1 [00:28<00:00, 28.55s/it]

Building trees: 100%|██████████| 1/1 [00:28<00:00, 28.55s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:03<02:04,  3.55s/it]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:03,  1.85s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:43,  1.32s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:34,  1.07s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:29,  1.07it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:07<00:25,  1.15it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:23,  1.21it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:22,  1.24it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.23it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:20,  1.20it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.16it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.10s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.12s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.14s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:39<00:06,  2.07s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:40<00:03,  1.81s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:41<00:01,  1.62s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.49s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.18s/it]

Selected split_temperature=0.182074901698571 based on validation mse=335624.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4279
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778349876403809 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5847320556640625 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4351
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.774864912033081 seconds

Building trees: 100%|██████████| 1/1 [00:19<00:00, 19.46s/it]

Building trees: 100%|██████████| 1/1 [00:19<00:00, 19.47s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.41it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:43,  1.72s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:35,  1.48s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:30,  1.33s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:27,  1.24s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:25,  1.19s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:23,  1.17s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:21,  1.16s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.16s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.16s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.17s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.19s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.20s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:39<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.12s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=339870.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4302
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.727457761764526 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.573102712631226 seconds

Early stopping at iteration 2
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4328
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.763187646865845 seconds

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.38s/it]

Building trees: 100%|██████████| 1/1 [00:22<00:00, 22.38s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.35it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.31it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.22it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.17it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.06it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.02it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:20,  1.06s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:35,  1.97s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:29,  1.73s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:25,  1.57s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:21,  1.46s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:19,  1.38s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:17,  1.33s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:15,  1.29s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:27<00:13,  1.27s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.25s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:11,  1.24s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.22s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.22s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.22s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:39<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:40<00:00,  1.12s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=366947.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4381
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778010606765747 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.54015851020813 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58008074760437 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581845045089722 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5853283405303955 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4249
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.757384538650513 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.573386907577515 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.71s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.71s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:21,  1.65it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.50it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.47it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.44it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:07<00:51,  1.71s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:40,  1.40s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:33,  1.21s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:29,  1.09s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:26,  1.01s/it]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:24,  1.02it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:12<00:23,  1.03it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:13<00:22,  1.03it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:14<00:21,  1.00it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:21,  1.02s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:21,  1.05s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:20,  1.08s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.10s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.12s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:21<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.17s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.18s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.19s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:27<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:11,  1.20s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:33<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:34<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.21s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:42<00:02,  2.09s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.83s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:43<00:00,  1.20s/it]

Selected split_temperature=0.21212000487151167 based on validation mse=346393.781250
Using soft routing for tree prediction

[I 2026-04-23 05:01:04,897] Trial 87 finished with value: 341013.0125 and parameters: {'exponent': 1.3031583724299043, 'kernel_type': 'kpq', 'bandwidth': 56.22340774392457, 'diag': False, 'norm_p': 1.7546799397964248, 'reg': 0.039448214077543745}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4315
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778775691986084 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580051898956299 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585580348968506 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577205657958984 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578124523162842 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4316
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.71562933921814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.55950665473938 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.67s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.67s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.04s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.78s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:11,  1.59s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.47s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.38s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.31s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.24s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=263500.250000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77705979347229 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582833766937256 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5825724601745605 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.580168962478638 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5368123054504395 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.751777410507202 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564620733261108 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.567226409912109 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.560188055038452 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.560953855514526 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.36s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.37s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:04<01:05,  1.99s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:47,  1.47s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:36,  1.19s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:30,  1.03s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:26,  1.07it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:24,  1.14it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:22,  1.18it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.19it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:21,  1.18it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.16it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:02,  2.05s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=261466.625000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4266
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.9755871295928955 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.710803985595703 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578150272369385 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581801414489746 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581324577331543 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4364
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.339064598083496 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578246116638184 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.587403774261475 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.6003851890563965 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581150054931641 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.48s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.48s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.80s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:32,  1.57s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:28,  1.42s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:25,  1.32s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:22,  1.26s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.22s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.05365345951302222 based on validation mse=283284.812500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782492637634277 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.52634072303772 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578792095184326 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581823110580444 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.58019495010376 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.77165150642395 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.584072113037109 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.54227614402771 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.584388017654419 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.587514638900757 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.01s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.76s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.58s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:16,  1.46s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.37s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.31s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=272990.968750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.786764144897461 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579007863998413 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.548969268798828 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5848352909088135 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581902503967285 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761664390563965 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575861930847168 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581125497817993 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.574911594390869 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.535946369171143 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=280303.187500
Using soft routing for tree prediction

[I 2026-04-23 05:08:51,808] Trial 88 finished with value: 272309.159375 and parameters: {'exponent': 1.3438248222305824, 'kernel_type': 'kpq', 'bandwidth': 3.0658973421929745, 'diag': False, 'norm_p': 1.787334103226912, 'reg': 0.013890258124352888}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.773276090621948 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.702686786651611 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.699918985366821 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.698988914489746 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.643484354019165 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.749605894088745 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.691531658172607 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.30s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.30s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.68it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:30,  2.02s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.77s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:20,  1.59s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:17,  1.47s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.39s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.33s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.28s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:10,  1.25s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.22s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=270237.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4312
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.783859968185425 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.704373359680176 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.65692663192749 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.69930100440979 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.69951605796814 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4319
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.744932413101196 seconds

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.64s/it]

Building trees: 100%|██████████| 1/1 [00:36<00:00, 36.64s/it]

Early stopping at iteration 1

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.67it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.51it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.48it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.45it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:21,  1.42it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.39it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.36it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.32it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.27it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.23it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:20,  1.18it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:20,  1.12it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:39,  1.87s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:32,  1.64s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:28,  1.48s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.38s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:22,  1.32s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:20,  1.27s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:22<00:18,  1.25s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.22s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.21s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.21s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:28<00:12,  1.21s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:29<00:10,  1.20s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.20s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:35<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=271106.812500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4277
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.772895097732544 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 7.651543617248535 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.6970953941345215 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.700014352798462 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.6934473514556885 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4353
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.764592170715332 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.7011072635650635 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.647765874862671 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.701537847518921 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.70772647857666 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.53it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.50it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:21,  1.47it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.37it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.33it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:30,  2.02s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.77s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:20,  1.59s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:17,  1.47s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.38s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.32s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.28s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:10,  1.25s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.22s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.20s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.19s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.0 based on validation mse=287090.093750
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4300
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.772702932357788 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.6947760581970215 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 7.651841878890991 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.787518501281738 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.811503887176514 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.7702250480651855 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.702532529830933 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.700895309448242 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.699168920516968 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.385634899139404 seconds

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Building trees: 100%|██████████| 1/1 [00:58<00:00, 58.41s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.58it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.41it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.38it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.34it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:20,  1.29it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:20,  1.24it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:20,  1.19it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:20,  1.14it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:20,  1.08it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:20,  1.00s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:20<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:21<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.06s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:14,  1.80s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:11,  1.62s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:08,  1.49s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.40s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.33s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.29s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.26s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.22s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=269158.468750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4380
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.779597282409668 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.702503442764282 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.705211400985718 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.700823783874512 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 7.664055585861206 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4250
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 0: 4.767743825912476 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 1: 4.6988537311553955 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 2: 4.692284107208252 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 3: 4.703242063522339 seconds

Using expensive batch size
Optimal M batch size: 2509

Time taken for round 4: 4.705045938491821 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.51s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.51s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.69it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:04<01:20,  2.37s/it]

Tuning split temperature:   8%|▊         | 3/36 [00:04<00:52,  1.60s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:39,  1.24s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:32,  1.05s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:07<00:28,  1.07it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:25,  1.14it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:23,  1.19it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:22,  1.20it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:11<00:21,  1.18it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.15it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:15<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:16<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:17<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.07s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.09s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.11s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.13s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:23<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:24<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.18s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:30<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:08,  1.18s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:39<00:06,  2.07s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:40<00:03,  1.81s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:41<00:01,  1.62s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.49s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:42<00:00,  1.18s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=293787.031250
Using soft routing for tree prediction

[I 2026-04-23 05:16:28,163] Trial 89 finished with value: 278276.05 and parameters: {'exponent': 1.281464126659184, 'kernel_type': 'kpq', 'bandwidth': 3.0446804832624714, 'diag': True, 'norm_p': 1.7973892773953772, 'reg': 0.013491612670472171}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778475999832153 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578895568847656 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585159063339233 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.583778142929077 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5825090408325195 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.698752403259277 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5693604946136475 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:22,  2.04s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:17,  1.78s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:14,  1.59s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:11,  1.46s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.37s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.31s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.24s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.21s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.20s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=266671.843750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.784362554550171 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575866937637329 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580437660217285 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.523272752761841 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575999021530151 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4336
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.755173683166504 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5702502727508545 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56560754776001 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.562074899673462 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.566762208938599 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.31s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:29<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:31<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:06,  2.05s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.78s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.60s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.47s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=266634.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4260
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777419328689575 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581088066101074 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578629493713379 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5736167430877686 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.570860385894775 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4370
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.731926202774048 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585488557815552 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583141326904297 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.586070775985718 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.580941677093506 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.46s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.46s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.72s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.49s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.34s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.25s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:23,  1.20s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:22,  1.16s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.15s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.14s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=284535.187500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4298
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.725519895553589 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586979389190674 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5835280418396 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.587143659591675 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.576646566390991 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4332
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.772795677185059 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5806660652160645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.541839122772217 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.584737062454224 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.626965284347534 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.63s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.63s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:30,  1.92s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:25,  1.69s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.53s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.42s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.34s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:14,  1.29s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.25s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.22s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.19s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.18s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=276402.250000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4389
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.786771059036255 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.589312791824341 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.546625137329102 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.592807292938232 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5905234813690186 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4241
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761207580566406 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58666467666626 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.576383590698242 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581672668457031 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.541101932525635 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.48s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.48s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.20it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.04s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.78s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.60s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.47s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.38s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=283941.312500
Using soft routing for tree prediction

[I 2026-04-23 05:24:15,357] Trial 90 finished with value: 275636.9625 and parameters: {'exponent': 1.350610180053987, 'kernel_type': 'kpq', 'bandwidth': 1.6813824478949866, 'diag': False, 'norm_p': 1.8661920511939891, 'reg': 0.022294389580954404}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782713890075684 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58144736289978 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5790674686431885 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.583713531494141 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.540029525756836 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.751785516738892 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5669450759887695 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.69s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.69s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.73s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.56s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.36s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.23s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=264348.437500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7762510776519775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.577664852142334 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.531396150588989 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578532457351685 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575554609298706 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.747812747955322 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.562551975250244 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.565507411956787 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.519756317138672 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.562614917755127 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.30s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.30s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.04s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.78s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:11,  1.60s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.47s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.38s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.31s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.24s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=263672.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4263
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.776990652084351 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.577114582061768 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579028367996216 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5835325717926025 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.524508237838745 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4367
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775927543640137 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579667806625366 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.582252264022827 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577541828155518 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.581977367401123 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.45s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.45s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:04<01:05,  1.99s/it]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:47,  1.47s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:36,  1.19s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:30,  1.03s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:26,  1.08it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:24,  1.15it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:22,  1.19it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:09<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:21,  1.19it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:20,  1.16it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.13it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.09it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:02,  2.05s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=284399.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.776809930801392 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579404592514038 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579583644866943 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578885316848755 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.574978828430176 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.7367987632751465 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5878214836120605 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579758644104004 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578706741333008 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.582368850708008 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.47s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.47s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.84s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.61s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:24,  1.35s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.24s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.22s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.20s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=274575.406250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4386
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.788834810256958 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.54127049446106 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581766605377197 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.582754373550415 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.584834814071655 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4244
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.764426946640015 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580467462539673 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.527972459793091 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577452182769775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.579413175582886 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.03s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:21,  1.77s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.59s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.46s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.37s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.31s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.23s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.21s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.20s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.19s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=282180.000000
Using soft routing for tree prediction

[I 2026-04-23 05:32:02,360] Trial 91 finished with value: 273835.25 and parameters: {'exponent': 1.34919221591215, 'kernel_type': 'kpq', 'bandwidth': 2.158366168678134, 'diag': False, 'norm_p': 1.8626137137802758, 'reg': 0.02290986043942309}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4333
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7818663120269775 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582265377044678 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583960771560669 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.539582014083862 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.598238229751587 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4298
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.75061821937561 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.568765640258789 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.71s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.71s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:39,  1.79s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:32,  1.56s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:28,  1.42s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:25,  1.32s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:22,  1.26s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:20,  1.22s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.20s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.18s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.18s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.17s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.17s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.17s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=265474.718750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.750153064727783 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585090637207031 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.576227426528931 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58129096031189 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.58287501335144 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7522454261779785 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564765691757202 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.53627872467041 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.598789691925049 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.643939733505249 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.50s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.51s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:27,  1.97s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.73s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.56s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.44s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.36s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.30s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=265644.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.770855903625488 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567333221435547 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.528753757476807 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.569325685501099 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57439112663269 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.769421815872192 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58253026008606 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.591180801391602 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579240798950195 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5288496017456055 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.37s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.37s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.12s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.14s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=285087.000000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4295
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.775744199752808 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.585707664489746 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.583126544952393 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.589733839035034 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.541830062866211 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4335
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782661437988281 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.595244884490967 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.585917711257935 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.587208271026611 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.584709167480469 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.53s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.53s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:48,  1.66s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:38,  1.37s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:32,  1.19s/it]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:27,  1.08s/it]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:25,  1.01s/it]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:23,  1.02it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:22,  1.03it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.00it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.02s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.04s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=277433.593750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4387
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.776492595672607 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.58798885345459 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.586748838424683 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58382511138916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.591148614883423 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4243
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.757741451263428 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.537991762161255 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.577954053878784 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579349756240845 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57141900062561 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.43s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:36,  1.91s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:30,  1.67s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:25,  1.51s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:22,  1.40s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:19,  1.33s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:17,  1.28s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:14,  1.22s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:13,  1.20s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.19s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.18s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.18s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=282658.250000
Using soft routing for tree prediction

[I 2026-04-23 05:39:49,569] Trial 92 finished with value: 275259.675 and parameters: {'exponent': 1.3531705893215018, 'kernel_type': 'kpq', 'bandwidth': 1.7348448424208622, 'diag': False, 'norm_p': 1.8698011585333927, 'reg': 0.026671653341245036}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777601718902588 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.523432731628418 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.587947845458984 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581254243850708 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578976392745972 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.748303651809692 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.564429759979248 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.561228513717651 seconds

Building trees: 100%|██████████| 1/1 [00:48<00:00, 48.19s/it]

Building trees: 100%|██████████| 1/1 [00:48<00:00, 48.19s/it]

Early stopping at iteration 3

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:28<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:30<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:31<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:06,  2.05s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:03,  1.78s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.60s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.47s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=276439.843750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4299
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778014183044434 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578557252883911 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580753326416016 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.586634874343872 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.582651615142822 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4332
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.712215185165405 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570662021636963 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56470799446106 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5729570388793945 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.566655158996582 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.40s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.40s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:41,  1.73s/it]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:34,  1.49s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:29,  1.34s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:26,  1.25s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:23,  1.20s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:22,  1.17s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:20,  1.15s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.14s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.14s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.15s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.15s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.15s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=274303.687500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.732248067855835 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.586320400238037 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578638553619385 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.583144426345825 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578423261642456 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.772173166275024 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.591082334518433 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.536231994628906 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.585361480712891 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5863940715789795 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.46s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.46s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.01s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.04s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:25,  1.73s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.56s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.36s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.23s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.17s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=290523.343750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782331943511963 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.577448129653931 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.532670736312866 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578575611114502 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.579519987106323 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.766882419586182 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5810019969940186 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.594208002090454 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.583241701126099 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.545339107513428 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.45s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.45s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:16,  2.05s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:12,  1.78s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:09,  1.60s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.47s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.38s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.31s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=282345.000000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4382
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.792815923690796 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581559896469116 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581806659698486 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581899881362915 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.539042949676514 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4248
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.761808395385742 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.581918478012085 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.579118251800537 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581603050231934 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5829668045043945 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.48s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.48s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:53,  1.73s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:41,  1.39s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:34,  1.17s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:29,  1.04s/it]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:25,  1.04it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:23,  1.09it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:22,  1.11it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:21,  1.09it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.06it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.03it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:20,  1.01s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:19,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  2.05s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=288011.343750
Using soft routing for tree prediction

[I 2026-04-23 05:47:44,361] Trial 93 finished with value: 282324.64375 and parameters: {'exponent': 1.382262969940494, 'kernel_type': 'kpq', 'bandwidth': 1.2089236515448496, 'diag': False, 'norm_p': 1.8311913296518663, 'reg': 0.025160355353393192}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4322
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.771941184997559 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582163095474243 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581254005432129 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579332590103149 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.57719874382019 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4309
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.701869010925293 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5588483810424805 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.64s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.64s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:21<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:18,  2.04s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:14,  1.78s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:11,  1.60s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:08,  1.47s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.38s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.31s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.24s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.21s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.20s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=265208.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4304
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777894973754883 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.57781457901001 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.577357530593872 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5827858448028564 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.5290610790252686 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4327
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.749262809753418 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.569560766220093 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.56208348274231 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.565324544906616 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5703535079956055 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.37s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.37s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:05<00:58,  1.83s/it]

Tuning split temperature:  14%|█▍        | 5/36 [00:06<00:43,  1.42s/it]

Tuning split temperature:  17%|█▋        | 6/36 [00:06<00:35,  1.18s/it]

Tuning split temperature:  19%|█▉        | 7/36 [00:07<00:29,  1.03s/it]

Tuning split temperature:  22%|██▏       | 8/36 [00:08<00:26,  1.06it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:09<00:24,  1.12it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:10<00:22,  1.15it/s]

Tuning split temperature:  31%|███       | 11/36 [00:10<00:21,  1.15it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:11<00:21,  1.14it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:20,  1.11it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:20,  1.07it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:20,  1.04it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:19,  1.00it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:19,  1.03s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:18,  1.06s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:18,  1.08s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:17,  1.10s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:16,  1.12s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:25<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:40<00:02,  2.05s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.78s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:41<00:00,  1.16s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=263876.718750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4262
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.774913311004639 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579864978790283 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58406400680542 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.578923463821411 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578807353973389 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4368
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.734828948974609 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5836992263793945 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580274820327759 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.589446544647217 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5826098918914795 seconds

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.49s/it]

Building trees: 100%|██████████| 1/1 [00:54<00:00, 54.49s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:38,  1.83s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:32,  1.60s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:27,  1.45s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:17<00:24,  1.35s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:21,  1.28s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:19,  1.24s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.20s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.19s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.18s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.18s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.17s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.17s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.17s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.17s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.17s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.17s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.182074901698571 based on validation mse=283156.218750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4290
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7771220207214355 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 7.528566837310791 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581100702285767 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579529047012329 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.584294557571411 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4340
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7691428661346436 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.582355260848999 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.536951541900635 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5772833824157715 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.578006982803345 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.42s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.42s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:26,  2.02s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:21,  1.77s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:17,  1.59s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.46s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.39s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.33s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.29s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.26s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.24s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.23s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.22s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.21s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.19s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.18s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=273970.125000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4397
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.787548780441284 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578878402709961 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.581886291503906 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 7.2314958572387695 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.583070278167725 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4233
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.760547161102295 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.575729131698608 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5726158618927 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.57282280921936 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.528587579727173 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.09s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.09s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.78s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=282649.281250
Using soft routing for tree prediction

[I 2026-04-23 05:55:31,355] Trial 94 finished with value: 273772.1 and parameters: {'exponent': 1.3463088152069103, 'kernel_type': 'kpq', 'bandwidth': 2.1965022081513976, 'diag': False, 'norm_p': 1.8360602079234873, 'reg': 0.015679040410994976}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4330
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.778934478759766 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.576762437820435 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.58024001121521 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577313423156738 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.584454298019409 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.75020694732666 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.570311784744263 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:28,  2.01s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:22,  1.76s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:18,  1.58s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:16,  1.46s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.37s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.31s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.23s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.21s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.20s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.19s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.18s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=269550.375000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7815470695495605 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.578732490539551 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.536177396774292 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.581319093704224 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5780158042907715 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.750214099884033 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5601818561553955 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.560770034790039 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.577696084976196 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.517621040344238 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.32s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.32s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.60it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.55it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.52it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:27<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:12,  2.05s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:08,  1.79s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:06,  1.60s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.47s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.38s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.31s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=274899.468750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4267
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777722120285034 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579824447631836 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.580521821975708 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.5803382396698 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.529661417007446 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4363
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.770587921142578 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.579162836074829 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578096866607666 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.582237720489502 seconds

Building trees: 100%|██████████| 1/1 [00:49<00:00, 49.88s/it]

Building trees: 100%|██████████| 1/1 [00:49<00:00, 49.88s/it]

Early stopping at iteration 4

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:12<00:40,  1.76s/it]

Tuning split temperature:  39%|███▉      | 14/36 [00:13<00:33,  1.53s/it]

Tuning split temperature:  42%|████▏     | 15/36 [00:14<00:28,  1.38s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:15<00:25,  1.29s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:16<00:23,  1.23s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:18<00:21,  1.19s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:19<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:18,  1.16s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:17,  1.16s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:16,  1.16s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:15,  1.16s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:13,  1.16s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:12,  1.16s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:11,  1.16s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.16s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:06,  1.16s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.16s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.16s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.16s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.16s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.16s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=295114.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4291
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 7.7506139278411865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.5752551555633545 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.578552484512329 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.579196214675903 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.575945138931274 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4339
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.7683820724487305 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580698251724243 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.546624183654785 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.58320951461792 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.5815112590789795 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.45s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.45s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.57it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.54it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.51it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.31it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:29,  2.00s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:24,  1.75s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:20,  1.57s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:17,  1.45s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:15,  1.36s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:13,  1.30s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.23s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.21s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.20s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.19s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.18s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.03393150300079013 based on validation mse=293003.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4383
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.786173343658447 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583859443664551 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.536289930343628 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.591387748718262 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.59237003326416 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4247
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.097384452819824 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9922521114349365 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.611636161804199 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.574383735656738 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 6.688135623931885 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.37s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.37s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.49it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.46it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.43it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:20,  1.39it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:20,  1.35it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.30it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.26it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.21it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.15it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.10it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.05it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.01it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:14<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:17<00:17,  1.09s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:18<00:16,  1.11s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:19<00:15,  1.13s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:20<00:14,  1.14s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:22<00:13,  1.15s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:23<00:12,  1.15s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:24<00:11,  1.15s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:25<00:10,  1.16s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:26<00:09,  1.16s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:14,  2.05s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:10,  1.78s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:07,  1.60s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.47s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:04,  1.38s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.31s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.08483837917962198 based on validation mse=284400.375000
Using soft routing for tree prediction

[I 2026-04-23 06:03:13,143] Trial 95 finished with value: 283393.53125 and parameters: {'exponent': 1.3416832861729848, 'kernel_type': 'kpq', 'bandwidth': 2.0495448469270476, 'diag': False, 'norm_p': 1.8262027869695532, 'reg': 0.10182965446599768}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4317
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.782193660736084 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.583115100860596 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.5854408740997314 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.582060098648071 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 7.53309178352356 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4314
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.753778696060181 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.567033529281616 seconds

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Building trees: 100%|██████████| 1/1 [00:40<00:00, 40.68s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.72it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.61it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.56it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:20,  1.53it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.50it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:03<00:20,  1.47it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.44it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:19,  1.40it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:19,  1.36it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:19,  1.32it/s]

Tuning split temperature:  31%|███       | 11/36 [00:07<00:19,  1.27it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:08<00:19,  1.22it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:09<00:19,  1.16it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:10<00:19,  1.11it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:11<00:19,  1.06it/s]

Tuning split temperature:  44%|████▍     | 16/36 [00:12<00:19,  1.02it/s]

Tuning split temperature:  47%|████▋     | 17/36 [00:13<00:19,  1.02s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:15<00:18,  1.05s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:16<00:18,  1.07s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:20<00:31,  1.98s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:21<00:26,  1.73s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:22<00:21,  1.56s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:23<00:18,  1.44s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:16,  1.36s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:14,  1.30s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:11,  1.23s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:09,  1.21s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.20s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.19s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:05,  1.18s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:04,  1.18s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.17s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.17s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.17s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:38<00:00,  1.08s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=263949.906250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 4.777971982955933 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.580991268157959 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 7.5260536670684814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.036436080932617 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 5.4195237159729 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.13884711265564 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.6281890869140625 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.644469738006592 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.337733507156372 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.677258014678955 seconds

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.28s/it]

Building trees: 100%|██████████| 1/1 [00:57<00:00, 57.28s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:20,  1.70it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:21,  1.59it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:01<00:21,  1.54it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:21,  1.51it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:20,  1.48it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:20,  1.45it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:04<00:20,  1.38it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.26it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.05it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.00it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:21,  1.09s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.12s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.15s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:20,  1.18s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.21s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.23s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.27s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.30s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.32s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:26<00:16,  1.47s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:27<00:14,  1.44s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:28<00:12,  1.41s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.36s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:31<00:09,  1.33s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:32<00:07,  1.30s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.28s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:36<00:03,  1.26s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:37<00:02,  1.26s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.25s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.24s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.11s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=265777.937500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4269
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.210798978805542 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.988971948623657 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.9886391162872314 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.0246686935424805 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 5.007708549499512 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4361
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.247905492782593 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.993178129196167 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.98907995223999 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.991041421890259 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.990681886672974 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.21s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.21s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:22,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=286996.187500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.216015815734863 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.995211362838745 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.999039173126221 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.020964622497559 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.995455741882324 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.204020261764526 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.999985694885254 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.996213436126709 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.002581596374512 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.995929718017578 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.23s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.23s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.29it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=278630.593750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4384
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.2259907722473145 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.999619007110596 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 5.002857446670532 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.999011516571045 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 5.000048875808716 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4246
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.200715780258179 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.991203784942627 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.991203784942627 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.992297887802124 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.9923622608184814 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.20s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.20s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.27it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.19it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.15it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.10it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=281810.500000
Using soft routing for tree prediction

[I 2026-04-23 06:11:01,759] Trial 96 finished with value: 275433.0 and parameters: {'exponent': 1.3146625737071833, 'kernel_type': 'kpq', 'bandwidth': 2.176054914844615, 'diag': False, 'norm_p': 1.7762637528791168, 'reg': 0.043760779121978274}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4326
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.213065147399902 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9957051277160645 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.998790264129639 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.002030611038208 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.996407985687256 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4305
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.181800842285156 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.98412299156189 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.15s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.15s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.12it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.09883799050275041 based on validation mse=265427.500000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4311
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.208434104919434 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.988798379898071 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.989481210708618 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.989678859710693 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.993395566940308 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4320
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.175836086273193 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.972464084625244 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.975403308868408 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.9792327880859375 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.976828098297119 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.03s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.04s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.39it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=263510.156250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4263
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.20326042175293 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.983199119567871 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.990721225738525 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.983894109725952 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 5.105293273925781 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4367
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.20098090171814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 5.004040718078613 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 5.002082109451294 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.003185033798218 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.998421907424927 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.29s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.29s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.29it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.12it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.07it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:13<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.24s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.27s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.28s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:14,  1.28s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.28s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.30s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.30s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:09,  1.29s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.28s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:33<00:06,  1.29s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.28s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.28s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.28s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.28s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.10s/it]

Selected split_temperature=0.07282170089875539 based on validation mse=283992.406250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4279
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.524768829345703 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 5.109726667404175 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.9969260692596436 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.999120712280273 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.991193771362305 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4351
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.199164390563965 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.994262218475342 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.992444276809692 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.016987085342407 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.993388414382935 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.68s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.68s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=273117.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4385
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.213391304016113 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 5.001545190811157 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.9956276416778564 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.994529962539673 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.997498035430908 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4245
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.190615892410278 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.987355947494507 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.983139991760254 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.989709854125977 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.9840874671936035 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.15s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.15s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.15it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=282730.906250
Using soft routing for tree prediction

[I 2026-04-23 06:18:49,962] Trial 97 finished with value: 273755.7 and parameters: {'exponent': 1.3571168332261887, 'kernel_type': 'kpq', 'bandwidth': 2.466452279241928, 'diag': False, 'norm_p': 1.830344208301501, 'reg': 0.011022748004750376}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4321
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.208637714385986 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.99126124382019 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.98710298538208 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.9892613887786865 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.986260890960693 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4310
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.187183618545532 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9710986614227295 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.10s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.10s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=264394.875000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4307
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.2077507972717285 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.978705167770386 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.983866453170776 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.982928037643433 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.993627309799194 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4324
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.170317649841309 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.978936195373535 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.977497100830078 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.9638512134552 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.96821403503418 seconds

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.99s/it]

Building trees: 100%|██████████| 1/1 [00:55<00:00, 55.99s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=262191.000000
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4277
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.203508138656616 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.97947096824646 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.982315540313721 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.982248783111572 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.984519720077515 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4353
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.190639495849609 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.995141267776489 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.99446439743042 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.996458292007446 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.99621057510376 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.09s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.09s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.29it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.16s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.029125376821935778 based on validation mse=282716.968750
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.207192659378052 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.986780881881714 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.986656665802002 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.995327949523926 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.990502119064331 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.195849657058716 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.994348526000977 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.996075391769409 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 5.004671573638916 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.9892737865448 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.14s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.14s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.29it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=272063.062500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4379
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.211582660675049 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.995361804962158 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.997510194778442 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.99622917175293 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.993659734725952 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4251
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.193428993225098 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.988933801651001 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.981683015823364 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.984115362167358 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.981533050537109 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.33it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.30it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:22,  1.27it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.23it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.19it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.15it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:19<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=281617.312500
Using soft routing for tree prediction

[I 2026-04-23 06:26:36,948] Trial 98 finished with value: 272596.64375 and parameters: {'exponent': 1.3542800629287444, 'kernel_type': 'kpq', 'bandwidth': 2.5390705650574885, 'diag': False, 'norm_p': 1.8395954813035147, 'reg': 0.014593878363600602}. Best is trial 86 with value: 272211.79375.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4323
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.201913118362427 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.994539499282837 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.9952497482299805 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.9912333488464355 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.989579916000366 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4308
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.166885852813721 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9720399379730225 seconds

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.09s/it]

Building trees: 100%|██████████| 1/1 [00:41<00:00, 41.09s/it]

Early stopping at iteration 2

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.11514774870862055 based on validation mse=275791.531250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4306
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.211089134216309 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.989969253540039 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.985513210296631 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.987574815750122 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.99550461769104 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20712, d: 27, and nval: 4325
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.174907684326172 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9707207679748535 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.980682134628296 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.974774122238159 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.966763496398926 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.01s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.01s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:15,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=278018.031250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4261
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.197723388671875 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.981882095336914 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.995133399963379 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.98418402671814 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.981808423995972 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4369
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.201462984085083 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.991204738616943 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 5.000438690185547 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.998796224594116 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.991586208343506 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:21,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.29it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.21it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.02it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.25s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.182074901698571 based on validation mse=291311.812500
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4301
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.204506158828735 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.987801551818848 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.995396375656128 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.983473062515259 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.997332572937012 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4329
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.192285776138306 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9931511878967285 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.9911370277404785 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.992908954620361 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.987437725067139 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.13s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.57it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.48it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:22,  1.44it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.41it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.38it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.35it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.32it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.28it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.25it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.16it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.11it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.03s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.07s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:23<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:37<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.1562854472336314 based on validation mse=283788.781250
Using soft routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using top_vector_agop_on_subset split method
Getting AGOP on subset
X_train torch.Size([24285, 27]) y_train torch.Size([24285, 1]) X_val torch.Size([1279, 27]) y_val torch.Size([1279, 1])
======================================================================
Fitting RFM with ntrain: 24285, d: 27, and nval: 1279
======================================================================

Using cheap batch size
Optimal M batch size: 2614
Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4390
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.209711074829102 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.993846893310547 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.992494344711304 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.995298862457275 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 5.00027871131897 seconds

Refilling validation set, because at least one split has been made.
======================================================================
Fitting RFM with ntrain: 20713, d: 27, and nval: 4240
======================================================================

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 0: 5.186997175216675 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 1: 4.9811835289001465 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 2: 4.988108158111572 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 3: 4.987762689590454 seconds

Using expensive batch size
Optimal M batch size: 2509

Using SVD
Time taken for round 4: 4.985810279846191 seconds

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.12s/it]

Building trees: 100%|██████████| 1/1 [00:56<00:00, 56.12s/it]

Tuning split temperature:   0%|          | 0/36 [00:00<?, ?it/s]

Tuning split temperature:   3%|▎         | 1/36 [00:00<00:22,  1.58it/s]

Tuning split temperature:   6%|▌         | 2/36 [00:01<00:23,  1.47it/s]

Tuning split temperature:   8%|▊         | 3/36 [00:02<00:23,  1.43it/s]

Tuning split temperature:  11%|█         | 4/36 [00:02<00:22,  1.40it/s]

Tuning split temperature:  14%|█▍        | 5/36 [00:03<00:22,  1.37it/s]

Tuning split temperature:  17%|█▋        | 6/36 [00:04<00:22,  1.34it/s]

Tuning split temperature:  19%|█▉        | 7/36 [00:05<00:22,  1.31it/s]

Tuning split temperature:  22%|██▏       | 8/36 [00:05<00:21,  1.27it/s]

Tuning split temperature:  25%|██▌       | 9/36 [00:06<00:21,  1.24it/s]

Tuning split temperature:  28%|██▊       | 10/36 [00:07<00:21,  1.20it/s]

Tuning split temperature:  31%|███       | 11/36 [00:08<00:21,  1.15it/s]

Tuning split temperature:  33%|███▎      | 12/36 [00:09<00:21,  1.10it/s]

Tuning split temperature:  36%|███▌      | 13/36 [00:10<00:21,  1.06it/s]

Tuning split temperature:  39%|███▉      | 14/36 [00:11<00:21,  1.01it/s]

Tuning split temperature:  42%|████▏     | 15/36 [00:12<00:21,  1.04s/it]

Tuning split temperature:  44%|████▍     | 16/36 [00:14<00:21,  1.08s/it]

Tuning split temperature:  47%|████▋     | 17/36 [00:15<00:21,  1.11s/it]

Tuning split temperature:  50%|█████     | 18/36 [00:16<00:20,  1.14s/it]

Tuning split temperature:  53%|█████▎    | 19/36 [00:17<00:19,  1.17s/it]

Tuning split temperature:  56%|█████▌    | 20/36 [00:18<00:19,  1.19s/it]

Tuning split temperature:  58%|█████▊    | 21/36 [00:20<00:18,  1.21s/it]

Tuning split temperature:  61%|██████    | 22/36 [00:21<00:17,  1.23s/it]

Tuning split temperature:  64%|██████▍   | 23/36 [00:22<00:16,  1.24s/it]

Tuning split temperature:  67%|██████▋   | 24/36 [00:24<00:14,  1.25s/it]

Tuning split temperature:  69%|██████▉   | 25/36 [00:25<00:13,  1.26s/it]

Tuning split temperature:  72%|███████▏  | 26/36 [00:26<00:12,  1.26s/it]

Tuning split temperature:  75%|███████▌  | 27/36 [00:27<00:11,  1.26s/it]

Tuning split temperature:  78%|███████▊  | 28/36 [00:29<00:10,  1.26s/it]

Tuning split temperature:  81%|████████  | 29/36 [00:30<00:08,  1.27s/it]

Tuning split temperature:  83%|████████▎ | 30/36 [00:31<00:07,  1.27s/it]

Tuning split temperature:  86%|████████▌ | 31/36 [00:32<00:06,  1.27s/it]

Tuning split temperature:  89%|████████▉ | 32/36 [00:34<00:05,  1.27s/it]

Tuning split temperature:  92%|█████████▏| 33/36 [00:35<00:03,  1.27s/it]

Tuning split temperature:  94%|█████████▍| 34/36 [00:36<00:02,  1.27s/it]

Tuning split temperature:  97%|█████████▋| 35/36 [00:38<00:01,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.27s/it]

Tuning split temperature: 100%|██████████| 36/36 [00:39<00:00,  1.09s/it]

Selected split_temperature=0.13414886285344563 based on validation mse=294898.343750
Using soft routing for tree prediction

[I 2026-04-23 06:34:24,363] Trial 99 finished with value: 284761.68125 and parameters: {'exponent': 1.3082530738165434, 'kernel_type': 'kpq', 'bandwidth': 1.2933379751208478, 'diag': False, 'norm_p': 1.824778631708211, 'reg': 0.015318863977567468}. Best is trial 86 with value: 272211.79375.

Best params: {'exponent': 1.3488314714785494, 'kernel_type': 'kpq', 'bandwidth': 3.392738013710273, 'diag': False, 'norm_p': 1.744017313867038, 'reg': 0.0137131961354413}
Best MSE: 272211.79375

In [8]:
model, pipeline, fit_time, train_metrics, val_metrics = fit_best_xrfm(
    X,
    y,
    best_trial,
    processor,
    n_num_cols,
    task=cfg["task"],
    device=device,
)

print(f"Training time: {fit_time:.2f}s")
print(f"Train RMSE: {train_metrics['rmse']:.4f}")
print(f"Val RMSE:   {val_metrics['rmse']:.4f}")

joblib.dump(model, MODELS_DIR / data_name / "xrfm.joblib")
joblib.dump(pipeline, MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [9]:
model = joblib.load(MODELS_DIR / data_name / "xrfm.joblib")
pipeline = joblib.load(MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [10]:
X_test = test_df.drop(columns=metadata["target_col"])
y_test = test_df[metadata["target_col"]].to_numpy().astype(np.float32)

X_test = pipeline.transform(X_test)
t0 = time.perf_counter()
y_pred = model.predict(X_test)
infer_time = (time.perf_counter() - t0) / len(X_test)

Using soft routing for tree prediction

In [11]:
results = evaluate_regression(y_test, y_pred)
print(f"RMSE: {results['rmse']:.4f}")
print(f"Inference time per sample: {infer_time * 1e6:.2f}µs")

RMSE: 520.0493
Inference time per sample: 110.26µs

In [12]:
output = {
    **results,
    "train_metrics": train_metrics,
    "val_metrics": val_metrics,
    "fit_time_s": fit_time,
    "infer_time_per_sample_s": infer_time,
    "best_params": {
        "tuning_metric": model.tuning_metric,
        "split_method": model.split_method,
        "max_leaf_size": model.max_leaf_size,
        **model.rfm_params,
    },
}

results_dir = RESULTS_BENCHMARK / "diamonds"
with open(results_dir / "xrfm.json", "w") as f:
    json.dump(output, f, indent=4)

print(f"Results saved to {results_dir / 'xrfm.json'}")