In [1]:
import json
import time

import joblib
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import LabelEncoder

from benchmark.config import DATA_PROCESSED, DATASETS, MODELS_DIR, RESULTS_BENCHMARK
from benchmark.metrics import (
    evaluate_classification,
    plot_confusion_matrix,
    plot_roc_curve,
    save_classification_report,
)
from benchmark.models.xrfm_model import make_processor
from benchmark.models.xrfm_model import fit_best_xrfm, fit_xrfm_cross_validation

data_name = "obesity_level"
cfg = DATASETS[data_name]
processed = DATA_PROCESSED / data_name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train_df = pd.read_csv(processed / "train.csv")
train_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,26,1.628019,108.265922,yes,yes,3,3,Sometimes,no,2,no,0,0,Sometimes,Public_Transportation,Obesity_Type_III
1,Female,23,1.480000,60.000000,yes,yes,2,1,Sometimes,yes,1,no,0,0,Sometimes,Public_Transportation,Overweight_Level_II
2,Female,15,1.650000,86.000000,yes,yes,3,3,Sometimes,no,1,no,3,2,no,Walking,Obesity_Type_I
3,Female,26,1.593321,110.168166,yes,yes,3,3,Sometimes,no,2,no,0,0,Sometimes,Public_Transportation,Obesity_Type_III
4,Male,18,1.803527,108.251044,yes,yes,2,2,Sometimes,no,3,no,1,1,no,Public_Transportation,Obesity_Type_I

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1688 entries, 0 to 1687
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          1688 non-null   object
 1   Age                             1688 non-null   int64
 2   Height                          1688 non-null   float64
 3   Weight                          1688 non-null   float64
 4   family_history_with_overweight  1688 non-null   object
 5   FAVC                            1688 non-null   object
 6   FCVC                            1688 non-null   int64
 7   NCP                             1688 non-null   int64
 8   CAEC                            1688 non-null   object
 9   SMOKE                           1688 non-null   object
 10  CH2O                            1688 non-null   int64
 11  SCC                             1688 non-null   object
 12  FAF                             1688 non-null   int64
 13  TUE                             1688 non-null   int64
 14  CALC                            1688 non-null   object
 15  MTRANS                          1688 non-null   object
 16  NObeyesdad                      1688 non-null   object
dtypes: float64(2), int64(6), object(9)
memory usage: 224.3+ KB

In [4]:
test_df = pd.read_csv(processed / "test.csv")
test_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,26,1.631856,110.804337,yes,yes,3,3,Sometimes,no,3,no,0,0,Sometimes,Public_Transportation,Obesity_Type_III
1,Female,19,1.609495,42.656563,no,yes,3,3,Sometimes,no,3,yes,2,1,no,Public_Transportation,Insufficient_Weight
2,Female,19,1.573816,39.850137,no,yes,1,2,Sometimes,no,1,no,1,2,Sometimes,Public_Transportation,Insufficient_Weight
3,Female,22,1.500000,63.652330,yes,no,2,1,Sometimes,no,2,no,0,1,no,Public_Transportation,Overweight_Level_II
4,Female,27,1.550000,63.000000,no,yes,2,3,Sometimes,no,1,no,0,1,Sometimes,Automobile,Overweight_Level_I

In [5]:
with open(processed / "metadata.json") as f:
    metadata = json.load(f)

print(metadata)

{'num_cols': ['TUE', 'FAF', 'CH2O', 'FCVC', 'Age', 'Height', 'Weight', 'NCP'], 'cat_cols': ['CAEC', 'CALC', 'MTRANS'], 'bin_cols': ['Gender', 'family_history_with_overweight', 'FAVC', 'SMOKE', 'SCC'], 'target_col': 'NObeyesdad'}

In [6]:
le = LabelEncoder()
X = train_df.drop(columns=metadata["target_col"])
y = le.fit_transform(train_df[metadata["target_col"]]).astype(np.int32)

print("Classes:", le.classes_)

Classes: ['Insufficient_Weight' 'Normal_Weight' 'Obesity_Type_I' 'Obesity_Type_II'
 'Obesity_Type_III' 'Overweight_Level_I' 'Overweight_Level_II']

In [7]:
processor = make_processor(metadata)
n_num_cols = len(metadata["num_cols"])

In [8]:
best_trial = fit_xrfm_cross_validation(
    X, y, processor, n_num_cols, task=cfg["task"], device=device
)

print(f"Best params: {best_trial.params}")
print(f"Best macro F1: {best_trial.value}")

[I 2026-04-22 21:32:00,701] A new study created in memory with name: no-name-f1854e33-6a4a-45dc-9bf8-d75542452791

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 0: 0.6664535999298096 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.01132965087890625 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.011075973510742188 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010804891586303711 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.01085662841796875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.01064443588256836 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011620759963989258 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0117950439453125 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010088205337524414 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.00991511344909668 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010657787322998047 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.01037454605102539 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.01176309585571289 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010850191116333008 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.012445688247680664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009948015213012695 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.00998997688293457 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.009695768356323242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.010567903518676758 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.009875059127807617 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009791374206542969 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010303020477294922 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010086297988891602 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:02,154] Trial 0 finished with value: 0.9790902117751992 and parameters: {'exponent': 1.0271644858581115, 'kernel_type': 'k2q', 'bandwidth': 1.970613996905623, 'diag': True, 'reg': 0.0026485784758470345}. Best is trial 0 with value: 0.9790902117751992.

Optimal M batch size: 1351
Time taken for round 3: 0.009841680526733398 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.009717464447021484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:869: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 0: 1.1368436813354492 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030677080154418945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030625104904174805 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03052544593811035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.030351638793945312 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028930187225341797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03053140640258789 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.031160593032836914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.031874656677246094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.033673763275146484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02857232093811035 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 1: 0.030216217041015625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030394792556762695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.030717134475708008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.030834436416625977 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02953052520751953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03112506866455078 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03242826461791992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.031636953353881836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.03070855140686035 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0288546085357666 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03335857391357422 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:04,234] Trial 1 finished with value: 0.980288846794861 and parameters: {'exponent': 0.7598959983417237, 'kernel_type': 'kpq', 'bandwidth': 31.128146769150394, 'diag': True, 'norm_p': 1.204380550596923, 'reg': 1.5178988352304667e-06}. Best is trial 1 with value: 0.980288846794861.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030045509338378906 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.031938791275024414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.032228708267211914 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010266780853271484 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011653661727905273 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.011974334716796875 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 3: 0.01064753532409668 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.012587547302246094 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.009996414184570312 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011620283126831055 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.010685205459594727 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010941028594970703 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010928630828857422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.012194395065307617 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.012171506881713867 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.012017011642456055 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.011714935302734375 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.011717796325683594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.013039350509643555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.011544227600097656 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.011215686798095703 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.009928464889526367 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010282754898071289 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.012700319290161133 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.012462139129638672 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010852813720703125 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.009709835052490234 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:04,686] Trial 2 finished with value: 0.8551824874657038 and parameters: {'exponent': 0.7416781387847737, 'kernel_type': 'k2q', 'bandwidth': 175.8288583045548, 'diag': True, 'reg': 0.5118691608584706}. Best is trial 1 with value: 0.980288846794861.

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010832071304321289 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028482437133789062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.031534433364868164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03101372718811035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03126788139343262 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0317530632019043 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028813600540161133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030867815017700195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03138589859008789 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.030371665954589844 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.031138896942138672 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.029013872146606445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.031141996383666992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030381202697753906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03108048439025879 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02899789810180664 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02922677993774414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03150224685668945 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02966785430908203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.032216548919677734 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02940082550048828 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.029556989669799805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03744316101074219 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03187108039855957 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1351
Time taken for round 3: 0.03128647804260254 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029406309127807617 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:05,658] Trial 3 finished with value: 0.9659070900055445 and parameters: {'exponent': 0.7550981778629094, 'kernel_type': 'kpq', 'bandwidth': 6.5017130686590825, 'diag': True, 'norm_p': 1.6741056103679175, 'reg': 0.15816844334894103}. Best is trial 1 with value: 0.980288846794861.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00916147232055664 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.010663032531738281 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.012489080429077148 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.011290550231933594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00947117805480957 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.009741067886352539 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.011454105377197266 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.00880122184753418 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010621070861816406 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.010385751724243164 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009765863418579102 seconds
Early stopping at iteration 3
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.012535333633422852 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010418415069580078 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.012591838836669922 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.011252641677856445 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010829925537109375 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.010946989059448242 seconds
Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:05,997] Trial 4 finished with value: 0.6499724358422566 and parameters: {'exponent': 1.2386834737442696, 'kernel_type': 'k2q', 'bandwidth': 90.48888237464404, 'diag': True, 'reg': 0.8236923920601619}. Best is trial 1 with value: 0.980288846794861.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.03642392158508301 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.03003716468811035 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.030181884765625 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.030681133270263672 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.029763221740722656 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.030398130416870117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.030066490173339844 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 1: 0.030174732208251953 seconds
Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.030411958694458008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:06,496] Trial 5 finished with value: 0.9172667193480922 and parameters: {'exponent': 1.3169801908670333, 'kernel_type': 'kpq', 'bandwidth': 19.84662081152421, 'diag': False, 'norm_p': 1.7995055455137243, 'reg': 0.05330158533580604}. Best is trial 1 with value: 0.980288846794861.

Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.030346393585205078 seconds
Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.03131842613220215 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.03031635284423828 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.030759334564208984 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.030652523040771484 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.03177523612976074 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.03193354606628418 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.03144049644470215 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.030822038650512695 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.03159356117248535 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.03292560577392578 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.03044581413269043 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.03307056427001953 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.031047821044921875 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.030707120895385742 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.03158116340637207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.03063058853149414 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.03382396697998047 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.03175973892211914 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.0304872989654541 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.03220939636230469 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02921891212463379 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.031711578369140625 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.03139543533325195 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.031211376190185547 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.031858205795288086 seconds
Tree has no split, stopping training

[I 2026-04-22 21:32:07,504] Trial 6 finished with value: 0.970633865482425 and parameters: {'exponent': 1.0948486965751747, 'kernel_type': 'kpq', 'bandwidth': 63.44132593183689, 'diag': False, 'norm_p': 1.4194589751409419, 'reg': 0.00011913672272764324}. Best is trial 1 with value: 0.980288846794861.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00940394401550293 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.009105920791625977 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009254217147827148 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010556697845458984 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008971691131591797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.008893013000488281 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011504888534545898 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.00875711441040039 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008024454116821289 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010327577590942383 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00885772705078125 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.009927749633789062 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.00991368293762207 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008671283721923828 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.009630441665649414 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.012369155883789062 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.012917757034301758 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010695219039916992 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.010289669036865234 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010010242462158203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.01128697395324707 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.011411190032958984 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.011008262634277344 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:07,899] Trial 7 finished with value: 0.9778630680373629 and parameters: {'exponent': 0.9163728423001612, 'kernel_type': 'k2q', 'bandwidth': 11.925101256066307, 'diag': True, 'reg': 0.021609288204221935}. Best is trial 1 with value: 0.980288846794861.

Time taken for round 3: 0.00993967056274414 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.009268760681152344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.009608268737792969 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.010778188705444336 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.010346174240112305 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.012603998184204102 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.011689901351928711 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010091781616210938 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.010509490966796875 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009853124618530273 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.009979248046875 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010221004486083984 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010071039199829102 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011399269104003906 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009568929672241211 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.009823083877563477 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.009644031524658203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.01183176040649414 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010492801666259766 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.011692523956298828 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.011234760284423828 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010325431823730469 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.010787248611450195 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010818004608154297 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010267972946166992 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.011333703994750977 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010808944702148438 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:08,318] Trial 8 finished with value: 0.9791233787277754 and parameters: {'exponent': 1.2060200075435343, 'kernel_type': 'k2q', 'bandwidth': 2.792736238727968, 'diag': True, 'reg': 0.0007660547961224706}. Best is trial 1 with value: 0.980288846794861.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00994873046875 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011304616928100586 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.011512279510498047 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.009985208511352539 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010304450988769531 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010704517364501953 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.010568380355834961 seconds
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.010279178619384766 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010443925857543945 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.011171817779541016 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.01141977310180664 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.014432430267333984 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.011712789535522461 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010631561279296875 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010535001754760742 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.012636184692382812 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.012810230255126953 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010485649108886719 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.011229991912841797 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.010257482528686523 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.01092839241027832 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.012670278549194336 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.011379003524780273 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.011245489120483398 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.01108098030090332 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:08,754] Trial 9 finished with value: 0.9798149463951512 and parameters: {'exponent': 0.7450034897059166, 'kernel_type': 'k2q', 'bandwidth': 1.880953078065556, 'diag': True, 'reg': 2.8141896704489657e-06}. Best is trial 1 with value: 0.980288846794861.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.029284954071044922 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.030155181884765625 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.029082536697387695 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029491186141967773 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.029351234436035156 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027835607528686523 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02954268455505371 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.028881072998046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02880072593688965 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.029804706573486328 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027243614196777344 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.028014183044433594 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027968406677246094 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.028263330459594727 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.02816939353942871 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.028133392333984375 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.02881622314453125 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.02800917625427246 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.028756380081176758 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.029407978057861328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.026779890060424805 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.02898240089416504 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.028710126876831055 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.028664112091064453 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.029205322265625 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:09,666] Trial 10 finished with value: 0.9686436989501379 and parameters: {'exponent': 0.8938451094397133, 'kernel_type': 'kpq', 'bandwidth': 33.51360317378641, 'diag': False, 'norm_p': 0.9213441785811907, 'reg': 1.2978677583901398e-06}. Best is trial 1 with value: 0.980288846794861.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027916669845581055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029768705368041992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028931379318237305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028691530227661133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029796838760375977 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027182817459106445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02899003028869629 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029592037200927734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.030660629272460938 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.03008580207824707 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027306079864501953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029317617416381836 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0290982723236084 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029562711715698242 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028153657913208008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026943683624267578 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03143572807312012 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028601408004760742 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028888940811157227 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02878880500793457 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026607513427734375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029819965362548828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029376506805419922 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028048038482666016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029146432876586914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:10,588] Trial 11 finished with value: 0.981528052879287 and parameters: {'exponent': 0.8579407492480471, 'kernel_type': 'kpq', 'bandwidth': 1.2162353529696637, 'diag': True, 'norm_p': 1.0994925821149664, 'reg': 1.6850504609816964e-06}. Best is trial 11 with value: 0.981528052879287.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0278775691986084 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02985405921936035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029532194137573242 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02892136573791504 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0288848876953125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02707672119140625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029193401336669922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02945709228515625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029998064041137695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028583288192749023 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02745509147644043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030854463577270508 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029736042022705078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029428482055664062 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02884840965270996 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02732062339782715 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029532194137573242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029237031936645508 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02885150909423828 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029372453689575195 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026752948760986328 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028753280639648438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02886176109313965 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029500722885131836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029805898666381836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:11,523] Trial 12 finished with value: 0.9796568295594801 and parameters: {'exponent': 0.888965866404843, 'kernel_type': 'kpq', 'bandwidth': 5.250227127115833, 'diag': True, 'norm_p': 1.1018818630084413, 'reg': 1.9458647887851433e-05}. Best is trial 11 with value: 0.981528052879287.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02675604820251465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028522253036499023 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02893233299255371 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028708696365356445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02851557731628418 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02624964714050293 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02954864501953125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02847766876220703 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028525590896606445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028782129287719727 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02725362777709961 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029869556427001953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03097844123840332 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0292661190032959 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028589248657226562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02709674835205078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02873063087463379 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029217958450317383 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02856135368347168 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.028554439544677734 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027935028076171875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029327392578125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02945399284362793 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028881072998046875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028765201568603516 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:12,431] Trial 13 finished with value: 0.980288846794861 and parameters: {'exponent': 0.8590897519227059, 'kernel_type': 'kpq', 'bandwidth': 31.17360374289351, 'diag': True, 'norm_p': 1.2106615339564746, 'reg': 1.3816695123182923e-05}. Best is trial 11 with value: 0.981528052879287.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027319908142089844 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.0276336669921875 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.030364036560058594 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.028802871704101562 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.029172182083129883 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027959346771240234 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02864861488342285 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027935028076171875 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.028534412384033203 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.0283815860748291 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027779817581176758 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02965831756591797 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.028888225555419922 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029645204544067383 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.029085397720336914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.027866363525390625 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.03115057945251465 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.03241395950317383 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.03191184997558594 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.03184103965759277 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:13,513] Trial 14 finished with value: 0.971051600631925 and parameters: {'exponent': 1.0244936600635248, 'kernel_type': 'kpq', 'bandwidth': 7.807963789521191, 'diag': False, 'norm_p': 1.2721157636632798, 'reg': 1.3177107944936844e-05}. Best is trial 11 with value: 0.981528052879287.

Using SVD
Time taken for round 0: 0.02974224090576172 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.030197620391845703 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.029395103454589844 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.029605388641357422 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.032573699951171875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 0: 0.029024124145507812 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030239582061767578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029036283493041992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028499364852905273 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02862405776977539 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025582313537597656 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 1: 0.029179811477661133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028371334075927734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027489900588989258 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028222322463989258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026148080825805664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029415369033813477 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.02867913246154785 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029012680053710938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02772045135498047 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02684783935546875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02901148796081543 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0279996395111084 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 3: 0.029459476470947266 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029152393341064453 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02688002586364746 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02908158302307129 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02768564224243164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029865741729736328 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:14,417] Trial 15 finished with value: 0.9808780946125888 and parameters: {'exponent': 0.8171372149284486, 'kernel_type': 'kpq', 'bandwidth': 1.2647886943110973, 'diag': True, 'norm_p': 0.9750831203562761, 'reg': 0.00012777199985593353}. Best is trial 11 with value: 0.981528052879287.

Time taken for round 4: 0.02872467041015625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025845050811767578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02837848663330078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029018402099609375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02864241600036621 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02848029136657715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02690911293029785 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02968287467956543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02921772003173828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02919745445251465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02831864356994629 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027582645416259766 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029247760772705078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027848243713378906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02863788604736328 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.028577089309692383 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026911020278930664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028845548629760742 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028749704360961914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028868913650512695 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02778458595275879 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02968001365661621 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03034186363220215 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0292050838470459 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028762102127075195 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02815413475036621 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:15,326] Trial 16 finished with value: 0.9815044028926522 and parameters: {'exponent': 0.8425365180195054, 'kernel_type': 'kpq', 'bandwidth': 1.156488568249114, 'diag': True, 'norm_p': 0.9056847421973827, 'reg': 0.00033451822525263307}. Best is trial 11 with value: 0.981528052879287.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02668285369873047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02837657928466797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02872943878173828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02873539924621582 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.03101205825805664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027457237243652344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03022170066833496 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029725074768066406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02982306480407715 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.02979302406311035 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027405261993408203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029732465744018555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029366493225097656 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029575824737548828 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029544830322265625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026824235916137695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028772830963134766 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029445648193359375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029178142547607422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029674530029296875 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026187419891357422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028825998306274414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028740644454956055 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029166460037231445 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02931809425354004 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:16,250] Trial 17 finished with value: 0.9821059724365634 and parameters: {'exponent': 0.996142080193055, 'kernel_type': 'kpq', 'bandwidth': 1.0001664132827537, 'diag': True, 'norm_p': 1.109608743345865, 'reg': 0.0023346143793490036}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02742624282836914 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029646873474121094 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.03077387809753418 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029648780822753906 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.028719425201416016 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.0276644229888916 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029584884643554688 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.030429601669311523 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029275178909301758 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.029163837432861328 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.028108835220336914 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029189109802246094 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.029654741287231445 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.030686616897583008 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.029091835021972656 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02771162986755371 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.028172969818115234 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.028470993041992188 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.029449939727783203 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.028720855712890625 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.027080059051513672 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.02765178680419922 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.02967071533203125 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.0316777229309082 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.0284578800201416 seconds
Tree has no split, stopping training

[I 2026-04-22 21:32:17,199] Trial 18 finished with value: 0.9741978335945264 and parameters: {'exponent': 0.9708146529892162, 'kernel_type': 'kpq', 'bandwidth': 3.555861603704035, 'diag': False, 'norm_p': 1.408616300677552, 'reg': 0.0032843658712042654}. Best is trial 17 with value: 0.9821059724365634.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027064800262451172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027593135833740234 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028558731079101562 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0287172794342041 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02918267250061035 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026551246643066406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028221845626831055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027938127517700195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028788328170776367 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02875208854675293 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02598118782043457 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028290271759033203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027853012084960938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0281217098236084 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029141664505004883 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026572704315185547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02774190902709961 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02795886993408203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028411149978637695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027482032775878906 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026198863983154297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02732396125793457 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027757644653320312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02796339988708496 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02753901481628418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:18,099] Trial 19 finished with value: 0.9803987269562642 and parameters: {'exponent': 1.163979856528721, 'kernel_type': 'kpq', 'bandwidth': 1.0098463142441405, 'diag': True, 'norm_p': 1.5650831883700949, 'reg': 0.002917795100582671}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025417566299438477 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028730154037475586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028125762939453125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027742385864257812 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027271747589111328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02528548240661621 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027532339096069336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027426481246948242 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0274813175201416 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027005910873413086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025532007217407227 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027915477752685547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028529644012451172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03163433074951172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028623342514038086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026467323303222656 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02812814712524414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028151273727416992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028045654296875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028012990951538086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026502609252929688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027941465377807617 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028481721878051758 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027884483337402344 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029253482818603516 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:18,963] Trial 20 finished with value: 0.9743541401516321 and parameters: {'exponent': 1.1141683901051114, 'kernel_type': 'kpq', 'bandwidth': 3.708320038930782, 'diag': True, 'norm_p': 1.3227776113981082, 'reg': 0.01536261703121169}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026611804962158203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029302120208740234 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02861809730529785 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0280001163482666 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029008865356445312 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025888681411743164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02872157096862793 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028258800506591797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028320789337158203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028354406356811523 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02593541145324707 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028307199478149414 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02960062026977539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.031150341033935547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028116226196289062 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026393890380859375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028776168823242188 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027706384658813477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027756214141845703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.0281217098236084 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0264129638671875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0282437801361084 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027909040451049805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027540922164916992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02865123748779297 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:19,837] Trial 21 finished with value: 0.9803593663953414 and parameters: {'exponent': 0.9955947061430138, 'kernel_type': 'kpq', 'bandwidth': 1.6462171744320533, 'diag': True, 'norm_p': 1.0841918489944795, 'reg': 0.0002565693125237326}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02588200569152832 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02803349494934082 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027506113052368164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027898550033569336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027335643768310547 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026065349578857422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02934432029724121 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028299570083618164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0283353328704834 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.028334379196166992 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02600884437561035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02852320671081543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028450727462768555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028296470642089844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027838706970214844 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02603745460510254 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02768874168395996 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02794337272644043 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02821636199951172 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027641773223876953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027101516723632812 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028016090393066406 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028427839279174805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02828836441040039 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:20,698] Trial 22 finished with value: 0.9821059724365634 and parameters: {'exponent': 0.9452112855311287, 'kernel_type': 'kpq', 'bandwidth': 1.0481925690269016, 'diag': True, 'norm_p': 1.0656946390841509, 'reg': 0.000722389508698302}. Best is trial 17 with value: 0.9821059724365634.

Optimal M batch size: 1351
Time taken for round 4: 0.02788257598876953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026802778244018555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028004884719848633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029221773147583008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027573823928833008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027785062789916992 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025355100631713867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027921199798583984 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0275418758392334 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027985572814941406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02804255485534668 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026517391204833984 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02859663963317871 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02895975112915039 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02857208251953125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02909064292907715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02635049819946289 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029039382934570312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027173995971679688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027517318725585938 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027934789657592773 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026076793670654297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027582406997680664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027540922164916992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027851104736328125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02757859230041504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:21,563] Trial 23 finished with value: 0.980960930868091 and parameters: {'exponent': 0.9463254527955385, 'kernel_type': 'kpq', 'bandwidth': 2.3711620253074983, 'diag': True, 'norm_p': 1.0822018121495882, 'reg': 5.844631827877643e-05}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026433706283569336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028823137283325195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028136253356933594 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027706384658813477 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028241872787475586 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025699377059936523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028281450271606445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02825188636779785 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027263402938842773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027826309204101562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025969743728637695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028375864028930664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027594327926635742 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028033018112182617 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02847576141357422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02633213996887207 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029721975326538086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027856826782226562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02791738510131836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028390884399414062 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026452302932739258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028844833374023438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028557777404785156 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02781963348388672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02741265296936035 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training

[I 2026-04-22 21:32:22,436] Trial 24 finished with value: 0.979068079485567 and parameters: {'exponent': 1.098397704855643, 'kernel_type': 'kpq', 'bandwidth': 1.5275191488275135, 'diag': True, 'norm_p': 1.1890689408483481, 'reg': 0.00925729020757241}. Best is trial 17 with value: 0.9821059724365634.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025310277938842773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02743983268737793 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02756977081298828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027297496795654297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027817964553833008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025632619857788086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02790212631225586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027893781661987305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027956247329711914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027830839157104492 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026057720184326172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02745795249938965 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027336835861206055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02753591537475586 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02684640884399414 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026579618453979492 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027903318405151367 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027268409729003906 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02714252471923828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026892662048339844 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025881290435791016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028149843215942383 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02782893180847168 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027970552444458008 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027324438095092773 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:23,290] Trial 25 finished with value: 0.9803261435451738 and parameters: {'exponent': 0.8128259610303348, 'kernel_type': 'kpq', 'bandwidth': 1.0057988699290599, 'diag': True, 'norm_p': 0.992386750251148, 'reg': 0.0010295057999580592}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027320384979248047 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02843952178955078 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.02892923355102539 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02790546417236328 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.027529001235961914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.026983022689819336 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.028171539306640625 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.02791595458984375 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02673506736755371 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.02700972557067871 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02718353271484375 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.027228593826293945 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.02706742286682129 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02797985076904297 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.027456045150756836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.029639244079589844 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.02791309356689453 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.028166770935058594 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.02745962142944336 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.02799057960510254 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02684807777404785 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.027868032455444336 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.02903151512145996 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.027798175811767578 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.026801347732543945 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:24,154] Trial 26 finished with value: 0.9709965859774934 and parameters: {'exponent': 0.9572706397501937, 'kernel_type': 'kpq', 'bandwidth': 3.331751542686887, 'diag': False, 'norm_p': 1.1388575214024865, 'reg': 0.07893593130162314}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025855064392089844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027839183807373047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026945114135742188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027486801147460938 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027254104614257812 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024834156036376953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027022838592529297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02725362777709961 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026464462280273438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027222871780395508 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0254971981048584 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029401540756225586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028163671493530273 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027550220489501953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027463197708129883 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025599002838134766 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.04036688804626465 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02659010887145996 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026859045028686523 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027073383331298828 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025874853134155273 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02828359603881836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027341127395629883 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02715468406677246 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:25,024] Trial 27 finished with value: 0.9803489529755947 and parameters: {'exponent': 1.063365754481832, 'kernel_type': 'kpq', 'bandwidth': 2.22647845064629, 'diag': True, 'norm_p': 1.3059667178711334, 'reg': 4.162701430474401e-05}. Best is trial 17 with value: 0.9821059724365634.

Time taken for round 4: 0.027200698852539062 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02489328384399414 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027059078216552734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027065753936767578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026920318603515625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028368711471557617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026384592056274414 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026260852813720703 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027354955673217773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02695918083190918 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026723146438598633 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025227069854736328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027595996856689453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0278928279876709 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02834296226501465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02715134620666504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026346206665039062 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02727651596069336 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026596546173095703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026770353317260742 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02709817886352539 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025585412979125977 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.031769752502441406 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026790142059326172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02675008773803711 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:25,856] Trial 28 finished with value: 0.9808169692209825 and parameters: {'exponent': 0.9225647283444507, 'kernel_type': 'kpq', 'bandwidth': 5.201116795492754, 'diag': True, 'norm_p': 1.0394659500744463, 'reg': 3.952640349338157e-06}. Best is trial 17 with value: 0.9821059724365634.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026421546936035156 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007265329360961914 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.01227116584777832 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008285999298095703 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008336544036865234 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.00782322883605957 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00817728042602539 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.007860183715820312 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.007402181625366211 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.007413625717163086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.007976293563842773 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.009936809539794922 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.011130571365356445 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 2: 0.010255575180053711 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008204936981201172 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.007368326187133789 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009320735931396484 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.008543252944946289 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008089542388916016 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.007898092269897461 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.008587837219238281 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009131669998168945 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.009032964706420898 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008887290954589844 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008535623550415039 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.008967876434326172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:26,182] Trial 29 finished with value: 0.9790628024278607 and parameters: {'exponent': 1.0205367663330467, 'kernel_type': 'k2q', 'bandwidth': 1.566535565299047, 'diag': True, 'reg': 0.0011667212141186658}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02480292320251465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026725292205810547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02618694305419922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02628779411315918 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026427745819091797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024497032165527344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0285189151763916 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025942087173461914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025448083877563477 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025721311569213867 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024976253509521484 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026685714721679688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02636265754699707 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02579641342163086 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0256192684173584 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0247344970703125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02705526351928711 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026787519454956055 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027290821075439453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026499271392822266 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02542424201965332 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026669740676879883 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02855825424194336 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02671027183532715 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026555538177490234 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:27,005] Trial 30 finished with value: 0.9767215138933821 and parameters: {'exponent': 0.7956078547448568, 'kernel_type': 'kpq', 'bandwidth': 9.797954897278112, 'diag': True, 'norm_p': 0.8499280400263098, 'reg': 0.006729343976935801}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024870634078979492 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026256561279296875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02664351463317871 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026282072067260742 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02675485610961914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025855541229248047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02959132194519043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027851104736328125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02730560302734375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0262758731842041 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025126934051513672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027034282684326172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02601027488708496 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026360511779785156 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026706933975219727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025157451629638672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026627302169799805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026941299438476562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026472806930541992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02596449851989746 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024989604949951172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027243375778198242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026427745819091797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027172088623046875 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:27,841] Trial 31 finished with value: 0.9808769421513306 and parameters: {'exponent': 0.8718838339729432, 'kernel_type': 'kpq', 'bandwidth': 1.0371121148982403, 'diag': True, 'norm_p': 0.9110001931423661, 'reg': 0.00038380613539701905}. Best is trial 17 with value: 0.9821059724365634.

Time taken for round 4: 0.029963016510009766 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02644634246826172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.031373023986816406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02731180191040039 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027228593826293945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027294635772705078 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025166749954223633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027350902557373047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027170658111572266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027066469192504883 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026372671127319336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02569580078125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027451753616333008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02676224708557129 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028174877166748047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026776790618896484 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025021076202392578 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027452468872070312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02671337127685547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02658700942993164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026570796966552734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026095151901245117 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026936769485473633 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02748250961303711 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02863621711730957 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026749134063720703 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:28,687] Trial 32 finished with value: 0.9808780946125888 and parameters: {'exponent': 0.8429321638383813, 'kernel_type': 'kpq', 'bandwidth': 1.389773582941272, 'diag': True, 'norm_p': 1.0048241807223932, 'reg': 0.00042481280802970933}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025134563446044922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026180744171142578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02652263641357422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0261685848236084 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026628971099853516 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0249478816986084 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027353763580322266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026978015899658203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02614307403564453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025933504104614258 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025404930114746094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02739858627319336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025707244873046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026333093643188477 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026587486267089844 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025026321411132812 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02647233009338379 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026258468627929688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026540279388427734 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.0265195369720459 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02521681785583496 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026233673095703125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026928424835205078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02655339241027832 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026228904724121094 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:29,509] Trial 33 finished with value: 0.9815859545961537 and parameters: {'exponent': 0.7962265199191708, 'kernel_type': 'kpq', 'bandwidth': 2.0878417233995643, 'diag': True, 'norm_p': 0.8334624067691139, 'reg': 0.001859548966356214}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025199174880981445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026350975036621094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027078628540039062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025835752487182617 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026184558868408203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027918338775634766 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027491331100463867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026870250701904297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0264739990234375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025890827178955078 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025592565536499023 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026419639587402344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026643037796020508 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026776790618896484 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026732206344604492 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025132179260253906 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02646350860595703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027355432510375977 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026070356369018555 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02673625946044922 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025998592376708984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026604652404785156 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027150630950927734 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02703380584716797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026520967483520508 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:30,342] Trial 34 finished with value: 0.9803331960070348 and parameters: {'exponent': 0.7027103053000602, 'kernel_type': 'kpq', 'bandwidth': 2.1649879065460134, 'diag': True, 'norm_p': 0.8038887612402243, 'reg': 0.0014846581837218834}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025986433029174805 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02675485610961914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0264739990234375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02627086639404297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02682352066040039 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025391340255737305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026427030563354492 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02650284767150879 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02678060531616211 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026931047439575195 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025361061096191406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027712106704711914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02637028694152832 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02688431739807129 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026525497436523438 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025640487670898438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028306245803833008 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028496980667114258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027363061904907227 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026941299438476562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.029287338256835938 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028136014938354492 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02842235565185547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028162002563476562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028517484664916992 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:31,191] Trial 35 finished with value: 0.9803619069118076 and parameters: {'exponent': 0.7908786327068559, 'kernel_type': 'kpq', 'bandwidth': 1.8579357580458107, 'diag': True, 'norm_p': 1.1566412162515805, 'reg': 0.004921234594834216}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.012123346328735352 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.012002944946289062 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009461164474487305 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.009055137634277344 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008147239685058594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.008876800537109375 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.00977325439453125 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008277416229248047 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008650779724121094 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.00820159912109375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.008087873458862305 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.00882863998413086 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009112119674682617 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.007752418518066406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.007942914962768555 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009997367858886719 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.00963592529296875 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.009003877639770508 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008791685104370117 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.00809621810913086 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.011398553848266602 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.012592554092407227 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010105371475219727 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.010226964950561523 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:31,546] Trial 36 finished with value: 0.9802347291600336 and parameters: {'exponent': 0.9788726028916512, 'kernel_type': 'k2q', 'bandwidth': 4.749647647230191, 'diag': True, 'reg': 0.02672249728218897}. Best is trial 17 with value: 0.9821059724365634.

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.00969243049621582 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02595973014831543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027812719345092773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028415679931640625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027932405471801758 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027515411376953125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025466442108154297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029915571212768555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027926206588745117 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028872966766357422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027876853942871094 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024941205978393555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02714705467224121 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02665114402770996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027584075927734375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0273745059967041 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025893688201904297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02697467803955078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027133703231811523 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02736806869506836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028238534927368164 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027727127075195312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0280611515045166 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028626441955566406 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028702259063720703 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027756214141845703 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:32,401] Trial 37 finished with value: 0.9474818035771507 and parameters: {'exponent': 1.3773495138232177, 'kernel_type': 'kpq', 'bandwidth': 2.880253980498889, 'diag': True, 'norm_p': 1.4705507229110868, 'reg': 0.19703583216814413}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.026398897171020508 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.026923656463623047 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027332067489624023 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.028038501739501953 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.02779531478881836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027090072631835938 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.027567386627197266 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027315139770507812 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.026444673538208008 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.026837825775146484 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02656841278076172 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.028029203414916992 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027047157287597656 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 3: 0.02886176109313965 seconds
Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02557682991027832 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.027341365814208984 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.026947736740112305 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.028080463409423828 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.02722620964050293 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.029381275177001953 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.027686119079589844 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.027246713638305664 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.027801513671875 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.027844905853271484 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:33,239] Trial 38 finished with value: 0.9637027924525541 and parameters: {'exponent': 0.7123740568022313, 'kernel_type': 'kpq', 'bandwidth': 1.3910823876712615, 'diag': False, 'norm_p': 0.7187782073128596, 'reg': 0.0022695907045556466}. Best is trial 17 with value: 0.9821059724365634.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00859689712524414 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008893966674804688 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 2: 0.008749723434448242 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0076143741607666016 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0083160400390625 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00887441635131836 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008555173873901367 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008419513702392578 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008391380310058594 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0081329345703125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.009929656982421875 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.009080648422241211 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008104801177978516 seconds
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 3: 0.007948875427246094 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.007320404052734375 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.010661602020263672 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.009728193283081055 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008126020431518555 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008765697479248047 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.00867462158203125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.008991003036499023 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.009253263473510742 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:33,584] Trial 39 finished with value: 0.9790769154241715 and parameters: {'exponent': 0.9391042232284783, 'kernel_type': 'k2q', 'bandwidth': 65.19968121835262, 'diag': True, 'reg': 0.00015440503876282}. Best is trial 17 with value: 0.9821059724365634.

Optimal M batch size: 1351
Time taken for round 2: 0.008286714553833008 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008109807968139648 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.008665800094604492 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025983095169067383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028358936309814453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02793264389038086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026694059371948242 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027857065200805664 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024947404861450195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02651524543762207 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026665687561035156 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02689981460571289 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026786088943481445 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024951457977294922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026591062545776367 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02687549591064453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02690577507019043 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027200937271118164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026288986206054688 seconds
Early stopping at iteration 3

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024797439575195312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027112960815429688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026671171188354492 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:34,250] Trial 40 finished with value: 0.8752723825236315 and parameters: {'exponent': 0.7672230227102806, 'kernel_type': 'kpq', 'bandwidth': 196.97609356801615, 'diag': True, 'norm_p': 1.0393934909299407, 'reg': 0.2845364916742331}. Best is trial 17 with value: 0.9821059724365634.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024741649627685547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02812671661376953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026484966278076172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027759552001953125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026484251022338867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025185108184814453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026294231414794922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02648305892944336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02658867835998535 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02663707733154297 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024486541748046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026600122451782227 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02630329132080078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026703834533691406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026521921157836914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025224924087524414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026599884033203125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027077913284301758 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026834487915039062 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026601791381835938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024767160415649414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026671171188354492 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026662826538085938 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026376008987426758 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:35,083] Trial 41 finished with value: 0.9808780946125888 and parameters: {'exponent': 0.8530527923773552, 'kernel_type': 'kpq', 'bandwidth': 1.1849553329950488, 'diag': True, 'norm_p': 0.9421672332398086, 'reg': 0.000578072164803105}. Best is trial 17 with value: 0.9821059724365634.

Time taken for round 4: 0.026047706604003906 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026383638381958008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027912139892578125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02787470817565918 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027433395385742188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02690720558166504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025078535079956055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027085542678833008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026212453842163086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027053117752075195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0268857479095459 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024494647979736328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02878880500793457 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02686333656311035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027142763137817383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027198314666748047 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025632619857788086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03526496887207031 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027358055114746094 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026857614517211914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02801823616027832 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026183366775512695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026756763458251953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027604341506958008 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02709674835205078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.0270845890045166 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:35,932] Trial 42 finished with value: 0.9796904766345124 and parameters: {'exponent': 0.9091339659091978, 'kernel_type': 'kpq', 'bandwidth': 19.6905991828451, 'diag': True, 'norm_p': 1.2440572684045492, 'reg': 0.0018531945463206923}. Best is trial 17 with value: 0.9821059724365634.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025756120681762695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027954578399658203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027655363082885742 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027320384979248047 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026569366455078125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025528907775878906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027559757232666016 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027428865432739258 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027602434158325195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026698827743530273 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025186538696289062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02689957618713379 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02664017677307129 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02750563621520996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029928922653198242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02656841278076172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0278017520904541 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02816295623779297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027370929718017578 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028501510620117188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025443077087402344 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027419328689575195 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0276796817779541 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029049396514892578 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027082443237304688 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:36,792] Trial 43 finished with value: 0.9821941233169648 and parameters: {'exponent': 0.8266944178149827, 'kernel_type': 'kpq', 'bandwidth': 1.8169724544596653, 'diag': True, 'norm_p': 0.8739867756221869, 'reg': 5.7741155858099045e-05}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025353193283081055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026817798614501953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027882099151611328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02760004997253418 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02774357795715332 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026456832885742188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027165651321411133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026398658752441406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026723861694335938 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026322364807128906 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025080442428588867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02687549591064453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026637554168701172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026866912841796875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026595592498779297 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025004148483276367 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0273439884185791 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02708268165588379 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026732444763183594 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026663780212402344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025653839111328125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027300119400024414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02644634246826172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02830791473388672 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:37,634] Trial 44 finished with value: 0.9803784304283024 and parameters: {'exponent': 0.7361351773121622, 'kernel_type': 'kpq', 'bandwidth': 2.570809938227492, 'diag': True, 'norm_p': 0.8165738537213418, 'reg': 6.0002466630345847e-05}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026745319366455078 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.009068489074707031 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.009478569030761719 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009375572204589844 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008689641952514648 seconds
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.008953332901000977 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.010651350021362305 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008901596069335938 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.00970005989074707 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.00811910629272461 seconds
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.008660554885864258 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007408857345581055 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008293390274047852 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008204460144042969 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.00811147689819336 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008746862411499023 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009536504745483398 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.009226322174072266 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.00912928581237793 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.009026288986206055 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.008977651596069336 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.008902311325073242 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.008890867233276367 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008861303329467773 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008785009384155273 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:37,977] Trial 45 finished with value: 0.9790628024278607 and parameters: {'exponent': 1.0559993880640202, 'kernel_type': 'k2q', 'bandwidth': 1.8872620095927295, 'diag': True, 'reg': 7.267912682921559e-06}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.008829355239868164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.025962114334106445 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.028057575225830078 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027216196060180664 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02752542495727539 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.02928924560546875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.026408672332763672 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.027891159057617188 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.028359651565551758 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.027208805084228516 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.027640581130981445 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.026021718978881836 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029989242553710938 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.027280807495117188 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02718329429626465 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.10351419448852539 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.026045799255371094 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.028026342391967773 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 2: 0.027554750442504883 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.02800726890563965 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.02784419059753418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.027679920196533203 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.027892589569091797 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.027712583541870117 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:38,918] Trial 46 finished with value: 0.9567959986143585 and parameters: {'exponent': 0.8859485407793423, 'kernel_type': 'kpq', 'bandwidth': 1.6928177664937494, 'diag': False, 'norm_p': 1.0349668027849925, 'reg': 1.9755159660906576e-06}. Best is trial 43 with value: 0.9821941233169648.

Using SVD
Time taken for round 3: 0.028528928756713867 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.02843785285949707 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02544689178466797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028432369232177734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027564048767089844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027270078659057617 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02621316909790039 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024965763092041016 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026452064514160156 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027790069580078125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026693344116210938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026513099670410156 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025484800338745117 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028148651123046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02677178382873535 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02688288688659668 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02628302574157715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025870084762573242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026800155639648438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02734375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027558088302612305 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026921749114990234 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0250551700592041 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027122020721435547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02709364891052246 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028448104858398438 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:39,757] Trial 47 finished with value: 0.9779229766723674 and parameters: {'exponent': 0.821588960912689, 'kernel_type': 'kpq', 'bandwidth': 114.87540337152656, 'diag': True, 'norm_p': 0.8750952210507881, 'reg': 5.231994623771427e-06}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02608966827392578 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02550220489501953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027027606964111328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027007341384887695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028497695922851562 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.02775859832763672 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02538776397705078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027698278427124023 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028010845184326172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028003692626953125 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026946306228637695 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02536177635192871 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02785968780517578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02736806869506836 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02764439582824707 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029315471649169922 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027587413787841797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02980780601501465 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029233694076538086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02924942970275879 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029476404190063477 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027678728103637695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029081106185913086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03165388107299805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029558181762695312 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:40,643] Trial 48 finished with value: 0.9808979302156133 and parameters: {'exponent': 0.7849836082958966, 'kernel_type': 'kpq', 'bandwidth': 1.3728470349124893, 'diag': True, 'norm_p': 1.125638154375733, 'reg': 2.712910251376398e-05}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.029430627822875977 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02783370018005371 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029291391372680664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029514551162719727 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029273271560668945 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029273509979248047 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02710127830505371 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029355287551879883 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02948927879333496 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02860283851623535 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02909111976623535 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.029839515686035156 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0305635929107666 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030418872833251953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029703378677368164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02905750274658203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028637409210205078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029148101806640625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029929637908935547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02936410903930664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029204845428466797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028048992156982422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03266119956970215 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030289649963378906 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.030489683151245117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:41,561] Trial 49 finished with value: 0.9799246158669591 and parameters: {'exponent': 0.9941614304371769, 'kernel_type': 'kpq', 'bandwidth': 4.103093555618648, 'diag': True, 'norm_p': 1.792741124630234, 'reg': 0.00020192260177605135}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.031021595001220703 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.010820150375366211 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.010008811950683594 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.00957489013671875 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.009993791580200195 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.009516477584838867 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.009613037109375 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.009982824325561523 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.00966954231262207 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.009756803512573242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.010129928588867188 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.009822368621826172 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.010291099548339844 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.009412765502929688 seconds
Using cheap batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.009529352188110352 seconds
Using cheap batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.009089231491088867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.010758161544799805 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.012022256851196289 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.012124776840209961 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.011614561080932617 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.011369466781616211 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.01231074333190918 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.011347532272338867 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.010089635848999023 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:41,948] Trial 50 finished with value: 0.9763525761708417 and parameters: {'exponent': 0.8729879230784844, 'kernel_type': 'k2q', 'bandwidth': 7.223026518577413, 'diag': False, 'reg': 1.0106002243093958e-06}. Best is trial 43 with value: 0.9821941233169648.

Using SVD
Time taken for round 3: 0.011276960372924805 seconds
Using cheap batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.009962081909179688 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02738475799560547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0304110050201416 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03083658218383789 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029868602752685547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029595375061035156 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02758646011352539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.031110286712646484 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03145265579223633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029884815216064453 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.029849767684936523 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027570486068725586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030005693435668945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029006004333496094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0300140380859375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029821157455444336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028220415115356445 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03116440773010254 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029393911361694336 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.03004932403564453 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02898693084716797 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027762174606323242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029328584671020508 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02940201759338379 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02893543243408203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029120445251464844 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:42,873] Trial 51 finished with value: 0.9808780946125888 and parameters: {'exponent': 0.8331438653009874, 'kernel_type': 'kpq', 'bandwidth': 1.2095826459777181, 'diag': True, 'norm_p': 0.933010727657553, 'reg': 0.0007031891972758148}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027170896530151367 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030345916748046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03110527992248535 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029289722442626953 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.030599594116210938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027399301528930664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02976393699645996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029210329055786133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028905391693115234 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02945995330810547 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02909398078918457 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.032999515533447266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030225038528442383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.030619382858276367 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.030182838439941406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02745509147644043 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03018784523010254 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029224634170532227 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02867889404296875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029184818267822266 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027737855911254883 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029811859130859375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029595613479614258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 2.893765449523926 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.030295133590698242 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]
[I 2026-04-22 21:32:46,658] Trial 52 finished with value: 0.9797642616121068 and parameters: {'exponent': 0.9273460765610789, 'kernel_type': 'kpq', 'bandwidth': 1.0000412228817182, 'diag': True, 'norm_p': 0.9886025630432084, 'reg': 0.0003043221544954239}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027576208114624023 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029341459274291992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029089927673339844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028630495071411133 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029820680618286133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02737140655517578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02980494499206543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02960205078125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029687881469726562 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029438495635986328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027657032012939453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03263592720031738 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030007123947143555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03052997589111328 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.029457569122314453 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028496980667114258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03042769432067871 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030880212783813477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029215335845947266 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028925180435180664 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02831125259399414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.030005455017089844 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.032126426696777344 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029309749603271484 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:47,586] Trial 53 finished with value: 0.9803020856048885 and parameters: {'exponent': 0.7635763493555359, 'kernel_type': 'kpq', 'bandwidth': 2.924218538029834, 'diag': True, 'norm_p': 0.7967735687121766, 'reg': 0.003995809495117461}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.029381513595581055 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027378082275390625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029884815216064453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029050588607788086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029980897903442383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.030894994735717773 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027340173721313477 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029199600219726562 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02862071990966797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02917623519897461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028037071228027344 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027107715606689453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03338050842285156 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028863191604614258 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02843952178955078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028969287872314453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027739524841308594 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02975749969482422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028928756713867188 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02936697006225586 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028944969177246094 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027646541595458984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029105186462402344 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029096603393554688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029836416244506836 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:48,497] Trial 54 finished with value: 0.9796625714641192 and parameters: {'exponent': 0.903011391853643, 'kernel_type': 'kpq', 'bandwidth': 2.04805633713928, 'diag': True, 'norm_p': 0.9724817298690538, 'reg': 0.014476151639172319}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.0295255184173584 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027906417846679688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030492067337036133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029987335205078125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028470277786254883 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02890324592590332 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027841567993164062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028965473175048828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028562307357788086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028771400451660156 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.028690576553344727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027831554412841797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029215097427368164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029308795928955078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02899312973022461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029431819915771484 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.03515791893005371 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.08364629745483398 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030375242233276367 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02895522117614746 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029463768005371094 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027858734130859375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03252124786376953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028547286987304688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02958846092224121 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028968095779418945 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:49,469] Trial 55 finished with value: 0.9809524518252373 and parameters: {'exponent': 0.842369617734987, 'kernel_type': 'kpq', 'bandwidth': 1.3602541395158494, 'diag': True, 'norm_p': 0.9035237956324722, 'reg': 0.0007487428564632267}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027788400650024414 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028900623321533203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02861499786376953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028608083724975586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02875685691833496 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02747964859008789 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0315403938293457 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029616832733154297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029429912567138672 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0286710262298584 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027401447296142578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029801368713378906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02875542640686035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02931809425354004 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0289766788482666 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027502059936523438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029651165008544922 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029295921325683594 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02902078628540039 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028868675231933594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027695655822753906 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02951836585998535 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02989959716796875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02953028678894043 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:50,376] Trial 56 finished with value: 0.9809524518252373 and parameters: {'exponent': 0.8090599594209734, 'kernel_type': 'kpq', 'bandwidth': 1.2458180003974675, 'diag': True, 'norm_p': 0.8666961448990775, 'reg': 6.063900789398258e-05}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.02916741371154785 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028562545776367188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03025221824645996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029471397399902344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02942657470703125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02927374839782715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027387619018554688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029702425003051758 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029756546020507812 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02941131591796875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02895355224609375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027804851531982422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029815673828125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029639244079589844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029704809188842773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029625654220581055 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027327775955200195 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02971172332763672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.032627105712890625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.03065967559814453 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02892613410949707 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02820611000061035 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029662370681762695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.07337522506713867 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02953815460205078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02886819839477539 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:51,345] Trial 57 finished with value: 0.9797852372190301 and parameters: {'exponent': 1.0132202606106984, 'kernel_type': 'kpq', 'bandwidth': 1.698428345732827, 'diag': True, 'norm_p': 1.0679200356332068, 'reg': 0.00013982845767944173}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027235031127929688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029345035552978516 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028792381286621094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0287172794342041 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.03005051612854004 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027651548385620117 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029738187789916992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02892923355102539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029602766036987305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028554677963256836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027191638946533203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029096364974975586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.032689809799194336 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 3: 0.030243873596191406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02924823760986328 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027635812759399414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03025507926940918 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030125856399536133 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029393434524536133 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029597043991088867 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028185367584228516 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.030003786087036133 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03094625473022461 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029702425003051758 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02992987632751465 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 21:32:52,263] Trial 58 finished with value: 0.9815143119940295 and parameters: {'exponent': 0.8611837759429406, 'kernel_type': 'kpq', 'bandwidth': 2.464649986226399, 'diag': True, 'norm_p': 1.1982804186375744, 'reg': 9.182703282640517e-05}. Best is trial 43 with value: 0.9821941233169648.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02815556526184082 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030158042907714844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029561996459960938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029755830764770508 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029499053955078125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027434587478637695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029564380645751953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028751373291015625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028564929962158203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02900099754333496 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027155637741088867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029805660247802734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028702735900878906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02941274642944336 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02940988540649414 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02910017967224121 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.030205965042114258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029909372329711914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029309988021850586 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02904033660888672 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02783799171447754 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029409170150756836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.030565500259399414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02994513511657715 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029020309448242188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:53,174] Trial 59 finished with value: 0.9808251624053111 and parameters: {'exponent': 0.9553688668522943, 'kernel_type': 'kpq', 'bandwidth': 2.499169350816661, 'diag': True, 'norm_p': 1.1717456478205674, 'reg': 8.2489459252116e-05}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02916431427001953 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029499292373657227 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.029020309448242188 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.049828529357910156 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.028685331344604492 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.027919769287109375 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029437541961669922 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.028870582580566406 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029798269271850586 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.029105663299560547 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.028823137283325195 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.029743194580078125 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.029177188873291016 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.029254436492919922 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.028771162033081055 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02971172332763672 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.02914881706237793 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.03482341766357422 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.02962803840637207 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.029375314712524414 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.029558181762695312 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.029742717742919922 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.02875375747680664 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.029315471649169922 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.0291593074798584 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:54,109] Trial 60 finished with value: 0.9702040368105666 and parameters: {'exponent': 1.2441068803248136, 'kernel_type': 'kpq', 'bandwidth': 3.2418117708822414, 'diag': False, 'norm_p': 1.2801115305122337, 'reg': 1.1410595190195492e-05}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028783559799194336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030499696731567383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.030046939849853516 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02909541130065918 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.029097795486450195 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02799701690673828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02858734130859375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029551982879638672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0285336971282959 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02978348731994629 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027085542678833008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02948164939880371 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029573678970336914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028746843338012695 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.028676986694335938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027718067169189453 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028765439987182617 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028775453567504883 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028670310974121094 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.0287630558013916 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027118444442749023 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03490185737609863 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029378414154052734 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028938770294189453 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029634714126586914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:55,021] Trial 61 finished with value: 0.9809422648484736 and parameters: {'exponent': 0.8648896628768473, 'kernel_type': 'kpq', 'bandwidth': 1.1568260449155643, 'diag': True, 'norm_p': 1.2153932604336652, 'reg': 2.4969162169926882e-05}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0273287296295166 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029240131378173828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029632568359375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02972555160522461 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.030460596084594727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02742481231689453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029047727584838867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02981853485107422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.03104257583618164 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.03626751899719238 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02761530876159668 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029184341430664062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028977632522583008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028825998306274414 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029509305953979492 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027709484100341797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029228687286376953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0295562744140625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029034852981567383 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.032952070236206055 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.029613018035888672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029789447784423828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029314517974853516 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.029778242111206055 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:55,942] Trial 62 finished with value: 0.9808979302156133 and parameters: {'exponent': 0.7799589105245099, 'kernel_type': 'kpq', 'bandwidth': 1.9955127616714745, 'diag': True, 'norm_p': 1.1005076580107314, 'reg': 0.0012407222950456978}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.02997756004333496 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028115034103393555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0294339656829834 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029221534729003906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028984785079956055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029587745666503906 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027423620223999023 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0294802188873291 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.03006911277770996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.031130075454711914 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.02946186065673828 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02841639518737793 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02948784828186035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02892923355102539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028823375701904297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029088258743286133 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.028475284576416016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029911041259765625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.029672861099243164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028499364852905273 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028443336486816406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02735304832458496 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029179096221923828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028658390045166016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028710603713989258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02861332893371582 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:56,851] Trial 63 finished with value: 0.9815859545961537 and parameters: {'exponent': 0.7436227176171468, 'kernel_type': 'kpq', 'bandwidth': 1.5855203021303577, 'diag': True, 'norm_p': 0.7712750884361098, 'reg': 0.00023172280183889773}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.027730941772460938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028419971466064453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02855205535888672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028742313385009766 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028653621673583984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02707195281982422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029244184494018555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028476476669311523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027949810028076172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02867579460144043 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02784442901611328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.030339717864990234 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028567790985107422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028899431228637695 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.028721094131469727 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0280153751373291 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028794527053833008 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028315305709838867 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028285980224609375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027944087982177734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026971817016601562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028688907623291016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03308844566345215 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028942108154296875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02776169776916504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:57,762] Trial 64 finished with value: 0.9821189385376297 and parameters: {'exponent': 0.7388099448219942, 'kernel_type': 'kpq', 'bandwidth': 1.528162711283539, 'diag': True, 'norm_p': 0.7396728607154374, 'reg': 9.481283702924168e-05}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02687811851501465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029573917388916016 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028959035873413086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0293576717376709 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028893709182739258 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.029427766799926758 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028557300567626953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029049396514892578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.029775619506835938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02847599983215332 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026364803314208984 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02896904945373535 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028928518295288086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02825474739074707 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028926849365234375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02756214141845703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028546571731567383 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028458118438720703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028444290161132812 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.03345298767089844 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027055740356445312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029010534286499023 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028755903244018555 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02899765968322754 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.028450727462768555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:58,662] Trial 65 finished with value: 0.9821756458125694 and parameters: {'exponent': 0.7315502033943473, 'kernel_type': 'kpq', 'bandwidth': 1.571637320466541, 'diag': True, 'norm_p': 0.7780070508770118, 'reg': 0.0004523238917643428}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028783082962036133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029366016387939453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029651165008544922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028794050216674805 seconds
Using expensive batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Optimal M batch size: 1350
Time taken for round 4: 0.02861475944519043 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028052806854248047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02867579460144043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028534412384033203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02886819839477539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02864551544189453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026762962341308594 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029256105422973633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028759479522705078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.033449649810791016 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.029187440872192383 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027490615844726562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02887701988220215 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02858448028564453 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028014183044433594 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02907276153564453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027329206466674805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.04151725769042969 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.028977632522583008 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.028972148895263672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.029081344604492188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:32:59,579] Trial 66 finished with value: 0.9815859545961537 and parameters: {'exponent': 0.7238277703006872, 'kernel_type': 'kpq', 'bandwidth': 1.6050226102624132, 'diag': True, 'norm_p': 0.7571667911599139, 'reg': 0.00019258686188549368}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028199195861816406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02969646453857422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.029331207275390625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02749800682067871 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026955366134643555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02443408966064453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027139902114868164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026755332946777344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027258872985839844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02664637565612793 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025277137756347656 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027739763259887695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026203632354736328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026584625244140625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027335166931152344 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02758622169494629 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028931140899658203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02853703498840332 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027098655700683594 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02767491340637207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025713205337524414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028190135955810547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02685379981994629 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026395559310913086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02715134620666504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:00,438] Trial 67 finished with value: 0.9765827575565172 and parameters: {'exponent': 0.7465694733399295, 'kernel_type': 'kpq', 'bandwidth': 16.156376550228668, 'diag': True, 'norm_p': 0.7686053019063982, 'reg': 0.00045169312033681026}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02500629425048828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02813577651977539 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026679277420043945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02630758285522461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02666759490966797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024903535842895508 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027197599411010742 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027166366577148438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02668166160583496 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026566505432128906 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02476954460144043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027347326278686523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026754140853881836 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026860952377319336 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026276588439941406 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025091171264648438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02585124969482422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.025704145431518555 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02662491798400879 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.025326013565063477 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026012182235717773 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.028844833374023438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026270151138305664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026467323303222656 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:01,271] Trial 68 finished with value: 0.9821189385376297 and parameters: {'exponent': 0.7295458909290992, 'kernel_type': 'kpq', 'bandwidth': 1.518772433698576, 'diag': True, 'norm_p': 0.7346533648083821, 'reg': 3.9076920874802434e-05}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026429414749145508 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.00801539421081543 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008248329162597656 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.007711887359619141 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.007961034774780273 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008010387420654297 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007842779159545898 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008190155029296875 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.00916600227355957 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008076906204223633 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008361101150512695 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.008043050765991211 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008747100830078125 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008523225784301758 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008215904235839844 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.00796198844909668 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.012743949890136719 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.011845588684082031 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.010404586791992188 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.009323358535766602 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.008183717727661133 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.008533954620361328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:01,605] Trial 69 finished with value: 0.9791452056230522 and parameters: {'exponent': 0.729300976101627, 'kernel_type': 'k2q', 'bandwidth': 4.321032898504594, 'diag': True, 'reg': 3.48107419884702e-05}. Best is trial 43 with value: 0.9821941233169648.

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.009817123413085938 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008748769760131836 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.007733345031738281 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.009293079376220703 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025368690490722656 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027397871017456055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027189254760742188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026322126388549805 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026215314865112305 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02457594871520996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026895523071289062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02607250213623047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026314258575439453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026376962661743164 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024680614471435547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02704000473022461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0295259952545166 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02662038803100586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025950908660888672 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024936914443969727 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026573896408081055 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026154279708862305 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02573561668395996 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.025877714157104492 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025141000747680664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026765108108520508 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02723860740661621 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02669048309326172 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02622056007385254 seconds
Tree has no split, stopping training

[I 2026-04-22 21:33:02,431] Trial 70 finished with value: 0.9815997191308655 and parameters: {'exponent': 0.709988990552432, 'kernel_type': 'kpq', 'bandwidth': 2.2588872572133813, 'diag': True, 'norm_p': 0.7118928370781886, 'reg': 0.002824982563203573}. Best is trial 43 with value: 0.9821941233169648.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024588823318481445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.025791168212890625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026032209396362305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025493383407592773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0257718563079834 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024822711944580078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027289390563964844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0267484188079834 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026905536651611328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026425600051879883 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02504754066467285 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026709794998168945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026239871978759766 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026031970977783203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02666926383972168 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02498936653137207 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027271747589111328 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02679896354675293 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.03123331069946289 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026305675506591797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02549290657043457 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03308558464050293 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026671171188354492 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026807308197021484 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026424169540405273 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:03,260] Trial 71 finished with value: 0.9814491414555381 and parameters: {'exponent': 0.7051499696189282, 'kernel_type': 'kpq', 'bandwidth': 2.0453601443909744, 'diag': True, 'norm_p': 0.7338771857992135, 'reg': 0.002281663673555435}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025085926055908203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026867151260375977 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02678680419921875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026564359664916992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025532960891723633 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028444290161132812 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027364492416381836 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.047870635986328125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02702021598815918 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026558637619018555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025670766830444336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026801586151123047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02752065658569336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0273590087890625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026736736297607422 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02633357048034668 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02743816375732422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027618408203125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026209115982055664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02595996856689453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025360107421875 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02784109115600586 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02715325355529785 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027007102966308594 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:04,129] Trial 72 finished with value: 0.9821150220615982 and parameters: {'exponent': 0.7556751180883862, 'kernel_type': 'kpq', 'bandwidth': 1.4049123129694772, 'diag': True, 'norm_p': 0.8321440903203984, 'reg': 0.006187623961223199}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026404857635498047 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025460004806518555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028255224227905273 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.036347150802612305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02694225311279297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025751113891601562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025691986083984375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027755260467529297 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026604175567626953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026494979858398438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02613997459411621 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02496480941772461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026530742645263672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02602219581604004 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027143239974975586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02683091163635254 seconds
Tree has no split, stopping training

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02515411376953125 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027123689651489258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026925325393676758 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026254892349243164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.025852441787719727 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024997949600219727 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02725815773010254 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026955604553222656 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02765941619873047 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.025965213775634766 seconds
Tree has no split, stopping training

[I 2026-04-22 21:33:04,968] Trial 73 finished with value: 0.9814594489611619 and parameters: {'exponent': 0.7569781043483017, 'kernel_type': 'kpq', 'bandwidth': 1.4679077870690418, 'diag': True, 'norm_p': 0.8369348564959261, 'reg': 0.006956489588425111}. Best is trial 43 with value: 0.9821941233169648.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02529287338256836 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026653289794921875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02609729766845703 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026407241821289062 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02610301971435547 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024918079376220703 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02662038803100586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02681446075439453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028797149658203125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02744150161743164 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02536916732788086 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026651859283447266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02596139907836914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02605438232421875 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026094436645507812 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02540874481201172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02725696563720703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026747941970825195 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02674579620361328 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02707195281982422 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026489973068237305 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02862238883972168 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026688098907470703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02706003189086914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026137113571166992 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:05,791] Trial 74 finished with value: 0.9821609752682038 and parameters: {'exponent': 0.7175571201214775, 'kernel_type': 'kpq', 'bandwidth': 1.1265396677847317, 'diag': True, 'norm_p': 0.7447657553999092, 'reg': 0.012055011971333416}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02503204345703125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027095794677734375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02614307403564453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026283740997314453 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02609872817993164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02465963363647461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02633953094482422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02659010887145996 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026293277740478516 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027120590209960938 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02546977996826172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027143239974975586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026065587997436523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026027917861938477 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026389122009277344 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025704622268676758 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026619911193847656 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026590824127197266 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02602672576904297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027146100997924805 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02511310577392578 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026178598403930664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026499509811401367 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026409387588500977 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026569128036499023 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:06,610] Trial 75 finished with value: 0.9796613716405755 and parameters: {'exponent': 0.7711870163975013, 'kernel_type': 'kpq', 'bandwidth': 1.068318100569126, 'diag': True, 'norm_p': 0.8855982052391087, 'reg': 0.05610691534959503}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025058269500732422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02872443199157715 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0265500545501709 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026308298110961914 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026194334030151367 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025219202041625977 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026551008224487305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026207447052001953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026021242141723633 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02638697624206543 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025470972061157227 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02677440643310547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026126623153686523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026475191116333008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027039289474487305 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025482654571533203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026651620864868164 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026683568954467773 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026040315628051758 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026568174362182617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02692103385925293 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027091026306152344 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027402400970458984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02655792236328125 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:07,436] Trial 76 finished with value: 0.9820943745988451 and parameters: {'exponent': 0.7336653696609464, 'kernel_type': 'kpq', 'bandwidth': 1.2692424631992691, 'diag': True, 'norm_p': 0.7926299179363123, 'reg': 0.014187436622238658}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.02654743194580078 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025547504425048828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026134014129638672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0262603759765625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026566505432128906 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026278257369995117 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02879786491394043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027524948120117188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026653051376342773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02613544464111328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02628302574157715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02505040168762207 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02674388885498047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025903940200805664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026773691177368164 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026186704635620117 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02572488784790039 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.030725479125976562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026775836944580078 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.025673627853393555 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026015281677246094 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025559186935424805 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026530742645263672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026546716690063477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02712869644165039 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:08,261] Trial 77 finished with value: 0.9808648395668069 and parameters: {'exponent': 0.7567717160750553, 'kernel_type': 'kpq', 'bandwidth': 1.1052041950707625, 'diag': True, 'norm_p': 0.834864744340507, 'reg': 0.03591155322774874}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026987552642822266 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.026180267333984375 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02657794952392578 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.026180744171142578 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02635335922241211 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.026155948638916016 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.025602102279663086 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.027153968811035156 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.026880264282226562 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02577972412109375 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.026924848556518555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.0263826847076416 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.027466773986816406 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.025827407836914062 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.02644181251525879 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.026966094970703125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.026081562042236328 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.026411056518554688 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.026708126068115234 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.030238628387451172 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.026158571243286133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.025673627853393555 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.026673555374145508 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.02667832374572754 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.02634906768798828 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:09,095] Trial 78 finished with value: 0.9574999910657567 and parameters: {'exponent': 0.7228455641650606, 'kernel_type': 'kpq', 'bandwidth': 1.7812432986476854, 'diag': False, 'norm_p': 0.7593767291677591, 'reg': 0.00951528702647389}. Best is trial 43 with value: 0.9821941233169648.

Using SVD
Time taken for round 4: 0.02624964714050293 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02508711814880371 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026545047760009766 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026173830032348633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026932477951049805 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025591135025024414 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02503490447998047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02683234214782715 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02659916877746582 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025975465774536133 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02839350700378418 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024941682815551758 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02768111228942871 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025989055633544922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026424407958984375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026812314987182617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025490760803222656 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.029712915420532227 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02621626853942871 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02591991424560547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02614116668701172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025469541549682617 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026942729949951172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026364803314208984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02655482292175293 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.027132272720336914 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:09,933] Trial 79 finished with value: 0.9736864483651047 and parameters: {'exponent': 0.8122176872993543, 'kernel_type': 'kpq', 'bandwidth': 26.516940451478458, 'diag': True, 'norm_p': 0.8549535769688943, 'reg': 0.005115181772369159}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007977724075317383 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008754491806030273 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.007536649703979492 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.007727622985839844 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008010149002075195 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007355213165283203 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.007923364639282227 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008304834365844727 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008254766464233398 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008334636688232422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007894515991210938 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008036613464355469 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.01393747329711914 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.008565425872802734 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.009030818939208984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.00898432731628418 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.008719444274902344 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 2: 0.00888204574584961 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008512496948242188 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.007974863052368164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.00945734977722168 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.01073598861694336 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008193254470825195 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.008107185363769531 seconds
Using cheap batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:10,262] Trial 80 finished with value: 0.9790628024278607 and parameters: {'exponent': 1.0404107403895653, 'kernel_type': 'k2q', 'bandwidth': 1.4320263648146911, 'diag': True, 'reg': 1.5634625826588123e-05}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.008421659469604492 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02519702911376953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027073383331298828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027202367782592773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025839805603027344 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026349306106567383 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02620220184326172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027625083923339844 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027025938034057617 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.028337955474853516 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02992081642150879 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025681495666503906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02916431427001953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02711796760559082 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026648998260498047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02668476104736328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025419235229492188 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026912450790405273 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026761531829833984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.025787353515625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026546001434326172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025478601455688477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026909351348876953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026543617248535156 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027495622634887695 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026772499084472656 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:11,104] Trial 81 finished with value: 0.9820943745988451 and parameters: {'exponent': 0.7346152823173668, 'kernel_type': 'kpq', 'bandwidth': 1.2696679607592587, 'diag': True, 'norm_p': 0.7963376920069212, 'reg': 0.015391116130201552}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.028728246688842773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02812504768371582 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027539968490600586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026479244232177734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026462554931640625 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025542020797729492 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027220726013183594 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026598453521728516 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026580333709716797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026696443557739258 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025190353393554688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02715301513671875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026364564895629883 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026798486709594727 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026949644088745117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024978160858154297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027375221252441406 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026879549026489258 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026569128036499023 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02655792236328125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025367021560668945 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02658247947692871 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02698826789855957 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026415586471557617 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027517318725585938 seconds
Tree has no split, stopping training

[I 2026-04-22 21:33:11,947] Trial 82 finished with value: 0.9767015713734178 and parameters: {'exponent': 1.0808160682673857, 'kernel_type': 'kpq', 'bandwidth': 1.2874217721091705, 'diag': True, 'norm_p': 1.095867407481026, 'reg': 0.02166009405703599}. Best is trial 43 with value: 0.9821941233169648.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025043725967407227 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026620864868164062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025983095169067383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025979995727539062 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02600383758544922 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02493739128112793 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027060985565185547 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026087045669555664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026377201080322266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025551319122314453 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025177955627441406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026183605194091797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026293516159057617 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02658224105834961 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026835203170776367 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026126861572265625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02765345573425293 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026694536209106445 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027071714401245117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02657794952392578 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025531530380249023 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026821136474609375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026371479034423828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026332616806030273 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02675652503967285 seconds
Tree has no split, stopping training

[I 2026-04-22 21:33:12,771] Trial 83 finished with value: 0.9815859545961537 and parameters: {'exponent': 0.7020566863554283, 'kernel_type': 'kpq', 'bandwidth': 1.779731069671038, 'diag': True, 'norm_p': 0.7338375631147348, 'reg': 9.627077178593795e-05}. Best is trial 43 with value: 0.9821941233169648.

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025776147842407227 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026526689529418945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02742743492126465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02649831771850586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.03285384178161621 seconds
Tree has no split, stopping training

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025821208953857422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02735137939453125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026463747024536133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027031421661376953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0260007381439209 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025473833084106445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02698540687561035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026921749114990234 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026526689529418945 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02653336524963379 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025438308715820312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026869535446166992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026781082153320312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027461528778076172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026723623275756836 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02587413787841797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027530193328857422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027439355850219727 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.03208446502685547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026813983917236328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:13,610] Trial 84 finished with value: 0.9803990778910554 and parameters: {'exponent': 1.13717034709251, 'kernel_type': 'kpq', 'bandwidth': 1.5297149018434895, 'diag': True, 'norm_p': 1.150553469407141, 'reg': 0.0009040565854053824}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025337934494018555 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02664327621459961 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02696537971496582 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026271820068359375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02700972557067871 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02539205551147461 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02681732177734375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026715755462646484 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026376008987426758 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.032033443450927734 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025676488876342773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02675604820251465 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026294708251953125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02607893943786621 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026185035705566406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025264739990234375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.025893449783325195 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026658296585083008 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026189804077148438 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02829718589782715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025382518768310547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0274198055267334 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0264437198638916 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02663135528564453 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:14,446] Trial 85 finished with value: 0.9815873774629207 and parameters: {'exponent': 0.7961316240938916, 'kernel_type': 'kpq', 'bandwidth': 1.1436542340368674, 'diag': True, 'norm_p': 0.8268148391294232, 'reg': 0.012700736804417313}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026193857192993164 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02486133575439453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027081966400146484 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.028438806533813477 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026630401611328125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0261380672454834 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025160551071166992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027059555053710938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02996540069580078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026691675186157227 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.0263669490814209 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025190114974975586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02684497833251953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02590489387512207 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0263979434967041 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02606487274169922 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025424957275390625 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026419639587402344 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026933670043945312 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02582573890686035 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.025604724884033203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025354385375976562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.03226757049560547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026853084564208984 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.027027606964111328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:15,276] Trial 86 finished with value: 0.9803990778910554 and parameters: {'exponent': 0.7713362203368619, 'kernel_type': 'kpq', 'bandwidth': 1.0514259122168264, 'diag': True, 'norm_p': 0.8001377674711845, 'reg': 4.146465203224788e-05}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026448488235473633 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02554011344909668 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026533842086791992 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02734661102294922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026422739028930664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026033401489257812 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024876117706298828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026659488677978516 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026491641998291016 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026019811630249023 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026792526245117188 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024824142456054688 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03239727020263672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026314735412597656 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026785612106323242 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025761127471923828 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025492191314697266 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026449918746948242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026613473892211914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.0257110595703125 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02583479881286621 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025641918182373047 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027733325958251953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0267794132232666 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026131868362426758 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:16,109] Trial 87 finished with value: 0.9722723173462136 and parameters: {'exponent': 0.7443470260938321, 'kernel_type': 'kpq', 'bandwidth': 10.75168725775223, 'diag': True, 'norm_p': 0.7757071003587057, 'reg': 0.03461194554095532}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02624344825744629 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024934053421020508 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02675318717956543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027597665786743164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02656698226928711 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026639461517333984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024927139282226562 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02650737762451172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026831388473510742 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02629685401916504 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027116775512695312 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02538442611694336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027614355087280273 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02599024772644043 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02611541748046875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026473283767700195 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.027297019958496094 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027059316635131836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026823759078979492 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026038169860839844 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026309490203857422 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.026389360427856445 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027049541473388672 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.031232833862304688 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02676534652709961 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:16,937] Trial 88 finished with value: 0.9820943745988451 and parameters: {'exponent': 0.7234035109081782, 'kernel_type': 'kpq', 'bandwidth': 1.3519297706232716, 'diag': True, 'norm_p': 0.7839045157174674, 'reg': 0.008750577569595014}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02634596824645996 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024960994720458984 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026732683181762695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026734113693237305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02626347541809082 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026105403900146484 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024900436401367188 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026512861251831055 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026525497436523438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026252269744873047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026488542556762695 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0250089168548584 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02739429473876953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026241779327392578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02821826934814453 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.028563499450683594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025266408920288086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026314496994018555 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026441335678100586 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026198387145996094 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026404142379760742 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025326013565063477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027691125869750977 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.027010440826416016 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02634453773498535 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:17,763] Trial 89 finished with value: 0.9796671599672051 and parameters: {'exponent': 0.828306737373288, 'kernel_type': 'kpq', 'bandwidth': 2.8226895990215377, 'diag': True, 'norm_p': 0.8850371529070356, 'reg': 0.003682900558621765}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.03159689903259277 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.025612592697143555 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.0273897647857666 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.026539325714111328 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.026909589767456055 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 4: 0.026565074920654297 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02648138999938965 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02725529670715332 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.02651381492614746 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.026923179626464844 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.02627420425415039 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 0: 0.02562689781188965 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 1: 0.02724480628967285 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 2: 0.026060104370117188 seconds
Using expensive batch size
Optimal M batch size: 1350
Using SVD
Time taken for round 3: 0.026020526885986328 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using SVD
Time taken for round 4: 0.02628803253173828 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.02596449851989746 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.026780128479003906 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.025942564010620117 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.026611328125 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.026499032974243164 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 0: 0.027655839920043945 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 1: 0.028018712997436523 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 2: 0.026820659637451172 seconds
Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 3: 0.026551246643066406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:18,592] Trial 90 finished with value: 0.9675784007884669 and parameters: {'exponent': 0.7806492806532961, 'kernel_type': 'kpq', 'bandwidth': 5.979000318751269, 'diag': False, 'norm_p': 0.825755525497045, 'reg': 0.00523426017089686}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Using SVD
Time taken for round 4: 0.026562213897705078 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024949312210083008 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02694416046142578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026091337203979492 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026652097702026367 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025957107543945312 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02506232261657715 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026787757873535156 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027152299880981445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026763439178466797 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02611255645751953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02662348747253418 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027787208557128906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026607513427734375 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02617168426513672 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 1.8024165630340576 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02512335777282715 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026847362518310547 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0259397029876709 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026778221130371094 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026044130325317383 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025600433349609375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0272519588470459 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026637554168701172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026486873626708984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:21,192] Trial 91 finished with value: 0.9796845025402192 and parameters: {'exponent': 0.7372560045706877, 'kernel_type': 'kpq', 'bandwidth': 1.2402193429240598, 'diag': True, 'norm_p': 0.7987438521743189, 'reg': 0.0602844747559873}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026498079299926758 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.026144027709960938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027416706085205078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026494264602661133 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02633953094482422 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025681734085083008 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02453327178955078 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026877164840698242 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027011632919311523 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026961088180541992 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02637791633605957 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025136470794677734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02727055549621582 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02628326416015625 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026454925537109375 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02874612808227539 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025425434112548828 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02611708641052246 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026506662368774414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026504993438720703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026345014572143555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02563023567199707 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.026549816131591797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.0259854793548584 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026316165924072266 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:22,022] Trial 92 finished with value: 0.9797579147698066 and parameters: {'exponent': 0.723125503615129, 'kernel_type': 'kpq', 'bandwidth': 1.483593397275585, 'diag': True, 'norm_p': 0.7470960741203735, 'reg': 0.020315944839995926}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026538848876953125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025518417358398438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02667999267578125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027222394943237305 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026208162307739258 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025594711303710938 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02489781379699707 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026747703552246094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026870012283325195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02939915657043457 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026561975479125977 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025518417358398438 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027570486068725586 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026175737380981445 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02577662467956543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026214122772216797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025630474090576172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0274350643157959 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.03015613555908203 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026106595993041992 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026097536087036133 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025821208953857422 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02660965919494629 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02626800537109375 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.025851964950561523 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:22,848] Trial 93 finished with value: 0.9765950477552016 and parameters: {'exponent': 0.7561352649699963, 'kernel_type': 'kpq', 'bandwidth': 1.1673328775602319, 'diag': True, 'norm_p': 0.8061507666929946, 'reg': 0.1153112227479448}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026086807250976562 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025288820266723633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027028322219848633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026552915573120117 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025904417037963867 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02634286880493164 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025034189224243164 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027946949005126953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026534080505371094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02667236328125 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026294231414794922 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02486586570739746 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.0267946720123291 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027119159698486328 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02816915512084961 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02657794952392578 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02606368064880371 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02693772315979004 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.025957345962524414 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026178359985351562 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026278257369995117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02512049674987793 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027404308319091797 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026372194290161133 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026479005813598633 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:23,672] Trial 94 finished with value: 0.980357682558083 and parameters: {'exponent': 0.7991753386618675, 'kernel_type': 'kpq', 'bandwidth': 1.8900103875855103, 'diag': True, 'norm_p': 0.8510770100423309, 'reg': 0.013021012244925315}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026944637298583984 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02504134178161621 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.027373552322387695 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026935100555419922 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026265621185302734 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026024341583251953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025066137313842773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026909351348876953 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027394533157348633 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026669979095458984 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.025992155075073242 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.024923324584960938 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028412818908691406 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026377201080322266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025970935821533203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02629566192626953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.0270082950592041 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0261385440826416 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026229381561279297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02651500701904297 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.025765419006347656 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.02561783790588379 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02816605567932129 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02796626091003418 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026480436325073242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:24,503] Trial 95 finished with value: 0.9607181064400303 and parameters: {'exponent': 0.9766058161766557, 'kernel_type': 'kpq', 'bandwidth': 1.3040123653633435, 'diag': True, 'norm_p': 0.992094487321608, 'reg': 0.9639841349954489}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02640056610107422 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025457143783569336 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02655792236328125 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0263063907623291 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02606821060180664 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.025959014892578125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025252580642700195 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026371479034423828 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.026978015899658203 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026360750198364258 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026844501495361328 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0259246826171875 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026688575744628906 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02643609046936035 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026183605194091797 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.027069091796875 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025307655334472656 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02647995948791504 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02594780921936035 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02600717544555664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02647876739501953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025727510452270508 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02673625946044922 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02640676498413086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.025997400283813477 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:25,325] Trial 96 finished with value: 0.9802554608612366 and parameters: {'exponent': 0.7374143965318657, 'kernel_type': 'kpq', 'bandwidth': 1.0125258204741672, 'diag': True, 'norm_p': 0.9570539419843156, 'reg': 0.0005787458696934097}. Best is trial 43 with value: 0.9821941233169648.

Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026360034942626953 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025204896926879883 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026029109954833984 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.025912046432495117 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.025797367095947266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.0265347957611084 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02512955665588379 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.026099443435668945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02743244171142578 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02585577964782715 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.025868892669677734 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.025159120559692383 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02718043327331543 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027568578720092773 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.02690410614013672 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026683330535888672 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025142192840576172 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02747201919555664 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026116371154785156 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026510953903198242 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.026487350463867188 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025380849838256836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02692556381225586 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.02639150619506836 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.02634906768798828 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:26,142] Trial 97 finished with value: 0.9741970041570879 and parameters: {'exponent': 0.7005245433362945, 'kernel_type': 'kpq', 'bandwidth': 43.88466292521244, 'diag': True, 'norm_p': 0.7041140282294701, 'reg': 0.001791892699005342}. Best is trial 43 with value: 0.9821941233169648.

Time taken for round 4: 0.026428699493408203 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.007935285568237305 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.007901191711425781 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.008112430572509766 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.009546518325805664 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.008733034133911133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.012789726257324219 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.01133871078491211 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.009270191192626953 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.010290861129760742 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.010590553283691406 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 0: 0.0074422359466552734 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 1: 0.008002758026123047 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1350
Time taken for round 2: 0.00821065902709961 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 3: 0.00871896743774414 seconds
Using cheap batch size
Optimal M batch size: 1350
Time taken for round 4: 0.007359981536865234 seconds
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.009255170822143555 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.0084075927734375 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.008975982666015625 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Using cheap batch size
Optimal M batch size: 1351
Time taken for round 3: 0.00910806655883789 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.00944662094116211 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 0: 0.010121583938598633 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 1: 0.010481595993041992 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 2: 0.009758472442626953 seconds
Using cheap batch size

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:26,496] Trial 98 finished with value: 0.9798149463951512 and parameters: {'exponent': 0.7730362133591083, 'kernel_type': 'k2q', 'bandwidth': 1.6594713750623258, 'diag': True, 'reg': 0.007997904432695633}. Best is trial 43 with value: 0.9821941233169648.

Optimal M batch size: 1351
Time taken for round 3: 0.008409976959228516 seconds
Using cheap batch size
Optimal M batch size: 1351
Time taken for round 4: 0.008505105972290039 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02643871307373047 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.03833127021789551 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02711653709411621 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.026612281799316406 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.027556419372558594 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.035041093826293945 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.02693009376525879 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.0268557071685791 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027169227600097656 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.026223421096801758 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02620553970336914 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.029062747955322266 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.02659773826599121 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.0266268253326416 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 4: 0.02642965316772461 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 30, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.024935007095336914 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.02642035484313965 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026058435440063477 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.025909900665283203 seconds
Using expensive batch size
Optimal M batch size: 1351

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.026616573333740234 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1351, d: 31, and nval: 337
======================================================================
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 0: 0.025955677032470703 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 1: 0.027306079864501953 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 2: 0.026728153228759766 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 3: 0.026517629623413086 seconds
Using expensive batch size
Optimal M batch size: 1351
Time taken for round 4: 0.02618408203125 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]
[I 2026-04-22 21:33:27,345] Trial 99 finished with value: 0.9764840008382087 and parameters: {'exponent': 0.9991570782873668, 'kernel_type': 'kpq', 'bandwidth': 2.254931842128807, 'diag': True, 'norm_p': 1.020633350784882, 'reg': 0.017740426487912565}. Best is trial 43 with value: 0.9821941233169648.

Tree has no split, stopping training
Using hard routing for tree prediction
Best params: {'exponent': 0.8266944178149827, 'kernel_type': 'kpq', 'bandwidth': 1.8169724544596653, 'diag': True, 'norm_p': 0.8739867756221869, 'reg': 5.7741155858099045e-05}
Best macro F1: 0.9821941233169648

In [9]:
model, pipeline, fit_time, train_metrics, val_metrics = fit_best_xrfm(
    X,
    y,
    best_trial,
    processor,
    n_num_cols,
    task=cfg["task"],
    device=device,
)

print(f"Training time: {fit_time:.2f}s")
print(
    f"Train Accuracy: {train_metrics['accuracy']:.4f}  AUC-ROC: {train_metrics['auc_roc']:.4f}"
)
print(
    f"Val Accuracy: {val_metrics['accuracy']:.4f}  AUC-ROC: {val_metrics['auc_roc']:.4f}"
)

joblib.dump(model, MODELS_DIR / data_name / "xrfm.joblib")
joblib.dump(pipeline, MODELS_DIR / data_name / "xrfm_pipeline.joblib")

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 1350, d: 31, and nval: 338
======================================================================
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 0: 0.02791118621826172 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 1: 0.028059959411621094 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 2: 0.027932405471801758 seconds
Using expensive batch size
Optimal M batch size: 1350
Time taken for round 3: 0.027331113815307617 seconds
Using expensive batch size
Optimal M batch size: 1350

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Time taken for round 4: 0.02706313133239746 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
Using hard routing for tree prediction
Training time: 0.16s
Train Accuracy: 1.0000  AUC-ROC: 1.0000
Val Accuracy: 0.9882  AUC-ROC: 0.9997

['/home/shado/college_project/comp9417/9417GroupProject/models/obesity_level/xrfm_pipeline.joblib']

In [10]:
model = joblib.load(MODELS_DIR / data_name / "xrfm.joblib")
pipeline = joblib.load(MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [11]:
X_test = test_df.drop(columns=metadata["target_col"])
y_test = le.transform(test_df[metadata["target_col"]]).astype(np.int32)

X_test = pipeline.transform(X_test)
t0 = time.perf_counter()
y_proba = model.predict_proba(X_test)
infer_time = (time.perf_counter() - t0) / len(X_test)

Using hard routing for tree prediction

In [12]:
results = evaluate_classification(y_test, y_proba)
print(f"Accuracy:  {results['accuracy']:.4f}")
print(f"AUC-ROC:   {results['auc_roc']:.4f}")
print(f"Inference time per sample: {infer_time * 1e6:.2f}µs")

Accuracy:  0.9835
AUC-ROC:   0.9997
Inference time per sample: 7.32µs

In [13]:
output = {
    **results,
    "train_metrics": train_metrics,
    "val_metrics": val_metrics,
    "fit_time_s": fit_time,
    "infer_time_per_sample_s": infer_time,
    "best_params": {
        "tuning_metric": model.tuning_metric,
        "split_method": model.split_method,
        "max_leaf_size": model.max_leaf_size,
        **model.rfm_params,
    },
}

results_dir = RESULTS_BENCHMARK / "obesity_level"
with open(results_dir / "xrfm.json", "w") as f:
    json.dump(output, f, indent=4)

plot_roc_curve(
    y_test,
    y_proba,
    save_path=results_dir / "roc_curve_xrfm.png",
    class_names=list(le.classes_),
)
plot_confusion_matrix(
    y_test,
    y_proba,
    save_path=results_dir / "confusion_matrix_xrfm.png",
    class_names=list(le.classes_),
)
save_classification_report(
    y_test,
    y_proba,
    save_path=results_dir / "classification_report_xrfm.json",
    class_names=list(le.classes_),
)

print(f"Results saved to {results_dir / 'xrfm.json'}")

Results saved to /home/shado/college_project/comp9417/9417GroupProject/results/obesity_level/xrfm.json