In [1]:
import json
import time

import joblib
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import LabelEncoder

from benchmark.config import DATA_PROCESSED, DATASETS, MODELS_DIR, RESULTS_BENCHMARK
from benchmark.metrics import (
    evaluate_classification,
    plot_confusion_matrix,
    plot_roc_curve,
    save_classification_report,
)
from benchmark.models.xrfm_model import make_processor
from benchmark.models.xrfm_model import fit_best_xrfm, fit_xrfm_cross_validation

data_name = "sleep_health"
cfg = DATASETS[data_name]
processed = DATA_PROCESSED / data_name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train_df = pd.read_csv(processed / "train.csv")
train_df.head()

,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,sleep_disorder_risk,rem_hrs,deep_sleep_hrs,light_sleep_hrs,wake_rate
0,23,Male,Software Engineer,29.4,USA,6.67,4.9,17.8,24.1,18,...,0,21.1,0.65,Winter,Weekend,Healthy,1.18726,1.60747,3.87527,0.599700
1,45,Female,Driver,25.7,South Korea,5.98,5.2,21.6,19.5,28,...,0,19.6,0.49,Spring,Weekday,Healthy,1.29168,1.16610,3.52222,0.334448
2,46,Female,Sales,26.7,USA,5.67,4.9,25.6,17.6,10,...,0,25.5,1.61,Winter,Weekday,Healthy,1.45152,0.99792,3.22056,0.176367
3,51,Male,Manager,30.8,USA,6.38,5.3,16.8,13.8,20,...,0,23.8,0.76,Winter,Weekday,Mild,1.07184,0.88044,4.42772,0.313480
4,20,Male,Retired,26.7,USA,9.33,7.1,23.8,23.2,25,...,0,23.8,1.90,Spring,Weekend,Healthy,2.22054,2.16456,4.94490,0.107181

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   age                          16000 non-null  int64
 1   gender                       16000 non-null  object
 2   occupation                   16000 non-null  object
 3   bmi                          16000 non-null  float64
 4   country                      16000 non-null  object
 5   sleep_duration_hrs           16000 non-null  float64
 6   sleep_quality_score          16000 non-null  float64
 7   rem_percentage               16000 non-null  float64
 8   deep_sleep_percentage        16000 non-null  float64
 9   sleep_latency_mins           16000 non-null  int64
 10  wake_episodes_per_night      16000 non-null  int64
 11  caffeine_mg_before_bed       16000 non-null  int64
 12  alcohol_units_before_bed     16000 non-null  float64
 13  screen_time_before_bed_mins  16000 non-null  int64
 14  exercise_day                 16000 non-null  int64
 15  steps_that_day               16000 non-null  int64
 16  nap_duration_mins            16000 non-null  int64
 17  stress_score                 16000 non-null  float64
 18  work_hours_that_day          16000 non-null  float64
 19  chronotype                   16000 non-null  object
 20  mental_health_condition      16000 non-null  object
 21  heart_rate_resting_bpm       16000 non-null  int64
 22  sleep_aid_used               16000 non-null  int64
 23  shift_work                   16000 non-null  int64
 24  room_temperature_celsius     16000 non-null  float64
 25  weekend_sleep_diff_hrs       16000 non-null  float64
 26  season                       16000 non-null  object
 27  day_type                     16000 non-null  object
 28  sleep_disorder_risk          16000 non-null  object
 29  rem_hrs                      16000 non-null  float64
 30  deep_sleep_hrs               16000 non-null  float64
 31  light_sleep_hrs              16000 non-null  float64
 32  wake_rate                    16000 non-null  float64
dtypes: float64(14), int64(11), object(8)
memory usage: 4.0+ MB

In [4]:
test_df = pd.read_csv(processed / "test.csv")
test_df.head()

,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,sleep_latency_mins,...,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,sleep_disorder_risk,rem_hrs,deep_sleep_hrs,light_sleep_hrs,wake_rate
0,29,Male,Lawyer,30.7,Brazil,6.00,4.8,21.2,24.0,18,...,0,24.1,1.17,Spring,Weekday,Mild,1.27200,1.44000,3.28800,1.000000
1,60,Female,Freelancer,26.3,Japan,7.37,6.8,24.0,17.7,19,...,0,23.3,1.48,Winter,Weekday,Healthy,1.76880,1.30449,4.29671,0.407056
2,23,Male,Manager,24.3,India,7.46,6.6,21.6,27.4,11,...,0,24.5,0.91,Spring,Weekday,Healthy,1.61136,2.04404,3.80460,0.402145
3,26,Male,Doctor,26.6,India,6.34,3.4,15.9,12.7,41,...,0,18.9,0.40,Summer,Weekday,Mild,1.00806,0.80518,4.52676,0.473186
4,28,Male,Freelancer,22.2,UK,5.14,3.1,25.5,19.8,32,...,0,20.7,0.26,Spring,Weekday,Moderate,1.31070,1.01772,2.81158,0.583658

In [5]:
with open(processed / "metadata.json") as f:
    metadata = json.load(f)

print(metadata)

{'num_cols': ['age', 'bmi', 'sleep_duration_hrs', 'sleep_quality_score', 'rem_percentage', 'deep_sleep_percentage', 'sleep_latency_mins', 'wake_episodes_per_night', 'caffeine_mg_before_bed', 'alcohol_units_before_bed', 'screen_time_before_bed_mins', 'exercise_day', 'steps_that_day', 'nap_duration_mins', 'stress_score', 'work_hours_that_day', 'heart_rate_resting_bpm', 'room_temperature_celsius', 'weekend_sleep_diff_hrs', 'rem_hrs', 'deep_sleep_hrs', 'light_sleep_hrs', 'wake_rate'], 'cat_cols': ['gender', 'occupation', 'country', 'chronotype', 'mental_health_condition', 'season', 'day_type'], 'bin_cols': ['sleep_aid_used', 'shift_work'], 'target_col': 'sleep_disorder_risk'}

In [6]:
le = LabelEncoder()
X = train_df.drop(columns=metadata["target_col"])
y = le.fit_transform(train_df[metadata["target_col"]]).astype(np.int32)

print("Classes:", le.classes_)

processor = make_processor(metadata)
n_num_cols = len(metadata["num_cols"])

Classes: ['Healthy' 'Mild' 'Moderate' 'Severe']

In [7]:
best_trial = fit_xrfm_cross_validation(
    X, y, processor, n_num_cols, task=cfg["task"], device=device
)

print(f"Best params: {best_trial.params}")
print(f"Best macro F1: {best_trial.value}")

[I 2026-04-22 21:46:45,181] A new study created in memory with name: no-name-2b874564-7b49-4e30-967d-9e5c82dc8d6e

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2661
Time taken for round 0: 0.5671148300170898 seconds
Using cheap batch size
Optimal M batch size: 2661
Time taken for round 1: 0.259413480758667 seconds
Using cheap batch size
Optimal M batch size: 2661
Time taken for round 2: 0.258436918258667 seconds
Using cheap batch size
Optimal M batch size: 2661
Time taken for round 3: 0.2625851631164551 seconds
Using cheap batch size
Optimal M batch size: 2661
Time taken for round 4: 0.27328038215637207 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.2562403678894043 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.3112781047821045 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.25830769538879395 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.26230883598327637 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.26485681533813477 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.2609865665435791 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.27442288398742676 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.27504420280456543 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.2739593982696533 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.2743346691131592 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.25997114181518555 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.26152825355529785 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.26394081115722656 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 3.0827059745788574 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.2625598907470703 seconds

Building trees:   0%|          | 0/1 [00:04<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 0: 0.26700305938720703 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 1: 0.27397680282592773 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 2: 0.2754490375518799 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.2771871089935303 seconds
Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.2758777141571045 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:46:56,437] Trial 0 finished with value: 0.7617937149324472 and parameters: {'exponent': 1.0271644858581115, 'kernel_type': 'k2q', 'bandwidth': 1.970613996905623, 'diag': True, 'reg': 0.0026485784758470345}. Best is trial 0 with value: 0.7617937149324472.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 399

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:869: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Time taken for round 0: 2.880387544631958 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1754703521728516 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1948578357696533 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.190704345703125 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1944468021392822 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.182767868041992 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.178422212600708 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1944615840911865 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1774191856384277 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1384997367858887 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.308431386947632 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.197627544403076 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 5.2032880783081055 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.185918092727661 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1273419857025146 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.184997320175171 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1888673305511475 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1835250854492188 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.200218677520752 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1614468097686768 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.199087142944336 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.203972339630127 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.196223735809326 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.202347993850708 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1529603004455566 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:48:00,319] Trial 1 finished with value: 0.7503974083905958 and parameters: {'exponent': 0.7598959983417237, 'kernel_type': 'kpq', 'bandwidth': 31.128146769150394, 'diag': True, 'norm_p': 1.204380550596923, 'reg': 1.5178988352304667e-06}. Best is trial 0 with value: 0.7617937149324472.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.25518345832824707 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2603600025177002 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2640857696533203 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2738041877746582 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.27480363845825195 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 3.1721105575561523 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.27198362350463867 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2713336944580078 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27736616134643555 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:04<?, ?it/s]

Time taken for round 4: 0.2741258144378662 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26938390731811523 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2731168270111084 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2710232734680176 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2761871814727783 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.2766554355621338 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26778268814086914 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.26154589653015137 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.25977063179016113 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2719559669494629 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.26172327995300293 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.253314733505249 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2742929458618164 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27249670028686523 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2770347595214844 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:48:11,142] Trial 2 finished with value: 0.6920266840706546 and parameters: {'exponent': 0.7416781387847737, 'kernel_type': 'k2q', 'bandwidth': 175.8288583045548, 'diag': True, 'reg': 0.5118691608584706}. Best is trial 0 with value: 0.7617937149324472.

Time taken for round 4: 0.273205041885376 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1871275901794434 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.185655117034912 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.2030458450317383 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1819663047790527 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.136108160018921 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.182037830352783 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.2013139724731445 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1957738399505615 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.194516658782959 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1515629291534424 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1527271270751953 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 5.129160642623901 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.181164503097534 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1812448501586914 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1415750980377197 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.186518669128418 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1859986782073975 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.179474353790283 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.183581590652466 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.142500162124634 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1877267360687256 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.196639060974121 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.194256067276001 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1965630054473877 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 5.105269193649292 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 21:49:16,981] Trial 3 finished with value: 0.7653446326919882 and parameters: {'exponent': 0.7550981778629094, 'kernel_type': 'kpq', 'bandwidth': 6.5017130686590825, 'diag': True, 'norm_p': 1.6741056103679175, 'reg': 0.15816844334894103}. Best is trial 3 with value: 0.7653446326919882.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2528262138366699 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.25907301902770996 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27318382263183594 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.279132604598999 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.27350544929504395 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26870226860046387 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2737236022949219 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27585315704345703 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27749156951904297 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.274524450302124 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2650923728942871 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.27349281311035156 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.26131558418273926 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2665095329284668 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.262958288192749 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.25328946113586426 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2613527774810791 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.26071643829345703 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27265357971191406 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.2610194683074951 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2722339630126953 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2913968563079834 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27550578117370605 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27918124198913574 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:49:24,908] Trial 4 finished with value: 0.5288736508580743 and parameters: {'exponent': 1.2386834737442696, 'kernel_type': 'k2q', 'bandwidth': 90.48888237464404, 'diag': True, 'reg': 0.8236923920601619}. Best is trial 3 with value: 0.7653446326919882.

Time taken for round 4: 0.2733299732208252 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1919760704040527 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1447181701660156 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1367247104644775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.131192684173584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1234710216522217 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190141201019287 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1318631172180176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1488187313079834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.132516384124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09195613861084 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.18908953666687 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.131338357925415 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.131308078765869 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.146888494491577 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0950121879577637 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1920387744903564 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1331241130828857 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.131348133087158 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1351115703582764 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0981698036193848 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190063238143921 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1317453384399414 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1323113441467285 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1322391033172607 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.068860292434692 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 21:50:29,761] Trial 5 finished with value: 0.768171272864999 and parameters: {'exponent': 1.3169801908670333, 'kernel_type': 'kpq', 'bandwidth': 19.84662081152421, 'diag': False, 'norm_p': 1.7995055455137243, 'reg': 0.05330158533580604}. Best is trial 5 with value: 0.768171272864999.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1918752193450928 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.137848138809204 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1322669982910156 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.143934726715088 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.093310832977295 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.191910982131958 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.144212484359741 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1334874629974365 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.132127523422241 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0915744304656982 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190824270248413 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1334099769592285 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.083184003829956 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.133408546447754 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.109712839126587 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1873984336853027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.13206148147583 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.150049924850464 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.133260726928711 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.099365234375 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1870126724243164 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.128542184829712 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.131235361099243 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1298413276672363 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.101348638534546 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:51:31,627] Trial 6 finished with value: 0.7894051442154407 and parameters: {'exponent': 1.0948486965751747, 'kernel_type': 'kpq', 'bandwidth': 63.44132593183689, 'diag': False, 'norm_p': 1.4194589751409419, 'reg': 0.00011913672272764324}. Best is trial 6 with value: 0.7894051442154407.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26276183128356934 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2732119560241699 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27518701553344727 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27675580978393555 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.27768492698669434 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2700505256652832 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2629814147949219 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2620220184326172 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27170300483703613 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:04<?, ?it/s]

Time taken for round 4: 0.2639904022216797 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2515585422515869 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.26483607292175293 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2619740962982178 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27000951766967773 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.2613692283630371 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.25423693656921387 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.260817289352417 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.26343536376953125 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2722814083099365 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Time taken for round 4: 0.2630620002746582 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.25404930114746094 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2735176086425781 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27783727645874023 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2794008255004883 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:51:42,449] Trial 7 finished with value: 0.7631683296822379 and parameters: {'exponent': 0.9163728423001612, 'kernel_type': 'k2q', 'bandwidth': 11.925101256066307, 'diag': True, 'reg': 0.021609288204221935}. Best is trial 6 with value: 0.7894051442154407.

Time taken for round 4: 0.27648282051086426 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2649199962615967 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2732248306274414 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27459216117858887 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.30170583724975586 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2833831310272217 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2684934139251709 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2743549346923828 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27364039421081543 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2817041873931885 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2769460678100586 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26619768142700195 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2742948532104492 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.27358198165893555 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27956247329711914 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.27577996253967285 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2675821781158447 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.27216243743896484 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2738215923309326 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2804737091064453 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2736649513244629 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26702332496643066 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2750282287597656 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2738661766052246 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2786293029785156 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2741518020629883 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:51:50,526] Trial 8 finished with value: 0.7624835241466776 and parameters: {'exponent': 1.2060200075435343, 'kernel_type': 'k2q', 'bandwidth': 2.792736238727968, 'diag': True, 'reg': 0.0007660547961224706}. Best is trial 6 with value: 0.7894051442154407.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26743626594543457 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2755444049835205 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2692244052886963 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27902865409851074 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2730748653411865 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2682487964630127 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.27437639236450195 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2760190963745117 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2808265686035156 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2751760482788086 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2569441795349121 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.26112985610961914 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.26501011848449707 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2840745449066162 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2722327709197998 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.2668285369873047 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.2729184627532959 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.275848388671875 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.2767765522003174 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.27727770805358887 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 0: 0.26623964309692383 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 1: 0.27355217933654785 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 2: 0.2748908996582031 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 3: 0.27719902992248535 seconds
Using cheap batch size
Optimal M batch size: 2659
Time taken for round 4: 0.2775249481201172 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 21:51:58,552] Trial 9 finished with value: 0.7622963057434841 and parameters: {'exponent': 0.7450034897059166, 'kernel_type': 'k2q', 'bandwidth': 1.880953078065556, 'diag': True, 'reg': 2.8141896704489657e-06}. Best is trial 6 with value: 0.7894051442154407.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1918435096740723 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.13561749458313 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.13499116897583 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1351850032806396 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1444201469421387 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.236335039138794 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.211080551147461 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.229426383972168 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1900155544281006 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1299452781677246 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2083895206451416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.129945993423462 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1320242881774902 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1290438175201416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.123667001724243 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1999101638793945 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.139704704284668 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1754589080810547 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.661426544189453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1345102787017822 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2357919216156006 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1950037479400635 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1929931640625 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2109737396240234 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.113619089126587 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:53:03,648] Trial 10 finished with value: 0.7876362295870517 and parameters: {'exponent': 1.093000780356796, 'kernel_type': 'kpq', 'bandwidth': 51.795692510136796, 'diag': False, 'norm_p': 1.353570346701657, 'reg': 5.873193543027173e-05}. Best is trial 6 with value: 0.7894051442154407.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1923835277557373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1283183097839355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1323049068450928 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1304614543914795 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0925190448760986 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1902430057525635 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1308608055114746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 4.744385242462158 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.130664825439453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1099517345428467 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1881699562072754 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.131721019744873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1330394744873047 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1303489208221436 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.096937656402588 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.186293601989746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1328701972961426 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129499912261963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.144617795944214 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0915589332580566 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.202467679977417 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.098236799240112 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.2053892612457275 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1301028728485107 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.091390609741211 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 21:54:08,174] Trial 11 finished with value: 0.786926749813665 and parameters: {'exponent': 1.0840208201939268, 'kernel_type': 'kpq', 'bandwidth': 53.712089708058606, 'diag': False, 'norm_p': 1.363865886008038, 'reg': 5.86365464007906e-05}. Best is trial 6 with value: 0.7894051442154407.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1893868446350098 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.12613582611084 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1274735927581787 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126579523086548 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1168298721313477 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.188192367553711 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1253976821899414 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1442716121673584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.129335403442383 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.091144561767578 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1890640258789062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1283648014068604 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129972219467163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1287357807159424 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0952653884887695 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190088987350464 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1277835369110107 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1319925785064697 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.145195484161377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.090930223464966 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2023069858551025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.146808385848999 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1319756507873535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.081984519958496 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.118574857711792 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 21:55:12,944] Trial 12 finished with value: 0.7915267719732526 and parameters: {'exponent': 1.0673028623797836, 'kernel_type': 'kpq', 'bandwidth': 78.52727625847996, 'diag': False, 'norm_p': 1.447722711864787, 'reg': 5.887225253621801e-05}. Best is trial 12 with value: 0.7915267719732526.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1882448196411133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1267495155334473 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.142160415649414 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126282215118408 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0945656299591064 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.189453601837158 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.126371145248413 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.12709379196167 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.142690896987915 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0890462398529053 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.187654733657837 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1290857791900635 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.041378021240234 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.145338296890259 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0905981063842773 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2018394470214844 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1434459686279297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129430055618286 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1278703212738037 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.116159200668335 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1868510246276855 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1285908222198486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.146817922592163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1285293102264404 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0945050716400146 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:56:14,733] Trial 13 finished with value: 0.7938325381460221 and parameters: {'exponent': 0.9791358910378201, 'kernel_type': 'kpq', 'bandwidth': 140.73605881542028, 'diag': False, 'norm_p': 1.5328501718816294, 'reg': 4.697179848505081e-05}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1880791187286377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.092089653015137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.170992851257324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1300570964813232 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.099128484725952 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1880364418029785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.144351005554199 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.130790948867798 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.129603624343872 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.094327926635742 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1864547729492188 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1433370113372803 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129971981048584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1313204765319824 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1073427200317383 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.188034772872925 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1293790340423584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1496169567108154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.129667043685913 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.092864751815796 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1883349418640137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1292057037353516 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1308090686798096 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.130341053009033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.085247755050659 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:57:19,502] Trial 14 finished with value: 0.7914319852242853 and parameters: {'exponent': 0.948809312578895, 'kernel_type': 'kpq', 'bandwidth': 188.1733876982921, 'diag': False, 'norm_p': 1.5772825831570314, 'reg': 9.409508652518459e-06}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.189811944961548 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1298859119415283 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1290950775146484 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1452298164367676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.073358774185181 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2058815956115723 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1290268898010254 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1289942264556885 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1299009323120117 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.113739252090454 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1878302097320557 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1281726360321045 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1482646465301514 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1286098957061768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.092756986618042 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1880130767822266 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.13143253326416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.06092095375061 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1459267139434814 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.092895746231079 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1903257369995117 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1484289169311523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1321628093719482 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1309821605682373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0949220657348633 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 21:58:24,337] Trial 15 finished with value: 0.7761426853217878 and parameters: {'exponent': 0.936922697657978, 'kernel_type': 'kpq', 'bandwidth': 110.72090422126284, 'diag': False, 'norm_p': 1.076790363570726, 'reg': 0.0004298615111079326}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.187791109085083 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.131225347518921 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1342501640319824 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.129969596862793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1128337383270264 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1884825229644775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.0784900188446045 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1318254470825195 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.130772352218628 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0925209522247314 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1880030632019043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1294939517974854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1272261142730713 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1310436725616455 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0963797569274902 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1881015300750732 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.130474805831909 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1310231685638428 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1297929286956787 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09657883644104 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.151564836502075 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1458940505981445 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1297857761383057 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.130415678024292 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1158766746520996 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 21:59:29,126] Trial 16 finished with value: 0.7826316670790218 and parameters: {'exponent': 0.8425365180195054, 'kernel_type': 'kpq', 'bandwidth': 29.985833451475123, 'diag': False, 'norm_p': 1.5352304925598035, 'reg': 1.3906871810136615e-05}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.189990282058716 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1296236515045166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1459460258483887 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.131685256958008 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.11503529548645 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1902878284454346 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.129578113555908 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1346757411956787 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1506965160369873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.043911933898926 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1874003410339355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1443440914154053 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1314263343811035 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.131331205368042 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1112477779388428 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190232992172241 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1310174465179443 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.146322011947632 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1305642127990723 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.096087694168091 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.187025785446167 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.127366781234741 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.083543539047241 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1489338874816895 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0944693088531494 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:00:33,984] Trial 17 finished with value: 0.7841120781654685 and parameters: {'exponent': 1.1679386853247093, 'kernel_type': 'kpq', 'bandwidth': 6.426322864124635, 'diag': False, 'norm_p': 1.6395821234461319, 'reg': 1.3220348323937287e-05}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.207758665084839 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.154672861099243 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1313631534576416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0528767108917236 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0689857006073 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.206693172454834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1340205669403076 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1171152591705322 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1009373664855957 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.143059492111206 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.190048933029175 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.090408086776733 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.133603811264038 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1313748359680176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.195797920227051 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.187800168991089 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1310768127441406 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.131657600402832 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.159404754638672 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.133474588394165 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2742834091186523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.103348970413208 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0961360931396484 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1048760414123535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.171229600906372 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:01:36,101] Trial 18 finished with value: 0.7916901858259245 and parameters: {'exponent': 1.0009724656341885, 'kernel_type': 'kpq', 'bandwidth': 124.87250457751097, 'diag': False, 'norm_p': 1.455335718832238, 'reg': 0.0033580754939653026}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.1305482387542725 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0644044876098633 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0952765941619873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.055581569671631 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0482118129730225 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.128263235092163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1057543754577637 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1386492252349854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1032848358154297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0803747177124023 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1387526988983154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1167995929718018 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0578503608703613 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0974786281585693 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 4.995106935501099 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.3220579624176025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.213162899017334 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.15000581741333 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0888235569000244 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1190617084503174 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1414499282836914 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0429177284240723 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.075486421585083 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1148407459259033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1518361568450928 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:02:40,446] Trial 19 finished with value: 0.7907939071486996 and parameters: {'exponent': 0.8764683716291947, 'kernel_type': 'kpq', 'bandwidth': 119.83302660634425, 'diag': False, 'norm_p': 1.2087707102464504, 'reg': 0.003959221090219732}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2207579612731934 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0882186889648438 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.100351095199585 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.774647235870361 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.240447998046875 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2043492794036865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.081637144088745 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1527862548828125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1007747650146484 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2606606483459473 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.308849811553955 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1901559829711914 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1622750759124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.037775754928589 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.056077480316162 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.139861583709717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.320153474807739 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1261439323425293 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0902113914489746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.257957935333252 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.352292060852051 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2864105701446533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.211704730987549 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.211419105529785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2115211486816406 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]
[I 2026-04-22 22:03:45,407] Trial 20 finished with value: 0.7924978691870879 and parameters: {'exponent': 1.0023427871057267, 'kernel_type': 'kpq', 'bandwidth': 34.23248429671807, 'diag': False, 'norm_p': 1.5091100058290248, 'reg': 0.007790608209690546}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2467715740203857 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0429487228393555 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.043809175491333 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1009182929992676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2726473808288574 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2149622440338135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.264484167098999 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1964833736419678 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.10703706741333 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.118565320968628 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2065746784210205 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.189333915710449 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.081894636154175 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0823590755462646 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1582207679748535 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1677582263946533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.173830986022949 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1514928340911865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.127716302871704 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1140167713165283 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.167198896408081 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0802977085113525 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.102407455444336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0842490196228027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.087045669555664 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:04:50,352] Trial 21 finished with value: 0.7931414286716646 and parameters: {'exponent': 0.9970812675233613, 'kernel_type': 'kpq', 'bandwidth': 44.83850971397115, 'diag': False, 'norm_p': 1.50873238736998, 'reg': 0.00817526224656724}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1602845191955566 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.167790412902832 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0858826637268066 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0989322662353516 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0839319229125977 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.142970085144043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.080064058303833 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.092117071151733 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2896413803100586 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.150238275527954 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1997971534729004 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1730635166168213 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.2294509410858154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1626195907592773 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1813926696777344 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.300605058670044 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0818352699279785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0833113193511963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.181636333465576 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1388561725616455 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.097209215164185 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0805370807647705 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1320230960845947 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1666088104248047 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.120933771133423 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:05:55,598] Trial 22 finished with value: 0.7910922676638472 and parameters: {'exponent': 0.9864822215231016, 'kernel_type': 'kpq', 'bandwidth': 33.1602641328765, 'diag': False, 'norm_p': 1.5404375671686492, 'reg': 0.014994945107482765}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1570305824279785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0887539386749268 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.083483934402466 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0786216259002686 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.08095383644104 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.132549524307251 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.154170036315918 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1903536319732666 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.131718158721924 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.121846914291382 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1300690174102783 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1090586185455322 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.134751319885254 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.099731683731079 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1396288871765137 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1286959648132324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1686782836914062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1464080810546875 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1711056232452393 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.080933094024658 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.105956792831421 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1483147144317627 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1449599266052246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.9993062019348145 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.229858160018921 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:07:00,266] Trial 23 finished with value: 0.7592156315088886 and parameters: {'exponent': 0.8621928332867694, 'kernel_type': 'kpq', 'bandwidth': 16.969226023679802, 'diag': False, 'norm_p': 0.8696388839585407, 'reg': 0.0002591077163471317}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2094717025756836 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.105882406234741 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129434585571289 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.121035099029541 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.192953109741211 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.257197141647339 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2474613189697266 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.141441822052002 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0815980434417725 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1612625122070312 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.155677080154419 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1834635734558105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.019338130950928 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1648848056793213 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1657817363739014 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1762921810150146 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.112443208694458 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.151498556137085 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.161562919616699 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.167290687561035 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.223964214324951 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1617002487182617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1761603355407715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1736347675323486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.179091453552246 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:08:02,930] Trial 24 finished with value: 0.779951858510275 and parameters: {'exponent': 1.1308069404673724, 'kernel_type': 'kpq', 'bandwidth': 41.577662189819236, 'diag': False, 'norm_p': 1.6664590610645242, 'reg': 0.021853902658355618}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.171715259552002 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1571576595306396 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1755833625793457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1342251300811768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0774641036987305 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1486546993255615 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1608383655548096 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1745669841766357 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1478137969970703 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.080548048019409 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2764697074890137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.229767322540283 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.160146474838257 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.169835090637207 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.1092283725738525 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None

Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2051773071289062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0797760486602783 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1551296710968018 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1952390670776367 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2013416290283203 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.131772041320801 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.080383539199829 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1543211936950684 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2249066829681396 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.217128276824951 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:09:08,519] Trial 25 finished with value: 0.7885616442699718 and parameters: {'exponent': 0.817627920644898, 'kernel_type': 'kpq', 'bandwidth': 12.140120303735587, 'diag': False, 'norm_p': 1.2703932925027275, 'reg': 0.006195500714805806}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2907826900482178 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1464545726776123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1753692626953125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.111287832260132 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1585853099823 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.215317964553833 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.15997314453125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1621711254119873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1652047634124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1762704849243164 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.223580837249756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.174539804458618 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.177690267562866 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1771137714385986 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1624507904052734 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2231600284576416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.117116212844849 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1927998065948486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1468729972839355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1532652378082275 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.116273880004883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.053535223007202 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0516374111175537 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0501370429992676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.182914972305298 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:10:14,049] Trial 26 finished with value: 0.7930027344163687 and parameters: {'exponent': 0.9809778413752444, 'kernel_type': 'kpq', 'bandwidth': 23.987771223901134, 'diag': False, 'norm_p': 1.5055021523429362, 'reg': 0.0015970658311454005}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.117496967315674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.045485019683838 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.091799736022949 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.128462314605713 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1404802799224854 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.1453752517700195 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1257710456848145 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1293864250183105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.093815326690674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0671920776367188 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1417324542999268 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.068789482116699 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.078312873840332 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0715410709381104 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0682895183563232 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.212106704711914 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1045033931732178 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.066807746887207 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.067739248275757 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.048279762268066 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.122342109680176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0646774768829346 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0934693813323975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0696284770965576 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.074267625808716 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:11:17,962] Trial 27 finished with value: 0.7163930613460305 and parameters: {'exponent': 0.9443211502092369, 'kernel_type': 'kpq', 'bandwidth': 1.0096139638133546, 'diag': False, 'norm_p': 1.7618396606991076, 'reg': 0.0015708038452987895}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.132643461227417 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.064521551132202 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.066789388656616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0702247619628906 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.069793462753296 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1198573112487793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0650699138641357 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.066585063934326 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.993173360824585 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0820870399475098 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1202757358551025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0804951190948486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0680675506591797 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.067110776901245 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2086596488952637 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2588233947753906 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2021515369415283 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.11904239654541 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1034247875213623 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1175291538238525 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.133053779602051 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.109179735183716 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.030364751815796 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.168928623199463 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2851669788360596 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:12:22,298] Trial 28 finished with value: 0.7833991951019325 and parameters: {'exponent': 0.90684376487133, 'kernel_type': 'kpq', 'bandwidth': 20.391415582902017, 'diag': False, 'norm_p': 1.6509364529895192, 'reg': 0.0010231700209601784}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.25110602378845215 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2564685344696045 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26164841651916504 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.26958489418029785 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.25710296630859375 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2784006595611572 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27472829818725586 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2703268527984619 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27091479301452637 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2685515880584717 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26453733444213867 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2733125686645508 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27244114875793457 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27390170097351074 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2692451477050781 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2619912624359131 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27053165435791016 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27387309074401855 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27443504333496094 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27123212814331055 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2629270553588867 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27210259437561035 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27100443840026855 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27315211296081543 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:12:30,186] Trial 29 finished with value: 0.7416916575532346 and parameters: {'exponent': 1.0401910067254547, 'kernel_type': 'k2q', 'bandwidth': 72.13494978402385, 'diag': False, 'reg': 0.09143543177038421}. Best is trial 13 with value: 0.7938325381460221.

Using SVD
Time taken for round 4: 0.2703554630279541 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2241263389587402 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.14066219329834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.078112840652466 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0953190326690674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1260578632354736 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.167579412460327 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.082669496536255 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0880377292633057 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.767790794372559 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.263260841369629 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1473546028137207 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1383938789367676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.077457904815674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0824053287506104 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.091872215270996 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.140355110168457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0792629718780518 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1266586780548096 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.082958221435547 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.08372163772583 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.134554147720337 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.785116672515869 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.073826789855957 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0751025676727295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0795891284942627 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:13:33,949] Trial 30 finished with value: 0.7805970656274035 and parameters: {'exponent': 0.8049607914036849, 'kernel_type': 'kpq', 'bandwidth': 6.7287130366937395, 'diag': False, 'norm_p': 1.3587804734443678, 'reg': 0.0001748800130912807}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.177595376968384 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.081573724746704 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0920984745025635 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.075284719467163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0824084281921387 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1630635261535645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.077923059463501 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.107988119125366 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.096924304962158 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0944724082946777 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.100157260894775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0818471908569336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.129887342453003 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.082864284515381 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.082366704940796 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1615498065948486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0761964321136475 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.109537363052368 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.106724739074707 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0826826095581055 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1880605220794678 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0973141193389893 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0830886363983154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0832014083862305 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.077841281890869 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:14:37,900] Trial 31 finished with value: 0.7933751985745449 and parameters: {'exponent': 1.0003064499465613, 'kernel_type': 'kpq', 'bandwidth': 24.709413000695342, 'diag': False, 'norm_p': 1.4945460977248692, 'reg': 0.011461957594382313}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1379363536834717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.10837721824646 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.082021951675415 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0805788040161133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081529140472412 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1738498210906982 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1011247634887695 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.077634572982788 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.078267812728882 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.114809513092041 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.147677183151245 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1179893016815186 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.111664056777954 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.0579259395599365 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0787343978881836 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1367781162261963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0776562690734863 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1072282791137695 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.094832181930542 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0797922611236572 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1323485374450684 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0810225009918213 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0842297077178955 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1094369888305664 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1081488132476807 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:15:38,906] Trial 32 finished with value: 0.7909631726175339 and parameters: {'exponent': 1.0287731517490346, 'kernel_type': 'kpq', 'bandwidth': 21.54080805388585, 'diag': False, 'norm_p': 1.59343505348327, 'reg': 0.0013835548181808403}. Best is trial 13 with value: 0.7938325381460221.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1930782794952393 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1899750232696533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.117878437042236 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0734570026397705 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1146230697631836 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1283624172210693 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0591726303100586 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0598576068878174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0461008548736572 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1002790927886963 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.122953176498413 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.042738199234009 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0660300254821777 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1031558513641357 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.057551145553589 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0989794731140137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.9775707721710205 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.09355092048645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0605361461639404 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0377962589263916 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1060566902160645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.054054021835327 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.041149139404297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.040571451187134 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.042983293533325 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:16:42,325] Trial 33 finished with value: 0.7949874431932923 and parameters: {'exponent': 0.9748663163962683, 'kernel_type': 'kpq', 'bandwidth': 26.53429776988508, 'diag': False, 'norm_p': 1.478267990780107, 'reg': 0.008627607021811742}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1051392555236816 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0635626316070557 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1281707286834717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1519219875335693 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.064178466796875 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.065511226654053 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0415947437286377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0418059825897217 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0411417484283447 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0643696784973145 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0951666831970215 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0398919582366943 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0416693687438965 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0439794063568115 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0399229526519775 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0962507724761963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0409727096557617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.040273427963257 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.044445037841797 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.042544364929199 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.05202054977417 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0521204471588135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.041999340057373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.039236307144165 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.038980484008789 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:17:45,233] Trial 34 finished with value: 0.7554338677062491 and parameters: {'exponent': 1.3908507298350492, 'kernel_type': 'kpq', 'bandwidth': 44.82855785639696, 'diag': False, 'norm_p': 1.5950079153146823, 'reg': 0.046434509265277625}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.089097738265991 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.09859299659729 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.082674980163574 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.0808539390563965 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.0839591026306152 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1565310955047607 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.154634952545166 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1242876052856445 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.186098575592041 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 5.096195459365845 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1552507877349854 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1261179447174072 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1227993965148926 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.195859432220459 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1592910289764404 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1255598068237305 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1278791427612305 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1313183307647705 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.148561954498291 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.2465081214904785 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.2006258964538574 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.160008192062378 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1422834396362305 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 5.078111171722412 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.126163959503174 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:18:50,127] Trial 35 finished with value: 0.7391392539819537 and parameters: {'exponent': 1.139357093535314, 'kernel_type': 'kpq', 'bandwidth': 8.728924856574004, 'diag': True, 'norm_p': 1.4707857065865622, 'reg': 0.2823718044885071}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.24842333793640137 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2572202682495117 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26443934440612793 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2723402976989746 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2594602108001709 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.250333309173584 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.26119470596313477 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26907873153686523 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.278275728225708 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2724735736846924 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26485705375671387 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2720789909362793 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2722506523132324 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2737693786621094 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2722795009613037 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.27857112884521484 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.28361082077026367 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.28957033157348633 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.28975772857666016 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2888906002044678 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.28138160705566406 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.29035258293151855 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2899782657623291 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.29752230644226074 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 4: 0.3050394058227539 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:18:58,207] Trial 36 finished with value: 0.7505092080727913 and parameters: {'exponent': 1.0401095830154794, 'kernel_type': 'k2q', 'bandwidth': 147.73137509292687, 'diag': False, 'reg': 0.011974079492789589}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.316260576248169 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1779308319091797 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0886969566345215 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1342520713806152 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.313744306564331 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2438101768493652 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.112632989883423 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.099522829055786 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.028798341751099 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1653337478637695 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.139942169189453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0777440071105957 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0741195678710938 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.075127601623535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.079226493835449 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2492098808288574 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1029045581817627 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0746827125549316 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.106867551803589 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0746567249298096 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1610422134399414 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.184074878692627 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.0781354904174805 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0986685752868652 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2009589672088623 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:20:03,298] Trial 37 finished with value: 0.7818181846490513 and parameters: {'exponent': 0.7072583895011285, 'kernel_type': 'kpq', 'bandwidth': 16.175560992301836, 'diag': False, 'norm_p': 1.2638113586891881, 'reg': 0.03389558167706755}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1521129608154297 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1429941654205322 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1285502910614014 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1310737133026123 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.140127420425415 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1270065307617188 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.124403476715088 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1248464584350586 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.124434471130371 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.138901710510254 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 5.095208644866943 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.130202293395996 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1291911602020264 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1325652599334717 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.144155740737915 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.133347749710083 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1428632736206055 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.159278154373169 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.18459153175354 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1620962619781494 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1414356231689453 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1264193058013916 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.160857677459717 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.122060537338257 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 5.076287031173706 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:21:08,162] Trial 38 finished with value: 0.708171573661587 and parameters: {'exponent': 0.9759447460451641, 'kernel_type': 'kpq', 'bandwidth': 90.43254083487487, 'diag': True, 'norm_p': 1.4053402263322812, 'reg': 0.12948413930048733}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2547767162322998 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2605931758880615 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26321911811828613 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.26934075355529785 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.26921677589416504 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2631857395172119 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2720780372619629 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2744486331939697 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.272658109664917 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2749326229095459 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2637059688568115 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2713184356689453 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27327847480773926 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27397704124450684 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27320241928100586 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26595258712768555 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2773618698120117 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.275559663772583 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2737865447998047 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27182960510253906 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26295924186706543 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27279186248779297 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2737715244293213 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27279138565063477 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:21:16,079] Trial 39 finished with value: 0.7650478378155299 and parameters: {'exponent': 0.8942591190970749, 'kernel_type': 'k2q', 'bandwidth': 26.079438720142864, 'diag': False, 'reg': 0.0053850709791731}. Best is trial 33 with value: 0.7949874431932923.

Using SVD
Time taken for round 4: 0.274918794631958 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1410892009735107 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.125974178314209 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.127239465713501 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.122434616088867 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1236119270324707 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1388967037200928 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.127068281173706 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1252923011779785 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.129016637802124 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1283154487609863 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1459195613861084 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.131718158721924 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.127150297164917 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.142066478729248 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.126772165298462 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1345574855804443 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.146526575088501 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1268720626831055 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.12658953666687 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1275203227996826 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.127969741821289 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1417148113250732 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.129528284072876 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1223723888397217 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 5.079124450683594 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:22:20,791] Trial 40 finished with value: 0.7717046294968458 and parameters: {'exponent': 1.121817435641387, 'kernel_type': 'kpq', 'bandwidth': 9.865357281420614, 'diag': True, 'norm_p': 1.555559736549482, 'reg': 1.1642352957937218e-06}. Best is trial 33 with value: 0.7949874431932923.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.338876485824585 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.115748405456543 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0791962146759033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0944464206695557 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.079594135284424 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1390810012817383 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.075721502304077 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.081529378890991 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0767130851745605 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0846383571624756 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1401233673095703 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0826144218444824 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.094167470932007 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.7601683139801025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.225356340408325 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1460094451904297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0868873596191406 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.085313558578491 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.082824230194092 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081988573074341 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.132845401763916 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0809617042541504 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0789363384246826 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0801825523376465 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0809202194213867 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:23:21,717] Trial 41 finished with value: 0.7953862554219633 and parameters: {'exponent': 0.9666900127063363, 'kernel_type': 'kpq', 'bandwidth': 24.362727823358433, 'diag': False, 'norm_p': 1.4889846987693494, 'reg': 0.0023018842959205144}. Best is trial 41 with value: 0.7953862554219633.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1370420455932617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.788891553878784 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0942230224609375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.119391679763794 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1062111854553223 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1317265033721924 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.099863052368164 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.080634593963623 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1257307529449463 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0811312198638916 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1348471641540527 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0772485733032227 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0841846466064453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.10406494140625 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0968024730682373 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.0875608921051025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.123553514480591 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1213583946228027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.090123176574707 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1875851154327393 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2771475315093994 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1927595138549805 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1466176509857178 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1467719078063965 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2609806060791016 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:24:26,203] Trial 42 finished with value: 0.795660818422989 and parameters: {'exponent': 0.9442082657883579, 'kernel_type': 'kpq', 'bandwidth': 36.64909822308767, 'diag': False, 'norm_p': 1.466095203633845, 'reg': 0.0024319765702090577}. Best is trial 42 with value: 0.795660818422989.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.233320474624634 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.10433030128479 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.087881326675415 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1153626441955566 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.095492839813232 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1955015659332275 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.113278388977051 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1243698596954346 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1305510997772217 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0659470558166504 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.246405601501465 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.086103677749634 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.097979784011841 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2227702140808105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1040313243865967 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2020177841186523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0791571140289307 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1003713607788086 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.062641382217407 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1188199520111084 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.161781072616577 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.116452932357788 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0520949363708496 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.093703508377075 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.11649751663208 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:25:30,829] Trial 43 finished with value: 0.792585878291697 and parameters: {'exponent': 0.9558303129135332, 'kernel_type': 'kpq', 'bandwidth': 13.245109182645395, 'diag': False, 'norm_p': 1.46528941359044, 'reg': 0.0005278949626490805}. Best is trial 42 with value: 0.795660818422989.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1626250743865967 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0936057567596436 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1074676513671875 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0869996547698975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.086667537689209 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.123296022415161 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0470917224884033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.02833890914917 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.077212333679199 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1119468212127686 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.145068645477295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.096052885055542 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.054720640182495 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0646281242370605 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0458192825317383 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.132911205291748 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0376412868499756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.065568685531616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1126863956451416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0959932804107666 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1324942111968994 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.007249593734741 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0792887210845947 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.072113275527954 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0748651027679443 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:26:34,406] Trial 44 finished with value: 0.796167149321403 and parameters: {'exponent': 0.9205640134127895, 'kernel_type': 'kpq', 'bandwidth': 57.578851736563706, 'diag': False, 'norm_p': 1.4050681380716323, 'reg': 0.002443825456653774}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.24875307083129883 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2546656131744385 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26497387886047363 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.277019739151001 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.26201295852661133 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.24909019470214844 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2572040557861328 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2573685646057129 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2686803340911865 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.25804853439331055 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.25824761390686035 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2673828601837158 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2656850814819336 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27129077911376953 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2671222686767578 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26259779930114746 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27419519424438477 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.28072118759155273 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2806205749511719 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27483057975769043 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2688291072845459 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.26928162574768066 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2737388610839844 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2785027027130127 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:26:42,239] Trial 45 finished with value: 0.7639700649353955 and parameters: {'exponent': 0.916401723547293, 'kernel_type': 'k2q', 'bandwidth': 40.021049370293824, 'diag': False, 'reg': 0.0022190318215019075}. Best is trial 44 with value: 0.796167149321403.

Using SVD
Time taken for round 4: 0.27225160598754883 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.182455062866211 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.04438853263855 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1001973152160645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0485470294952393 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.164828300476074 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1909587383270264 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.000917911529541 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0628867149353027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1370813846588135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1633405685424805 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.233203887939453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1324684619903564 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.154444694519043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1328251361846924 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1240739822387695 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.154651165008545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0659284591674805 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0421741008758545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.044625759124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0346803665161133 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.063024044036865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0632951259613037 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0346105098724365 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0378193855285645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.034801959991455 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:27:46,189] Trial 46 finished with value: 0.7903930963751644 and parameters: {'exponent': 0.8041062271086944, 'kernel_type': 'kpq', 'bandwidth': 58.524870096662454, 'diag': False, 'norm_p': 1.3242495184892265, 'reg': 0.0004464729971966106}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1122024059295654 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1167378425598145 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.096846103668213 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1051928997039795 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1276018619537354 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.087428569793701 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.0804131031036377 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.0830209255218506 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.103543281555176 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.096569299697876 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1053545475006104 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.121628761291504 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1278092861175537 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.113994836807251 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.0974409580230713 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.106139898300171 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.151017904281616 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.2044434547424316 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.2440459728240967 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.138885021209717 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.2973952293395996 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.16566801071167 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.09017014503479 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 5.089920520782471 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.102109670639038 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:28:50,771] Trial 47 finished with value: 0.7665143097411816 and parameters: {'exponent': 0.855449057119493, 'kernel_type': 'kpq', 'bandwidth': 67.34912589102265, 'diag': True, 'norm_p': 1.3974298100792124, 'reg': 0.003228820639869308}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.108590602874756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.037921190261841 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0477283000946045 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.041577100753784 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0719172954559326 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.102631092071533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0660159587860107 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0504958629608154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.05489444732666 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0455968379974365 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1170246601104736 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0558834075927734 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.076822280883789 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.003498315811157 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.044297695159912 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0922329425811768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.050607681274414 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.073680877685547 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.068958282470703 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0591061115264893 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2133939266204834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.120358467102051 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1470377445220947 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1436896324157715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1641039848327637 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:29:51,213] Trial 48 finished with value: 0.7902207379383263 and parameters: {'exponent': 1.0692361465398645, 'kernel_type': 'kpq', 'bandwidth': 95.01284492852149, 'diag': False, 'norm_p': 1.4184830236183106, 'reg': 3.1141060015984965e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1263349056243896 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.0019850730896 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.038104772567749 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0424442291259766 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.045057773590088 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1082334518432617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.059636354446411 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.068122386932373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0526421070098877 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0833730697631836 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1319377422332764 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0383925437927246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.091939926147461 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0475447177886963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0825586318969727 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.104888439178467 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.004490852355957 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0556116104125977 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.056251287460327 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.045748710632324 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0994327068328857 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.048389434814453 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0396392345428467 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.046349287033081 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.059631586074829 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:30:54,228] Trial 49 finished with value: 0.7819975342035068 and parameters: {'exponent': 0.9227595914584238, 'kernel_type': 'kpq', 'bandwidth': 174.17862625489016, 'diag': False, 'norm_p': 1.725252489960632, 'reg': 0.0008369611876540216}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.24836087226867676 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.25741076469421387 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2689080238342285 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2694385051727295 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2661309242248535 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2790641784667969 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2567157745361328 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2577652931213379 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2630183696746826 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 4: 0.26090359687805176 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.25671863555908203 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.26532959938049316 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27121639251708984 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.28554797172546387 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 4: 0.2771885395050049 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2617471218109131 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27124595642089844 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2711448669433594 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27419137954711914 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 4: 0.26788949966430664 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26221513748168945 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2683742046356201 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2701833248138428 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2883634567260742 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 4: 0.28757429122924805 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:31:02,115] Trial 50 finished with value: 0.7633685037607878 and parameters: {'exponent': 0.8924122907197766, 'kernel_type': 'k2q', 'bandwidth': 31.670863640595908, 'diag': False, 'reg': 3.887259864723194e-06}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1279096603393555 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.015169382095337 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.071324110031128 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0553929805755615 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0536017417907715 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.096968173980713 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.063608169555664 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.06585431098938 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.055647850036621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0672078132629395 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.145153760910034 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.054093837738037 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.054323196411133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0641062259674072 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.061375141143799 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0972750186920166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.011058330535889 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0767524242401123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0414042472839355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0436675548553467 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.115023374557495 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0528812408447266 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.047051191329956 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.040478229522705 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.048815965652466 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:32:05,140] Trial 51 finished with value: 0.7921183741214274 and parameters: {'exponent': 0.9610961113071806, 'kernel_type': 'kpq', 'bandwidth': 16.118149775757043, 'diag': False, 'norm_p': 1.4826633791235229, 'reg': 0.014189296963447093}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.094367027282715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.061353921890259 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0678398609161377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0553488731384277 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0567121505737305 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.045609474182129 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.086050033569336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.21148943901062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.084219217300415 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.073942184448242 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.150714874267578 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.041640281677246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.056291103363037 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0464882850646973 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.07228946685791 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1228559017181396 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0571720600128174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.059729814529419 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0905511379241943 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 4.58023738861084 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.131892204284668 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.104869842529297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0967822074890137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.100590944290161 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.135695219039917 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:33:08,323] Trial 52 finished with value: 0.7954451741572077 and parameters: {'exponent': 1.0174122483183947, 'kernel_type': 'kpq', 'bandwidth': 27.519115080684177, 'diag': False, 'norm_p': 1.4492728403528765, 'reg': 0.002025950374937497}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.090385675430298 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0567269325256348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0479578971862793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.080301523208618 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.038163423538208 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1146721839904785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0609138011932373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0608761310577393 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.685289144515991 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0566349029541016 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.106201410293579 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.071953296661377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0970232486724854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0372586250305176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.049381732940674 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.108626365661621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1591665744781494 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1387104988098145 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0865139961242676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0883004665374756 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1551575660705566 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.107978582382202 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.035436153411865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0890042781829834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.091404914855957 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:34:11,467] Trial 53 finished with value: 0.7943926932335069 and parameters: {'exponent': 1.022889375711667, 'kernel_type': 'kpq', 'bandwidth': 53.05177527408895, 'diag': False, 'norm_p': 1.4281994562508684, 'reg': 0.002320139989952119}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1437978744506836 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0829849243164062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0879197120666504 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0884430408477783 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0863051414489746 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1449036598205566 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0904083251953125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.103635787963867 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0882418155670166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0854623317718506 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1501572132110596 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.0437047481536865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.087329149246216 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.090480089187622 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.103346824645996 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1413519382476807 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083946466445923 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0871598720550537 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0841455459594727 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.090757131576538 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1440494060516357 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1059536933898926 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.119255304336548 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.117126226425171 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1051089763641357 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:35:12,491] Trial 54 finished with value: 0.7937681392112639 and parameters: {'exponent': 1.0317832804653666, 'kernel_type': 'kpq', 'bandwidth': 53.61268434616217, 'diag': False, 'norm_p': 1.4348671990704092, 'reg': 0.002193989056152808}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.100227355957031 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0858700275421143 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0867559909820557 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08909273147583 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0907349586486816 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1421844959259033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.090758800506592 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.088585615158081 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1059587001800537 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.088775634765625 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.159968376159668 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083104372024536 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0890355110168457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0890774726867676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.066741466522217 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.141742706298828 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.102048397064209 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.088685989379883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1077563762664795 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0918688774108887 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.147002696990967 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.098909378051758 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1038897037506104 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0891001224517822 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0886759757995605 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:36:16,480] Trial 55 finished with value: 0.7921962293911051 and parameters: {'exponent': 1.0597867475740517, 'kernel_type': 'kpq', 'bandwidth': 28.983126048701994, 'diag': False, 'norm_p': 1.3956797659211435, 'reg': 0.004733248637099782}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.144812822341919 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0880634784698486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.099153995513916 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.0715882778167725 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0922770500183105 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.147080898284912 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0856821537017822 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0891451835632324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.099163293838501 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0917651653289795 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1532716751098633 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.088271141052246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0911076068878174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.091198682785034 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1061348915100098 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1398141384124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1095290184020996 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.037309169769287 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1026875972747803 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0868477821350098 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.143608331680298 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.087985038757324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0865392684936523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0887558460235596 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.08940052986145 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:37:20,463] Trial 56 finished with value: 0.7897652351055136 and parameters: {'exponent': 1.2570380487292578, 'kernel_type': 'kpq', 'bandwidth': 37.13846371123458, 'diag': False, 'norm_p': 1.4365740669425695, 'reg': 0.0026589700429596624}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1566359996795654 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.136737585067749 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.135840654373169 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.15100359916687 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1343605518341064 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1419708728790283 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 5.092904567718506 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.13523268699646 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.142285108566284 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.140549421310425 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1350011825561523 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1392908096313477 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.148646831512451 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1382668018341064 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1406447887420654 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.154607057571411 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1482675075531006 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.138406276702881 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.136262893676758 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.148930788040161 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 5.095775127410889 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1402270793914795 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1497159004211426 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1382198333740234 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.132871389389038 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:38:25,411] Trial 57 finished with value: 0.747700063074086 and parameters: {'exponent': 1.013851136847297, 'kernel_type': 'kpq', 'bandwidth': 49.98503934493676, 'diag': True, 'norm_p': 1.3177119852736618, 'reg': 0.00025460675143993723}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1588335037231445 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0887458324432373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0877745151519775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.087663173675537 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.103605031967163 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1436522006988525 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0914039611816406 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0879411697387695 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.10349178314209 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.050718307495117 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1435627937316895 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.088254690170288 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0885164737701416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0859429836273193 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0950543880462646 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1490864753723145 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0885918140411377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0894594192504883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.087353229522705 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.101616382598877 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1443190574645996 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0897059440612793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.09074330329895 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.059834241867065 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0861659049987793 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:39:29,417] Trial 58 finished with value: 0.7908553362378473 and parameters: {'exponent': 1.0864098331604093, 'kernel_type': 'kpq', 'bandwidth': 18.400112279537684, 'diag': False, 'norm_p': 1.3930049696501754, 'reg': 0.0009918701850567327}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.227574586868286 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1271088123321533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.094512462615967 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126805067062378 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0862419605255127 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2312557697296143 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0928454399108887 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.095644950866699 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0924618244171143 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1299431324005127 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1724889278411865 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.045088768005371 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.091909885406494 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.11464524269104 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1146857738494873 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.164919853210449 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1551015377044678 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1124536991119385 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0971179008483887 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.097219467163086 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1721112728118896 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1079864501953125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0953891277313232 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1206257343292236 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.098618984222412 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:40:30,997] Trial 59 finished with value: 0.7832453422778434 and parameters: {'exponent': 0.9345698369209406, 'kernel_type': 'kpq', 'bandwidth': 75.40728860437564, 'diag': False, 'norm_p': 1.3662892522264272, 'reg': 0.02687727976550331}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.108700513839722 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0928828716278076 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0905396938323975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1091909408569336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0868396759033203 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.155665636062622 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0872890949249268 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.088268995285034 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0920021533966064 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.133544445037842 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2346625328063965 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.18985652923584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1884284019470215 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.221445322036743 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.105813026428223 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1893327236175537 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0733144283294678 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1434688568115234 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1925759315490723 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2032649517059326 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.310392141342163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.173865795135498 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1729514598846436 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.172586679458618 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1762847900390625 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:41:36,370] Trial 60 finished with value: 0.7905588019136492 and parameters: {'exponent': 0.8339712233027822, 'kernel_type': 'kpq', 'bandwidth': 27.032920937853074, 'diag': False, 'norm_p': 1.2753945243408735, 'reg': 0.000569794890103889}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2292182445526123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0869054794311523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1802470684051514 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.052731275558472 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1845157146453857 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.264305830001831 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.125617027282715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1227378845214844 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1264944076538086 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0973401069641113 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2575013637542725 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1705944538116455 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1748340129852295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.197558879852295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.195835828781128 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2543087005615234 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.682624578475952 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.219158172607422 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.22204852104187 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2256712913513184 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.293684720993042 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.246809482574463 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.189085006713867 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.169038772583008 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.169546604156494 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:42:42,210] Trial 61 finished with value: 0.7928900320274358 and parameters: {'exponent': 0.9743527166004943, 'kernel_type': 'kpq', 'bandwidth': 36.92993702614398, 'diag': False, 'norm_p': 1.5402106608090416, 'reg': 0.004512117023066186}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.228231191635132 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.17163348197937 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1724562644958496 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.170250415802002 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.172877550125122 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2300682067871094 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.168086290359497 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1697354316711426 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.168898105621338 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1860787868499756 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.229238986968994 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1677327156066895 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.183053731918335 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.184847354888916 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2048165798187256 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1423563957214355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083332061767578 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.083544969558716 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.03741455078125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1271817684173584 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.177776575088501 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1246109008789062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0948565006256104 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1332430839538574 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1040232181549072 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:43:47,276] Trial 62 finished with value: 0.7871859302544315 and parameters: {'exponent': 0.8752592193910702, 'kernel_type': 'kpq', 'bandwidth': 95.81134972800454, 'diag': False, 'norm_p': 1.5917617096945833, 'reg': 0.008422634216197102}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1699342727661133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2058639526367188 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.166962146759033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.150261402130127 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1894397735595703 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1709518432617188 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.135925054550171 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.058500051498413 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2312843799591064 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1607813835144043 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.165834665298462 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0914957523345947 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0953376293182373 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0980188846588135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2964541912078857 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1365957260131836 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.120267391204834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0923819541931152 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1277453899383545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0893020629882812 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.150470018386841 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.06664514541626 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1102590560913086 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.106231451034546 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.109184980392456 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:44:52,344] Trial 63 finished with value: 0.7941901999255014 and parameters: {'exponent': 1.0132753703586617, 'kernel_type': 'kpq', 'bandwidth': 22.425331905223473, 'diag': False, 'norm_p': 1.4526007101885918, 'reg': 9.020882897032756e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.162100315093994 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.082603931427002 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1088709831237793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.106163740158081 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1217217445373535 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1557259559631348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1143276691436768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1030027866363525 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0861666202545166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1131176948547363 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1539018154144287 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.114175796508789 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0926802158355713 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0896992683410645 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1295337677001953 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.165128707885742 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.086149215698242 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.085024356842041 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.108914613723755 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1060760021209717 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1436960697174072 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.100813865661621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1548409461975098 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0929296016693115 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.074527740478516 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:45:56,654] Trial 64 finished with value: 0.7944826562636516 and parameters: {'exponent': 1.0143752025407047, 'kernel_type': 'kpq', 'bandwidth': 20.788089244563636, 'diag': False, 'norm_p': 1.449817535160879, 'reg': 0.00030595056902875547}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1730003356933594 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1246137619018555 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.107879877090454 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0943849086761475 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.094240188598633 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.148390769958496 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1103928089141846 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.089667558670044 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1057684421539307 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.090003728866577 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1547021865844727 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0899205207824707 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.065648794174194 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0881495475769043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1250243186950684 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.170804500579834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0843234062194824 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1062915325164795 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126741647720337 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0818443298339844 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1558964252471924 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.102344036102295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1074931621551514 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0917367935180664 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0960841178894043 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:46:57,926] Trial 65 finished with value: 0.7921748372651332 and parameters: {'exponent': 0.9647321528260249, 'kernel_type': 'kpq', 'bandwidth': 14.963247118184237, 'diag': False, 'norm_p': 1.4349973691926206, 'reg': 0.0014575377774848314}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1489458084106445 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.042412757873535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1076016426086426 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1028549671173096 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1072919368743896 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2015726566314697 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.13581919670105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0938096046447754 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1019749641418457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0877039432525635 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1805286407470703 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0937857627868652 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0936179161071777 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.089932680130005 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.109727382659912 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.095882177352905 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.096379041671753 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0909762382507324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.105722188949585 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09037184715271 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1409966945648193 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.093182325363159 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1063015460968018 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.089909553527832 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.08907413482666 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:48:02,099] Trial 66 finished with value: 0.795586221899785 and parameters: {'exponent': 1.0551156998537288, 'kernel_type': 'kpq', 'bandwidth': 45.648092203151364, 'diag': False, 'norm_p': 1.5166497902786087, 'reg': 0.00025186575550824384}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1553330421447754 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.096773624420166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.087925672531128 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126344680786133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.045361518859863 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.143808603286743 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0823845863342285 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0906901359558105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0896682739257812 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0892820358276367 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1594748497009277 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0887022018432617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0926432609558105 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.091837167739868 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1052017211914062 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.14854097366333 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0876739025115967 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0861876010894775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.065313100814819 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09071683883667 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1428492069244385 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0871782302856445 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0865509510040283 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.078615427017212 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081080198287964 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:49:06,060] Trial 67 finished with value: 0.7943024258456253 and parameters: {'exponent': 1.105682280604408, 'kernel_type': 'kpq', 'bandwidth': 31.378986334476807, 'diag': False, 'norm_p': 1.5098612077583344, 'reg': 0.0002928712064974874}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.147482395172119 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.079676389694214 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.112680673599243 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.084324359893799 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1006715297698975 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1451385021209717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1013081073760986 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.035629034042358 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.089956283569336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.085906505584717 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1461129188537598 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0876247882843018 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.087285041809082 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.105894088745117 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0896949768066406 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1411004066467285 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083669900894165 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.086409568786621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0892539024353027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0847957134246826 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1573145389556885 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.044179201126099 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.08699631690979 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0865368843078613 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0914134979248047 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:50:09,972] Trial 68 finished with value: 0.7927573049552973 and parameters: {'exponent': 1.1631308979032169, 'kernel_type': 'kpq', 'bandwidth': 19.416842970828935, 'diag': False, 'norm_p': 1.4754254947276237, 'reg': 0.0001130978525341914}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2501688003540039 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2613091468811035 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26032161712646484 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.28264689445495605 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27497363090515137 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26470327377319336 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2689969539642334 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27339982986450195 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2757444381713867 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.272158145904541 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2823920249938965 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2897911071777344 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27577853202819824 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2751123905181885 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2753570079803467 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26715588569641113 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2726569175720215 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27031397819519043 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2767183780670166 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27522873878479004 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2687547206878662 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27221083641052246 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2715799808502197 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.28267502784729004 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 22:50:17,964] Trial 69 finished with value: 0.7629313432012209 and parameters: {'exponent': 1.06404501086156, 'kernel_type': 'k2q', 'bandwidth': 45.93696622712074, 'diag': False, 'reg': 0.0001562809730738762}. Best is trial 44 with value: 0.796167149321403.

Using SVD
Time taken for round 4: 0.2724606990814209 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1537058353424072 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.084639072418213 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.083635091781616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0839431285858154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0839920043945312 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1586649417877197 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.103713035583496 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0866334438323975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.087646961212158 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0803024768829346 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.3425769805908203 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2920982837677 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.2860617637634277 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.915030479431152 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.46458101272583 seconds

Building trees:   0%|          | 0/1 [00:16<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.3426849842071533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.280117988586426 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.281543493270874 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2820956707000732 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2794289588928223 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.350097894668579 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2716829776763916 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.247626304626465 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0870330333709717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0857949256896973 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:51:22,455] Trial 70 finished with value: 0.7919255449744134 and parameters: {'exponent': 0.9432525771325867, 'kernel_type': 'kpq', 'bandwidth': 62.5698654157912, 'diag': False, 'norm_p': 1.5622488224608682, 'reg': 0.00032466637995303153}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.143543243408203 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.651721715927124 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.087080955505371 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.088831901550293 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.087686061859131 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1370108127593994 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.082706928253174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0830495357513428 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.095085859298706 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.078683376312256 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.145890951156616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0776705741882324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.162749767303467 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1811485290527344 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1653811931610107 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.3389153480529785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.314094066619873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.308412551879883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.3001644611358643 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.306905508041382 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.3366448879241943 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.13665771484375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0884742736816406 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08829927444458 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.086981773376465 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:52:25,623] Trial 71 finished with value: 0.7952137738810758 and parameters: {'exponent': 1.0501990282047877, 'kernel_type': 'kpq', 'bandwidth': 36.532276838944775, 'diag': False, 'norm_p': 1.5185959403167855, 'reg': 0.0025771151723959418}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1439552307128906 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0805718898773193 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1014747619628906 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0878875255584717 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 3.6097500324249268 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1432547569274902 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.085108518600464 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1031253337860107 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0819358825683594 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0851268768310547 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1403210163116455 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1800801753997803 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.2341713905334473 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1484375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1290204524993896 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1884758472442627 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.132436990737915 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.098480224609375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1753649711608887 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2106573581695557 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.22344970703125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1115050315856934 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.109302282333374 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.098576545715332 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1005630493164062 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:53:29,066] Trial 72 finished with value: 0.7939356976295149 and parameters: {'exponent': 1.0510434725897455, 'kernel_type': 'kpq', 'bandwidth': 35.370897696344635, 'diag': False, 'norm_p': 1.5120006458077675, 'reg': 0.0007174813321261882}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2267181873321533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1822621822357178 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.178271770477295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.163740634918213 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.193120002746582 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1799583435058594 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.92763090133667 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.09104585647583 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1224207878112793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.153200387954712 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.126704454421997 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0676565170288086 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1162712574005127 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2123472690582275 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1587486267089844 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.252617359161377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.161907196044922 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.176248550415039 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.315678596496582 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1900787353515625 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.354771375656128 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.3261377811431885 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.164926290512085 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.167132616043091 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1667723655700684 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]
[I 2026-04-22 22:54:34,811] Trial 73 finished with value: 0.7930352523536959 and parameters: {'exponent': 0.9936843309155358, 'kernel_type': 'kpq', 'bandwidth': 26.166083327688014, 'diag': False, 'norm_p': 1.493991980558172, 'reg': 0.0012795136728719547}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2567014694213867 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.195389747619629 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.198840379714966 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.206176280975342 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.2366690635681152 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.285571336746216 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.222635269165039 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.209946870803833 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.448122501373291 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.282628297805786 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2549684047698975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0898313522338867 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.081164836883545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.075286865234375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.12398362159729 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1280765533447266 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0880064964294434 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0753743648529053 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.096562623977661 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0714287757873535 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1289751529693604 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 4.865185737609863 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.074357748031616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1753413677215576 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.116074800491333 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:55:39,430] Trial 74 finished with value: 0.7900233210494114 and parameters: {'exponent': 1.1106865634313785, 'kernel_type': 'kpq', 'bandwidth': 23.025281887411012, 'diag': False, 'norm_p': 1.6200096452970127, 'reg': 0.00811541487391396}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.256312131881714 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1916093826293945 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0777039527893066 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.3063511848449707 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.104360580444336 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1473593711853027 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0900685787200928 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0756478309631348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.096188545227051 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.10660982131958 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.098701477050781 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0872244834899902 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0939128398895264 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.100470781326294 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0959532260894775 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.150926113128662 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.09189510345459 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.101477861404419 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0793604850769043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1015172004699707 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.150716781616211 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1236894130706787 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1025164127349854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1090142726898193 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.041355848312378 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 22:56:43,867] Trial 75 finished with value: 0.7939637218555429 and parameters: {'exponent': 0.9288804426640441, 'kernel_type': 'kpq', 'bandwidth': 44.34034021035398, 'diag': False, 'norm_p': 1.522784214741441, 'reg': 0.0032393500395540716}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.216038465499878 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0783283710479736 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0733513832092285 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0938563346862793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0731570720672607 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1319358348846436 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0733745098114014 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0890355110168457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0889477729797363 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0763721466064453 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1344070434570312 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0835814476013184 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.088527202606201 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 4.9533655643463135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.077491044998169 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1559112071990967 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.08949875831604 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1077651977539062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0839011669158936 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1105659008026123 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1574721336364746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0863287448883057 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.099388599395752 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1081531047821045 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.100266218185425 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:57:44,788] Trial 76 finished with value: 0.7939243995552991 and parameters: {'exponent': 0.8943691047035109, 'kernel_type': 'kpq', 'bandwidth': 29.813836847349226, 'diag': False, 'norm_p': 1.347364275452953, 'reg': 0.0018319950416734892}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.157313823699951 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1389870643615723 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 5.108833074569702 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.137657642364502 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1314570903778076 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.127225160598755 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.156921625137329 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1420981884002686 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1615278720855713 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1431565284729004 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.141298770904541 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.14070463180542 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1251943111419678 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.1417343616485596 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.147127866744995 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1491708755493164 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 5.105233430862427 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1632883548736572 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.147116184234619 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.154261350631714 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.130169153213501 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1326303482055664 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.137718677520752 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.183107376098633 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.158137321472168 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:58:49,880] Trial 77 finished with value: 0.7693800634155882 and parameters: {'exponent': 0.987590151211645, 'kernel_type': 'kpq', 'bandwidth': 39.1971158909425, 'diag': True, 'norm_p': 1.461075249066011, 'reg': 0.0010149430202537884}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.149306297302246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.108011484146118 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1066277027130127 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0765974521636963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0827174186706543 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.143611431121826 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.111708879470825 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.083625316619873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0813138484954834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0913071632385254 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1328911781311035 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0927894115448 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1134183406829834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1035332679748535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1026041507720947 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1886351108551025 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.143605947494507 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0894076824188232 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0826377868652344 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.100571632385254 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.195755958557129 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0869855880737305 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.082841634750366 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0910017490386963 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.095489501953125 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 22:59:54,077] Trial 78 finished with value: 0.7884488429173204 and parameters: {'exponent': 1.0148190081138209, 'kernel_type': 'kpq', 'bandwidth': 10.719363484944846, 'diag': False, 'norm_p': 1.5639042265125442, 'reg': 0.0064771400954517205}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.153311014175415 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0843327045440674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1720759868621826 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.094050407409668 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.088693618774414 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.169332265853882 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0864551067352295 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0884554386138916 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.069150924682617 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1785099506378174 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.168642044067383 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.076691150665283 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0768003463745117 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0800158977508545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0782597064971924 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1289138793945312 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0985398292541504 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.213979959487915 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.171692132949829 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.128232717514038 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.189342975616455 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.079214811325073 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.112356185913086 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0796782970428467 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0845394134521484 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:00:58,542] Trial 79 finished with value: 0.7895058024731056 and parameters: {'exponent': 1.0787074664634773, 'kernel_type': 'kpq', 'bandwidth': 18.39857667284766, 'diag': False, 'norm_p': 1.3768254101512953, 'reg': 0.000588847854235133}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.156489133834839 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.086320638656616 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.084376811981201 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0830931663513184 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1593050956726074 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1826443672180176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1079764366149902 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0852932929992676 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0882608890533447 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1010067462921143 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.086820602416992 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.138181447982788 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1869828701019287 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.194340229034424 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.178581714630127 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.243845224380493 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1664979457855225 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.181025266647339 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1830317974090576 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0984790325164795 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.169785499572754 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1048309803009033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.117393970489502 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1559641361236572 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.03960919380188 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:02:03,496] Trial 80 finished with value: 0.7827257034807574 and parameters: {'exponent': 1.1507710300811131, 'kernel_type': 'kpq', 'bandwidth': 61.61681792250724, 'diag': False, 'norm_p': 1.4824204985579137, 'reg': 0.01631333869036932}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1684272289276123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1373462677001953 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0931038856506348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0957987308502197 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.128488063812256 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.163367748260498 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.076345205307007 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1163852214813232 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1230249404907227 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0953116416931152 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1446187496185303 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0822455883026123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0825555324554443 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.051920175552368 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1291346549987793 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1475977897644043 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.085391044616699 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0871150493621826 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0845296382904053 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.103684663772583 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1530396938323975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1428894996643066 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0771327018737793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.101022243499756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.159956216812134 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:03:04,827] Trial 81 finished with value: 0.7943784220417833 and parameters: {'exponent': 1.0219660533584782, 'kernel_type': 'kpq', 'bandwidth': 55.36828197347152, 'diag': False, 'norm_p': 1.4264140121765145, 'reg': 0.002267585948702634}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.182370901107788 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1169016361236572 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.116295337677002 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.153397798538208 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081951856613159 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.138277769088745 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.177156925201416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1285910606384277 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1402204036712646 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.179337739944458 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1688499450683594 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.145517110824585 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.200873374938965 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.126826524734497 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.202648878097534 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.243113040924072 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.123539447784424 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.3563501834869385 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.301464796066284 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.219776153564453 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2885453701019287 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1153616905212402 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1262619495391846 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1675775051116943 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.154752254486084 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:04:10,892] Trial 82 finished with value: 0.77299243867521 and parameters: {'exponent': 0.9547200896732263, 'kernel_type': 'kpq', 'bandwidth': 3.9212707769747377, 'diag': False, 'norm_p': 1.4533518734558415, 'reg': 0.0001879812682227179}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.206197500228882 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1060454845428467 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1056180000305176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1376168727874756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 4.690181732177734 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1973347663879395 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.140138864517212 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.145357131958008 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.2740232944488525 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.243661403656006 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.271054983139038 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.209221839904785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.216738700866699 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0886476039886475 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1189992427825928 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.147526502609253 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1341712474823 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 4.823370456695557 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1932265758514404 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1772348880767822 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2390851974487305 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.176363706588745 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1754977703094482 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.192469596862793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1723008155822754 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:05:16,151] Trial 83 finished with value: 0.7934185506428266 and parameters: {'exponent': 1.0439338998815393, 'kernel_type': 'kpq', 'bandwidth': 47.800257650488916, 'diag': False, 'norm_p': 1.5314084463886724, 'reg': 0.003643915131526223}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.240042209625244 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.169637441635132 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1848502159118652 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1544930934906006 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.096088409423828 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1668155193328857 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.0217626094818115 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.097360134124756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1138031482696533 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.173313856124878 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.229367971420288 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1781768798828125 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.170137643814087 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1655755043029785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.176064968109131 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.229022264480591 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1224000453948975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.106812000274658 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0914368629455566 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.089709520339966 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.159390687942505 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.082824945449829 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0856778621673584 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.084693670272827 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0903804302215576 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:06:21,173] Trial 84 finished with value: 0.7949162678975107 and parameters: {'exponent': 1.0021835461781212, 'kernel_type': 'kpq', 'bandwidth': 42.09042828767181, 'diag': False, 'norm_p': 1.4152716878908447, 'reg': 0.0004032099359174129}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2527046203613281 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.26018619537353516 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2639179229736328 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.26769471168518066 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2599639892578125 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2517976760864258 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.26144933700561523 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2640373706817627 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.26815152168273926 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2615785598754883 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.25171756744384766 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27120399475097656 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2736659049987793 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2779080867767334 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2711155414581299 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2626945972442627 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.29021286964416504 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27900266647338867 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2765023708343506 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.273068904876709 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2664914131164551 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2719693183898926 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.2730832099914551 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2759718894958496 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 23:06:29,049] Trial 85 finished with value: 0.7622031792566146 and parameters: {'exponent': 0.9714326004382674, 'kernel_type': 'k2q', 'bandwidth': 33.96909547361028, 'diag': False, 'reg': 0.0003611448381159393}. Best is trial 44 with value: 0.796167149321403.

Using SVD
Time taken for round 4: 0.2748239040374756 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.19451642036438 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.082634687423706 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1240148544311523 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1724836826324463 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1813254356384277 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.1410088539123535 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1382086277008057 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.128392219543457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1076292991638184 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.204017162322998 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2372820377349854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.2293193340301514 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.165616750717163 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1737351417541504 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1083014011383057 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.261976718902588 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.181389808654785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.165179967880249 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1656265258789062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.1230149269104 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2211687564849854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1334633827209473 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.161208152770996 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.181255340576172 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.157660722732544 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:07:34,814] Trial 86 finished with value: 0.7946217015800008 and parameters: {'exponent': 0.998726923453602, 'kernel_type': 'kpq', 'bandwidth': 41.193106600763194, 'diag': False, 'norm_p': 1.4140142957364512, 'reg': 0.0007594803133491242}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2233338356018066 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.177471876144409 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1788179874420166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.19107723236084 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1645755767822266 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2217907905578613 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1621601581573486 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.124465465545654 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1659371852874756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1654212474823 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2276501655578613 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.166083812713623 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.167860269546509 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.182323455810547 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.180947780609131 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2380385398864746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.168233633041382 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.185903787612915 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1765244007110596 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.146726608276367 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.186185359954834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1739542484283447 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.160975933074951 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1595571041107178 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.15722918510437 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:08:40,932] Trial 87 finished with value: 0.7941880181995816 and parameters: {'exponent': 0.9064284770796723, 'kernel_type': 'kpq', 'bandwidth': 41.72973524503396, 'diag': False, 'norm_p': 1.3209164521597316, 'reg': 0.0007027651491990081}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.212301254272461 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.211805582046509 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.212327003479004 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.2055697441101074 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.215733051300049 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.2112984657287598 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.233452796936035 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.2183802127838135 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.212669849395752 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 5.112121820449829 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1327569484710693 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1291513442993164 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.145146608352661 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.128746747970581 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1283388137817383 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.1468558311462402 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.135077714920044 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1298270225524902 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 2.143402576446533 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1304678916931152 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Time taken for round 0: 2.149456739425659 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 1: 2.1417412757873535 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 2: 2.1303153038024902 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 3: 5.083337783813477 seconds
Using expensive batch size
Optimal M batch size: 398
Time taken for round 4: 2.1300222873687744 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:09:46,494] Trial 88 finished with value: 0.7643623105473556 and parameters: {'exponent': 0.993300103792462, 'kernel_type': 'kpq', 'bandwidth': 82.34351456907767, 'diag': True, 'norm_p': 1.4079211236508133, 'reg': 0.0014122736645819894}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.140443801879883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0786752700805664 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0817854404449463 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0831029415130615 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081058979034424 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1377646923065186 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0803654193878174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0799317359924316 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.095581293106079 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0787413120269775 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.139463186264038 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.078827381134033 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.038665771484375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.094304323196411 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.078843116760254 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1400606632232666 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.079831838607788 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.093130111694336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0826573371887207 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0856540203094482 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1425745487213135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0788092613220215 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0941386222839355 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.080018997192383 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0793821811676025 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:10:47,270] Trial 89 finished with value: 0.7880386755158133 and parameters: {'exponent': 1.0424907134689123, 'kernel_type': 'kpq', 'bandwidth': 68.25001291900065, 'diag': False, 'norm_p': 1.3824964170185274, 'reg': 0.009843385035625546}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.070359706878662 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.035395622253418 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0815484523773193 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0920052528381348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081737518310547 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0694925785064697 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0775818824768066 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.078707695007324 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.081881046295166 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0946431159973145 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0670130252838135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0804946422576904 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0757710933685303 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.080948829650879 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0819685459136963 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.027134656906128 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083544969558716 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0824437141418457 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0971760749816895 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0969738960266113 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.0677595138549805 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0959737300872803 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.079533338546753 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1767396926879883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0950751304626465 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:11:50,782] Trial 90 finished with value: 0.7699853979165046 and parameters: {'exponent': 0.9454146738787652, 'kernel_type': 'kpq', 'bandwidth': 28.85761224991209, 'diag': False, 'norm_p': 0.9692360691436762, 'reg': 0.001079657771618184}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.244633674621582 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.15263032913208 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.142123222351074 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0768191814422607 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.096536874771118 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2419915199279785 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.098856210708618 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.092482328414917 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.099376678466797 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0896785259246826 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1598405838012695 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.086118698120117 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1043760776519775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.086428165435791 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.103386640548706 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1428864002227783 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0843911170959473 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.089228868484497 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.0633955001831055 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0796780586242676 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.273361921310425 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.161113977432251 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1759748458862305 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1813085079193115 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1224617958068848 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:12:55,582] Trial 91 finished with value: 0.7934520365690156 and parameters: {'exponent': 1.0014197359500656, 'kernel_type': 'kpq', 'bandwidth': 24.074832223843547, 'diag': False, 'norm_p': 1.4909098481838547, 'reg': 0.00025427900494442876}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1491177082061768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.101055383682251 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0941593647003174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1100895404815674 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1261401176452637 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.2188637256622314 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.106003046035767 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.097290515899658 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0763344764709473 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.099299430847168 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.15244197845459 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1009361743927 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.084629774093628 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08416748046875 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.083040714263916 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1377947330474854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0900001525878906 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0824942588806152 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.081912040710449 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0816457271575928 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.09737491607666 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.080519199371338 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.095311403274536 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.155496597290039 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.080972194671631 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:13:59,735] Trial 92 finished with value: 0.790158063972962 and parameters: {'exponent': 1.0548708812817518, 'kernel_type': 'kpq', 'bandwidth': 34.490154461991004, 'diag': False, 'norm_p': 1.4145432997527092, 'reg': 0.00042329041182498985}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.138873338699341 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0803208351135254 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0840418338775635 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0960843563079834 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0812339782714844 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1403911113739014 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0833513736724854 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.079793930053711 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0918936729431152 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1151740550994873 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1718249320983887 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.19735050201416 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.117905378341675 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.112123727798462 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.1107258796691895 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.150344133377075 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0796751976013184 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1100471019744873 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08105206489563 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.083806037902832 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.151125431060791 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.076904296875 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.092665672302246 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0784788131713867 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 4.770082950592041 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:15:03,412] Trial 93 finished with value: 0.7924908565630121 and parameters: {'exponent': 1.0958655491053029, 'kernel_type': 'kpq', 'bandwidth': 21.178645157046343, 'diag': False, 'norm_p': 1.4664471979053904, 'reg': 0.005700597555342646}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1402275562286377 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.091907262802124 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.075212240219116 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0824830532073975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0948896408081055 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.136415958404541 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0819993019104004 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0764284133911133 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.082003593444824 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081259250640869 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1366145610809326 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0809881687164307 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0802314281463623 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.036167144775391 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.079523801803589 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.136946678161621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0979137420654297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.080383777618408 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.077134847640991 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.081446647644043 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.137136697769165 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0797674655914307 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0841028690338135 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.099017858505249 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0778017044067383 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:16:04,178] Trial 94 finished with value: 0.7948761781641659 and parameters: {'exponent': 0.982299098561792, 'kernel_type': 'kpq', 'bandwidth': 41.00715271628415, 'diag': False, 'norm_p': 1.4472929210738423, 'reg': 8.49272469118543e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1396000385284424 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.077765703201294 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.031895399093628 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.081785202026367 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0795748233795166 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1378986835479736 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0755434036254883 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0845043659210205 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.094244956970215 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0813772678375244 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1385626792907715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0789589881896973 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0788824558258057 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0972347259521484 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0765156745910645 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 5.087865352630615 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0823559761047363 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0812175273895264 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.083324432373047 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0858945846557617 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1414928436279297 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0838801860809326 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.081017017364502 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0824999809265137 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0845274925231934 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:17:07,876] Trial 95 finished with value: 0.7322354402551445 and parameters: {'exponent': 0.9731929036378437, 'kernel_type': 'kpq', 'bandwidth': 40.39937336006869, 'diag': False, 'norm_p': 1.3520257445719686, 'reg': 0.9639841349954489}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.138751983642578 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0768544673919678 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0957233905792236 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0809762477874756 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0821497440338135 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1503524780273438 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0803422927856445 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0912435054779053 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.082376003265381 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.099271297454834 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.136662244796753 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0983729362487793 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.077176332473755 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0833044052124023 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09442400932312 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1394801139831543 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0835769176483154 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0820326805114746 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0871059894561768 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 5.040887117385864 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1418728828430176 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0874671936035156 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.083556890487671 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.1016225814819336 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0846190452575684 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]
[I 2026-04-22 23:18:11,689] Trial 96 finished with value: 0.7926992866492021 and parameters: {'exponent': 0.9144314271978129, 'kernel_type': 'kpq', 'bandwidth': 48.004848199457, 'diag': False, 'norm_p': 1.5385836229174708, 'reg': 3.468508754884916e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.144028902053833 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0814719200134277 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.099902391433716 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08442759513855 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.087588310241699 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1512510776519775 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.084730386734009 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.084409236907959 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 5.040647268295288 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0831823348999023 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1553025245666504 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0836949348449707 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0825884342193604 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.085148334503174 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.09722638130188 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1365163326263428 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0985310077667236 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.0970306396484375 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.11008882522583 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0850045680999756 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1385693550109863 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.083989381790161 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.038062334060669 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.08648681640625 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0865325927734375 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:19:15,556] Trial 97 finished with value: 0.7947519443404323 and parameters: {'exponent': 0.957324147122395, 'kernel_type': 'kpq', 'bandwidth': 57.5472392145011, 'diag': False, 'norm_p': 1.4983553596218042, 'reg': 5.9936448685996015e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26828551292419434 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.2732813358306885 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27160215377807617 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2723734378814697 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27570462226867676 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2641890048980713 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27614474296569824 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.27196311950683594 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.27300047874450684 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.27127599716186523 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.26244354248046875 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.27150630950927734 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.26903438568115234 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.2783849239349365 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.2737720012664795 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2662961483001709 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.28949761390686035 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.29094433784484863 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.29247045516967773 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Using SVD
Time taken for round 4: 0.29125213623046875 seconds
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 0: 0.2842836380004883 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 1: 0.295055627822876 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 2: 0.29274606704711914 seconds
Using cheap batch size
Optimal M batch size: 2659
Using SVD
Time taken for round 3: 0.29044556617736816 seconds
Using cheap batch size
Optimal M batch size: 2659

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]
[I 2026-04-22 23:19:23,715] Trial 98 finished with value: 0.7626814419355992 and parameters: {'exponent': 0.939457219978376, 'kernel_type': 'k2q', 'bandwidth': 56.73221789823231, 'diag': False, 'reg': 6.991999084278742e-05}. Best is trial 44 with value: 0.796167149321403.

Using SVD
Time taken for round 4: 0.2913837432861328 seconds
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.152301549911499 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0860230922698975 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.091010570526123 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.108508586883545 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.083778142929077 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.141627073287964 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.081007719039917 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 5.042667627334595 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0845718383789062 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.088221549987793 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1532959938049316 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.0833868980407715 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1005332469940186 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0818257331848145 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0857884883880615 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.153658151626587 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.1086411476135254 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.084683656692505 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.0883066654205322 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.085293769836426 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1429085731506348 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 5.048088312149048 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.08471941947937 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.10334849357605 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0889265537261963 seconds

Building trees:   0%|          | 0/1 [00:14<?, ?it/s]
[I 2026-04-22 23:20:27,638] Trial 99 finished with value: 0.7953358242990728 and parameters: {'exponent': 0.9581952058375022, 'kernel_type': 'kpq', 'bandwidth': 31.77149139542352, 'diag': False, 'norm_p': 1.497244663805375, 'reg': 2.0713835983453015e-05}. Best is trial 44 with value: 0.796167149321403.

Tree has no split, stopping training
Using hard routing for tree prediction
Best params: {'exponent': 0.9205640134127895, 'kernel_type': 'kpq', 'bandwidth': 57.578851736563706, 'diag': False, 'norm_p': 1.4050681380716323, 'reg': 0.002443825456653774}
Best macro F1: 0.796167149321403

In [8]:
model, pipeline, fit_time, train_metrics, val_metrics = fit_best_xrfm(
    X,
    y,
    best_trial,
    processor,
    n_num_cols,
    task=cfg["task"],
    device=device,
)

print(f"Training time: {fit_time:.2f}s")
print(
    f"Train Accuracy: {train_metrics['accuracy']:.4f}  AUC-ROC: {train_metrics['auc_roc']:.4f}"
)
print(
    f"Val Accuracy: {val_metrics['accuracy']:.4f}  AUC-ROC: {val_metrics['auc_roc']:.4f}"
)

joblib.dump(model, MODELS_DIR / data_name / "xrfm.joblib")
joblib.dump(pipeline, MODELS_DIR / data_name / "xrfm_pipeline.joblib")

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 12800, d: 70, and nval: 3200
======================================================================
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 0: 2.1988418102264404 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 1: 2.137434959411621 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 2: 2.1404078006744385 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 3: 2.140713930130005 seconds
Using expensive batch size
Optimal M batch size: 398
Using SVD
Time taken for round 4: 2.0965147018432617 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

Using hard routing for tree prediction
Training time: 11.61s
Train Accuracy: 1.0000  AUC-ROC: 1.0000
Val Accuracy: 0.8859  AUC-ROC: 0.9743

['/home/shado/college_project/comp9417/9417GroupProject/models/sleep_health/xrfm_pipeline.joblib']

In [9]:
model = joblib.load(MODELS_DIR / data_name / "xrfm.joblib")
pipeline = joblib.load(MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [10]:
X_test = test_df.drop(columns=metadata["target_col"])
y_test = le.transform(test_df[metadata["target_col"]]).astype(np.int32)

X_test = pipeline.transform(X_test)
t0 = time.perf_counter()
y_proba = model.predict_proba(X_test)
infer_time = (time.perf_counter() - t0) / len(X_test)

Using hard routing for tree prediction

In [11]:
results = evaluate_classification(y_test, y_proba)
print(f"Accuracy:  {results['accuracy']:.4f}")
print(f"AUC-ROC:   {results['auc_roc']:.4f}")
print(f"Inference time per sample: {infer_time * 1e6:.2f}µs")

Accuracy:  0.8905
AUC-ROC:   0.9756
Inference time per sample: 49.71µs

In [12]:
output = {
    **results,
    "train_metrics": train_metrics,
    "val_metrics": val_metrics,
    "fit_time_s": fit_time,
    "infer_time_per_sample_s": infer_time,
    "best_params": {
        "tuning_metric": model.tuning_metric,
        "split_method": model.split_method,
        "max_leaf_size": model.max_leaf_size,
        **model.rfm_params,
    },
}

results_dir = RESULTS_BENCHMARK / "sleep_health"
with open(results_dir / "xrfm.json", "w") as f:
    json.dump(output, f, indent=4)

plot_roc_curve(
    y_test,
    y_proba,
    save_path=results_dir / "roc_curve_xrfm.png",
    class_names=list(le.classes_),
)
plot_confusion_matrix(
    y_test,
    y_proba,
    save_path=results_dir / "confusion_matrix_xrfm.png",
    class_names=list(le.classes_),
)
save_classification_report(
    y_test,
    y_proba,
    save_path=results_dir / "classification_report_xrfm.json",
    class_names=list(le.classes_),
)

print(f"Results saved to {results_dir / 'xrfm.json'}")

Results saved to /home/shado/college_project/comp9417/9417GroupProject/results/sleep_health/xrfm.json