In [1]:
import json
import time

import joblib
import numpy as np
import pandas as pd
import torch

from benchmark.config import DATA_PROCESSED, DATASETS, MODELS_DIR, RESULTS_BENCHMARK
from benchmark.metrics import evaluate_regression
from benchmark.models.xrfm_model import make_processor
from benchmark.models.xrfm_model import fit_best_xrfm, fit_xrfm_cross_validation

data_name = "superconductor"
cfg = DATASETS[data_name]
processed = DATA_PROCESSED / data_name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
train_df = pd.read_csv(processed / "train.csv")
train_df.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,2,61.785750,56.797395,60.826648,56.061368,0.677665,0.644466,21.688500,17.577195,10.844250,...,4.730000,4.472136,4.707651,0.686962,0.537250,1,2.570000,0.500000,0.443959,6.60
1,3,47.310532,51.865118,43.807482,49.246493,1.032302,0.828781,34.628195,30.002880,16.267662,...,2.412000,2.519842,2.306971,1.039721,1.013695,2,0.788000,0.942809,0.808861,6.70
2,4,76.517718,56.808817,59.310096,35.773432,1.197273,0.981880,122.906070,34.833160,44.289459,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,34.50
3,4,137.184413,105.454381,129.327237,95.279217,1.333014,0.937968,122.454000,50.444024,43.422607,...,4.470588,4.426728,4.400411,1.368922,0.826315,2,2.800000,0.866025,0.848365,4.11
4,5,98.562254,57.854867,71.960198,35.849123,1.364108,0.958288,192.981000,38.095568,67.769561,...,2.296067,2.605171,2.250329,1.531778,1.042065,3,1.151276,1.166190,0.500706,22.70

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 82 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   number_of_elements               17010 non-null  int64
 1   mean_atomic_mass                 17010 non-null  float64
 2   wtd_mean_atomic_mass             17010 non-null  float64
 3   gmean_atomic_mass                17010 non-null  float64
 4   wtd_gmean_atomic_mass            17010 non-null  float64
 5   entropy_atomic_mass              17010 non-null  float64
 6   wtd_entropy_atomic_mass          17010 non-null  float64
 7   range_atomic_mass                17010 non-null  float64
 8   wtd_range_atomic_mass            17010 non-null  float64
 9   std_atomic_mass                  17010 non-null  float64
 10  wtd_std_atomic_mass              17010 non-null  float64
 11  mean_fie                         17010 non-null  float64
 12  wtd_mean_fie                     17010 non-null  float64
 13  gmean_fie                        17010 non-null  float64
 14  wtd_gmean_fie                    17010 non-null  float64
 15  entropy_fie                      17010 non-null  float64
 16  wtd_entropy_fie                  17010 non-null  float64
 17  range_fie                        17010 non-null  float64
 18  wtd_range_fie                    17010 non-null  float64
 19  std_fie                          17010 non-null  float64
 20  wtd_std_fie                      17010 non-null  float64
 21  mean_atomic_radius               17010 non-null  float64
 22  wtd_mean_atomic_radius           17010 non-null  float64
 23  gmean_atomic_radius              17010 non-null  float64
 24  wtd_gmean_atomic_radius          17010 non-null  float64
 25  entropy_atomic_radius            17010 non-null  float64
 26  wtd_entropy_atomic_radius        17010 non-null  float64
 27  range_atomic_radius              17010 non-null  int64
 28  wtd_range_atomic_radius          17010 non-null  float64
 29  std_atomic_radius                17010 non-null  float64
 30  wtd_std_atomic_radius            17010 non-null  float64
 31  mean_Density                     17010 non-null  float64
 32  wtd_mean_Density                 17010 non-null  float64
 33  gmean_Density                    17010 non-null  float64
 34  wtd_gmean_Density                17010 non-null  float64
 35  entropy_Density                  17010 non-null  float64
 36  wtd_entropy_Density              17010 non-null  float64
 37  range_Density                    17010 non-null  float64
 38  wtd_range_Density                17010 non-null  float64
 39  std_Density                      17010 non-null  float64
 40  wtd_std_Density                  17010 non-null  float64
 41  mean_ElectronAffinity            17010 non-null  float64
 42  wtd_mean_ElectronAffinity        17010 non-null  float64
 43  gmean_ElectronAffinity           17010 non-null  float64
 44  wtd_gmean_ElectronAffinity       17010 non-null  float64
 45  entropy_ElectronAffinity         17010 non-null  float64
 46  wtd_entropy_ElectronAffinity     17010 non-null  float64
 47  range_ElectronAffinity           17010 non-null  float64
 48  wtd_range_ElectronAffinity       17010 non-null  float64
 49  std_ElectronAffinity             17010 non-null  float64
 50  wtd_std_ElectronAffinity         17010 non-null  float64
 51  mean_FusionHeat                  17010 non-null  float64
 52  wtd_mean_FusionHeat              17010 non-null  float64
 53  gmean_FusionHeat                 17010 non-null  float64
 54  wtd_gmean_FusionHeat             17010 non-null  float64
 55  entropy_FusionHeat               17010 non-null  float64
 56  wtd_entropy_FusionHeat           17010 non-null  float64
 57  range_FusionHeat                 17010 non-null  float64
 58  wtd_range_FusionHeat             17010 non-null  float64
 59  std_FusionHeat                   17010 non-null  float64
 60  wtd_std_FusionHeat               17010 non-null  float64
 61  mean_ThermalConductivity         17010 non-null  float64
 62  wtd_mean_ThermalConductivity     17010 non-null  float64
 63  gmean_ThermalConductivity        17010 non-null  float64
 64  wtd_gmean_ThermalConductivity    17010 non-null  float64
 65  entropy_ThermalConductivity      17010 non-null  float64
 66  wtd_entropy_ThermalConductivity  17010 non-null  float64
 67  range_ThermalConductivity        17010 non-null  float64
 68  wtd_range_ThermalConductivity    17010 non-null  float64
 69  std_ThermalConductivity          17010 non-null  float64
 70  wtd_std_ThermalConductivity      17010 non-null  float64
 71  mean_Valence                     17010 non-null  float64
 72  wtd_mean_Valence                 17010 non-null  float64
 73  gmean_Valence                    17010 non-null  float64
 74  wtd_gmean_Valence                17010 non-null  float64
 75  entropy_Valence                  17010 non-null  float64
 76  wtd_entropy_Valence              17010 non-null  float64
 77  range_Valence                    17010 non-null  int64
 78  wtd_range_Valence                17010 non-null  float64
 79  std_Valence                      17010 non-null  float64
 80  wtd_std_Valence                  17010 non-null  float64
 81  critical_temp                    17010 non-null  float64
dtypes: float64(79), int64(3)
memory usage: 10.6 MB

In [4]:
test_df = pd.read_csv(processed / "test.csv")
test_df.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,5,88.936744,51.227894,70.358975,34.902572,1.445824,1.467243,122.90607,14.729974,46.482335,...,2.099846,2.352158,2.082630,1.589027,1.289155,1,1.009217,0.489898,0.299795,61.0
1,5,89.337180,53.389543,70.560647,35.669394,1.444537,1.425029,124.90825,17.776145,46.917667,...,2.115830,2.491462,2.086660,1.564957,1.307861,2,0.957529,0.800000,0.423832,28.2
2,4,76.517718,57.468202,59.310096,35.985997,1.197273,0.909037,122.90607,37.745630,44.289459,...,2.277143,2.213364,2.237858,1.368922,1.011105,1,1.125714,0.433013,0.447588,14.0
3,5,83.244760,58.211883,59.506081,35.973651,1.311510,1.407001,192.98100,22.872726,67.233835,...,2.383509,2.402249,2.248543,1.519383,1.396410,3,0.849473,1.200000,1.001723,81.0
4,5,61.357238,51.028500,26.270151,33.490036,1.217667,1.291771,136.31906,21.119847,49.466135,...,2.061562,1.888175,2.041492,1.557113,1.245082,2,1.030396,0.632456,0.297579,72.5

In [5]:
with open(processed / "metadata.json") as f:
    metadata = json.load(f)

print(metadata)

{'num_cols': ['number_of_elements', 'mean_atomic_mass', 'wtd_mean_atomic_mass', 'gmean_atomic_mass', 'wtd_gmean_atomic_mass', 'entropy_atomic_mass', 'wtd_entropy_atomic_mass', 'range_atomic_mass', 'wtd_range_atomic_mass', 'std_atomic_mass', 'wtd_std_atomic_mass', 'mean_fie', 'wtd_mean_fie', 'gmean_fie', 'wtd_gmean_fie', 'entropy_fie', 'wtd_entropy_fie', 'range_fie', 'wtd_range_fie', 'std_fie', 'wtd_std_fie', 'mean_atomic_radius', 'wtd_mean_atomic_radius', 'gmean_atomic_radius', 'wtd_gmean_atomic_radius', 'entropy_atomic_radius', 'wtd_entropy_atomic_radius', 'range_atomic_radius', 'wtd_range_atomic_radius', 'std_atomic_radius', 'wtd_std_atomic_radius', 'mean_Density', 'wtd_mean_Density', 'gmean_Density', 'wtd_gmean_Density', 'entropy_Density', 'wtd_entropy_Density', 'range_Density', 'wtd_range_Density', 'std_Density', 'wtd_std_Density', 'mean_ElectronAffinity', 'wtd_mean_ElectronAffinity', 'gmean_ElectronAffinity', 'wtd_gmean_ElectronAffinity', 'entropy_ElectronAffinity', 'wtd_entropy_ElectronAffinity', 'range_ElectronAffinity', 'wtd_range_ElectronAffinity', 'std_ElectronAffinity', 'wtd_std_ElectronAffinity', 'mean_FusionHeat', 'wtd_mean_FusionHeat', 'gmean_FusionHeat', 'wtd_gmean_FusionHeat', 'entropy_FusionHeat', 'wtd_entropy_FusionHeat', 'range_FusionHeat', 'wtd_range_FusionHeat', 'std_FusionHeat', 'wtd_std_FusionHeat', 'mean_ThermalConductivity', 'wtd_mean_ThermalConductivity', 'gmean_ThermalConductivity', 'wtd_gmean_ThermalConductivity', 'entropy_ThermalConductivity', 'wtd_entropy_ThermalConductivity', 'range_ThermalConductivity', 'wtd_range_ThermalConductivity', 'std_ThermalConductivity', 'wtd_std_ThermalConductivity', 'mean_Valence', 'wtd_mean_Valence', 'gmean_Valence', 'wtd_gmean_Valence', 'entropy_Valence', 'wtd_entropy_Valence', 'range_Valence', 'wtd_range_Valence', 'std_Valence', 'wtd_std_Valence'], 'target_col': 'critical_temp'}

In [6]:
X = train_df.drop(columns=metadata["target_col"])
y = train_df[metadata["target_col"]].to_numpy().astype(np.float32)

processor = make_processor(metadata)
n_num_cols = len(metadata["num_cols"])

In [7]:
best_trial = fit_xrfm_cross_validation(
    X, y, processor, n_num_cols, task=cfg["task"], device=device
)

print(f"Best params: {best_trial.params}")
print(f"Best MSE: {best_trial.value}")

[I 2026-04-22 23:30:06,324] A new study created in memory with name: no-name-a2eb6b48-15ef-42b0-af68-9d8fc7980e05

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2661

Time taken for round 0: 0.7337002754211426 seconds
Using cheap batch size
Optimal M batch size: 2661

Time taken for round 1: 0.2344820499420166 seconds
Using cheap batch size
Optimal M batch size: 2661

Time taken for round 2: 0.23223471641540527 seconds
Using cheap batch size
Optimal M batch size: 2661

Time taken for round 3: 0.23144125938415527 seconds

Using cheap batch size
Optimal M batch size: 2661
Time taken for round 4: 0.2560732364654541 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 0: 0.22974944114685059 seconds

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 1: 0.243880033493042 seconds

Using cheap batch size

Optimal M batch size: 2666
Time taken for round 2: 0.24322032928466797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 0: 0.232177734375 seconds

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 1: 0.23407268524169922 seconds

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 2: 0.23470807075500488 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.2805440425872803 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 0: 0.24232983589172363 seconds

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 1: 0.24406170845031738 seconds

Using cheap batch size

Optimal M batch size: 2666
Time taken for round 2: 0.2496650218963623 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 0: 0.23335981369018555 seconds

Using cheap batch size
Optimal M batch size: 2666

Time taken for round 1: 0.23622775077819824 seconds

Using cheap batch size

Optimal M batch size: 2666
Time taken for round 2: 0.2473006248474121 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 3: 0.26506662368774414 seconds

Using cheap batch size
Optimal M batch size: 2666
Time taken for round 4: 0.24758481979370117 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

[I 2026-04-22 23:30:13,118] Trial 0 finished with value: 97.74626312255859 and parameters: {'exponent': 1.0271644858581115, 'kernel_type': 'k2q', 'bandwidth': 1.970613996905623, 'diag': True, 'reg': 0.0026485784758470345}. Best is trial 0 with value: 97.74626312255859.

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1298

/home/shado/college_project/comp9417/9417GroupProject/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:869: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Time taken for round 0: 3.1808507442474365 seconds

Building trees:   0%|          | 0/1 [00:04<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.309546947479248 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.374908924102783 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.400275230407715 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4999711513519287 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3674936294555664 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-22 23:30:37,458] Trial 1 finished with value: 4521.8490234375 and parameters: {'exponent': 0.7598959983417237, 'kernel_type': 'kpq', 'bandwidth': 31.128146769150394, 'diag': True, 'norm_p': 1.204380550596923, 'reg': 1.5178988352304667e-06}. Best is trial 0 with value: 97.74626312255859.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================
Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.23401618003845215 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.23627448081970215 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 0: 0.24880504608154297 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 1: 0.247511625289917 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.24251365661621094 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 1: 0.2520880699157715 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 0: 0.24473214149475098 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 1: 0.25101304054260254 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.24068021774291992 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 1: 0.25853443145751953 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:30:41,178] Trial 2 finished with value: 169.46051330566405 and parameters: {'exponent': 0.7416781387847737, 'kernel_type': 'k2q', 'bandwidth': 175.8288583045548, 'diag': True, 'reg': 0.5118691608584706}. Best is trial 0 with value: 97.74626312255859.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4885427951812744 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3939502239227295 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.354217529296875 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.363335132598877 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.309368371963501 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3573646545410156 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.36444091796875 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3612070083618164 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.364748477935791 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3622546195983887 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.364933967590332 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3753116130828857 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-22 23:31:18,811] Trial 3 finished with value: 94.33801574707032 and parameters: {'exponent': 0.7550981778629094, 'kernel_type': 'kpq', 'bandwidth': 6.5017130686590825, 'diag': True, 'norm_p': 1.6741056103679175, 'reg': 0.15816844334894103}. Best is trial 3 with value: 94.33801574707032.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================
Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.23281621932983398 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.23144030570983887 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.2346210479736328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.23333978652954102 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.23385405540466309 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:31:21,191] Trial 4 finished with value: 231.01329956054687 and parameters: {'exponent': 1.2386834737442696, 'kernel_type': 'k2q', 'bandwidth': 90.48888237464404, 'diag': True, 'reg': 0.8236923920601619}. Best is trial 3 with value: 94.33801574707032.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3896706104278564 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.365184783935547 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 5.317860841751099 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3707363605499268 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.5186455249786377 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-22 23:31:42,320] Trial 5 finished with value: 106.60344085693359 and parameters: {'exponent': 1.3169801908670333, 'kernel_type': 'kpq', 'bandwidth': 19.84662081152421, 'diag': False, 'norm_p': 1.7995055455137243, 'reg': 0.05330158533580604}. Best is trial 3 with value: 94.33801574707032.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.5877749919891357 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.5559771060943604 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.367933750152588 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3440661430358887 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3690013885498047 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3741538524627686 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3746628761291504 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 4.517629623413086 seconds

Building trees:   0%|          | 0/1 [00:07<?, ?it/s]

[I 2026-04-22 23:32:09,908] Trial 6 finished with value: 97.10934906005859 and parameters: {'exponent': 1.0948486965751747, 'kernel_type': 'kpq', 'bandwidth': 63.44132593183689, 'diag': False, 'norm_p': 1.4194589751409419, 'reg': 0.00011913672272764324}. Best is trial 3 with value: 94.33801574707032.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================
Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.23374676704406738 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.23711729049682617 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.24168634414672852 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.23712539672851562 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.23547720909118652 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 1: 0.24196839332580566 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 2: 0.2414863109588623 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.2328190803527832 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.23677778244018555 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 0: 0.24325156211853027 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 1: 0.24059653282165527 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 2: 0.23679447174072266 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:13,992] Trial 7 finished with value: 90.93719482421875 and parameters: {'exponent': 0.9163728423001612, 'kernel_type': 'k2q', 'bandwidth': 11.925101256066307, 'diag': True, 'reg': 0.021609288204221935}. Best is trial 7 with value: 90.93719482421875.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.23516225814819336 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.2384507656097412 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 2: 0.23775506019592285 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 3: 0.2561948299407959 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 4: 0.239854097366333 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.23408722877502441 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 1: 0.2447042465209961 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 2: 0.24520182609558105 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 3: 0.25434422492980957 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.2475895881652832 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.2491898536682129 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 2: 0.24794745445251465 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 3: 0.2544286251068115 seconds

Using cheap batch size
Optimal M batch size: 2647
Time taken for round 4: 0.24889111518859863 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.24630999565124512 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.25029921531677246 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 2: 0.2496180534362793 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.24434566497802734 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 1: 0.24616122245788574 seconds

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 2: 0.24776911735534668 seconds

Using cheap batch size

Optimal M batch size: 2647
Time taken for round 3: 0.2575044631958008 seconds

Building trees:   0%|          | 0/1 [00:01<?, ?it/s]

[I 2026-04-22 23:32:20,384] Trial 8 finished with value: 96.9387939453125 and parameters: {'exponent': 1.2060200075435343, 'kernel_type': 'k2q', 'bandwidth': 2.792736238727968, 'diag': True, 'reg': 0.0007660547961224706}. Best is trial 7 with value: 90.93719482421875.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Time taken for round 0: 0.2446117401123047 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.24379372596740723 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.2441866397857666 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.24689745903015137 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Time taken for round 0: 0.24705290794372559 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:32:22,829] Trial 9 finished with value: 267.89666442871095 and parameters: {'exponent': 0.7450034897059166, 'kernel_type': 'k2q', 'bandwidth': 1.880953078065556, 'diag': True, 'reg': 2.8141896704489657e-06}. Best is trial 7 with value: 90.93719482421875.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24785518646240234 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25228309631347656 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2487783432006836 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24828362464904785 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2529599666595459 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2502274513244629 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.2519712448120117 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24705290794372559 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25258398056030273 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:26,288] Trial 10 finished with value: 90.95035705566406 and parameters: {'exponent': 0.9364012267236584, 'kernel_type': 'k2q', 'bandwidth': 7.547668737995126, 'diag': False, 'reg': 0.0295551492784938}. Best is trial 7 with value: 90.93719482421875.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2478034496307373 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24843502044677734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24786376953125 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2508676052093506 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24973464012145996 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2486276626586914 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.251298189163208 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:29,245] Trial 11 finished with value: 90.66849517822266 and parameters: {'exponent': 0.9287322809174521, 'kernel_type': 'k2q', 'bandwidth': 7.747562096309485, 'diag': False, 'reg': 0.015302498684740692}. Best is trial 11 with value: 90.66849517822266.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24670028686523438 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2473611831665039 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2484421730041504 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25218772888183594 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24932241439819336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24941396713256836 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.2501225471496582 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:32:32,200] Trial 12 finished with value: 92.50455169677734 and parameters: {'exponent': 0.9063187435879375, 'kernel_type': 'k2q', 'bandwidth': 7.323898374305409, 'diag': False, 'reg': 0.0036880414911128648}. Best is trial 11 with value: 90.66849517822266.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24828267097473145 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2528650760650635 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2502279281616211 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24883174896240234 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2531740665435791 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2463085651397705 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2526731491088867 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24834680557250977 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25319862365722656 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:35,657] Trial 13 finished with value: 90.42331085205078 and parameters: {'exponent': 0.9369240159226784, 'kernel_type': 'k2q', 'bandwidth': 13.85625819848838, 'diag': False, 'reg': 0.00987903300413025}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2506711483001709 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2491922378540039 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2504086494445801 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24843764305114746 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2487931251525879 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2530496120452881 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:38,368] Trial 14 finished with value: 135.75150451660156 and parameters: {'exponent': 1.0420753585912648, 'kernel_type': 'k2q', 'bandwidth': 3.6453089857830587, 'diag': False, 'reg': 0.00013572231247761845}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24679231643676758 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2477092742919922 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2493436336517334 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 3.2114171981811523 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24955534934997559 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24816441535949707 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2518424987792969 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:44,279] Trial 15 finished with value: 90.80355072021484 and parameters: {'exponent': 0.8511992379284726, 'kernel_type': 'k2q', 'bandwidth': 28.412265199515584, 'diag': False, 'reg': 0.006724213134140834}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24734711647033691 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24742937088012695 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24912786483764648 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.247605562210083 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24920225143432617 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2528095245361328 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:32:47,003] Trial 16 finished with value: 93.9902587890625 and parameters: {'exponent': 1.122087137875329, 'kernel_type': 'k2q', 'bandwidth': 13.499230428493368, 'diag': False, 'reg': 0.0003074779846369913}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.25844573974609375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.25861048698425293 seconds

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2732887268066406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.2600586414337158 seconds

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.26025915145874023 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24096083641052246 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24026727676391602 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:32:50,045] Trial 17 finished with value: 139.60279388427733 and parameters: {'exponent': 0.9892051833229232, 'kernel_type': 'k2q', 'bandwidth': 1.0331799967130502, 'diag': False, 'reg': 4.1947890504844455e-05}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3496670722961426 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.351208448410034 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.346733331680298 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.348902940750122 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3459455966949463 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-22 23:33:07,871] Trial 18 finished with value: 91.74988250732422 and parameters: {'exponent': 0.8565477956835642, 'kernel_type': 'kpq', 'bandwidth': 46.56668870756515, 'diag': False, 'norm_p': 0.856600103333394, 'reg': 0.0938745971775253}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================
Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2370762825012207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23807430267333984 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.2535412311553955 seconds

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25226807594299316 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2489011287689209 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.25128841400146484 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.24978089332580566 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:33:10,974] Trial 19 finished with value: 91.32315979003906 and parameters: {'exponent': 0.9757334201479622, 'kernel_type': 'k2q', 'bandwidth': 4.640635792522595, 'diag': False, 'reg': 0.011575165702524369}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2474212646484375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2472362518310547 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2471301555633545 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2502901554107666 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2502760887145996 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2502014636993408 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.2500460147857666 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:33:13,920] Trial 20 finished with value: 413.79394989013673 and parameters: {'exponent': 0.8351149126560048, 'kernel_type': 'k2q', 'bandwidth': 11.003763443752444, 'diag': False, 'reg': 0.0013964856196374417}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23932123184204102 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24477696418762207 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2419118881225586 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 2.9962406158447266 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2469024658203125 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24120187759399414 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23622989654541016 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24645376205444336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:33:19,806] Trial 21 finished with value: 90.98284149169922 and parameters: {'exponent': 0.8414897367239664, 'kernel_type': 'k2q', 'bandwidth': 26.366299042706917, 'diag': False, 'reg': 0.011133150447277692}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2366318702697754 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23911380767822266 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2378380298614502 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24500203132629395 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23977994918823242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23854565620422363 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2428727149963379 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:33:22,680] Trial 22 finished with value: 91.22025299072266 and parameters: {'exponent': 0.8190714625991534, 'kernel_type': 'k2q', 'bandwidth': 25.364322300445757, 'diag': False, 'reg': 0.005983409275027286}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23853731155395508 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2392885684967041 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23558640480041504 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23614907264709473 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23597145080566406 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:33:25,073] Trial 23 finished with value: 94.6860336303711 and parameters: {'exponent': 0.8938227062920068, 'kernel_type': 'k2q', 'bandwidth': 17.286634604387512, 'diag': False, 'reg': 0.0007526216444463674}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23717904090881348 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24447345733642578 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2403883934020996 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23815321922302246 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.24398040771484375 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23896145820617676 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.24147391319274902 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2397761344909668 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:33:28,191] Trial 24 finished with value: 121.23062591552734 and parameters: {'exponent': 0.9693284254833694, 'kernel_type': 'k2q', 'bandwidth': 48.22558479850418, 'diag': False, 'reg': 0.11718509149125861}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2385845184326172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2373497486114502 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23639321327209473 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23656964302062988 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2376875877380371 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

[I 2026-04-22 23:33:30,582] Trial 25 finished with value: 113.33790130615235 and parameters: {'exponent': 1.0987947790621233, 'kernel_type': 'k2q', 'bandwidth': 9.333743623516035, 'diag': False, 'reg': 0.2798410616686891}. Best is trial 13 with value: 90.42331085205078.

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.346789836883545 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3482260704040527 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.356330633163452 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.349236249923706 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.345391273498535 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.348179817199707 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3482964038848877 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 5.311157941818237 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.4738173484802246 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3712425231933594 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3753504753112793 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.373260498046875 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.349431037902832 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3478024005889893 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.345022678375244 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-22 23:34:15,180] Trial 26 finished with value: 125.13189086914062 and parameters: {'exponent': 0.8082025959350908, 'kernel_type': 'kpq', 'bandwidth': 4.693727645945524, 'diag': False, 'norm_p': 0.8212885311007054, 'reg': 0.03223658251150762}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================
Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2410414218902588 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24608564376831055 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.25053906440734863 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24238920211791992 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25139379501342773 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24326562881469727 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.24460768699645996 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24503421783447266 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2490067481994629 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:18,626] Trial 27 finished with value: 91.79732513427734 and parameters: {'exponent': 0.8805063816295212, 'kernel_type': 'k2q', 'bandwidth': 104.87669499397968, 'diag': False, 'reg': 0.005425902273967661}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2455129623413086 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24080681800842285 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24258756637573242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24177002906799316 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24182796478271484 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24952244758605957 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:21,316] Trial 28 finished with value: 469.40410766601565 and parameters: {'exponent': 0.7058904476252916, 'kernel_type': 'k2q', 'bandwidth': 41.815571444930214, 'diag': False, 'reg': 1.764607659699382e-05}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24390268325805664 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24057888984680176 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24046063423156738 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24987173080444336 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24483942985534668 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2396526336669922 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.25251317024230957 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:24,236] Trial 29 finished with value: 90.79199676513672 and parameters: {'exponent': 1.0121812798663599, 'kernel_type': 'k2q', 'bandwidth': 17.966888285987654, 'diag': False, 'reg': 0.0023915751252550996}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24294376373291016 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24053120613098145 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24028801918029785 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24796342849731445 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24506235122680664 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23849892616271973 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2501206398010254 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:29,557] Trial 30 finished with value: 91.18704681396484 and parameters: {'exponent': 1.0174832317106592, 'kernel_type': 'k2q', 'bandwidth': 17.12522288177603, 'diag': False, 'reg': 0.0018030740528585945}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2425978183746338 seconds

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 1: 0.2431163787841797 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2457866668701172 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.23995661735534668 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24619245529174805 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24465107917785645 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24504756927490234 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24852252006530762 seconds

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2680015563964844 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:33,013] Trial 31 finished with value: 90.59314270019532 and parameters: {'exponent': 0.9314795231576439, 'kernel_type': 'k2q', 'bandwidth': 16.7374138893105, 'diag': False, 'reg': 0.012786612928373547}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24612641334533691 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training

Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24231433868408203 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24517083168029785 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24965286254882812 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.24846100807189941 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24557805061340332 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2521696090698242 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:35,979] Trial 32 finished with value: 92.44239349365235 and parameters: {'exponent': 0.9390644546113504, 'kernel_type': 'k2q', 'bandwidth': 9.612353998153985, 'diag': False, 'reg': 0.002300823568939657}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24440979957580566 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24824166297912598 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.24663448333740234 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.2422330379486084 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.2520864009857178 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 0: 0.24744486808776855 seconds

Using cheap batch size
Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24697017669677734 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using cheap batch size
Optimal M batch size: 2647

Using SVD
Time taken for round 0: 0.24593329429626465 seconds

Using cheap batch size

Optimal M batch size: 2647
Using SVD
Time taken for round 1: 0.24884724617004395 seconds

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-04-22 23:34:39,429] Trial 33 finished with value: 92.4897476196289 and parameters: {'exponent': 1.0615835846561934, 'kernel_type': 'k2q', 'bandwidth': 18.766107439544264, 'diag': False, 'reg': 0.01807230806067718}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction
None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.4235939979553223 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3424930572509766 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.370365858078003 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3674139976501465 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.4044158458709717 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3776135444641113 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.4153027534484863 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 4.81833291053772 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.398993730545044 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.343737840652466 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

[I 2026-04-22 23:35:11,831] Trial 34 finished with value: 90.59663848876953 and parameters: {'exponent': 1.1613151686842453, 'kernel_type': 'kpq', 'bandwidth': 5.577996309399183, 'diag': False, 'norm_p': 1.4740610261782978, 'reg': 0.05372294375047337}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3754115104675293 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3736445903778076 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3793790340423584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380587100982666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4037628173828125 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36828351020813 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376544713973999 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3797383308410645 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.251092910766602 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.381340265274048 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.407473564147949 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4388461112976074 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4495949745178223 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.398017406463623 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3769073486328125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3761181831359863 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3772902488708496 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3694751262664795 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380207061767578 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3829166889190674 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3927111625671387 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.085106372833252 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:36:16,104] Trial 35 finished with value: 91.1233154296875 and parameters: {'exponent': 1.1643526041198207, 'kernel_type': 'kpq', 'bandwidth': 4.500474820236397, 'diag': True, 'norm_p': 1.4662314828486758, 'reg': 0.045426375564043726}. Best is trial 13 with value: 90.42331085205078.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.42612361907959 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.4459474086761475 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.4357824325561523 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3822503089904785 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3730645179748535 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-22 23:36:34,353] Trial 36 finished with value: 104.11615142822265 and parameters: {'exponent': 1.28905174515165, 'kernel_type': 'kpq', 'bandwidth': 6.015549608794045, 'diag': False, 'norm_p': 1.5468441417113576, 'reg': 0.30321405351336805}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.380518674850464 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.349712371826172 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.3525948524475098 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 3: 2.361739158630371 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 4: 2.371835708618164 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.407482147216797 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.416966199874878 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.4184329509735107 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 3: 2.4146840572357178 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 4: 2.3521361351013184 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3733410835266113 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.345109462738037 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.3583333492279053 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 3: 2.352463722229004 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 4: 2.3433563709259033 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3819875717163086 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3674323558807373 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 5.02550196647644 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 3: 2.4070451259613037 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 4: 2.416602849960327 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.43957781791687 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 1: 2.3452510833740234 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 2: 2.3492519855499268 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 3: 2.347578525543213 seconds

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 4: 2.3455965518951416 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:37:45,167] Trial 37 finished with value: 116.22713470458984 and parameters: {'exponent': 1.159453759961738, 'kernel_type': 'kpq', 'bandwidth': 2.0625673234130284, 'diag': False, 'norm_p': 1.3194526446986559, 'reg': 0.08566386023441647}. Best is trial 13 with value: 90.42331085205078.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372649908065796 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3771700859069824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3881802558898926 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.385368824005127 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.042510032653809 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4478652477264404 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.449951648712158 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.429013967514038 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377021312713623 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3757495880126953 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379864454269409 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3755886554718018 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3695805072784424 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378526449203491 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382524251937866 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3833096027374268 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.057744979858398 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.447434186935425 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.449143171310425 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.452721357345581 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

[I 2026-04-22 23:38:44,673] Trial 38 finished with value: 107.3314712524414 and parameters: {'exponent': 0.77963376847414, 'kernel_type': 'kpq', 'bandwidth': 3.0866403840395966, 'diag': True, 'norm_p': 1.1052469051321878, 'reg': 0.8242218790806876}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3849072456359863 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.372849702835083 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.374070167541504 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.3785018920898438 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Using SVD
Time taken for round 0: 2.374356985092163 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-22 23:39:02,662] Trial 39 finished with value: 105.98524169921875 and parameters: {'exponent': 1.3907856445885327, 'kernel_type': 'kpq', 'bandwidth': 6.338052852104917, 'diag': False, 'norm_p': 1.6609561591882744, 'reg': 0.23409060109217344}. Best is trial 13 with value: 90.42331085205078.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3725314140319824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.071297645568848 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4344019889831543 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4639523029327393 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.454373836517334 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369729995727539 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3768093585968018 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385134696960449 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3751254081726074 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382270097732544 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3707845211029053 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3762879371643066 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376833200454712 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3817336559295654 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.1094396114349365 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.43241810798645 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4409844875335693 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.397092819213867 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3806982040405273 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3678200244903564 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3747119903564453 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375479221343994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375370502471924 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3776280879974365 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:40:11,689] Trial 40 finished with value: 89.00162353515626 and parameters: {'exponent': 0.9506389742729571, 'kernel_type': 'kpq', 'bandwidth': 13.210481739460162, 'diag': True, 'norm_p': 1.2858638589663247, 'reg': 0.012849477079297488}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366955518722534 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3741471767425537 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.108047962188721 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4067611694335938 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3998665809631348 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372220993041992 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380094051361084 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382061004638672 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379112482070923 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.37751841545105 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3681890964508057 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376556634902954 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3771860599517822 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3873984813690186 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.2437357902526855 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3689005374908447 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375382900238037 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3786399364471436 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3770267963409424 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368706226348877 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3766915798187256 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3781654834747314 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3767831325531006 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3877124786376953 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:41:20,519] Trial 41 finished with value: 89.00371398925782 and parameters: {'exponent': 0.9528442199773708, 'kernel_type': 'kpq', 'bandwidth': 12.966686461360574, 'diag': True, 'norm_p': 1.2775884341555388, 'reg': 0.01331522630558405}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3674967288970947 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.394026279449463 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.334845542907715 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3675448894500732 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379728317260742 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.38626766204834 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3708057403564453 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369931936264038 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376980781555176 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3824031352996826 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-22 23:41:53,370] Trial 42 finished with value: 90.66783752441407 and parameters: {'exponent': 1.0707771736583336, 'kernel_type': 'kpq', 'bandwidth': 13.61758076774894, 'diag': True, 'norm_p': 1.2920805958526809, 'reg': 0.05405853773944059}. Best is trial 40 with value: 89.00162353515626.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373847723007202 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380004405975342 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376213788986206 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375349283218384 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.317671298980713 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3701226711273193 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3749465942382812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381274700164795 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375586748123169 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3779778480529785 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.374854803085327 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3882558345794678 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375659942626953 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375056505203247 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3827321529388428 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372912645339966 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.336317777633667 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.374169111251831 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3697450160980225 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374635696411133 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3730835914611816 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.381453037261963 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3779654502868652 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:43:00,062] Trial 43 finished with value: 89.76367492675782 and parameters: {'exponent': 0.9603940555002259, 'kernel_type': 'kpq', 'bandwidth': 23.11067218196928, 'diag': True, 'norm_p': 1.1564982040472294, 'reg': 0.007940067671413408}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3709070682525635 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3754162788391113 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3762454986572266 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3795647621154785 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370647430419922 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.340623378753662 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4582204818725586 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.5473763942718506 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.40844988822937 seconds

Building trees:   0%|          | 0/1 [00:16<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.413097620010376 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3917548656463623 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3851735591888428 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384639024734497 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3780767917633057 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3961756229400635 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4116344451904297 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.414578676223755 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 4.857441425323486 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4126856327056885 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4442076683044434 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4524872303009033 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4464242458343506 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:44:04,688] Trial 44 finished with value: 90.06804504394532 and parameters: {'exponent': 0.9588701383444962, 'kernel_type': 'kpq', 'bandwidth': 34.47347511659552, 'diag': True, 'norm_p': 1.1112629890036747, 'reg': 0.008485750477848556}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3886029720306396 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.386892080307007 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376415252685547 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3752126693725586 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3773508071899414 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368622303009033 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.373302698135376 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 4.978800296783447 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3812289237976074 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379978656768799 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3691153526306152 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376673460006714 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3773646354675293 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375143527984619 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3773727416992188 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3696606159210205 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3753252029418945 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370920419692993 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378863573074341 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.335888385772705 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3796796798706055 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377204179763794 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:45:08,663] Trial 45 finished with value: 94.65578765869141 and parameters: {'exponent': 0.9593602490202513, 'kernel_type': 'kpq', 'bandwidth': 35.28413862741479, 'diag': True, 'norm_p': 1.1242544001314831, 'reg': 0.0005286034883491635}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369907855987549 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3833460807800293 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3804595470428467 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3839118480682373 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3756461143493652 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3694863319396973 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.382122039794922 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.374135732650757 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3793375492095947 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3815395832061768 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.321716547012329 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3770992755889893 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376587152481079 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.376060962677002 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.381484031677246 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.371635675430298 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375206708908081 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3824710845947266 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373049020767212 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374800205230713 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3791697025299072 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3779971599578857 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.334329843521118 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:46:15,375] Trial 46 finished with value: 90.78928833007812 and parameters: {'exponent': 0.9959789510979347, 'kernel_type': 'kpq', 'bandwidth': 58.12866639491408, 'diag': True, 'norm_p': 1.168847154980164, 'reg': 0.004563652464050769}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3728764057159424 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3761720657348633 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3816869258880615 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.378127098083496 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3776004314422607 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3673903942108154 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3850831985473633 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3819046020507812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3787081241607666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3776087760925293 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3662824630737305 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.3341591358184814 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.391843557357788 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.383047342300415 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3823015689849854 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369882106781006 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3869385719299316 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3730478286743164 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3664188385009766 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378540515899658 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375692844390869 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3761842250823975 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3819150924682617 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:47:19,148] Trial 47 finished with value: 90.81816101074219 and parameters: {'exponent': 0.8768199931844705, 'kernel_type': 'kpq', 'bandwidth': 23.11919930701545, 'diag': True, 'norm_p': 1.0077130196747364, 'reg': 0.007938663255282875}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3672566413879395 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.337490558624268 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3805956840515137 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3765225410461426 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369269847869873 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376593828201294 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.374051570892334 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375401735305786 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3784055709838867 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377135992050171 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.375608205795288 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373817205429077 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3731138706207275 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3711788654327393 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380009651184082 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382219076156616 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3762741088867188 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3821301460266113 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:48:13,959] Trial 48 finished with value: 90.05261993408203 and parameters: {'exponent': 0.954620713863239, 'kernel_type': 'kpq', 'bandwidth': 36.394870673041716, 'diag': True, 'norm_p': 1.2683711497758094, 'reg': 0.02276712367033086}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3685853481292725 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37760591506958 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.375441312789917 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377713918685913 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369875431060791 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3869380950927734 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.325745105743408 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3680343627929688 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369810104370117 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3760433197021484 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3808555603027344 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3781380653381348 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

[I 2026-04-22 23:48:51,540] Trial 49 finished with value: 91.90337524414062 and parameters: {'exponent': 1.0447385035477381, 'kernel_type': 'kpq', 'bandwidth': 35.09584859633917, 'diag': True, 'norm_p': 1.2757481182528738, 'reg': 0.025233456040081828}. Best is trial 40 with value: 89.00162353515626.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372633218765259 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3824546337127686 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.37595796585083 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3755569458007812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3764288425445557 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3752248287200928 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.335629463195801 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382467269897461 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3767783641815186 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376636266708374 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.379984140396118 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3749020099639893 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3793246746063232 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377028465270996 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.389801025390625 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3751819133758545 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375659704208374 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3842685222625732 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.340429306030273 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369826078414917 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374911069869995 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3891119956970215 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375178098678589 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382255792617798 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:50:00,667] Trial 50 finished with value: 89.9216552734375 and parameters: {'exponent': 0.9108408099613411, 'kernel_type': 'kpq', 'bandwidth': 73.42328031478353, 'diag': True, 'norm_p': 1.233042285573084, 'reg': 0.0033716638618109247}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369267702102661 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3755218982696533 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.37805438041687 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377452850341797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.388899564743042 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3682074546813965 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3768277168273926 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.331067800521851 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379133939743042 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379056692123413 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368414878845215 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37748646736145 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3746776580810547 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3743278980255127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.396444082260132 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.371554136276245 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3773202896118164 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3767759799957275 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3677709102630615 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.342209339141846 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376973867416382 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3835856914520264 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3787622451782227 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:51:07,401] Trial 51 finished with value: 90.1696548461914 and parameters: {'exponent': 0.9554369426313308, 'kernel_type': 'kpq', 'bandwidth': 111.56849094248474, 'diag': True, 'norm_p': 1.2260773581868343, 'reg': 0.004527448948303925}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.585918664932251 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.6032509803771973 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.394432783126831 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3890647888183594 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3927559852600098 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377175807952881 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383014440536499 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379103422164917 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 4.818575143814087 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.390122413635254 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3702292442321777 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3796334266662598 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3777239322662354 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.37886381149292 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3790152072906494 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3690457344055176 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379183769226074 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.380037546157837 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384782075881958 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3818962574005127 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.3273444175720215 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.382952928543091 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4012532234191895 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.494088888168335 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.375673294067383 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:52:19,018] Trial 52 finished with value: 89.27073364257812 and parameters: {'exponent': 0.9069170379592407, 'kernel_type': 'kpq', 'bandwidth': 72.92156221334288, 'diag': True, 'norm_p': 1.366841011705115, 'reg': 0.003268266041454052}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3746156692504883 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374772310256958 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.386265754699707 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3755569458007812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3759419918060303 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3698410987854004 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3788559436798096 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3810205459594727 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.190551280975342 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.38419508934021 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.374255657196045 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.390227794647217 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385310649871826 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3862967491149902 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.383615016937256 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3683390617370605 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374809980392456 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381953001022339 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.383814573287964 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4021003246307373 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.325308799743652 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4397668838500977 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.543480157852173 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3936808109283447 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3983843326568604 seconds

Building trees:   0%|          | 0/1 [00:16<?, ?it/s]

[I 2026-04-22 23:53:30,682] Trial 53 finished with value: 89.82808380126953 and parameters: {'exponent': 0.9101318261620783, 'kernel_type': 'kpq', 'bandwidth': 195.11450266011806, 'diag': True, 'norm_p': 1.3776393143640775, 'reg': 0.0010931570179670167}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.385741710662842 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3817222118377686 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379446506500244 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.391396999359131 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4149274826049805 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4180097579956055 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.420936346054077 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 4.894519805908203 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4014341831207275 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.474654197692871 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4452834129333496 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.43931245803833 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.432481288909912 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370195150375366 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383826732635498 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3942272663116455 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.391178846359253 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3945443630218506 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.412433385848999 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 4.911584377288818 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:54:29,985] Trial 54 finished with value: 92.02017822265626 and parameters: {'exponent': 0.907067737101049, 'kernel_type': 'kpq', 'bandwidth': 178.36314903644399, 'diag': True, 'norm_p': 1.3575102480387975, 'reg': 0.0003400495574270035}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.418459892272949 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3948020935058594 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376981496810913 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3782119750976562 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376539707183838 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3707313537597656 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3750176429748535 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.38289737701416 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3770790100097656 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.387876033782959 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3692264556884766 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.244076728820801 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3789868354797363 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.400193452835083 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.450378656387329 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4414212703704834 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4150264263153076 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3774588108062744 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3818016052246094 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369518995285034 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3835086822509766 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3792035579681396 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384608030319214 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.388258695602417 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-22 23:55:39,031] Trial 55 finished with value: 89.97839965820313 and parameters: {'exponent': 0.9102461088683123, 'kernel_type': 'kpq', 'bandwidth': 139.315545842872, 'diag': True, 'norm_p': 1.3735771269425934, 'reg': 0.001125170472963504}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377831220626831 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.425337553024292 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.464404344558716 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4898767471313477 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.435392379760742 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3701136112213135 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3921396732330322 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.377187967300415 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3852360248565674 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379802703857422 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3897480964660645 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3919100761413574 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.0493152141571045 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3983211517333984 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4543251991271973 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4440090656280518 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4283347129821777 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3779664039611816 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.382280111312866 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.37727689743042 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370147943496704 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.387972593307495 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3725829124450684 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.378541946411133 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.062614679336548 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:56:50,568] Trial 56 finished with value: 90.4125732421875 and parameters: {'exponent': 0.8688531214927783, 'kernel_type': 'kpq', 'bandwidth': 67.72094808389967, 'diag': True, 'norm_p': 1.2193514626814779, 'reg': 0.002705848491736779}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4034817218780518 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4584009647369385 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.443237066268921 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4063990116119385 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3777220249176025 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3778605461120605 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3782365322113037 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3790969848632812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3868956565856934 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382112741470337 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.37627911567688 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373206853866577 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.44806170463562 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4460184574127197 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4472591876983643 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3924593925476074 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

[I 2026-04-22 23:57:37,907] Trial 57 finished with value: 94.28504791259766 and parameters: {'exponent': 0.7969906185317845, 'kernel_type': 'kpq', 'bandwidth': 77.54491603016174, 'diag': True, 'norm_p': 1.3723307354975434, 'reg': 0.00017508650215092067}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372718572616577 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3738436698913574 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3864245414733887 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3761987686157227 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3756256103515625 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370661735534668 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3753163814544678 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.094127893447876 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4225473403930664 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.441392660140991 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4418675899505615 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375565767288208 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.383937358856201 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3765294551849365 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.374683141708374 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3813090324401855 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379716396331787 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3785159587860107 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.376734495162964 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376351833343506 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.423807144165039 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4415769577026367 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.442676544189453 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.405743360519409 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3787474632263184 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

[I 2026-04-22 23:58:49,324] Trial 58 finished with value: 90.24385833740234 and parameters: {'exponent': 1.0054458405008702, 'kernel_type': 'kpq', 'bandwidth': 145.85067675970953, 'diag': True, 'norm_p': 1.3234396353009321, 'reg': 0.0009590829051616383}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368507146835327 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375680446624756 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.380791425704956 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3780555725097656 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.385549783706665 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3714969158172607 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375382661819458 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.135730266571045 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.426218271255493 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4278316497802734 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3816850185394287 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3856732845306396 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3767144680023193 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380401611328125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3794169425964355 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3773679733276367 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.381563663482666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3825104236602783 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3755908012390137 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.167726516723633 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3885340690612793 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3730556964874268 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3870832920074463 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382941246032715 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-22 23:59:58,212] Trial 59 finished with value: 90.97194213867188 and parameters: {'exponent': 0.984953544399642, 'kernel_type': 'kpq', 'bandwidth': 88.27624000483567, 'diag': True, 'norm_p': 1.4300653307393543, 'reg': 0.0005572304455239811}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3682096004486084 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3778512477874756 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3781278133392334 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3754727840423584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3757433891296387 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366647958755493 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3783609867095947 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.324644327163696 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3910624980926514 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3795716762542725 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3692188262939453 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376065254211426 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3778092861175537 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3810620307922363 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.387871742248535 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36623477935791 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3859188556671143 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375222682952881 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3804030418395996 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.338466167449951 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.382244825363159 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3761672973632812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3759067058563232 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3805251121520996 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:01:07,305] Trial 60 finished with value: 89.9629135131836 and parameters: {'exponent': 0.8345605302870036, 'kernel_type': 'kpq', 'bandwidth': 193.12983530079774, 'diag': True, 'norm_p': 1.1888472267332006, 'reg': 0.0030396537425435304}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368370532989502 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3755760192871094 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.383831262588501 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3817381858825684 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3761889934539795 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3779361248016357 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.373713254928589 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3804802894592285 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.340668439865112 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3855130672454834 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368914842605591 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.39089035987854 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3922276496887207 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377441644668579 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378946542739868 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3730783462524414 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3752169609069824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3822717666625977 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3690097332000732 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.381272077560425 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.3295605182647705 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.386326551437378 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.384366750717163 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:02:14,054] Trial 61 finished with value: 90.20506744384765 and parameters: {'exponent': 0.8917430114411291, 'kernel_type': 'kpq', 'bandwidth': 187.53553328984742, 'diag': True, 'norm_p': 1.1826307215790797, 'reg': 0.0030887545348843547}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3676228523254395 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3760077953338623 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3826913833618164 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377375841140747 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3773179054260254 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3678977489471436 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380108118057251 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.389559507369995 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3864336013793945 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3865041732788086 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3709487915039062 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3797531127929688 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.389680862426758 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3788154125213623 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379885196685791 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.374593734741211 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3796770572662354 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379803419113159 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377091884613037 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3769309520721436 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369600772857666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3772921562194824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.338108062744141 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3831088542938232 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4780678749084473 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:03:25,677] Trial 62 finished with value: 92.6512680053711 and parameters: {'exponent': 0.8400816505711111, 'kernel_type': 'kpq', 'bandwidth': 143.82776087744867, 'diag': True, 'norm_p': 1.0348670843020598, 'reg': 0.001821488221813225}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3742661476135254 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3836398124694824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3885438442230225 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3728013038635254 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3757176399230957 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.392922878265381 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3981754779815674 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4082703590393066 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.11340594291687 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.407933235168457 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4742355346679688 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.440187931060791 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4432358741760254 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.428460121154785 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

[I 2026-04-23 00:04:08,233] Trial 63 finished with value: 92.65694122314453 and parameters: {'exponent': 0.9219343585759312, 'kernel_type': 'kpq', 'bandwidth': 124.51183018162219, 'diag': True, 'norm_p': 1.251880526116386, 'reg': 0.014327994218983335}. Best is trial 40 with value: 89.00162353515626.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3687214851379395 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374293565750122 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3890345096588135 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3839070796966553 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3752033710479736 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3664333820343018 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 4.987950325012207 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381556987762451 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3819634914398193 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376302480697632 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3745968341827393 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.372711181640625 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375298500061035 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377868175506592 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3830361366271973 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36681866645813 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3743650913238525 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382219076156616 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3765764236450195 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.329544544219971 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.390839099884033 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3753066062927246 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3758769035339355 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3751885890960693 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:05:16,978] Trial 64 finished with value: 89.9354736328125 and parameters: {'exponent': 0.7654144193292025, 'kernel_type': 'kpq', 'bandwidth': 198.09320219703244, 'diag': True, 'norm_p': 1.1894579906696399, 'reg': 0.0037704517501011827}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3656749725341797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378430128097534 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3812644481658936 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.378420829772949 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3832690715789795 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3762595653533936 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3837878704071045 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.329936742782593 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.382974863052368 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3863725662231445 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367622137069702 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3754043579101562 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385763168334961 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3738667964935303 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3779213428497314 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3708994388580322 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3752455711364746 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3701751232147217 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.380189895629883 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.265148162841797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3747050762176514 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.388882875442505 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:06:21,264] Trial 65 finished with value: 92.64105377197265 and parameters: {'exponent': 0.7244962904801099, 'kernel_type': 'kpq', 'bandwidth': 93.03029248192004, 'diag': True, 'norm_p': 1.060300219761309, 'reg': 0.001389681369541944}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3683876991271973 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376894474029541 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3817477226257324 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3828771114349365 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.387112617492676 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36615252494812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3770902156829834 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385006904602051 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375948905944824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.386275053024292 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3745574951171875 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3746097087860107 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.38354229927063 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3902876377105713 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.387543201446533 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3684871196746826 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3818531036376953 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3775405883789062 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.386620283126831 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377605676651001 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373408794403076 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383410930633545 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.339349746704102 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379316568374634 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382746458053589 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:07:32,853] Trial 66 finished with value: 89.70752716064453 and parameters: {'exponent': 0.7731579756003907, 'kernel_type': 'kpq', 'bandwidth': 55.24564884326342, 'diag': True, 'norm_p': 1.3363905073997069, 'reg': 0.006157733464042878}. Best is trial 40 with value: 89.00162353515626.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3753933906555176 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3869853019714355 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3876681327819824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.389389753341675 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376278877258301 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3741378784179688 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3781447410583496 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3753623962402344 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.385237693786621 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3820478916168213 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3660261631011963 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3797483444213867 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.378223180770874 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3755788803100586 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376631736755371 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3668880462646484 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376197338104248 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.38818359375 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3698501586914062 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3769173622131348 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.378194570541382 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3780407905578613 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.3269617557525635 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:08:39,582] Trial 67 finished with value: 88.95467529296874 and parameters: {'exponent': 1.0371905075075156, 'kernel_type': 'kpq', 'bandwidth': 21.2786279350736, 'diag': True, 'norm_p': 1.3252286659913302, 'reg': 0.008843021531850622}. Best is trial 67 with value: 88.95467529296874.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.38082218170166 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3763587474823 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.377095937728882 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375731945037842 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.376981258392334 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377455234527588 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3789777755737305 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3776397705078125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3767147064208984 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378709554672241 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3800652027130127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.3483593463897705 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376652956008911 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3833720684051514 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.375117540359497 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367673635482788 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3768978118896484 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3864846229553223 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380488157272339 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367616891860962 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3779830932617188 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381566286087036 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3774118423461914 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377514123916626 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:09:48,706] Trial 68 finished with value: 89.14923706054688 and parameters: {'exponent': 1.0254407884707994, 'kernel_type': 'kpq', 'bandwidth': 22.09488830673164, 'diag': True, 'norm_p': 1.3260418502846567, 'reg': 0.006563002678539028}. Best is trial 67 with value: 88.95467529296874.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3749656677246094 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3751795291900635 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3738551139831543 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3790290355682373 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3761134147644043 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3743114471435547 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3831675052642822 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3801777362823486 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385232925415039 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-23 00:10:16,232] Trial 69 finished with value: 92.3195556640625 and parameters: {'exponent': 1.1232206577434685, 'kernel_type': 'kpq', 'bandwidth': 21.24295612841724, 'diag': True, 'norm_p': 1.3163879604247657, 'reg': 0.0346651998435338}. Best is trial 67 with value: 88.95467529296874.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3761391639709473 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.337323188781738 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382101535797119 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.374191999435425 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3758535385131836 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.371255874633789 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3758084774017334 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375464916229248 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.376873254776001 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377857208251953 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3688273429870605 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.373924970626831 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.384049415588379 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3817801475524902 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.342404365539551 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368042469024658 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.386064291000366 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3830726146698 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3769097328186035 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3767125606536865 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.375231981277466 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3757307529449463 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382145404815674 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.389031171798706 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3834280967712402 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:11:27,734] Trial 70 finished with value: 89.06433868408203 and parameters: {'exponent': 1.0315408291426214, 'kernel_type': 'kpq', 'bandwidth': 11.612619420133464, 'diag': True, 'norm_p': 1.420903328940645, 'reg': 0.007540255614471809}. Best is trial 67 with value: 88.95467529296874.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3666298389434814 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.323273420333862 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3753321170806885 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.38558292388916 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.383692502975464 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369189977645874 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.392151117324829 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3780300617218018 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380474090576172 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3895652294158936 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3735435009002686 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3749465942382812 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.374022960662842 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.3332178592681885 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377883195877075 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.380162239074707 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3800389766693115 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385251998901367 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3821306228637695 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3856441974639893 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3694348335266113 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3789124488830566 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3812196254730225 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3773176670074463 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.403843879699707 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:12:39,251] Trial 71 finished with value: 88.91003875732422 and parameters: {'exponent': 1.0302543789979557, 'kernel_type': 'kpq', 'bandwidth': 12.428602193480236, 'diag': True, 'norm_p': 1.4194625377317356, 'reg': 0.008109043981876788}. Best is trial 71 with value: 88.91003875732422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3790860176086426 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.330901622772217 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3777949810028076 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380204439163208 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4039528369903564 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3844573497772217 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3824431896209717 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.380061626434326 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.377429485321045 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3780694007873535 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.371680498123169 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3759982585906982 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.391261339187622 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.327949523925781 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3929083347320557 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4647111892700195 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3789641857147217 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3795950412750244 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3842263221740723 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3802545070648193 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3718743324279785 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.381535053253174 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4026918411254883 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.401700735092163 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.4014458656311035 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:13:50,983] Trial 72 finished with value: 88.62881622314453 and parameters: {'exponent': 1.0330941217944933, 'kernel_type': 'kpq', 'bandwidth': 9.283248960803107, 'diag': True, 'norm_p': 1.4500636234774757, 'reg': 0.01632419958175083}. Best is trial 72 with value: 88.62881622314453.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.127074718475342 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4178519248962402 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.46222186088562 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.428497552871704 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.429490804672241 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4073479175567627 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3718366622924805 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385866165161133 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375399112701416 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3690080642700195 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374243974685669 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.386157989501953 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3762259483337402 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.011419773101807 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36798357963562 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3829338550567627 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3759632110595703 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368093252182007 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3742005825042725 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376850128173828 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3788626194000244 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3755345344543457 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:14:55,073] Trial 73 finished with value: 88.5848602294922 and parameters: {'exponent': 1.0308824089542061, 'kernel_type': 'kpq', 'bandwidth': 10.436642177885744, 'diag': True, 'norm_p': 1.5033167198505193, 'reg': 0.016481075330919276}. Best is trial 73 with value: 88.5848602294922.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3806419372558594 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374690055847168 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382507562637329 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.344391107559204 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.386209487915039 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3716681003570557 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3800745010375977 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.38435697555542 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3697092533111572 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3767311573028564 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3797526359558105 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384378671646118 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3781638145446777 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3754141330718994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383066177368164 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.329455614089966 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.37070894241333 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376805543899536 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3828935623168945 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3784399032592773 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378965377807617 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:15:57,085] Trial 74 finished with value: 88.57009735107422 and parameters: {'exponent': 1.0356639820698017, 'kernel_type': 'kpq', 'bandwidth': 12.508264327921696, 'diag': True, 'norm_p': 1.5212010907067888, 'reg': 0.01550573055035075}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366260051727295 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3754019737243652 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375455617904663 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3762199878692627 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3689956665039062 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374819040298462 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.335142612457275 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3731637001037598 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3884029388427734 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382291316986084 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3884189128875732 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3764259815216064 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3695406913757324 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.387437105178833 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3684163093566895 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3747429847717285 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3777835369110107 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3785808086395264 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 5.327860355377197 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:16:54,272] Trial 75 finished with value: 88.62092437744141 and parameters: {'exponent': 1.0845987479688564, 'kernel_type': 'kpq', 'bandwidth': 11.245749805325254, 'diag': True, 'norm_p': 1.5244392329562944, 'reg': 0.016178339467748774}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.375479221343994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378364086151123 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3771042823791504 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.380915403366089 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378716468811035 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3756604194641113 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3781681060791016 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3820502758026123 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.376347064971924 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3739349842071533 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381657838821411 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.34788966178894 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3796567916870117 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369924783706665 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3743948936462402 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.378095865249634 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3852572441101074 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379363536834717 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.377422571182251 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3845059871673584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379390239715576 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:17:53,315] Trial 76 finished with value: 88.65491180419922 and parameters: {'exponent': 1.082178160459724, 'kernel_type': 'kpq', 'bandwidth': 9.199384784590148, 'diag': True, 'norm_p': 1.5464589996502898, 'reg': 0.017191893660469706}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3696935176849365 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370703935623169 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372239828109741 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3799057006835938 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3756637573242188 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367774248123169 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3830580711364746 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

[I 2026-04-23 00:18:19,029] Trial 77 finished with value: 93.59860687255859 and parameters: {'exponent': 1.0805997222272146, 'kernel_type': 'kpq', 'bandwidth': 10.46350420753161, 'diag': True, 'norm_p': 1.5414863443751423, 'reg': 0.08655367011518317}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3759865760803223 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3793365955352783 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3749027252197266 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3678719997406006 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3750064373016357 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.37404727935791 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.335365533828735 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.377685070037842 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3797719478607178 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3818352222442627 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.368381977081299 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.38128924369812 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3675949573516846 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377991199493408 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3839497566223145 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.376054525375366 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3872103691101074 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:19:08,528] Trial 78 finished with value: 88.7993896484375 and parameters: {'exponent': 1.1136780313027381, 'kernel_type': 'kpq', 'bandwidth': 8.347595701166675, 'diag': True, 'norm_p': 1.540889747377588, 'reg': 0.021101559193162922}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3692948818206787 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.333014965057373 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369908332824707 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375481367111206 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377122163772583 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3808753490448 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3764941692352295 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379445791244507 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3665571212768555 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3875255584716797 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3810219764709473 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375417709350586 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.334786653518677 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.38358473777771 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

[I 2026-04-23 00:19:53,844] Trial 79 finished with value: 89.511279296875 and parameters: {'exponent': 1.1070373247750407, 'kernel_type': 'kpq', 'bandwidth': 8.462793773003119, 'diag': True, 'norm_p': 1.5181232010257344, 'reg': 0.037940511992498184}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3686683177948 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377098798751831 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3699283599853516 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3731744289398193 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37190842628479 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3675317764282227 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.383265256881714 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3830506801605225 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

[I 2026-04-23 00:20:18,969] Trial 80 finished with value: 91.34997863769532 and parameters: {'exponent': 1.128159773160292, 'kernel_type': 'kpq', 'bandwidth': 7.609952956273538, 'diag': True, 'norm_p': 1.6222703442855724, 'reg': 0.060388924415806226}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369682550430298 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.333755016326904 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3909082412719727 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366828203201294 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375262975692749 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.372425079345703 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.385803699493408 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3798580169677734 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3786590099334717 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.381383180618286 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3695263862609863 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3782365322113037 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.332966089248657 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3771233558654785 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385255813598633 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3771708011627197 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3907618522644043 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:21:11,449] Trial 81 finished with value: 88.93561248779297 and parameters: {'exponent': 1.057431704617205, 'kernel_type': 'kpq', 'bandwidth': 14.999486434779078, 'diag': True, 'norm_p': 1.4834512509132187, 'reg': 0.019787091864017115}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370575189590454 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3785998821258545 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3767402172088623 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36954665184021 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3796350955963135 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.371649980545044 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3770880699157715 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.378838539123535 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.339707136154175 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379155158996582 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36982798576355 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376725912094116 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3786566257476807 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.391878604888916 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381817579269409 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3783011436462402 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379256010055542 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:22:00,968] Trial 82 finished with value: 88.79892120361328 and parameters: {'exponent': 1.0521211020625096, 'kernel_type': 'kpq', 'bandwidth': 15.238675401514524, 'diag': True, 'norm_p': 1.4691743104764219, 'reg': 0.018160306826749753}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3744213581085205 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3775112628936768 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3831794261932373 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.336004972457886 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3862223625183105 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3740427494049072 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3747124671936035 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3829169273376465 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3693931102752686 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3786122798919678 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3776817321777344 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.383532762527466 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.381767988204956 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3720967769622803 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37601637840271 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.33735203742981 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.382458209991455 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377582550048828 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3843274116516113 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3853533267974854 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.383047342300415 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:23:02,979] Trial 83 finished with value: 88.69341278076172 and parameters: {'exponent': 1.0865223548591878, 'kernel_type': 'kpq', 'bandwidth': 8.861129566896631, 'diag': True, 'norm_p': 1.4829377990657466, 'reg': 0.01970914031429876}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3672263622283936 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366633892059326 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4261388778686523 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.417605400085449 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.188615322113037 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

[I 2026-04-23 00:23:24,223] Trial 84 finished with value: 98.38260345458984 and parameters: {'exponent': 1.0814988160280752, 'kernel_type': 'kpq', 'bandwidth': 9.394428643962693, 'diag': True, 'norm_p': 1.595962481597805, 'reg': 0.16242905624658496}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.8016836643218994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.50081729888916 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3820624351501465 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3691341876983643 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374917984008789 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3761446475982666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3861358165740967 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3819031715393066 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.388796091079712 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3834776878356934 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 4.320148706436157 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3753325939178467 seconds

Building trees:   0%|          | 0/1 [00:07<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370120048522949 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3798763751983643 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385723829269409 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.374439001083374 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378938674926758 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:24:13,312] Trial 85 finished with value: 89.12067565917968 and parameters: {'exponent': 1.1366193299821457, 'kernel_type': 'kpq', 'bandwidth': 7.051327582219341, 'diag': True, 'norm_p': 1.5024983297124213, 'reg': 0.027221759128481703}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3753907680511475 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3754560947418213 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3766062259674072 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376020908355713 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369736671447754 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.334039211273193 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3773560523986816 seconds

Building trees:   0%|          | 0/1 [00:11<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3821191787719727 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.38950777053833 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3827600479125977 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3741934299468994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3896851539611816 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-23 00:24:50,972] Trial 86 finished with value: 89.43340759277343 and parameters: {'exponent': 1.0959138758437048, 'kernel_type': 'kpq', 'bandwidth': 15.332743543601794, 'diag': True, 'norm_p': 1.577960414237354, 'reg': 0.019203652513857493}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3741607666015625 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3744397163391113 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.37198543548584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383145809173584 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.280603885650635 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.381556510925293 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.385028123855591 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3808083534240723 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370612144470215 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.38277530670166 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3709542751312256 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.385171890258789 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3805840015411377 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3794162273406982 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

[I 2026-04-23 00:25:33,300] Trial 87 finished with value: 91.99936065673828 and parameters: {'exponent': 1.1905644889500888, 'kernel_type': 'kpq', 'bandwidth': 5.216620193896778, 'diag': True, 'norm_p': 1.4505260684417043, 'reg': 0.07217692300150834}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.37808895111084 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369652032852173 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.449458599090576 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.438271999359131 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367647647857666 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3679592609405518 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377321720123291 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

[I 2026-04-23 00:25:59,150] Trial 88 finished with value: 94.80765686035156 and parameters: {'exponent': 1.0554461030561886, 'kernel_type': 'kpq', 'bandwidth': 8.494523575544772, 'diag': True, 'norm_p': 1.537750851539132, 'reg': 0.13332782240752605}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3683931827545166 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3781943321228027 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377181053161621 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3895108699798584 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3712902069091797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.166339635848999 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376073122024536 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.377331018447876 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3688693046569824 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3793749809265137 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3798751831054688 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-23 00:26:34,214] Trial 89 finished with value: 90.05662384033204 and parameters: {'exponent': 1.1102099092386333, 'kernel_type': 'kpq', 'bandwidth': 10.749450906372152, 'diag': True, 'norm_p': 1.4877725239525013, 'reg': 0.039072348789706314}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3758866786956787 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3786725997924805 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3899381160736084 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3701627254486084 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3698112964630127 seconds

Building trees:   0%|          | 0/1 [00:06<?, ?it/s]

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367868661880493 seconds

Building trees:   0%|          | 0/1 [00:03<?, ?it/s]

[I 2026-04-23 00:26:57,569] Trial 90 finished with value: 548.8869873046875 and parameters: {'exponent': 1.073396678557619, 'kernel_type': 'kpq', 'bandwidth': 12.103792716342781, 'diag': True, 'norm_p': 1.5786373202545376, 'reg': 4.260635539645422e-06}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 1
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366292715072632 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.388244390487671 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3721041679382324 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3692874908447266 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3825135231018066 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3683605194091797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3770203590393066 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3765480518341064 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3779635429382324 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377533435821533 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.255351305007935 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379711389541626 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369788408279419 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3754773139953613 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3804445266723633 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3803627490997314 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3772387504577637 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:27:46,974] Trial 91 finished with value: 88.86727447509766 and parameters: {'exponent': 1.0579250032824907, 'kernel_type': 'kpq', 'bandwidth': 15.342546150952364, 'diag': True, 'norm_p': 1.4614288416331453, 'reg': 0.01880740307165369}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3691868782043457 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379490613937378 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.386906385421753 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.382061719894409 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3892362117767334 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.388061046600342 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376429319381714 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.383936882019043 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3814640045166016 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.387531042098999 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3710222244262695 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3806679248809814 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3888931274414062 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3814570903778076 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.383234739303589 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3749136924743652 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3750147819519043 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379128932952881 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.332374334335327 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3876917362213135 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.369532585144043 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3758902549743652 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3773605823516846 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.385990619659424 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.396498203277588 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:28:58,583] Trial 92 finished with value: 89.29697113037109 and parameters: {'exponent': 1.1479919943129562, 'kernel_type': 'kpq', 'bandwidth': 6.76376251214571, 'diag': True, 'norm_p': 1.4558817568113007, 'reg': 0.01116135824828655}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.367912530899048 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3761589527130127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3762176036834717 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.383951187133789 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3827641010284424 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.332146167755127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.376683235168457 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.389787435531616 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3834638595581055 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3657476902008057 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.375195026397705 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3788468837738037 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.375643253326416 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382688045501709 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.376622438430786 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.38606333732605 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.373924732208252 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.319932699203491 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3755645751953125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.376924991607666 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.374271869659424 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377366304397583 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:30:02,926] Trial 93 finished with value: 88.6137481689453 and parameters: {'exponent': 1.0122316752026175, 'kernel_type': 'kpq', 'bandwidth': 9.967600887312015, 'diag': True, 'norm_p': 1.5148333736753425, 'reg': 0.017351414577520465}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3748698234558105 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.379103183746338 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379835367202759 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.374025583267212 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.375255584716797 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.379112482070923 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3741374015808105 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 5.345115661621094 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.37641978263855 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377134084701538 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3679866790771484 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3749306201934814 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.380495071411133 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.379610776901245 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3790531158447266 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.366954803466797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37626314163208 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375218391418457 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.392103433609009 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3774592876434326 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.330908536911011 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377875804901123 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3908956050872803 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384481906890869 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.386693239212036 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

[I 2026-04-23 00:31:14,446] Trial 94 finished with value: 88.74853973388672 and parameters: {'exponent': 1.0131904783626529, 'kernel_type': 'kpq', 'bandwidth': 8.160115130192937, 'diag': True, 'norm_p': 1.5301837931594058, 'reg': 0.01586921600788267}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3758628368377686 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.374121904373169 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3778679370880127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.376763105392456 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.36954402923584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37666916847229 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3789734840393066 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.323307991027832 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.388669490814209 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381906509399414 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.382080554962158 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3735251426696777 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3689281940460205 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3787906169891357 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3826112747192383 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3790814876556396 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3796274662017822 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3849005699157715 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3756589889526367 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:32:08,717] Trial 95 finished with value: 88.90560150146484 and parameters: {'exponent': 1.0065881337264788, 'kernel_type': 'kpq', 'bandwidth': 8.231475182526768, 'diag': True, 'norm_p': 1.525228144344621, 'reg': 0.030746575349499004}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.328189373016357 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3748626708984375 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.388141393661499 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4444570541381836 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.6010677814483643 seconds

Building trees:   0%|          | 0/1 [00:16<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.555738687515259 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.373161792755127 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3812150955200195 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3795032501220703 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378796339035034 seconds

Building trees:   0%|          | 0/1 [00:13<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.375300645828247 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.383690357208252 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 4.706143379211426 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3770651817321777 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3778247833251953 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3752708435058594 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3798015117645264 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.381883382797241 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3842086791992188 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.373911142349243 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3784663677215576 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.375394821166992 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.382519006729126 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3755581378936768 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:33:17,785] Trial 96 finished with value: 88.74423370361328 and parameters: {'exponent': 0.9853535462128183, 'kernel_type': 'kpq', 'bandwidth': 9.67316466951976, 'diag': True, 'norm_p': 1.5584954413495258, 'reg': 0.014290876031318296}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 5.333960294723511 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.378370761871338 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.4253361225128174 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4396677017211914 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.378814935684204 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3840012550354004 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3758535385131836 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3791844844818115 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3902666568756104 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.379164457321167 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3687098026275635 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3856945037841797 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.37969970703125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 5.206573963165283 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.384697675704956 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3683743476867676 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3828275203704834 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.382336139678955 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.378725528717041 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3695526123046875 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3751065731048584 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.379357099533081 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.378377914428711 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3772034645080566 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:34:26,898] Trial 97 finished with value: 88.75611724853516 and parameters: {'exponent': 0.9762030175228964, 'kernel_type': 'kpq', 'bandwidth': 9.85275474523432, 'diag': True, 'norm_p': 1.567350687664968, 'reg': 0.015084464735282646}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.365912914276123 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.334001064300537 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.5161807537078857 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.408928632736206 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3892853260040283 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.403883934020996 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3798274993896484 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.38179087638855 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3959600925445557 seconds

Building trees:   0%|          | 0/1 [00:05<?, ?it/s]

Early stopping at iteration 2
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.4108219146728516 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4298834800720215 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.414673328399658 seconds

Building trees:   0%|          | 0/1 [00:08<?, ?it/s]

[I 2026-04-23 00:35:04,896] Trial 98 finished with value: 90.262353515625 and parameters: {'exponent': 0.9744613436040971, 'kernel_type': 'kpq', 'bandwidth': 9.686151552013827, 'diag': True, 'norm_p': 1.6690653260170023, 'reg': 0.04577676790790243}. Best is trial 74 with value: 88.57009735107422.

Early stopping at iteration 3
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 4.923089981079102 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.405278444290161 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.477602005004883 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.4444029331207275 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.448223114013672 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3742241859436035 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.37721848487854 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.377699613571167 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3915092945098877 seconds

Building trees:   0%|          | 0/1 [00:10<?, ?it/s]

Early stopping at iteration 4
Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3995697498321533 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.4157297611236572 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.423696756362915 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 4.875614166259766 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.41715931892395 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3780148029327393 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.3866729736328125 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3797178268432617 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3858089447021484 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.3781843185424805 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.3727285861968994 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 2.377746105194092 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.386186122894287 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.3772926330566406 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.382873296737671 seconds

Building trees:   0%|          | 0/1 [00:12<?, ?it/s]

[I 2026-04-23 00:36:13,651] Trial 99 finished with value: 90.44933013916015 and parameters: {'exponent': 0.9911187709784457, 'kernel_type': 'kpq', 'bandwidth': 4.017454407390906, 'diag': True, 'norm_p': 1.7273111514537483, 'reg': 0.015172336519636856}. Best is trial 74 with value: 88.57009735107422.

Tree has no split, stopping training
Using hard routing for tree prediction
Best params: {'exponent': 1.0356639820698017, 'kernel_type': 'kpq', 'bandwidth': 12.508264327921696, 'diag': True, 'norm_p': 1.5212010907067888, 'reg': 0.01550573055035075}
Best MSE: 88.57009735107422

In [8]:
model, pipeline, fit_time, train_metrics, val_metrics = fit_best_xrfm(
    X,
    y,
    best_trial,
    processor,
    n_num_cols,
    task=cfg["task"],
    device=device,
)

print(f"Training time: {fit_time:.2f}s")
print(f"Train RMSE: {train_metrics['rmse']:.4f}")
print(f"Val RMSE:   {val_metrics['rmse']:.4f}")

joblib.dump(model, MODELS_DIR / data_name / "xrfm.joblib")
joblib.dump(pipeline, MODELS_DIR / data_name / "xrfm_pipeline.joblib")

None
Fitting xRFM with 1 trees and 0 iterations per tree

Building trees:   0%|          | 0/1 [00:00<?, ?it/s]

======================================================================
Fitting RFM with ntrain: 13608, d: 81, and nval: 3402
======================================================================

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 0: 2.370130777359009 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 1: 5.267009496688843 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 2: 2.3777503967285156 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 3: 2.384120225906372 seconds

Using expensive batch size
Optimal M batch size: 1289

Time taken for round 4: 2.377072334289551 seconds

Building trees:   0%|          | 0/1 [00:15<?, ?it/s]

Tree has no split, stopping training
Using hard routing for tree prediction

Using hard routing for tree prediction
Training time: 12.90s
Train RMSE: 5.0208
Val RMSE:   9.4292

['/home/shado/college_project/comp9417/9417GroupProject/models/superconductor/xrfm_pipeline.joblib']

In [9]:
model = joblib.load(MODELS_DIR / data_name / "xrfm.joblib")
pipeline = joblib.load(MODELS_DIR / data_name / "xrfm_pipeline.joblib")

In [10]:
X_test = test_df.drop(columns=metadata["target_col"])
y_test = test_df[metadata["target_col"]].to_numpy().astype(np.float32)

X_test = pipeline.transform(X_test)
t0 = time.perf_counter()
y_pred = model.predict(X_test)
infer_time = (time.perf_counter() - t0) / len(X_test)

Using hard routing for tree prediction

In [11]:
results = evaluate_regression(y_test, y_pred)
print(f"RMSE: {results['rmse']:.4f}")
print(f"Inference time per sample: {infer_time * 1e6:.2f}µs")

RMSE: 9.8139
Inference time per sample: 50.30µs

In [12]:
output = {
    **results,
    "train_metrics": train_metrics,
    "val_metrics": val_metrics,
    "fit_time_s": fit_time,
    "infer_time_per_sample_s": infer_time,
    "best_params": {
        "tuning_metric": model.tuning_metric,
        "split_method": model.split_method,
        "max_leaf_size": model.max_leaf_size,
        **model.rfm_params,
    },
}

results_dir = RESULTS_BENCHMARK / "superconductor"
with open(results_dir / "xrfm.json", "w") as f:
    json.dump(output, f, indent=4)

print(f"Results saved to {results_dir / 'xrfm.json'}")

Results saved to /home/shado/college_project/comp9417/9417GroupProject/results/superconductor/xrfm.json